### ISSUE TITLE
[Discussion] Tech Stack for the Community Website

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#1]
Tech stack discussion for the official website of the community.

**Comment by codewithvk** [comment]
Can you please tell me which purpose you need to create a website?

**Comment by Kajol-Kumari** [comment]
Hey @codewithvk We are creating this site for sharing the resources. So if you look at [this](https://github.com/HITK-TECH-Community/HITK_Tech_Community) repo, we are storing all the resources in the form of broadcast which we send in our private HITK TECH Community channel. so the purpose of creating this site will make those available for everybody.

**Comment by codewithvk** [comment]
Greate !!
