### ISSUE TITLE
[Open for all] UI Design for FAQs page of the website

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#10]
Make UI for the FAQs page of the website using any of the UI designing tool like figma

This page will contain the list of all frequently asked questions along with their answers.

**Comment by codewithvk** [comment]
Hey @Kajol-Kumari,
I want to work on this issue, can you assign me?

**Comment by codewithvk** [comment]
![Capture](https://user-images.githubusercontent.com/61119120/101349292-279f8800-38b3-11eb-9807-fc0339e90be1.PNG)
@Kajol-Kumari Can you see this?
I am not a designer so I don't request to assigned.

**Comment by codewithvk** [comment]
If you like this one then assign me I will add PR.

**Comment by Kajol-Kumari** [comment]
@codewithvk This looks nice. Feel free to open up a PR with this :)

**Comment by Aaryan8751** [comment]
@Kajol-Kumari Added FAQ UI Design in the assets folder. Could you now assign this to me?
![FAQ](https://user-images.githubusercontent.com/60098288/101624059-62362b80-3a3f-11eb-90de-c6f19cfcd59d.png)
Here is the screenshot of FAQ UI Design
