### ISSUE TITLE
[Frontend] The Navbar gets distorted on small screen

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#100]
Deliverables-

- [ ] Make the navbar responsive for different screen sizes
- [ ] Fix the menu option hover effect for smaller screens
![Screenshot from 2020-12-28 12-47-05](https://user-images.githubusercontent.com/44888949/103196878-01e22d80-490b-11eb-81d3-e144c93a848d.png)

**Comment by atharva-upadhye-01** [comment]
I would like to work on this.
Please assign this to me.

**Comment by sakshikhachane** [comment]
@Kajol-Kumari I would like to work on this issue. I have worked on a responsive website design. Please assign this issue to me.

**Comment by Kajol-Kumari** [comment]
Hey @atharva-upadhye-01 go ahead with this issue and @sakshikhachane as we are following FCFS so please look at any other opened issue.

**Comment by atharva-upadhye-01** [comment]
<img width="40%" src="https://user-images.githubusercontent.com/70993547/103227754-25ca6100-4955-11eb-9b2c-c7abc90c0945.png"><img width="40%" src="https://user-images.githubusercontent.com/70993547/103227790-3e3a7b80-4955-11eb-88d7-9f429ed34fe7.png">
@Kajol-Kumari Does this solve the issue ? Should I send PR ?

**Comment by Kajol-Kumari** [comment]
@atharva-upadhye-01 yes! Go-ahead and make a PR for this
