### ISSUE TITLE
Adding comment feature to the Q&A question

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [HITK-TECH-Community/Community-Website#1000]
**Is your feature request related to a problem? Please describe.**
I want to add the Comment feature on Q&A that will help users to share their views .

![Screenshot 2024-05-31 223228](https://github.com/HITK-TECH-Community/Community-Website/assets/118350936/58d6778f-6ae9-488b-ba0b-4e9bb7ed4975)

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Write your answer here.
yes

**Comment by Kajol-Kumari** [comment]
@Ayushmaanagarwal1211 as the page is open, we will be allowing users to answer/comment and so https://github.com/HITK-TECH-Community/Community-Website/issues/886 this issue should cover everything
