### ISSUE TITLE
Social media icon in footer should be decrease their size after it hhit the small screen size

### ISSUE THREAD

**Issue by Damini2004** [HITK-TECH-Community/Community-Website#1002]
**Describe the bug**
The social media icons in the footer of your website do not resize properly when viewed on smaller screens. Instead of decreasing in size to fit the smaller viewport, they either remain too large or are not correctly responsive, potentially causing layout issues or making the footer look unprofessional.

**To Reproduce**
1. Go to Inspect
2. Click on Responsive size of Surface Pro 7
3. Scroll down to till footer
4. See error in footer section

**Expected behavior**
As the screen size decreases, the social media icons should scale down proportionally to maintain a balanced and visually appealing footer layout.

**Screenshots**
![image](https://github.com/HITK-TECH-Community/Community-Website/assets/119414762/b03fe952-7d84-4008-9960-78eda17e93df)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser microsoft edge

**Smartphone (please complete the following information):**
 - Device: surface pro 
 - OS: windows
 - Browser microsoft edge

**Additional context**
Insteads of  placing the icon one after another we can reduce its size and place it as 2 icon in one row that will more suitable to look for those screen size.

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Write your answer here.

**Comment by Kajol-Kumari** [comment]
@Damini2004 its intentionally left aligned but regarding the size if we can fit 2 icons in a row it might look better

**Comment by BHS-Harish** [comment]
Hey @Kajol-Kumari 

Please assign this issue to me

**Comment by BHS-Harish** [comment]
hello @Kajol-Kumari 

Assign me this issue too
