### ISSUE TITLE
Downvote in Q&A bug

### ISSUE THREAD

**Issue by mukilan2815** [HITK-TECH-Community/Community-Website#1004]
**Describe the bug**
When i press the downvote twice , the upvote is decreasing . 
**To Reproduce**
1. Go to 'Q&A'
2. Click on 'Downvote twice'
3. . See error

**Expected behavior**
Each user can vote only once
**Screenshots**
![image](https://github.com/HITK-TECH-Community/Community-Website/assets/71129858/4a042f0b-5857-4ebb-bdbe-3588791ff659)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Assign this under GSSOC'24

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Yes

**Comment by Kajol-Kumari** [comment]
@mukilan2815  thanks for pointing, this logic was bugging me, currently the total upvotes is just shown but ideally total upvotes and total downvotes should have been shown. I would be more that happy if u can fix that logic

**Comment by BHS-Harish** [comment]
Hey @Kajol-Kumari 

Assign me the issue
