### ISSUE TITLE
Replace "Sign up" button for "Subscribe"

### ISSUE THREAD

**Issue by AkhilaSunesh** [HITK-TECH-Community/Community-Website#1011]
**Describe the bug**
We subscribe to a newsletter not Sign up

**Expected behavior**
More professional approach

**Screenshots**
Location: Footer
![image](https://github.com/HITK-TECH-Community/Community-Website/assets/140897461/e5f0e7cb-9170-4cb5-9bf5-fa35afe8178c)

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
yes,
Kindly assign this issue to me.

**Comment by Kajol-Kumari** [comment]
This isn't a bug and its as per the expectation.
