### ISSUE TITLE
Replace "Admin?" with "Login"

### ISSUE THREAD

**Issue by AkhilaSunesh** [HITK-TECH-Community/Community-Website#1012]
**Describe the bug**
Replace "Admin?" with "Login"

**Expected behavior**
More profession and better outlook

**Screenshots**
![image](https://github.com/HITK-TECH-Community/Community-Website/assets/140897461/382ff1e3-6f76-4676-8333-23c116ce2340)

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
I have raised 2 issues already. Please keep this on hold while I fix the other issues after assigning me.

**Comment by Kajol-Kumari** [comment]
That button is only relevant to admins so has been kept intentionally that way :)
