### ISSUE TITLE
Button text is out of alignment on mobile view

### ISSUE THREAD

**Issue by shivamgaur99** [HITK-TECH-Community/Community-Website#1013]
**Describe the bug**
The text overflows out of the buttons.

**Expected behavior**
The text should be properly aligned within the buttons.

**Screenshots**
![image](https://github.com/HITK-TECH-Community/Community-Website/assets/128178418/e53a606d-9d94-468a-bca6-0dcad0e0c241)

**Additional context**

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Write your answer here.
yes

**Comment by Kajol-Kumari** [comment]
@shivamgaur99 this is a very very small issue so just adding `gssoc` label without any `level`
