### ISSUE TITLE
Re-Designing the Dark mode theme for all  Website Pages

### ISSUE THREAD

**Issue by sri766** [HITK-TECH-Community/Community-Website#1014]
### The Website is Awesome and Needs a more detailed Color Palette in a dark Mode theme to engage the users.
---

**Screenshot of the Theme I want to implement:**
<img src="https://github.com/HITK-TECH-Community/Community-Website/assets/84568590/61d64b65-657b-4b5c-a841-8ca952a871eb" width="600"/>

I have read the Code of Conduct and commit to following all instructions.
Please assign it to me under GSSOC.

Thank you

**Comment by Kajol-Kumari** [comment]
@sri766  we had decided the color pallet in the beginning of the project itself and the dark mode color is in sync with the community logo, so i am not planning to change it in near future, thanks for taking time to point it tho
