### ISSUE TITLE
There should be 2 more buttons on manage broadcasts card

### ISSUE THREAD

**Issue by Hemu21** [HITK-TECH-Community/Community-Website#1015]
**Describe the bug**
There should be 2 more buttons on manage broadcasts card - `approve` and `reject` .
This is a part of the Issue #976 

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Write your answer here.
yes

**Comment by Hemu21** [comment]
@Kajol-Kumari  can you please assign this to me

**Comment by Kajol-Kumari** [comment]
@Hemu21  please note that the button should be functional
