### ISSUE TITLE
Add a filter of `isApproved=true` in the Broadcast and all broadcast page.

### ISSUE THREAD

**Issue by SwayamRana808** [HITK-TECH-Community/Community-Website#1016]
**Describe the bug**
add a filter of `isApproved=true` in the Broadcast and all broadcast page.
#976 
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Write your answer here.
yes

**Comment by Kajol-Kumari** [comment]
@SwayamRana808  please note that only approved braodcasts should be visible in all broadcast and broadcast page and manage broadcast should show all the approved/non-approved braodcasts.

**Comment by Kajol-Kumari** [comment]
@SwayamRana808 any update on this issue?

**Comment by BHS-Harish** [comment]
Hey @Kajol-Kumari 

I'm interest in work on the issue

**Comment by Kajol-Kumari** [comment]
This has been covered in the last merged pr as we will only ve showing approvedBroadcasts to the user, so this filter won’t be required anymore
