### ISSUE TITLE
Enhance the navigation bar and footer arrangement while adding consistent animations throughout the website to improve overall user experience.

### ISSUE THREAD

**Issue by nirajsingh015** [HITK-TECH-Community/Community-Website#1018]
As part of my GSSOC contribution, I aim to enhance the user experience o the website by updating the navigation bar for better accessibility and visual appeal, reorganizing the footer for a cleaner and more structured layout, and incorporating consistent animations across the site to improve interactivity and maintain a cohesive design aesthetic.

**Comment by Kajol-Kumari** [comment]
@nirajsingh015  i am not looking for revision of the ui right now, the focus is to complete the website e2e.

**Comment by nirajsingh015** [comment]
@Kajol-Kumari  there are some inconsistencies in the website particluarly in the nav bar and footer animations. so i want to resolve that. 
![image](https://github.com/HITK-TECH-Community/Community-Website/assets/115022991/3b2cdf82-0e0f-47ee-ba43-dfaf219af0df)
![image](https://github.com/HITK-TECH-Community/Community-Website/assets/115022991/79a693bb-c759-4ec0-a877-b7f1f638c7f7)
and the footer is not resposive accordint to differnt screen sizes.

**Comment by Kajol-Kumari** [comment]
@nirajsingh015 the fix will be take care under - https://github.com/HITK-TECH-Community/Community-Website/issues/1002
