### ISSUE TITLE
[Frontend] Improve FAQ page

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#102]
Deliverables:

- [ ] Better deisgn to FAQ page
- [ ] Remove all the inline styles from `faqs.js` file and put it in a new file named `faqs.css` and just use the classNames in JS file

**Comment by sakshikhachane** [comment]
@Kajol-Kumari I would like to work on this issue. Please assign me this issue.

**Comment by kanishkaa24** [comment]
@Kajol-Kumari I would like to work on this.

**Comment by Kajol-Kumari** [comment]
@sakshikhachane go ahead with this issue :) 

@kanishkaa24 we can't assign this issue to more than one at a time so please look for other issues

**Comment by sakshikhachane** [comment]
@Kajol-Kumari I am having one query here. In the faqs.js page Accordion is used, but can I use other than Accordion for making the faq page design better?

**Comment by Abhishek971999** [comment]
> @Kajol-Kumari I am having one query here. In the faqs.js page Accordion is used, but can I use other than Accordion for making the faq page design better?

@sakshikhachane you can use the same accordion if you wish or if you have another better design in mind then go ahead with that.

**Comment by sakshikhachane** [comment]
![HITK Tech Community - Google Chrome 29-12-2020 17_27_48](https://user-images.githubusercontent.com/53635792/103282315-611f6b00-49fb-11eb-9282-8bc6815130dd.png)
![HITK Tech Community - Google Chrome 29-12-2020 17_27_36](https://user-images.githubusercontent.com/53635792/103282320-654b8880-49fb-11eb-8be6-dce029fa4d97.png)
![HITK Tech Community - Google Chrome 29-12-2020 17_26_49](https://user-images.githubusercontent.com/53635792/103282322-65e41f00-49fb-11eb-8e35-b396d1f3dbe9.png)

@Kajol-Kumari Is this design better? Please suggest the changes required.

**Comment by Kajol-Kumari** [comment]
Hey @sakshikhachane it's looking pretty good. Just make sure that if you are using the image, remove the texts `FREQUENTLY ASKED QUESTIONS WANT TO ASK SOMETHING FROM US? `

**Comment by sakshikhachane** [comment]
Yes removed!
Should I make a PR?

**Comment by Kajol-Kumari** [comment]
> Yes removed!
> Should I make a PR?

yeah sure :)
