### ISSUE TITLE
[Frontend] Adding a testimonials section.

### ISSUE THREAD

**Issue by nagalakshmi08** [HITK-TECH-Community/Community-Website#1020]
**Is your feature request related to a problem? Please describe.**
When a user open a website, he wants to ensure whether it is a good website or not. 

**Describe the solution you'd like**
Testimonials are then used to provide some user reviews of the website to show how good the website is.

**Describe alternatives you've considered**
The user can go and search in google but it's time taken process.

**Additional context**
![image](https://github.com/HITK-TECH-Community/Community-Website/assets/121669832/fbf8511e-4a03-45d5-83fd-86f66a72b772)
This is one of my previous testimonials section.
Please assign me this issue, I would like to contribute to this project under GSSoC'24.

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Yes, I have read and understood them.

**Comment by Kajol-Kumari** [comment]
@nagalakshmi08 I liked this idea, will u be working on frontend or backend of this?

**Comment by nagalakshmi08** [comment]
> @nagalakshmi08 I liked this idea, will u be working on frontend or backend of this?

I will be working on the front end part of this.

**Comment by Kajol-Kumari** [comment]
sure @nagalakshmi08 , you can keep this section below `join us` and please keep the theme in sync with the other sections of the home page

**Comment by nagalakshmi08** [comment]
> sure @nagalakshmi08 , you can keep this section below `join us` and please keep the theme in sync with the other sections of the home page

Yeah sure, I will add the styles based on the theme of this website.
