### ISSUE TITLE
Refactor the resource form so that a new broadcast gets created on successful submission

### ISSUE THREAD

**Issue by shivamgaur99** [HITK-TECH-Community/Community-Website#1021]
Refactoring the `resource form` as per the [proposed style](https://github.com/HITK-TECH-Community/Community-Website/blob/main/frontend/PROPOSAL.md). 

this issue is part of issue #976 

Introduce isApproved flag in broadcats model. Refactor the resource form so that a new broadcast gets created on successful submission, with isApproved set to false.

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Write your answer here.
yes

**Comment by Kajol-Kumari** [comment]
@shivamgaur99 flag will get introduced under https://github.com/HITK-TECH-Community/Community-Website/issues/1016, you please focus on resource form refactoring

**Comment by Kajol-Kumari** [comment]
upgrading the issue level as the changes required is more than expected
