### ISSUE TITLE
[Backend] Create Get Testimonial API

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#1024]
## Description

In order to show the testimonials, the data will be stored in db, i want an api to be exposed to fetch the testimonial from DB in order to be shown on the website, to be used by https://github.com/HITK-TECH-Community/Community-Website/issues/1020#issuecomment-2147371880 

P.S - I will be storing the testimonial directly to DB.

**Comment by shivamgaur99** [comment]
@Kajol-Kumari could you please assing me this issue

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari could you please assign this to me, also could you clarify the required fields and for each testimonial object?

Hey @shivamgaur99 , refer https://github.com/HITK-TECH-Community/Community-Website/blob/main/frontend/src/pages/Home/components/Testimonials/testimonials.js for the fields needs for each testimonial object.

**Comment by shivamgaur99** [comment]
thank you for providing details
