### ISSUE TITLE
it is subscribe not sign up

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [HITK-TECH-Community/Community-Website#1025]
**Describe the bug**
it is subscribe not sign up

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/HITK-TECH-Community/Community-Website/assets/125277258/d4442202-aaea-4129-8e6c-6a8e6fe4b41f)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Write your answer here.

**Comment by Kajol-Kumari** [comment]
Its kept intentionally that way, its not a bug :)
