### ISSUE TITLE
FAQ page need to be fixed

### ISSUE THREAD

**Issue by kashnx** [HITK-TECH-Community/Community-Website#1026]
![Screenshot_2024-06-05-01-57-03-50_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/HITK-TECH-Community/Community-Website/assets/148524648/b92f79f7-f1d5-4819-9ab3-2f2f817014a4)

**Comment by kashnx** [comment]
Can you please assign level2 to this issue?

**Comment by Kajol-Kumari** [comment]
@kashnx  as this is gonna be a very small change so i will keep just `gssoc` for now, if i see that the level needs to be added, i will add it
