### ISSUE TITLE
Admin Button Fix

### ISSUE THREAD

**Issue by Parth20GitHub** [HITK-TECH-Community/Community-Website#1029]
**Describe your Proposal**
A clear and concise description of what the proposal is to change Admin button

**Additional context**
![image](https://github.com/HITK-TECH-Community/Community-Website/assets/142086512/c38822ad-671f-400a-be9d-6bc665ead699)

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Write your answer here.
YES

**Comment by Kajol-Kumari** [comment]
@Parth20GitHub its kept as expected, no need to change it :)
