### ISSUE TITLE
[Frontend] Integrate Get Testimonials API with frontend

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#1037]
## Description
Currently testimonials is being loaded from [https://github.com/HITK-TECH-Community/Community-Website/blob/main/frontend/src/pages/Home/components/Testimonials/testimonials.js](https://github.com/HITK-TECH-Community/Community-Website/blob/main/frontend/src/pages/Home/components/Testimonials/testimonials.js) file

## Requirement

- [ ] Remove https://github.com/HITK-TECH-Community/Community-Website/blob/main/frontend/src/pages/Home/components/Testimonials/testimonials.js file
- [ ] Integrate the [https://github.com/HITK-TECH-Community/Community-Website/blob/main/backend/app/routes/testimonial/getTestimonials.js](https://github.com/HITK-TECH-Community/Community-Website/blob/main/backend/app/routes/testimonial/getTestimonials.js) API 
- [ ] Make sure to include the required loader/toast messages

**Comment by shivamgaur99** [comment]
@Kajol-Kumari please assign me this issue
