### ISSUE TITLE
[Frontend] Fix the Broadcast UI

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#1038]
## Description 

- [ ] The Recent broadcast list and in all broadcast page, there should be trimmed content shown so that the card size remains consistent, user can always click on view details to see the full broadcast detail
- [ ] On the Admin's `Manage Broadcast` page the link button isn't working, fix it

<img width="1484" alt="Screenshot 2024-06-10 at 10 37 10 PM" src="https://github.com/HITK-TECH-Community/Community-Website/assets/44888949/e1580f49-39dc-407e-afe1-0655c42defb0">
<img width="1509" alt="Screenshot 2024-06-10 at 10 38 22 PM" src="https://github.com/HITK-TECH-Community/Community-Website/assets/44888949/bd89390b-b599-4d61-9e61-c40880003ff7">

**Comment by naisargi17** [comment]
Can you assign me under GSSOC'24 ?

**Comment by naisargi17** [comment]
Hi ,Kajol I have node version v20.11.0 in my pc .So I have change the version of the node for this project.As I'm facing many error while installing the packages . Can you please help me out .

**Comment by Kajol-Kumari** [comment]
@naisargi17  please follow https://github.com/HITK-TECH-Community/Community-Website?tab=readme-ov-file#nvm

**Comment by vaibhavi-singh-673** [comment]
@Kajol-Kumari if the work is not finished can you assign it to me?

**Comment by Kajol-Kumari** [comment]
@vaibhavi-singh-673 assigning it to u as its been more than 2 weeks without any update on this issue

**Comment by samarth-5** [comment]
Please assign this issue to me. I will surely be updating on it.

**Comment by samarth-5** [comment]
@Kajol-Kumari  Please assign this issue to me. I will surely be updating on it.

**Comment by Kajol-Kumari** [comment]
@vaibhavi-singh-673 please keep us posted on this issue.

**Comment by vaibhavi-singh-673** [comment]
i am working on it please find another issue

**Comment by vaibhavi-singh-673** [comment]
@Kajol-Kumari I am working on it will be done soon

**Comment by vaibhavi-singh-673** [comment]
@Kajol-Kumari PR send kiya hai mam, check karlijiye

**Comment by Kajol-Kumari** [comment]
@vaibhavi-singh-673 left some review comments. Also, changing the issue level as there will a little more changes required as per my latest comment

**Comment by vaibhavi-singh-673** [comment]
@Kajol-Kumari, mam, can you look through it? I made the necessary changes

**Comment by Kajol-Kumari** [comment]
Reducing the level as part-1 was fixed under - https://github.com/HITK-TECH-Community/Community-Website/issues/1078

**Comment by Kajol-Kumari** [comment]
closed by https://github.com/HITK-TECH-Community/Community-Website/issues/1080
