### ISSUE TITLE
admin profile username validation

### ISSUE THREAD

**Issue by ayushpatel1248** [HITK-TECH-Community/Community-Website#1042]
**Describe the bug**

- if admin try to update there username they are not able to add any number or underscore in there username due to which they are unable to update there user name 
- generally username can have numbers and underscore 
- this type of username are not allowed right now "kajol123" 

**To Reproduce**
1. going to the frontend in admin pages 
2. correcting the validation of admin username
3.  by correcting the regex in the validation schema 

**Expected behavior**

- username can have both number and _ 

**Screenshots**

https://github.com/HITK-TECH-Community/Community-Website/assets/127100604/d64af7a8-9781-4ac5-9263-8082631ad031

**Desktop (please complete the following information):**
 - OS: macos
 - Browser chrome
 - Version 22

**Additional context**
can you assign me this under gssoc label 

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
yes

**Comment by Kajol-Kumari** [comment]
<img width="799" alt="Screenshot 2024-06-12 at 9 58 16 PM" src="https://github.com/HITK-TECH-Community/Community-Website/assets/44888949/292e8845-311a-48e9-aa71-1c4a52d0fc8c">
@ayushpatel1248 as you have pointed it yes, please correct the validation for firstName, lastName and Username. Alomg with that, currently the userName is not shown under `myProfile` please add it there
