### ISSUE TITLE
[Frontend] Update Broadcast Functionality Not Working

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#1045]
**Describe the bug**
The update Broadcast modal is n't populating the existing description. Also, it should have provide the same interface as create broadcast so the we can add style during the updation
<img width="1097" alt="Screenshot 2024-06-12 at 10 13 07 PM" src="https://github.com/HITK-TECH-Community/Community-Website/assets/44888949/76bb0f4e-5bf7-4eae-96ee-59b097714214">

**Comment by shivamgaur99** [comment]
@Kajol-Kumari could you please assign it to me?

**Comment by Kajol-Kumari** [comment]
@shivamgaur99 just checking are u familiar with reactNative?

**Comment by shivamgaur99** [comment]
@Kajol-Kumari I have mostly worked with react, but I have explored react native a bit. however, i can grasp it quickly.

**Comment by Kajol-Kumari** [comment]
Good to know, feel free to checkout [https://github.com/Kajol-Kumari/InfluMart](https://github.com/Kajol-Kumari/InfluMart) as `community-website` project is about to be completed so i think you will find a lot of work in frontend in this other project as its pretty new as have a lot of work required in frontend

**Comment by BHS-Harish** [comment]
Hey @Kajol-Kumari 

Please assign me the issue If its still exists

**Comment by Kajol-Kumari** [comment]
Hi @BHS-Harish its still open, assigning it to you. Also sharing https://github.com/Kajol-Kumari/InfluMart/issues/296, if you can work on this before this issue, it would be great :)
