### ISSUE TITLE
[Frontend] Manage/Add Testimonial on Admin Panel

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#1049]
## Description

- [ ] Introduce a new card called `Testimonial` on admin dashboard, Clicking on this should take us to a page having 2 cards `Create Testimonial` and `Manage Testimonial`
- [ ] The Create Testimonial should open a form which admin will use to save the testimonials in DB
- [ ] The Manage Testimonial should have list of testimonials fetched and each of the fetched testimonial card should have a delete button, clicking on which the testimonial should get removed from the DB.

NOTE - Make sure to integrate all the required API

**Comment by Hemu21** [comment]
@Kajol-Kumari  can you please assign this to me.

**Comment by shivamgaur99** [comment]
@Kajol-Kumari could you please assign this to me ?

**Comment by Kajol-Kumari** [comment]
Assigning it to @Hemu21 in the basis of FCFS
