### ISSUE TITLE
[DOC]: The README.md file needs to be updated with screenshots of the web app to reflect the current state and appearance 

### ISSUE THREAD

**Issue by codercake** [HITK-TECH-Community/Community-Website#1050]
**Context:**
The current screenshots in the README.md might be outdated or do not accurately represent the latest features and design changes of the web application. Updating these screenshots will provide users with a clearer understanding of the user interface and functionality.

**Steps to Resolve:**
1. Capture new screenshots of different sections or key features of the web app.
2. Replace the existing screenshots in the README.md file with the newly captured screenshots.
3. Ensure that the screenshots are clear, relevant, and properly labeled to guide users effectively.
4. Commit and push the changes to the main repository.

Have you spent some time to check if this issue has been raised before? - YES

Please check the repository's existing issues and documentation to ensure this update aligns with any previous discussions or plans.

Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?

Yes, I have read the Code of Conduct and will ensure all updates and contributions adhere to its guidelines.

**RECORD**
- [x] I'm a GSSoC Contributor
- [x] I want to work on this issue

**Comment by Kajol-Kumari** [comment]
We already have the hosted url attached in repo about section so anyone who wants to know about the app can explore there, i don’t see much use of adding screenshots in readme
