### ISSUE TITLE
[FEAT]: Add "Remember Me" Section for Auth

### ISSUE THREAD

**Issue by codercake** [HITK-TECH-Community/Community-Website#1051]
**Is your feature request related to a problem? Please describe.**
Repeatedly logging in with username and password can be quite time-consuming.

**Describe the solution you'd like**
The “Remember Me” feature for authentication is designed to improve user experience by reducing the frequency of login prompts. When a user selects “Remember Me” during login, the system stores a persistent cookie in the user’s browser. This cookie allows the system to recognize the user’s device and browser for a set period, typically ranging from several days to a few months.

 *Screenshots*
![Screenshot 2024-06-14 133636](https://github.com/HITK-TECH-Community/Community-Website/assets/117517206/36f8870b-8991-4b81-869e-2af8be22db74)

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
YES

RECORD
- [x] I'm a GSSoC Contributor
- [x] I want to work on this issue

**Comment by Kajol-Kumari** [comment]
closed under #1127
