### ISSUE TITLE
Add more questions to FAQs

### ISSUE THREAD

**Issue by vanisharma2003** [HITK-TECH-Community/Community-Website#1052]
**Describe your Proposal**
More questions should be added to FAQs i.e. Frequently asked questions so that user can get in depth  knowledge regarding the website. Currently only two questions are present in FAQs. There should be more content present so that in case user face any difficulty can refer to those FAQs and solve his/her query.
**Additional context**
![Screenshot 2024-06-15 104322](https://github.com/HITK-TECH-Community/Community-Website/assets/137780818/b7071cb6-9231-4eed-985e-b8016ec35588)
See here are only two questions present. More questions and answers should be added here.
I am an active contributor in GSSOC. Please assign this issue to me.

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Yes

**Comment by Kajol-Kumari** [comment]
Admins will add the required faqs no need of hardcoding anything:)
