### ISSUE TITLE
[BUG] post testimonials backend 

### ISSUE THREAD

**Issue by Hemu21** [HITK-TECH-Community/Community-Website#1054]
**Describe the bug**
- [ ] We are using to save in image using multer. In backend the post testimonials is not used the multer. This leads to ask user to ask url from frontend. that will reduce user experience. 
- [ ] along with backend update we need to update the frontend for posting and getting of the image and data. 
- [ ] Need to update the image display process in frontend. 

Note: This issue includes both frontend and backend changes.

**Priority**
High

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Write your answer here.
yes

**Comment by Hemu21** [comment]
@Kajol-Kumari  can you please assign this to me.

**Comment by Kajol-Kumari** [comment]
this had been bugging me actually, thanks for raising.
