### ISSUE TITLE
updating the design of my profile card in admin panel as it not showing the username of the admin 

### ISSUE THREAD

**Issue by ayushpatel1248** [HITK-TECH-Community/Community-Website#1055]
**Is your feature request related to a problem? Please describe.**

- in the my profile section in admin panel the card is not displaying the actual username of the admin which they have entered inside the update information

**Describe the solution you'd like**

- ill add a username also in the card whose font would be smaller then the first name and second name and it will appear below the name 
- like this ill display the username 
- 
<img width="201" alt="Screenshot 2024-06-15 at 11 19 34 PM" src="https://github.com/HITK-TECH-Community/Community-Website/assets/127100604/c5fac44e-142e-469b-a36f-c3f09e825e97">

https://github.com/HITK-TECH-Community/Community-Website/assets/127100604/43e66202-f995-4431-a98c-3e62b445f0a4

**Additional context**
this is important as admin have to see there username frequently and they dont have that in profile card
assign me this under gssoc label 
and can you please assign me this under level 2

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
yes

**Comment by Kajol-Kumari** [comment]
https://github.com/HITK-TECH-Community/Community-Website/issues/1042 this issue should cover it as that's thereason it was given level1.
