### ISSUE TITLE
[BUG] manage team is not showing any data

### ISSUE THREAD

**Issue by Hemu21** [HITK-TECH-Community/Community-Website#1057]
**Describe the bug**
Manage team should show data. But it not showing anything.

**To Reproduce**
1. Go to website. login as admin.
2. add a team member.
3. now check in manage team member.

**Expected behavior**
Manage team should show all available team members.

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Write your answer here.
yes

**Comment by Hemu21** [comment]
@Kajol-Kumari  can you please assign this to me.

**Comment by Kajol-Kumari** [comment]
As there is no data in db, so its not showing up, its expected.

**Comment by Hemu21** [comment]
@Kajol-Kumari  once try to add the team member data from add teammemmber. after adding also it is not showing. can you please check once.

**Comment by Hemu21** [comment]
@Kajol-Kumari  can you see this video. can you please reopen this issue and assign me.


https://github.com/HITK-TECH-Community/Community-Website/assets/106808387/4f507750-6c07-415e-9283-666cdaa66ee4

**Comment by BHS-Harish** [comment]
Hello @Kajol-Kumari 

Please assign me the issue
