### ISSUE TITLE
Admin login panel design is not responsive for mobile

### ISSUE THREAD

**Issue by ayushpatel1248** [HITK-TECH-Community/Community-Website#1058]
**Describe the bug**

1. the design of the admin login panel is not responsive 
2. if we go to the mobile size the big image is not looking good above the login form 
3. the footer of the website very long in mobile screen which is not according to design standards 
4. overall design of the page is disturbed and it make ui experience bad for the user 

**To Reproduce**
1. going to the css of the page
2. writing new css code in media screen for the mobile size 
3.removing the image when coming to the mobile screen and adding project name above the form which look simple and pretty 
4. making the size of font ,icons, and form size small in footer and also flexing them so all information take small space and footer look good 
**Expected behavior**
the new design will be responsive and give the good user experince and interface.

the design would be somewhat like this 
<img width="294" alt="Screenshot 2024-06-18 at 12 08 08 AM" src="https://github.com/HITK-TECH-Community/Community-Website/assets/127100604/c1a59af0-9e87-41b1-96a8-cbfc155c3ca7">
and this is the existing form design in which image is looking to big and ugly
<img width="290" alt="Screenshot 2024-06-18 at 12 09 21 AM" src="https://github.com/HITK-TECH-Community/Community-Website/assets/127100604/b99d0dd5-a3ba-4899-955a-3c77023192a2">
 
**Screenshots**
this is the long existing footer 

https://github.com/HITK-TECH-Community/Community-Website/assets/127100604/dfeb5fc0-50af-473b-aeee-50b2647b4feb

**Desktop (please complete the following information):**
 - OS: macos
 - Browser chrome

**Additional context**
assign me this under gssoc label 

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
yes

**Comment by ayushpatel1248** [comment]
@Kajol-Kumari please check it out

**Comment by Kajol-Kumari** [comment]
@ayushpatel1248 the page is responsive, what do u mean by not responsive?

**Comment by ayushpatel1248** [comment]
@Kajol-Kumari  sorry for miscommunication actually i was talking about the footer design which can be enhanced further by making the navingation and others in same flex box and also making the size of social media logos small , further we can also remove the image above the login which is looking odd when we go to mobile size

**Comment by Kajol-Kumari** [comment]
@ayushpatel1248 footer is as per design only(left aligned)
