### ISSUE TITLE
Add Preloader

### ISSUE THREAD

**Issue by AsmitaMishra24** [HITK-TECH-Community/Community-Website#1060]
**Is your feature request related to a problem? Please describe.**
Yes, the absence of a preloader can lead to a poor user experience as users may not understand whether the application is working or not while content is being loaded. This can cause frustration and potentially lead to users abandoning the application. A preloader helps to keep users engaged by providing a visual indication that content is loading.

**Describe the solution you'd like**
**Design and Appearance:**
1. A simple and visually appealing animation.
2. Should match the overall design language of the application.
3. Customizable options for color, size, and style to fit different themes.

**Functionality:**
1. Should display during the loading of heavy components or data fetching processes.
2. Must cover the main content area that is being loaded.
3. Option to show the preloader globally (entire screen) or locally (specific component).

**Performance:**
1. Lightweight and optimized to prevent additional load times.
2. Should not interfere with the loading process of the main content.

**Implementation:**
1. Should be implemented as a reusable component.
2. Easy to integrate with different parts of the application.
3. Must include appropriate documentation for usage and customization.

**Describe alternatives you've considered**
1. Skeleton Screens: Instead of a preloader animation, skeleton screens can be used to display a placeholder for content that is loading. This approach can be less distracting and provide a more seamless experience.
2. Progress Bars: Another alternative is to use a progress bar that shows the percentage of content loaded. This can provide more detailed feedback to users about the loading process.
3. Lazy Loading Indicators: For sections of content that load as the user scrolls, implementing lazy loading indicators can also serve as an alternative to a full preloader.

**Additional context**
Previous Work:-
https://github.com/HITK-TECH-Community/Community-Website/assets/146121869/811a37dd-adee-41c2-96c6-713a188ebf27

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Yes

**Comment by AnshumanMahato** [comment]
I don't think the overall site requires a preloader. It is only needed on the"Broadcast" page and the "QnA" page which already have one.
