### ISSUE TITLE
Eye toggle used incorrectly

### ISSUE THREAD

**Issue by AkhilaSunesh** [HITK-TECH-Community/Community-Website#1063]
**Describe the bug**
![image](https://github.com/HITK-TECH-Community/Community-Website/assets/140897461/590bbced-f95e-4f93-a3c0-143d68da6442)
In the login form when the user click on the eye button the password should be seen. The current scenario does the exact opposite.
This creates a sense of confusion for the users.

**Additional context**
Kindly assign this issue to me.

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
yes

**Comment by Kajol-Kumari** [comment]
it is as expected
