### ISSUE TITLE
Feedback option

### ISSUE THREAD

**Issue by AkhilaSunesh** [HITK-TECH-Community/Community-Website#1065]
**Describe your Proposal**
Users find it difficult to type in the type of feedback.
Adding a dropdown facility will ease down their effort.
![WhatsApp Image 2024-06-14 at 15 12 33_7ea25036](https://github.com/HITK-TECH-Community/Community-Website/assets/140897461/8d931578-5c1f-478b-9dce-aadb0b71509e)

**Additional context**
Kindly assign me this issue.

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
yes

**Comment by Kajol-Kumari** [comment]
@AkhilaSunesh the contactUs form is for these kind of purposes only
