### ISSUE TITLE
Feat: Adding Searchbar with multiple filters.

### ISSUE THREAD

**Issue by deepak759** [HITK-TECH-Community/Community-Website#1066]
Describe the feature
There is no search bar on this website, making it difficult to find any data. It is not a good option to go through the entire page to find a specific data. I want to add this feature.

After performing a search, the user will land on a search results page where they can see all relevant results. This will improve the user experience.
and I also want add some filters like newly added, high ratings.

![Screenshot 2024-06-22 093705](https://github.com/HITK-TECH-Community/Community-Website/assets/83724070/4a5455db-59d8-4094-826a-9a22c6a4e49c)

**Comment by Kajol-Kumari** [comment]
not required
