### ISSUE TITLE
add text animation on main page

### ISSUE THREAD

**Issue by heli0707** [HITK-TECH-Community/Community-Website#1067]
**Is your feature request related to a problem? Please describe.**
Yes, the current main page lacks dynamic elements that engage visitors. The absence of text animation makes the page feel static and less interactive, which might affect the user experience and retention rates.

**Describe the solution you'd like**
I would like to add text animation to the main page to enhance visual interest and improve user engagement. 

https://github.com/HITK-TECH-Community/Community-Website/assets/95361125/f283208f-3f70-4db4-a568-32c45f0fd2f6

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Write your answer here.
Yes, I have read

**Comment by Kajol-Kumari** [comment]
Not required in this website
