### ISSUE TITLE
Floating animation to the home image

### ISSUE THREAD

**Issue by Damini2004** [HITK-TECH-Community/Community-Website#1070]
**Is your feature request related to a problem? Please describe.**
Providing tempting effect to the website.
**Describe the solution you'd like**
helps to grab more user attention.
**Describe alternatives you've considered**

**Additional context**
![image](https://github.com/HITK-TECH-Community/Community-Website/assets/119414762/507f64e4-f113-46dc-b817-390841a7d70e)

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Write your answer here.

**Comment by Kajol-Kumari** [comment]
not needed, I am trying to keep the ui very simple
