### ISSUE TITLE
The Q&A option in nav bar throws an error

### ISSUE THREAD

**Issue by CoderGirl2844** [HITK-TECH-Community/Community-Website#1075]
**Describe the bug**
The Q&A option in nav bar throws a white blank page on clicking it

**To Reproduce**
1. Go to 'Navbar'
2. Click on 'Q&A'
3. See error

**Screenshots**

https://github.com/user-attachments/assets/e552b55d-bd59-417a-8aa2-5e6f1f4b45b3

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

Please assign me this issue

**Comment by Kajol-Kumari** [comment]
@CoderGirl2844 any update on this?

**Comment by BHS-Harish** [comment]
Hey @Kajol-Kumari 

Please assign me the issue

**Comment by CoderGirl2844** [comment]
@Kajol-Kumari I am working on this issue will raise a PR shortly

**Comment by Kajol-Kumari** [comment]
@CoderGirl2844 its a very small bug so i will till tomorrow, else would assign the next person.

**Comment by BHS-Harish** [comment]
Hello @CoderGirl2844 
Did you completed the issue..? 
It's better if you complete the issue before i start the issue #1004
