### ISSUE TITLE
[Bug] Fix BroadCasts UI

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#1078]
### Description
Currently, the text in broadcast page overflows and looks bad, as we already have `vew detail` feature, just show 250 characters or so so that it fits in the card length and also, for the links, the width needs to be adjusted so that it doesn't go cross the card.
<img width="1492" alt="Screenshot 2024-07-27 at 6 50 07 PM" src="https://github.com/user-attachments/assets/b14dd9b8-fe6f-4f05-aac4-cd1f0b5f35e7">

**Comment by shivamgaur99** [comment]
@Kajol-Kumari could you please assign me?
