### ISSUE TITLE
[Frontend] Fix Bugs In Broadcasts 

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#1080]
### Description
1. Under `Manage Broadcast` page, if the broadcast has already been approved, user should only see `reject` button
<img width="341" alt="Screenshot 2024-07-27 at 8 37 28 PM" src="https://github.com/user-attachments/assets/336041ec-138b-450f-9c62-d844f7af1e8e">
2. Under `Broadcasts` page (https://deploy-preview-1079--hitk-tech-community.netlify.app/broadcasts), only the approved broadcasts should be shown, currently, it shows all the broadcasts irrespective of approvals
3. Make the length of the text aroudn 200 or 250 characters so that the broadcasts in carousel look consistent. Make sure that the carousel only shows the approved broadcasts
<img width="1502" alt="Screenshot 2024-07-27 at 8 39 44 PM" src="https://github.com/user-attachments/assets/fc44dcae-41ef-4953-830d-3a949c2278fd">

**Comment by shivamgaur99** [comment]
@Kajol-Kumari could you please assign me?
