### ISSUE TITLE
[Frontend] isApproved Feature under Manage Broadcast Page

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#1084]
### Description

- [ ] As the number of broadcasts increases, it will become hard for admins to track which broadcast is approved and which isn't. There should be a `isApproved` filter which should just come under `Manage Broadcast` tab under admin panel and not for normal user. 
- [ ]Make sure the filter looks similar to the current existing filters.

**Comment by BHS-Harish** [comment]
Hey @Kajol-Kumari 

Please assign me the issue
