### ISSUE TITLE
Bug: All broadcast Should show approved broadcast only

### ISSUE THREAD

**Issue by BHS-Harish** [HITK-TECH-Community/Community-Website#1087]
**Describe the bug**
All broadcast displays both approved and unapproved broadcasts

**To Reproduce**
1. Go to 'https://hitk-tech-community.netlify.app/all-broadcasts'
2. It shows both approved and unapproved broadcasts

**Expected behavior**
All broadcast should show approved broadcast only.

**Comment by BHS-Harish** [comment]
Hello @Kajol-Kumari 

Please assign it to me

**Comment by Kajol-Kumari** [comment]
https://github.com/HITK-TECH-Community/Community-Website/issues/1080 this issue should have covered it, not sure how it got missed
