### ISSUE TITLE
[Frontend] Improve the Manage Q&A UI

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#1096]
## Description
The Current `Manage Q&A` page doesn't look good. Improve the UI to make it look cleaner. We can have collapsible kind of thing maybe to show answers instead of opening a new window? Whichever way it look good
<img width="1476" alt="Screenshot 2024-07-31 at 11 08 14 PM" src="https://github.com/user-attachments/assets/721869d9-55db-4802-a9c3-e59924d0101d">

**Comment by shivamgaur99** [comment]
@Kajol-Kumari could you please assign it to me
