### ISSUE TITLE
gap between social icons in mobile view

### ISSUE THREAD

**Issue by dhairyagothi** [HITK-TECH-Community/Community-Website#1098]
**Documentation**
A clear and concise description of what the issue is.
![image](https://github.com/user-attachments/assets/d5c4a903-0924-482f-aa63-6843a3b6042b)

fixing gap between icons 

**Have you spent some time to check if this issue has been raised before?**
Have you checked our older issues for a similar bug.

**Additional context**
Add any other context or screenshots about the documentation updates here.

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Write your answer here.

**Comment by Kajol-Kumari** [comment]
@dhairyagothi I don't find it looking bad/distorted in any way
