### ISSUE TITLE
[Open for all] UI Design for Resource Sharing page of the website

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#11]
- Make UI for the resource sharing page of the website using any of the UI designing tool like figma

This page will include a brief introduction and a form with the fields same as [this]( https://docs.google.com/forms/d/1NMwEz60vhrvHC94Z05qeh3FI2XcgFzeI_I1HyHp-u90/viewform?usp=sharing_eil&ts=5f9ad1d8&urp=gmail_link&gxids=7628&edit_requested=true ) form.

**Comment by Sapphire-Skies** [comment]
Ma'am, this is my first time using figma. The colours aren't final because they'll depend on the homepage. Is this prototype satisfactory? https://www.figma.com/file/sh8ubRJgEXtQRbxCiJ3b48/Untitled?node-id=4%3A13

**Comment by Kajol-Kumari** [comment]
Hey @Sapphire-Skies Good try. I would recommend you to work a bit on giving the finishing tough to the design like making the input box with rounded corner, using better font for the form heading, Keeping the `submit` button in the bottom-most separate line etc. You can go ahead with this issue and make the required changes and open up the PR. Also feel free to reach out on [slack](https://join.slack.com/t/hitkteckcommunity/shared_invite/zt-jgr1sd87-lhiXHO_x63Kt7h8VBxDaFw) for further discussion.

Happy Learning :)

**Comment by Sapphire-Skies** [comment]
https://github.com/HITK-TECH-Community/Community-Website/pull/32 Thank you for your advice. I'll work on the front-end part when there is further info regarding the theme of the website on slack! Sorry the previous PR was too messy so I deleted it altogether.
![Resource_Sharing_Form](https://user-images.githubusercontent.com/55662582/101748817-0af19300-3af3-11eb-827c-c9a83678a9a1.JPG)

**Comment by Aniket31-coder** [comment]
I would like to contribute to this issue!

**Comment by Kajol-Kumari** [comment]
> I would like to contribute to this issue!

sure @Aniket31-coder Go ahead with this issue.

**Comment by Aniket31-coder** [comment]
Hey!
I have tried to make a simple UI for the resource page, please let me know if any change is required!
https://www.figma.com/file/Mi5e2rygIF0mu1K5J01MnV/Untitled?node-id=0%3A1

**Comment by Kajol-Kumari** [comment]
> Hey!
> I have tried to make a simple UI for the resource page, please let me know if any change is required!
> https://www.figma.com/file/Mi5e2rygIF0mu1K5J01MnV/Untitled?node-id=0%3A1

Hey @Aniket31-coder it's pretty good. Can you please try using [this](https://colors.lol/blocky) color pallet for the UI

**Comment by Aniket31-coder** [comment]
I have edited the color as per your feedback, please let me know if any changes are required.
https://www.figma.com/file/Mi5e2rygIF0mu1K5J01MnV/Untitled?node-id=0%3A1

**Comment by Kajol-Kumari** [comment]
> I have edited the color as per your feedback, please let me know if any changes are required.
> https://www.figma.com/file/Mi5e2rygIF0mu1K5J01MnV/Untitled?node-id=0%3A1

Thanks for incorporating the suggested changes. Please open up a PR now having this link under `assets/<your_name>` folder

**Comment by abhinav-huria** [comment]
I would like to work on this.

**Comment by kanishkaa24** [comment]
I would like to work on this issue.

**Comment by Sshivani-12** [comment]
Interested to work!

**Comment by Kajol-Kumari** [comment]
Sure @Sshivani-12 ! Go ahead with this issue.

**Comment by kanishkaa24** [comment]
![Resource Sharing  (1)](https://user-images.githubusercontent.com/71253790/104168228-bc9e1f80-5423-11eb-9869-7751667cf266.png)
Hey @Kajol-Kumari 
I have made a design. Please let me know the changes if any.

**Comment by Kajol-Kumari** [comment]
Hey @kanishkaa24 we have finalised our design and all the issues having `No more assignment` label can't be assigned to anyone anymore

**Comment by kanishkaa24** [comment]
> Hey @kanishkaa24 I really appreciate your effort but we have finalised our design and all the issues having `No more assignment` label can't be assigned to anyone anymore

It was already assigned to me.

**Comment by Kajol-Kumari** [comment]
> > Hey @kanishkaa24 I really appreciate your effort but we have finalised our design and all the issues having `No more assignment` label can't be assigned to anyone anymore
> 
> It was already assigned to me.

Ah, my bad! Can we please have enhancements based on the current form look like changing the check-box with select box. The way input heading is appearing etc.

**Comment by kanishkaa24** [comment]
> > > Hey @kanishkaa24 I really appreciate your effort but we have finalised our design and all the issues having `No more assignment` label can't be assigned to anyone anymore
> > 
> > 
> > It was already assigned to me.
> 
> Ah, my bad! Can we please have enhancements based on the current form look like changing the check-box with select box. The way input heading is appearing etc.

Can you please share the current form?

**Comment by Kajol-Kumari** [comment]
@kanishkaa24 This is the current form
![Screenshot from 2021-01-14 11-31-11](https://user-images.githubusercontent.com/44888949/104551033-112bdf80-565c-11eb-8ed8-95a2c250fe9c.png)

**Comment by kanishkaa24** [comment]
![Resource Sharing  (2)](https://user-images.githubusercontent.com/71253790/105141443-2a7ed100-5b1f-11eb-9a42-d3fbab5a9aa3.png)
@Kajol-Kumari Please review this

**Comment by Kajol-Kumari** [comment]
@kanishkaa24 you can make a PR with this!
