### ISSUE TITLE
Backend: Fixing Upvote and Downvote for Answers

### ISSUE THREAD

**Issue by BHS-Harish** [HITK-TECH-Community/Community-Website#1107]
**Describe the bug**
Currently the upvote works fine in backend but the while downvote, the upvote count was decreased. Each user can upvote or downvote for many times.

**Expected behavior**
The behavior like as broadcast upvote and downvote
- [x] Both upvote and downvote count seperately
- [x] Each user can upvote or downvote an answer only once.

**Comment by BHS-Harish** [comment]
Hello @Kajol-Kumari 

Assign me the issue

**Comment by Kajol-Kumari** [comment]
@BHS-Harish  I am thinking to have - 
1. Separate count for upvote and downvote(this will require just a little tweak)
2. Can we introduce author in both question and answer? And if user gives the author name, we can show it as `- <author>` in bottom right of the question and answer cards

Let me know if this sounds good, i will add the proper labels then

**Comment by BHS-Harish** [comment]
@Kajol-Kumari 

Yeah we can introduce author...Can we get the author name from question and answer form with the field **name**..?

**Comment by BHS-Harish** [comment]
Hello @Kajol-Kumari 

Assign me the issue
It needs to be completed before frontend issue :)

**Comment by Kajol-Kumari** [comment]
@BHS-Harish if name already exists, we can use the same, not need to introduce a new field
