### ISSUE TITLE
[Frontend] UI Enhancements in Manage Q&A Section of Admin Panel

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#1112]
### Description

- [ ] We should only show `Delete` button after approval in both question and answer
- [ ] The loader while fetching the answer is making the UI look bad, either shift the loader under the expanded section of `answers` or replace the ui with pop-up for better user experience

<img width="1482" alt="Screenshot 2024-08-06 at 3 38 23 PM" src="https://github.com/user-attachments/assets/17c2381c-26e0-491a-9264-796bbd319b77">

**Comment by BHS-Harish** [comment]
Hey @Kajol-Kumari 

Please assign me the issue
