### ISSUE TITLE
[Frontend] Admin Button 

### ISSUE THREAD

**Issue by lolpanda2004** [HITK-TECH-Community/Community-Website#1114]
**Describe the bug**
Admin button do not need "?"

**To Reproduce**
1. Go to homepage

**Expected behavior**
Admin button doesnt need "?" and can have hovering animation and similar color to that of the home button

**Screenshots**
![header](https://github.com/user-attachments/assets/34b42f36-6b38-4e0e-a6e7-c1691d3ce112)

**Desktop (please complete the following information):**
 - OS: Window
 - Browser Edge
 - Version 127.0.2651.86

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
yes

**Comment by Kajol-Kumari** [comment]
It's intentional :)
