### ISSUE TITLE
Integrate Update Admin profile with backend

### ISSUE THREAD

**Issue by BHS-Harish** [HITK-TECH-Community/Community-Website#1124]
**Description**

1. Go to 'http://localhost:3000/dashboard'
2. Click settings
3. Click Myprofile and click edit icon
4. The data not updated while submitting the form.

**Comment by BHS-Harish** [comment]
Hey @Kajol-Kumari 

Please assign me the issue

**Comment by Kajol-Kumari** [comment]
It was working last time i check, not sure what changed

**Comment by Kajol-Kumari** [comment]
@BHS-Harish  even right now i updated the image for one of the admins profile, can you clarify the bug here?

**Comment by BHS-Harish** [comment]
Hello @Kajol-Kumari 

Sorry,
I checked in the local so that i have raised the issue.
It's working fine in production. :)
