### ISSUE TITLE
[Backend] Every New Broadcast should be Broadcasted to Subscribers

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#1125]
### Description
Currently, students needs to visit the site to see the resource. 

### solution
As soon as a broadcast gets approved by the admins, it should broadcast it to all the email subscribers. This will help students to be updated with any new opportunities posted on the site.

**Comment by BHS-Harish** [comment]
Hey @Kajol-Kumari 

Assign me the issue
