### ISSUE TITLE
[Feature] Keep me loggedIn feature

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#1127]
## Description
As the token expires in an hour due to security reasons, admins need to login again and again. There should be a checkbox of `keep me logged in` in the admin login form, once admins check that box, the token of the admins shouldn't expire until they change their password

NOTES - 
1. The token shouldn't expire if the checkbox is checked
2. As soon as the admin change their password, the token should expire

**Comment by BHS-Harish** [comment]
Hey @Kajol-Kumari 

Let me resolve the issue.
Please assign it to me :)
