### ISSUE TITLE
[FRONTEND] Improve Footer Component

### ISSUE THREAD

**Issue by Swastik1710** [HITK-TECH-Community/Community-Website#125]
Make the footer component more attractive and lively and also add a Newsletter column to it.

**Comment by Swastik1710** [comment]
Hey @Kajol-Kumari , can I work on this issue.

**Comment by Kajol-Kumari** [comment]
Go ahead @Swastik1710

**Comment by Swastik1710** [comment]
Thank you @Kajol-Kumari  for the guidance . I've made the PR regarding this issue and if you have any other suggestions do let me know. Thank You.
