### ISSUE TITLE
Create Code of Conduct. md

### ISSUE THREAD

**Issue by muthuannamalai12** [HITK-TECH-Community/Community-Website#135]
Hi,
I found that this project repository is not having a code of conduct file in this repository, kindly assign me this issue and I would like to contribute a well-formatted code of conduct file as you know code of conduct is a necessary file which the contributors need to follow so that everyone follows a decorum.

**Comment by muthuannamalai12** [comment]
I would love to work on this issue as a part of DWOC. Kindly assign me

**Comment by Kajol-Kumari** [comment]
Hey @muthuannamalai12 thanks for taking time to open up this issue. But we already have the code of conduct fille [here](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md), so closing this issue

**Comment by muthuannamalai12** [comment]
Ok Thank you.
