### ISSUE TITLE
[Frontend] Make the Admin's Home Page

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#138]
Deliverables:

- [ ] Make separate navbar for admin taking reference of [this](https://www.figma.com/file/KIwDSv3VcoD682JFVdgPuK/hitk-tech-design?node-id=0%3A1) design
- [ ] Make the admin home page, taking reference from [this](https://www.figma.com/file/KIwDSv3VcoD682JFVdgPuK/hitk-tech-design?node-id=0%3A1) design.
- [ ] Make `/admin` route that will direct to the admin's home page

- Use [this](https://colors.lol/blocky) color pallet
- Make a separate folder under `component` and put all the codes there
- Improvements are welcomed :)

**Comment by sakshikhachane** [comment]
@Kajol-Kumari I would like to work on this issue. Please assign me.

**Comment by Kajol-Kumari** [comment]
sure @sakshikhachane Go ahead with this issue

**Comment by antaramunshi** [comment]
@Kajol-Kumari i would like to give it a shot as well.Can you assign this to me?

**Comment by Kajol-Kumari** [comment]
sure @antaramunshi go ahead with this issue!

**Comment by Bishal05** [comment]
Hello can i contribute in the issue under swoc @Kajol-Kumari ?

**Comment by Kajol-Kumari** [comment]
sure @Bishal05 Pleasego ahead with this issue.

**Comment by himanshu007-creator** [comment]
Please assign me this issue as well

**Comment by Sloth-Panda** [comment]
Would like to work on this issue

**Comment by himanshu007-creator** [comment]
@Kajol-Kumari  mam do i have to submit individual submission keeping the issue in mind, or all assignees have to work collaboratively and send a single request?

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari mam do i have to submit individual submission keeping the issue in mind, or all assignees have to work collaboratively and send a single request?

You need to make individual submission for this issue

**Comment by kenkirito** [comment]
can i work on this issue @Kajol-Kumari
