### ISSUE TITLE
Color of icon is different on different page 

### ISSUE THREAD

**Issue by rounaksarda** [HITK-TECH-Community/Community-Website#143]
The color of icon in the form of  'Contact us' page is grey 

![Screenshot (541)](https://user-images.githubusercontent.com/36100122/103373642-7c719f80-4afb-11eb-9094-39e417c76bc2.png)

The color of icon in the form of 'Resource' page is dark(black)
![Screenshot (542)](https://user-images.githubusercontent.com/36100122/103373703-a5923000-4afb-11eb-85a6-e01cd91f9302.png)

**Comment by rounaksarda** [comment]
can I change it.

**Comment by Kajol-Kumari** [comment]
Hey @rounaksarda thanks for taking time to open up this issue but we had kept that color to the icon intentionally. Also I request you to not go ahead to work on an issue untill tou get assigned to it. Please feel free to close this isse and take up another one :)

**Comment by rounaksarda** [comment]
@Kajol-Kumari  okay!
