### ISSUE TITLE
[ Enhancement] Integrate welcome bot 

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#148]
Deliverables

- [ ] Add welcome bot config file having proper message that will show up when any user will open up an issue or pull-request for the first time.

For reference, checkout https://github.com/apps/welcome

**Comment by musavveer** [comment]
Hi @Kajol-Kumari  I would like to work on it.

**Comment by Kajol-Kumari** [comment]
@musavveer go ahead!

**Comment by musavveer** [comment]
Include NWOC label

**Comment by Kajol-Kumari** [comment]
> Include NWOC label

This project isn't under NWOC(Njack Winter of Code)

**Comment by musavveer** [comment]
> > Include NWOC label
> 
> Hey @musavveer this project isn't under NWOC(Njack Winter of Code)

Ok
