### ISSUE TITLE
[Backend] Email Service

### ISSUE THREAD

**Issue by jackfrost13** [HITK-TECH-Community/Community-Website#152]
We need a helper function capable of sending emails. It should accept the necessary fields like recipient list, body, subject etc.
The configurations for email service should be in the `config` folder. We will also need an `emailTemplates.json` file which will contain the templates so that one can select a template and roll out the email without hardcoding the email matter.
For starter make one template named `inviteAdmin` which will be used to for inviting someone to be an admin.

One needs to incorporate dynamic variables for emailTemplates

Let me know if you have any queries.

**Comment by mak-ux** [comment]
can you please describe a little-bit for emailTemplates.json?

**Comment by jackfrost13** [comment]
something like this
```json
{
  "INVITE_ADMIN" : {
    "subject" : "Invitation for becoming an Admin",
    "body" : "You are invited to join HITK Tech Community as an admin.\n\nUse {link} to sign up",
    "recipients" : "{email}"
  }
}
```
This is just a rough template just for demonstration.

**Comment by Piyush3436** [comment]
@jackfrost13 can I take this up?

**Comment by jackfrost13** [comment]
Sure

**Comment by kenkirito** [comment]
Can i work on this issue

**Comment by jackfrost13** [comment]
@kenkirito Someone has been already assigned. I believe you already been assigned an issue which is not yet complete. As per the limitations one can work only on one issue at a time

**Comment by kenkirito** [comment]
i have completed with the issue i am making a pr

**Comment by jackfrost13** [comment]
@Piyush3436 Please update your status

**Comment by Piyush3436** [comment]
@jackfrost13 I think some confusion has been created. I was working on the issue, but @kenkirito made a PR and I didn't work on it further.

**Comment by jackfrost13** [comment]
I never gave a clearance to him or removed you from the assignee. You could have cleared this earlier.

**Comment by Piyush3436** [comment]
Sorry about it. Just give me a day or two, I'll make the PR. Really sorry for that.

**Comment by priyanshu20** [comment]
Hey @jackfrost13 can I take this up as GSSOC '21 participant?

**Comment by jackfrost13** [comment]
@priyanshu20 Can you help us with a timeline for closing this issue? Many other issues depends on this one, hence we are looking forward to close this ASAP since this has been ongoing for quite a while

**Comment by priyanshu20** [comment]
Sure, I presume this will be finished by tonight
Or tommorow morning by the latest

**Comment by priyanshu20** [comment]
@jackfrost13 In the email template, do we require some HTML and Styling or will a standard email do?

**Comment by jackfrost13** [comment]
for now we are just using normal text, later on we will be incorporating the HTML data
