### ISSUE TITLE
[Backend] Link shortener service

### ISSUE THREAD

**Issue by jackfrost13** [HITK-TECH-Community/Community-Website#153]
We need a link shortener service which accepts a query parameter `link` and shortens it to a code of length 5. One using that link it should redirect to the original link if valid; else throw a proper error. 
Use collection `shortLinks` for storage

API testing required for this. 
**For API testing briefing refer to #81**

**Comment by abdus** [comment]
I want to work on this task. please assign it to me :)

**Comment by jackfrost13** [comment]
@abdus Sure go ahead, Happy Coding ;)
Before getting into the code please discuss the architecture once with me

**Comment by abdus** [comment]
@jackfrost13 sure thing.

**Comment by abdus** [comment]
@jackfrost13 here's how I am thinking to implement it:

The URL shortener service would listen for requests in a pathname, for example, `example.com/l/w3erw`. This can be a subdomain as well(say, `links.example.com/w3erw`. Obviously, it will follow microservice architecture.

To generate a unique string for any given URL, we could simply hash the string in, say, `md5` and take the first 5 characters. Of course, hashing is a resource-intensive process although it's hardly matters when the input data is small. 

To make the system even more performant, efficient and accurate; we could generate a bunch of unique 5-char strings and store them in a database ahead of time. Benefits: users won't have to wait for the system to generate and select a unique string. Less load on the system.

Let me know if you have any questions. I will start writing code once you approve this approach :)

**Comment by jackfrost13** [comment]
Yeah, the approach seems apt enough. I think so generating it before-hand will not be very useful( as it will incur an extra DB call). We can go ahead with hash one or even generating a random 5 character shortcode. Please go ahead with the coding, just make sure it behaves as an independent service( a simple helper function). Happy Coding :)

**Comment by jackfrost13** [comment]
@abdus Please update your status!

**Comment by abdus** [comment]
@jackfrost13 hey, sorry for the late response. you may assign this issue to someone else.

**Comment by nehaparmar99** [comment]
Can I give it a try?

**Comment by jackfrost13** [comment]
go ahead

**Comment by nehaparmar99** [comment]
Hey!I created an API which generates random numbers using the shortid npm package, it'll take the first 5 digits.And for the url it'll take the hostname+the random id generated.
The hostname will be taken from the url which has to be shortened.
For eg.
https://github.com/HITK-TECH-Community/Community-Website -> github.com/clHK8

**Comment by jackfrost13** [comment]
seems fine. You just need to make the redirection path, `github.com/XXXXX` doesn't mean anything for anyone.

**Comment by nehaparmar99** [comment]
I did not get your point on the redirection path.😅 Could you please elaborate?

**Comment by jackfrost13** [comment]
> I did not get your point on the redirection path.😅 Could you please elaborate?

nothing much. Just that in 
> For eg.
https://github.com/HITK-TECH-Community/Community-Website -> github.com/clHK8
And for redirection: http://localhost:3500/clHK8
Please let me know if it needs to be done in any other way

We have nothing to do with `github.com/clHK8`

**Comment by nehaparmar99** [comment]
> > I did not get your point on the redirection path.😅 Could you please elaborate?
> 
> nothing much. Just that in
> 
> > For eg.
> > https://github.com/HITK-TECH-Community/Community-Website -> github.com/clHK8
> > And for redirection: http://localhost:3500/clHK8
> > Please let me know if it needs to be done in any other way
> 
> We have nothing to do with `github.com/clHK8`

Okay so should I make it something like hitk.tech/clHK8 ?

**Comment by jackfrost13** [comment]
Just the `domainName/code` should work. For now it will be `localhost:3500/code`

**Comment by nehaparmar99** [comment]
> Just the `domainName/code` should work. For now it will be `localhost:3500/code`

Oh okay, will make the pr by tomorrow then

**Comment by jackfrost13** [comment]
Please try to do it soon, it is difficult to review PR's during weekdays

**Comment by nehaparmar99** [comment]
> Please try to do it soon, it is difficult to review PR's during weekdays

Yes sure, the code was done, I have to do API testing, and since im doing it for the first time, its taking time😅
