### ISSUE TITLE
[Backend] Route for getting admins list

### ISSUE THREAD

**Issue by jackfrost13** [HITK-TECH-Community/Community-Website#154]
We need a get route for getting a list of admins.
It will not be an open API
It should have pagination. 
Route path is `/admin`

API Testing is required!
Refer to #81 for a brief overview of our API Testing procedure

**Comment by atharva-upadhye-01** [comment]
I would like to work on this.
Please assign this to me.

**Comment by jackfrost13** [comment]
Sure go ahead. Make sure you follow the structure of our codebase.

**Comment by atharva-upadhye-01** [comment]
Thanks, yes I will.

**Comment by atharva-upadhye-01** [comment]
`localhost:3500/admin/admin-list` route is now giving this list on POSTMAN.
I wasn't able to find predefined tests, please guide me.

![image](https://user-images.githubusercontent.com/70993547/103471895-3b53e680-4dac-11eb-899e-b7d0fe2b4e6e.png)
Note: In database some admins didn't insert their names so it returned null. Hence list of emails is being returned as this is inserted by each admin

**Comment by jackfrost13** [comment]
Please change the route to `/admin`
The list seems fine, since it's in dev mode it is completely fine that the names are null. 
Please add a query parameter `superAdmin` which if is true get only superadmins. If false get only admins. If nothing is provided get all. Something like this.
