### ISSUE TITLE
[Enhancement] Make the contact us form under card, similar to `login` form

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#161]
Deliverables:

- [ ] Make the Contact-us page UI better with the form being displaying over a card similar to the login page.

**Comment by shraddha-1402** [comment]
Hey @Kajol-Kumari i would like to work on this issue, please assign me!

**Comment by Kajol-Kumari** [comment]
sure @shraddha-1402 please go ahead with this issue.
