### ISSUE TITLE
[Frontend] Make privacy policy page

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#162]
Deliverables:

- [ ] Add route for `privacy policy` text of the footer section.
- [ ] Make a good looking standard `privacy policy` page with dummy data as of now.

Please make sure to show the design here once before opening up the PR.

**Comment by pankajkumarbij** [comment]
I would like to work on this.
Please assign this to me.

**Comment by Kajol-Kumari** [comment]
Sure @pankajkumarbij go ahead with this issue. Looking forward to your PR :)

**Comment by shraddha-1402** [comment]
Hey @Kajol-Kumari can i also work on this issue?

**Comment by shraddha-1402** [comment]
How does this design look?

![image](https://user-images.githubusercontent.com/69422250/103532468-4cd2e680-4eb1-11eb-9c55-d9522758bc9a.png)

**Comment by Kajol-Kumari** [comment]
@shraddha-1402 just make the left side image vertically centre aligned and I feel it would be good to go :)

**Comment by shraddha-1402** [comment]
> @shraddha-1402 just make the left side image vertically centre aligned and I feel it would be good to go :)

Hey, @Kajol-Kumari does this meet your expectations?
![image](https://user-images.githubusercontent.com/69422250/103547884-f96d9200-4eca-11eb-8ec7-7cf5e2b7459f.png)

**Comment by Kajol-Kumari** [comment]
@shraddha-1402 I told vertically centre. Btw check whether this or vertically centre looks good and make PR with that :)

**Comment by shraddha-1402** [comment]
> @shraddha-1402 I told vertically centre. Btw check whether this or vertically centre looks good and make PR with that :)

Oh, i misunderstood! i'll do it vertically centre and send for review!

**Comment by shraddha-1402** [comment]
@Kajol-Kumari please review this design and suggest changes if any, and whichever design looks fine to you i'll make the pr of that.

![image](https://user-images.githubusercontent.com/69422250/103632502-66843480-4f6a-11eb-8975-2f23f1b90a8a.png)

**Comment by Kajol-Kumari** [comment]
> > @shraddha-1402 just make the left side image vertically centre aligned and I feel it would be good to go :)
> 
> Hey, @Kajol-Kumari does this meet your expectations?
> ![image](https://user-images.githubusercontent.com/69422250/103547884-f96d9200-4eca-11eb-8ec7-7cf5e2b7459f.png)

@shraddha-1402 please make the PR for this design.

**Comment by shraddha-1402** [comment]
> > > @shraddha-1402 just make the left side image vertically centre aligned and I feel it would be good to go :)
> > 
> > 
> > Hey, @Kajol-Kumari does this meet your expectations?
> > ![image](https://user-images.githubusercontent.com/69422250/103547884-f96d9200-4eca-11eb-8ec7-7cf5e2b7459f.png)
> 
> @shraddha-1402 please make the PR for this design.

okay @Kajol-Kumari, i'll make the pr, but are there any changes i could do to make it better?

**Comment by Kajol-Kumari** [comment]
Hey @shraddha-1402 thanks for asking, I would recommend you to see the `terms` page and follow that for heading and also if you can find some better image than what you have used now, for this page, it would be appreciated :)

**Comment by shraddha-1402** [comment]
> Hey @shraddha-1402 thanks for asking, I would recommend you to see the `terms` page and follow that for heading and also if you can find some better image than what you have used now, for this page, it would be appreciated :)

Sure @Kajol-Kumari i'll look into the `Terms` page. And for the image do you want me to find one which covers the whole width of the page?

**Comment by Kajol-Kumari** [comment]
@shraddha-1402 not necessarily the whole width, just need to look better than the current one :)

**Comment by shraddha-1402** [comment]
> @shraddha-1402 not necessarily the whole width, just need to look better than the current one :)

Sure! Can i send you the images on slack channel for review?

**Comment by Kajol-Kumari** [comment]
sure @shraddha-1402 !

**Comment by shraddha-1402** [comment]
@Kajol-Kumari do tell if any other changes are required, i'd be happy to implement them!

![image](https://user-images.githubusercontent.com/69422250/103683268-fbf5e780-4faf-11eb-9ca5-7487b99447d1.png)

**Comment by Kajol-Kumari** [comment]
Nice and clean! Looks good to go
