### ISSUE TITLE
[Frontend] Make Terms of Use Page

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#163]
Deliverables:
- [ ] Add route for `terms of use` text of the footer section. Don't add this in the navbar
- [ ]  Make a good looking standard `terms-of-use` page with dummy data as of now.

Please make sure to show the design here once before opening up the PR.

**Comment by luckykumarirai** [comment]
I would like to work on this.
Please assign this to me.

**Comment by Kajol-Kumari** [comment]
sure @luckykumarirai GO ahead with this issue. Looking forward to your PR :)

**Comment by vedikaag99** [comment]
@Kajol-Kumari I would like to work on this.

**Comment by vedikaag99** [comment]
https://user-images.githubusercontent.com/67699840/103481108-9c0c0f00-4dfe-11eb-8def-82db6d47be84.mov

@Kajol-Kumari Please review.

**Comment by Kajol-Kumari** [comment]
@vedikaag99 looks nice and clean :+1:

**Comment by kenkirito** [comment]
is this issue still open

**Comment by Kajol-Kumari** [comment]
> is this issue still open

Hey! All the issues with the label `No more assignment` is not available for grab
