### ISSUE TITLE
[Frontend] Make Get Involved page

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#164]
Deliverables:

- [ ] Add route for `get Involved` page
- [ ]  Make a good looking standard `Get Involved` page having the ways of getting involved like Opening up an Issue, contributing to codebase etc. You can take reference from [here](https://eval.ai/get-involved) and [here](https://canvasboard.live/contribution)

Please make sure to show the design here once before opening up the PR.

**Comment by atharva-upadhye-01** [comment]
I would like to work on this.
Please assign this to me.

**Comment by Kajol-Kumari** [comment]
sure @atharva-upadhye-01 Go ahead with this issue. Looking forward to your PR :)

**Comment by atharva-upadhye-01** [comment]
Adding Get Involved item in nav bar looks good in mobile view but gets distorted in landscape view
<img src="https://user-images.githubusercontent.com/70993547/103457071-056a2000-4d22-11eb-9068-c0c176ae471f.png" width="40%">
<img src="https://user-images.githubusercontent.com/70993547/103457067-fdaa7b80-4d21-11eb-9c28-3b3706e5cd7a.png" >
So digging on it too.

**Comment by Kajol-Kumari** [comment]
@atharva-upadhye-01 don't add this in navbar, in footer we have a text `Get Involved` under `Other` section, just make that direct to the Get Involve page

**Comment by atharva-upadhye-01** [comment]
Yes I won't add `Get Involved`. But I just now fixed the CSS of navbar so that it can contain more tabs.
![image](https://user-images.githubusercontent.com/70993547/103458197-ba550a80-4d2b-11eb-87ad-70a568a3231c.png)
Would you like to merge this ?

**Comment by Kajol-Kumari** [comment]
> Yes I won't add `Get Involved`. But I just now fixed the CSS of navbar so that it can contain more tabs.
> ![image](https://user-images.githubusercontent.com/70993547/103458197-ba550a80-4d2b-11eb-87ad-70a568a3231c.png)
> Would you like to merge this ?

remove the other tab and just open up the PR with fixes(if any) I will check that on my end once and if i find that relevant, I would surely merge that with proper labels :)

**Comment by atharva-upadhye-01** [comment]
How does this design look ?

![image](https://user-images.githubusercontent.com/70993547/103471746-bc5dae80-4da9-11eb-91e2-4263ab5c1923.png)

**Comment by Kajol-Kumari** [comment]
@atharva-upadhye-01 design looks preety good but instead of using picture in the card, please use few lines describing the heading like under `Report Issue` , you can put `If you came across something that isn't working perfectly, feel free to open up an issue for the same`

**Comment by atharva-upadhye-01** [comment]
@Kajol-Kumari  How is this ?

![image](https://user-images.githubusercontent.com/70993547/103536090-e1404780-4eb7-11eb-86ef-64f4f3a05126.png)

**Comment by Kajol-Kumari** [comment]
@atharva-upadhye-01 looks nice and clean, just make the heading consistent with other pages and it will be good to go :(

**Comment by atharva-upadhye-01** [comment]
- [x] Heading font made consistent
- [x] Added hovering effect

![image](https://user-images.githubusercontent.com/70993547/103789221-c3b0e080-5065-11eb-9692-42536ff43d7d.png)

**Comment by Kajol-Kumari** [comment]
Hey @atharva-upadhye-01 just make the heading size and style similar to other pages like `FAQs` and feel free to open up a PR :)

**Comment by vedikaag99** [comment]
Is this issue open to grab? @Kajol-Kumari

**Comment by Kajol-Kumari** [comment]
Hey @vedikaag99 we can't assign this to more than one person. We will be opening more issues very soon :)

**Comment by yashsehgal** [comment]
Can I work on this issue?
