### ISSUE TITLE
Create CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by tharunc** [HITK-TECH-Community/Community-Website#167]
Hello there,
    I would like to add CODE_OF_CONDUCT.md to this repo. Kindly assign me this issue as a part of DWOC.

**Comment by Kajol-Kumari** [comment]
Hey @tharuncthabks for taking time to open up this issue. But we already have `code of conduct` in our project [here](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md), so closing this issue
