### ISSUE TITLE
[Enhancement] Add preetier as pre-commit-hook

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#172]
Deliverables:

- [ ] Add `preetier` code formatter as pre-commit hook to this repo.
- [ ] Test it on your forked repo and paste the screenshot in PR description

Refrence links: https://dev.to/botreetechnologies/setting-up-husky-pre-commit-hook-with-eslint-prettier-and-lint-staged-for-react-and-react-native-d05

**Comment by shraddha-1402** [comment]
Hey @Kajol-Kumari i would like to work on this. Please assign me!

**Comment by Kajol-Kumari** [comment]
Sure @shraddha-1402 go ahead with this issue

**Comment by shraddha-1402** [comment]
> Sure @shraddha-1402 go ahead with this issue

Hey @Kajol-Kumari do you want all the files to get reformatted when we commit or only the staged files?

**Comment by Kajol-Kumari** [comment]
Hey @shraddha-1402 just keep it limited to staged files.

**Comment by dollyjain51099** [comment]
Hey, I would like to work on this issue. Please assign it to me!

**Comment by Kajol-Kumari** [comment]
Hey @dollyjain51099 thanka for your interst but we can't assign this issue to more than one person. Please take a look at other issues and feel free to claim if it's up for grab :)
