### ISSUE TITLE
[Frontend] Fix the team card in about page

### ISSUE THREAD

**Issue by salil-naik** [HITK-TECH-Community/Community-Website#179]
- [ ] Fix the LinkedIn icon which is not visible.
- [ ] Remove the `linear-gradient` effect on hover. Just keep `box-shadow`. 

![image](https://user-images.githubusercontent.com/20141508/103610410-214e0b80-4f46-11eb-9282-42ea6a5aee97.png)

**Comment by abhay313** [comment]
Can I work on this issue?

**Comment by mohit355** [comment]
Yes, of course, go ahead

**Comment by N00Bmaster2810** [comment]
If this issue is available then can I work on this @mohit355

**Comment by mohit355** [comment]
@N00Bmaster2810  this issue is already assigned to another participant. So if he is not able to complete this issue within 7days then I will assign this to you.

**Comment by vedikaag99** [comment]
can I work on this?
