### ISSUE TITLE
[Enhancement] Make Login page better

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#180]
Deliverables:

- [ ] Make the `Sign In` button similar to that in `contact-us` page having the same hovering effect and look.
- [ ] After click on input box, currently we see a black border, replace that with the bolder box shadow
- [ ] Make the hide/show icon feature working
- [ ] Make the cursor pointer to the `hide/show` icon

**Comment by kenkirito** [comment]
assign me

**Comment by urvashi-code1255** [comment]
@Kajol-Kumari I want to work on this project. Kindly assign this issue to me 
Thanks & Regards
Urvashi Anand

**Comment by Kajol-Kumari** [comment]
Hey @kenkirito as you are already assigned three issue, please make sure to get atleast one of them merged in order to get more issues assigned.
@urvashi-code1255 you can go ahead with this issue.

**Comment by urvashi-code1255** [comment]
Thank you for assigning this to me 😄

**Comment by kenkirito** [comment]
i have completed my issues

**Comment by kenkirito** [comment]
i have made the pr

**Comment by Kajol-Kumari** [comment]
> i have made the pr

You need to make sure to get at least one of them merged. Also you haven't incorporated the requested changes. So please make sure to do that otherwise it's goona pile up which isn't good for both of us

**Comment by kenkirito** [comment]
ok

**Comment by urvashi-code1255** [comment]
@Kajol-Kumari I did other changes, but can you please tell from where the black border of input box is coming. I am unable to find it. I have spend a lot of time finding it. 😅

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari I did other changes, but can you please tell from where the black border of input box is coming. I am unable to find it. I have spend a lot of time finding it.

just click on any of the input field, you will get it

**Comment by urvashi-code1255** [comment]
No, I get it, but from code i am not getting it

**Comment by Kajol-Kumari** [comment]
> No, I get it, but from code i am not getting it

Maybe that's the default style of input field(on -click) try inspecting the element and changing the input tag on-click border color

**Comment by yashsehgal** [comment]
Can I work on this issue?

**Comment by Kp779** [comment]
@Kajol-Kumari i would like to resolve this issue.

**Comment by Kajol-Kumari** [comment]
Hey @Kp779 thanks for your interest but we can't asisgn this issue to more than one person. Please feel free to check out other issues

**Comment by Kp779** [comment]
@Kajol-Kumari ok sure
