### ISSUE TITLE
[Frontend] Hide/Show Icon change

### ISSUE THREAD

**Issue by urvashi-code1255** [HITK-TECH-Community/Community-Website#191]
Deliverable: 

- [ ] Change the hide/show icon to open eye when we can see the password and closed eye when input is of password type.

@Kajol-Kumari Please assign this issue to me.

**Comment by amanprateek123** [comment]
@urvashi-code1255  please assign this issue to me

**Comment by Kajol-Kumari** [comment]
Hey @urvashi-code1255 the third point of [this](https://github.com/HITK-TECH-Community/Community-Website/issues/180) issue covers this. Please feel free to close this issue

**Comment by urvashi-code1255** [comment]
Sure :)
