### ISSUE TITLE
[Frontend] Update the "Our Motives" sections in the Home Page. 

### ISSUE THREAD

**Issue by tejan-singh** [HITK-TECH-Community/Community-Website#213]
- Content to be loaded in sections can be found here.
https://docs.google.com/document/d/1CJ6KzyLUzI46xIFN59gjiLLnJ8x2CtvIKTFF7FrSch8/edit?usp=drivesdk
-  Replace the dummy data with this content along with relevant icons.
- No need to change the design.

**Comment by urvashi-code1255** [comment]
@tejan-singh  I want to work on this issue

**Comment by sakshi300699** [comment]
Would want to work on this.

**Comment by chait04** [comment]
I would like to work on this issue

**Comment by tejan-singh** [comment]
@urvashi-code1255 you can work on this issue.

**Comment by tejan-singh** [comment]
@chait04 we are accepting only assigned issues. Please read contribution guidelines.

**Comment by tejan-singh** [comment]
This is only available for one person.

**Comment by urvashi-code1255** [comment]
@tejan-singh thank you for assigning this issue to me

**Comment by urvashi-code1255** [comment]
@tejan-singh how should I add the content you provided? Like this?
![motive](https://user-images.githubusercontent.com/63122133/103903801-35fae280-50b1-11eb-9ef1-88c65832a531.PNG)

**Comment by Kajol-Kumari** [comment]
> @tejan-singh how should I add the content you provided? Like this?
> ![motive](https://user-images.githubusercontent.com/63122133/103903801-35fae280-50b1-11eb-9ef1-88c65832a531.PNG)

Hey @urvashi-code1255 you are supposed to replace the card's content with the content we provided you.

**Comment by urvashi-code1255** [comment]
@Kajol-Kumari Okay means I have to do some addition in that content as it's not enough?

**Comment by urvashi-code1255** [comment]
@Kajol-Kumari Also,please tell if these icons are Okay?

**Comment by himanshu007-creator** [comment]
i would like to work on this issue
please assign me this issue, if things don't work out

**Comment by tejan-singh** [comment]
> @Kajol-Kumari Okay means I have to do some addition in that content as it's not enough?

@urvashi-code1255 you have to put content in those cards that we provided you in the description of this issue.

**Comment by vedikaag99** [comment]
@tejan-singh Is this issue open to grab?

**Comment by tejan-singh** [comment]
@vedikaag99 its assigned.

**Comment by yashsehgal** [comment]
Can I work on this issue?

**Comment by urvashi-code1255** [comment]
> > @Kajol-Kumari Okay means I have to do some addition in that content as it's not enough?
> 
> @urvashi-code1255 you have to put content in those cards that we provided you in the description of this issue.

Okay☺

**Comment by urvashi-code1255** [comment]
![Capture](https://user-images.githubusercontent.com/63122133/104028754-f5b56600-517d-11eb-88a1-8e0b7d2f7b7a.PNG)

@Kajol-Kumari @tejan-singh Is this Okay?

**Comment by tejan-singh** [comment]
@urvashi-code1255  You can make a PR for this issue.
