### ISSUE TITLE
Enhacement in FAQ page

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#216]
Deliverables:

- [ ] Make the image and card containing FAQs one below another rather than side by side
- [ ] Give hover effect to the Faq card (#016795)

**Comment by urvashi-code1255** [comment]
@Kajol-Kumari Can I take this issue? Also, please give your review for https://github.com/HITK-TECH-Community/Community-Website/pull/188

Thanks & Regards
Urvashi Anand

**Comment by Kajol-Kumari** [comment]
Hey @urvashi-code1255 I request you to please get atleast one of your PRs merged before claiming any further issue

**Comment by urvashi-code1255** [comment]
Sure @Kajol-Kumari

**Comment by kenkirito** [comment]
can i work on this issue

**Comment by kenkirito** [comment]
i am done with my task and I had made the pr

**Comment by kenkirito** [comment]
and please u review my pr

**Comment by Kajol-Kumari** [comment]
Hey @kenkirito your PRs have conflicts and we can't review/test or merge any PR having conflicts! Also please try to keep the comments short and precise,like here you can have conveyed your word in a single line :)

Also I request you to please get atleast one of your PRs merged as they are getting piled up!

**Comment by kenkirito** [comment]
my one pr got merged 2 days ago

**Comment by chait04** [comment]
can i work on this .. everytime someone gets assinged on the issue i like

**Comment by kenkirito** [comment]
i have solved the conflicts

**Comment by Kajol-Kumari** [comment]
Hey @kenkirito you are still assigned 3 issues, please fix them first as we can only assign 2 issues at max to anyone!

**Comment by chait04** [comment]
hey @Kajol-Kumari can i work on this issue

**Comment by kenkirito** [comment]
ok

**Comment by shraddha-1402** [comment]
@Kajol-Kumari i would like to work on this issue, please assign me!

**Comment by Kajol-Kumari** [comment]
Hey @chait04 please go ahead with this issue. 

@shraddha-1402 please look for some other issue. We would be opening more very soon :)

**Comment by vedikaag99** [comment]
@Kajol-Kumari I would like to work on this.

**Comment by Kajol-Kumari** [comment]
Hey @vedikaag99 we can't assign this to more than one person. Please checkout other issues

**Comment by chait04** [comment]
1. First it look like this 
![Screenshot (182)](https://user-images.githubusercontent.com/59140343/103977776-f7902100-519f-11eb-9405-271d9cc5442e.png)

2.  which hover effect i have to add ...

**Comment by Kajol-Kumari** [comment]
Hey @chait04 please increase the width of the main card containing the faq cards and also provide a bit more margin/padding to left and right of the card containing faq-content

**Comment by chait04** [comment]
ok
