### ISSUE TITLE
Enhacement in About Us page

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#219]
Deliverables:

- [ ] Make the card containing team details look like [this](https://github.com/HITK-TECH-Community/Community-Website/blob/main/assets/About%20us%20page/SHIVANI%20WAKDE/About%20Us%202.png) having a cool hover effect.
- [ ] You can take the `Meet the crew` part from [here](https://www.canva.com/design/DAERm1blcVE/FgNJwq-gUKFeVXiBzXGQ4A/edit)
- [ ] Need better background image for the overview section

**Comment by vedikaag99** [comment]
@Kajol-Kumari I can work on this.

**Comment by Utkarshn10** [comment]
@Kajol-Kumari I would like to work in this issue. I was just waiting for my PR to get merged.

**Comment by Kajol-Kumari** [comment]
Hey @vedikaag99 you can go ahead with this issue. @Utkarshn10 we follow FCFS so please feel free to pick any other issues :)

**Comment by vedikaag99** [comment]
![Screen Shot 2021-01-10 at 4 38 55 PM](https://user-images.githubusercontent.com/67699840/104121177-5ac9b100-5362-11eb-9a8e-58fcc6c33af5.png)

**Comment by vedikaag99** [comment]
![Screen Shot 2021-01-10 at 4 38 49 PM](https://user-images.githubusercontent.com/67699840/104121188-6ae19080-5362-11eb-9607-d4af01eeec3e.png)
@Kajol-Kumari Couldn't find the exact images as given in the design for `Meet the Crew` part. Is this okay?

**Comment by vedikaag99** [comment]
![Screen Shot 2021-01-10 at 4 45 30 PM](https://user-images.githubusercontent.com/67699840/104121342-5356d780-5363-11eb-84b3-2dd05aa9bcc3.png)
