### ISSUE TITLE
Enhacement in Contact Us page

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#221]
Deliverables:

- [ ] Make background color white
- [ ] better box-shadow or border after clicking on input field.
- [ ] Provide standard hovering effect to the icons used in the input fields
- [ ] Make the pointer to cursor for icons of the input fields

**Comment by vedikaag99** [comment]
@Kajol-Kumari I would love to work on this.

**Comment by Kajol-Kumari** [comment]
Hey @vedikaag99 let's keep the background white, to maintain consistency and keep the form card color same as we have now

**Comment by vedikaag99** [comment]
ok, Should I also keep the Let's talk button in the centre?

**Comment by vedikaag99** [comment]
https://user-images.githubusercontent.com/67699840/103998983-7007d980-51c2-11eb-99f5-0bbeb91d5d33.mov

@Kajol-Kumari please review.

**Comment by Kajol-Kumari** [comment]
Hey @vedikaag99 it looks good. Just see if you can find any better icon for `pen-icon`
