### ISSUE TITLE
[ Frontend ] Make admin page UI

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#222]
Deliverables:

- [ ] Make admin page using [this](https://github.com/HITK-TECH-Community/Community-Website/blob/main/assets/Admin_page_assets/yashsehgal/admin-page.png) UI
- [ ] Try to implement it using [this](https://colors.lol/blocky) color pallet
- [ ] Add an `/admin` route that will direct to the admin's dashboard

**Comment by Utkarshn10** [comment]
@Kajol-Kumari In this we have to keep the navbar and footer as the original ones right?

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari In this we have to keep the navbar and footer as the original ones right?

No, we will have different navbar and footer for admin as it will show different options for admin

**Comment by Utkarshn10** [comment]
> > @Kajol-Kumari In this we have to keep the navbar and footer as the original ones right?
> 
> No, we will have different navbar and footer for admin as it will show different options for admin

Ok, I would like to work on it and also I am a Swoc participant. It was mentioned in the issue that I earlier worked on but not on the PR.

**Comment by Kajol-Kumari** [comment]
Thanks for pointing @Utkarshn10 and you can go ahead with this issue :)

**Comment by Utkarshn10** [comment]
@Kajol-Kumari This is how the page looks. Please suggest changes.
![Screenshot (13)](https://user-images.githubusercontent.com/58587256/104096023-15ed3e00-52c0-11eb-8a7d-6844aeb757fb.png)
![Screenshot (12)](https://user-images.githubusercontent.com/58587256/104096025-17b70180-52c0-11eb-9429-576d600bad56.png)

**Comment by Kajol-Kumari** [comment]
Hey @Utkarshn10 Just few changes. Under Dashboard section,, replace the text with following
1. Broadcasts
2. Admins
3. About Us
Keep a dummy count value for each of them and also replace these icon with more relevant ones.

**Comment by Utkarshn10** [comment]
@Kajol-Kumari  Changes suggested have been made.

Doubt: I have added  the admin dashboard in the navbar itself. Should I comment the code in app.js before making PR so that it can be used in future.

![Screenshot (14)](https://user-images.githubusercontent.com/58587256/104114432-68fbdb00-532a-11eb-91e4-9dee761be54b.png)

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari Changes suggested have been made.
> 
> Doubt: I have added the admin dashboard in the navbar itself. Should I comment the code in app.js before making PR so that it can be used in future.
> 
> ![Screenshot (14)](https://user-images.githubusercontent.com/58587256/104114432-68fbdb00-532a-11eb-91e4-9dee761be54b.png)

Yeah, just comment it as you have done this just for testing purpose. Also make a draft PR maybe so that I can test and suggest you the required changes

**Comment by Utkarshn10** [comment]
> > @Kajol-Kumari Changes suggested have been made.
> > Doubt: I have added the admin dashboard in the navbar itself. Should I comment the code in app.js before making PR so that it can be used in future.
> > ![Screenshot (14)](https://user-images.githubusercontent.com/58587256/104114432-68fbdb00-532a-11eb-91e4-9dee761be54b.png)
> 
> Yeah, just comment it as you have done this just for testing purpose. Also make a draft PR maybe so that I can test and suggest you the required changes

By draft PR you mean normal PR, right?

**Comment by kanishkaa24** [comment]
Hey @Kajol-Kumari 
Can I work on this issue ?

**Comment by Kajol-Kumari** [comment]
Hey @kanishkaa24 we can't assign this to more than one person
