### ISSUE TITLE
[Frontend] Make navbar for admin panel

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#223]
Deliverables:

- [ ] Make the navbar for admin panel taking reference from [this](https://github.com/HITK-TECH-Community/Community-Website/blob/main/assets/Admin_page_assets/yashsehgal/admin-page.png) UI

**Comment by chait04** [comment]
I would like to work on this issue

**Comment by Swapnil-Gaur** [comment]
@kajol Kumari can I work on it?

**Comment by Kajol-Kumari** [comment]
Hey @Swapnil-Gaur we serve FCFS so I request you to please look for any other issue.

**Comment by chait04** [comment]
@Swapnil-Gaur u can go for it

**Comment by Kajol-Kumari** [comment]
@Swapnil-Gaur would you like to go ahead with this issue?

**Comment by Swapnil-Gaur** [comment]
Just one thing I wanna know that can I  use css According to me or there is any particular format is there?

**Comment by Kajol-Kumari** [comment]
> Just one thing I wanna know that can I use css According to me or there is any particular format is there?
we just use `preetier` for formatting, apart from this we don't have any specific format

**Comment by carbseater** [comment]
Is this issue available for working ? @Kajol-Kumari

**Comment by Kajol-Kumari** [comment]
Yeah @carbseater it's up for grab

**Comment by carbseater** [comment]
But I guess one person is already working , So should i look upon this issue ? @Kajol-Kumari , If not then assign me.
Dwoc participant

**Comment by Kajol-Kumari** [comment]
@carbseater he hasn't given any confirmation till now so you can go ahead with this issue.

**Comment by kenkirito** [comment]
assign me @Kajol-Kumari

**Comment by carbseater** [comment]
Sorry brother I'm working on the nav @kenkirito

**Comment by Swapnil-Gaur** [comment]
@kajol I am working on the issue.

**Comment by Kajol-Kumari** [comment]
@Swapnil-Gaur @carbseater i m going to accept the PRs from both of you 
@kenkirito please look for some other issue.

**Comment by Kajol-Kumari** [comment]
@Swapnil-Gaur @carbseater please provide the update on this PR

**Comment by Swapnil-Gaur** [comment]
Need one day please,

**Comment by Sloth-Panda** [comment]
@Kajol-Kumari would love to do this please let me know can make Pr in a day

**Comment by kenkirito** [comment]
@Kajol-Kumari can I work on this issue

**Comment by ashuvssut** [comment]
@Kajol-Kumari  THE UI example link is giving a 404 Page not found

**Comment by Kajol-Kumari** [comment]
Hey! This issue has been resolved now so closing this.
