### ISSUE TITLE
Enhacement in Resource sharing Page UI

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#224]
Deliverables:

- [ ] Add icon in each input field just like `contact-us` page 
- [ ] Make the cursor pointer for icons
- [ ] Add hover effect to the icons
- [ ] On click, the input box background color should be white
- [ ] Beeter border/box-shadow on click to the input field

**Comment by kenkirito** [comment]
assign me I have done my all task.please

**Comment by carbseater** [comment]
Can I collab on this project. I am a DWOC participant. Thanks

**Comment by Kajol-Kumari** [comment]
@carbseater please go ahead with this issue. @kenkirito waiting for your commit on the PR for the requested changes :)

**Comment by carbseater** [comment]
> Deliverables:
> 
> * [ ]  Add icon in each input field just like `contact-us` page
> * [ ]  Make the cursor pointer for icons
> * [ ]  Add hover effect to the icons
> * [ ]  On click, the input box background color should be white
> * [ ]  Beeter border/box-shadow on click to the input field

I have completed the starting 4 targets , Could you explain 5th point that what do you mean by Beeter border ? Is it "Better" you trying to say ;If yes then should it be like the contact-us page input box-shadows or different from that @Kajol-Kumari

**Comment by Kajol-Kumari** [comment]
Hey @carbseater sorry for typo, please make the box shadow/border here same sa that used in [this](https://github.com/HITK-TECH-Community/Community-Website/pull/228) PR
