### ISSUE TITLE
Enhancement in login page

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#226]
Deliverables:

- [ ] Replace current image on login page with [this](https://github.com/HITK-TECH-Community/Community-Website/blob/main/frontend/src/components/auth/loginPage-VaishnaviShah/student-login.png) image
- [ ] Make the background of the page white
- [ ] Make the `Sign In` button same as `submit` button on `contact-us` page
- [ ] Add hover effect to the icons of the input box with proper hovering effect

**Comment by musavveer** [comment]
@Kajol-Kumari I would like to give it a try.

**Comment by Kajol-Kumari** [comment]
Sure @musavveer go ahead with this issue

**Comment by vedikaag99** [comment]
@Kajol-Kumari Is this issue open to grab?

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari Is this issue open to grab?

No @vedikaag99 I can only assign this issue to one person

**Comment by kenkirito** [comment]
can you assign me this issue @Kajol-Kumari

**Comment by Kajol-Kumari** [comment]
> can you assign me this issue @Kajol-Kumari

@kenkirito all the issues with `no more assignment` label can't be assigned to anyone anymore. So i can't assign this to you

**Comment by Kajol-Kumari** [comment]
@musavveer can you please provide me the update on this issue?

**Comment by Sloth-Panda** [comment]
@Kajol-Kumari  would love to work on this can make a pr soon very soon too let me know

**Comment by musavveer** [comment]
> @musavveer can you please provide me the update on this issue?
Sorry for the inconvenience! I'm busy with my exams so please assign it to someone else.😞

**Comment by Sloth-Panda** [comment]
@Kajol-Kumari  would love to work on this. Please assign it to me

**Comment by kenkirito** [comment]
assign to me i will complete it by midnight

**Comment by vedikaag99** [comment]
@Kajol-Kumari I would like to work on it.

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari would love to work on this can make a pr soon very soon too let me know

Hey @Sloth-Panda please go ahead with this issue and @kenkirito @vedikaag99 we would be opening more issues very soon!

**Comment by Kajol-Kumari** [comment]
@Sloth-Panda can you please provide the update on this issue?

**Comment by Sloth-Panda** [comment]
I will be making the pr tomorrow

**Comment by Sloth-Panda** [comment]
@Kajol-Kumari  you can checkout the pr now
