### ISSUE TITLE
[bug] Issue templates are not appearing as expected

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#229]
Deliverables:

- [ ] Make the bug and feature templates appear properly.
- [ ] Test it on your forked repo and share the screenshot

**Comment by carbseater** [comment]
Where is the issues template ? I couldn't able to find and how do you expect it to look ? @Kajol-Kumari .
I am a Dwoc participant and interested in this issue.
Thanks

**Comment by Kajol-Kumari** [comment]
Hey @carbseater you will find the issue templates at [here](https://github.com/HITK-TECH-Community/Community-Website/tree/main/.github/ISSUE_TEMPLATE)  It's content is fine. But it was supposed to show up whenever someone clicks on `create new issue` in this repo but isn't showing up. This issue is for the same

**Comment by carbseater** [comment]
Ok i got it, can i work on this @Kajol-Kumari

**Comment by Kajol-Kumari** [comment]
Sure @carbseater go ahead with this issue
