### ISSUE TITLE
[Frontend] Enhance the carousel in the homepage. 

### ISSUE THREAD

**Issue by salil-naik** [HITK-TECH-Community/Community-Website#232]
In the **Curious to know more about us?** section

- [ ] Add padding on top and bottom of the section
- [ ] Fix the carousel navigation buttons. Make sure the chevron icon is vertically centre aligned. 
- [ ] Fix the mobile view as the cards look very small when viewed on the mobile device.

**Comment by urvashi-code1255** [comment]
![Capture](https://user-images.githubusercontent.com/63122133/104090261-7f227200-522a-11eb-9547-44927a67a138.PNG)
In mobile view, Cards are of this size. What to do with them @salil-naik. Looks Good to me

**Comment by urvashi-code1255** [comment]
![Capture](https://user-images.githubusercontent.com/63122133/104090306-ba24a580-522a-11eb-94e1-405b21746da0.PNG)
And below this, it will be like one card in one row.

**Comment by urvashi-code1255** [comment]
![Capture](https://user-images.githubusercontent.com/63122133/104090504-10deaf00-522c-11eb-97f1-b06cf274065c.PNG)
@salil-naik I think chevron icon is vertically centre aligned in this picture. Otherwise please let me know what type of change do you expect?

**Comment by salil-naik** [comment]
@urvashi-code1255 which branch are you working on? I don't see any of these changes in the main branch.

**Comment by urvashi-code1255** [comment]
Ohh😅 I m.on Our_motives branch made by me

**Comment by urvashi-code1255** [comment]
Let me see on main branch

**Comment by urvashi-code1255** [comment]
![Capture](https://user-images.githubusercontent.com/63122133/104090682-45069f80-522d-11eb-8a55-719b71c3b06c.PNG)
Okay Are you talking about this size of card at 500px @salil-naik ?

**Comment by salil-naik** [comment]
> Ohh😅 I m.on Our_motives branch made by me

As per the screenshots you shared earlier, it looks like its already fixed in the branch you are working on.

**Comment by urvashi-code1255** [comment]
> > Ohh😅 I m.on Our_motives branch made by me
> 
> As per the screenshots you shared earlier, it looks like its already fixed in the branch you are working on.

No @salil-naik Its not fixed for around 500px.

**Comment by urvashi-code1255** [comment]
Can you assign me this issue @salil-naik ?

**Comment by salil-naik** [comment]
@urvashi-code1255 In dev tools there is an option to select the mobile sizes. Kindly make sure it works fine for **iPhone 6/7/8** and **iPhone 5/SE**

I have attached an image below.

![image](https://user-images.githubusercontent.com/20141508/104090388-6b175880-529c-11eb-9478-332350cde613.png)

**Comment by urvashi-code1255** [comment]
Sure @salil-naik

**Comment by kenkirito** [comment]
can i work on this issue @salil-naik

**Comment by urvashi-code1255** [comment]
I m working on it. My viva were going on. I will do it now.

**Comment by urvashi-code1255** [comment]
![1](https://user-images.githubusercontent.com/63122133/104430172-31b04880-553b-11eb-8e85-4d2ca8cfdcdc.PNG)
![2](https://user-images.githubusercontent.com/63122133/104430263-55738e80-553b-11eb-93ed-43da2465b87c.PNG)
![3](https://user-images.githubusercontent.com/63122133/104430562-b00cea80-553b-11eb-9dd6-0f11b1e6423c.PNG)
![4](https://user-images.githubusercontent.com/63122133/104430572-b56a3500-553b-11eb-885f-6ddc7e94cbdd.PNG)
![5](https://user-images.githubusercontent.com/63122133/104430593-bd29d980-553b-11eb-9ab5-de138f6de7ba.PNG)

@salil-naik Please check.

**Comment by salil-naik** [comment]
@urvashi-code1255 good job so far! 👌 Please make sure there is a padding of at least 20px on either side of the card for smaller view ports.

**Comment by urvashi-code1255** [comment]
Sure @salil-naik

**Comment by urvashi-code1255** [comment]
![1](https://user-images.githubusercontent.com/63122133/104440008-ac329580-5546-11eb-9721-aaf11743c71a.PNG)
![2](https://user-images.githubusercontent.com/63122133/104440035-b6549400-5546-11eb-87bb-299cdb157459.PNG)
![3](https://user-images.githubusercontent.com/63122133/104440094-c66c7380-5546-11eb-9df6-cedef3722898.PNG)
![4](https://user-images.githubusercontent.com/63122133/104440130-d1bf9f00-5546-11eb-8ada-ca5e7fed9a8f.PNG)

@salil-naik Please check now.

**Comment by salil-naik** [comment]
Good. You can make a PR. I'll review your code.

**Comment by Amit366** [comment]
Is this issue still open??

**Comment by salil-naik** [comment]
> can i work on this issue @salil-naik.

Do you want to work on this issue @kenkirito?

**Comment by kenkirito** [comment]
Yes

**Comment by kenkirito** [comment]
https://lakshya-gmail-3.tinytake.com/media/f08210?filename=1610725106172_TinyTake_15-01-2021-09-08-17.png&sub_type=thumbnail_preview&type=attachment&width=1199&height=760

**Comment by salil-naik** [comment]
@kenkirito Add padding of 20px on either side and show the buttons as well.

**Comment by kenkirito** [comment]
ok

**Comment by kenkirito** [comment]
https://lakshya-gmail-3.tinytake.com/media/f0e24f?filename=1611024625004_TinyTake_19-01-2021-08-20-17.png&sub_type=thumbnail_preview&type=attachment&width=1199&height=760

**Comment by salil-naik** [comment]
> @kenkirito  In dev tools there is an option to select the mobile sizes. Kindly make sure it works fine for **iPhone 6/7/8** and **iPhone 5/SE**
> 
> I have attached an image below.
> 
> ![image](https://user-images.githubusercontent.com/20141508/104090388-6b175880-529c-11eb-9478-332350cde613.png)

**Comment by kenkirito** [comment]
https://lakshya-gmail-3.tinytake.com/media/f10879?filename=1611103761337_TinyTake_20-01-2021-06-19-07.png&sub_type=thumbnail_preview&type=attachment&width=1199&height=760

**Comment by kenkirito** [comment]
@salil-naik i have solved the issue should I make the pr

**Comment by kenkirito** [comment]
https://lakshya-gmail-3.tinytake.com/media/f11787?filename=1611141699420_TinyTake_20-01-2021-04-51-31.png&sub_type=thumbnail_preview&type=attachment&width=1199&height=760
