### ISSUE TITLE
[Frontend] Fix the hero image in about us. 

### ISSUE THREAD

**Issue by salil-naik** [HITK-TECH-Community/Community-Website#233]
The image in the hero section of the **about page** stretches in a weird way. 

Resize the image to fit its container. Note that the dimension of the image remains the same. Just fit the image by preserving the aspect ratio of the original image with the help of CSS.

**Comment by abhay313** [comment]
Please assign this to me

**Comment by abhay313** [comment]
![Screenshot from 2021-01-09 21-21-35](https://user-images.githubusercontent.com/43968252/104096167-decb5c80-52c0-11eb-918d-e792833bbe2b.png)

Is it fine ?

**Comment by salil-naik** [comment]
yes.

**Comment by abhay313** [comment]
ok and thanks for your reply
