### ISSUE TITLE
Enhancement in Broadcast page

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#234]
Deliverables:

- [ ] Remove the unnecessary `recent broadcast` section present at the end of the page
- [ ] Fix the card size and make the line break in the form of ellipses(...)
- [ ] The ellipses(...) shouldn't be hardcoded
- [ ] The modal should show the text of the particular card on which the user will click

**Comment by Kajol-Kumari** [comment]
@amanprateek123 please claim this issue so that I can assign this to you

**Comment by amanprateek123** [comment]
@Kajol-Kumari  Got it!! Thank you for assigning me

**Comment by Sloth-Panda** [comment]
Hey, can I too work on this issue??

**Comment by Kajol-Kumari** [comment]
> Hey, can I too work on this issue??

Hey! Can't assign this to more than one person. Will be opening up new issues very soon :)
