### ISSUE TITLE
[Bug] Fix the buttons for small screens

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#235]
Deliverables:

- [ ] Fix the button for resource sharing form for small screens
- [ ] Fix the button on contact-us page for small screens

![Screenshot from 2021-01-09 14-42-52](https://user-images.githubusercontent.com/44888949/104088095-5d58d780-528a-11eb-9bbf-e053a5441cda.png)

![Screenshot from 2021-01-09 14-43-02](https://user-images.githubusercontent.com/44888949/104088082-41553600-528a-11eb-9643-8f3bbb1fdef2.png)

**Comment by kenkirito** [comment]
can I work o this issue

**Comment by mohit355** [comment]
Go ahead @kenkirito

**Comment by kenkirito** [comment]
ok

**Comment by kenkirito** [comment]
done

**Comment by kenkirito** [comment]
![HITK Tech Community and 6 more pages - Personal - Microsoft​ Edge 10-01-2021 04_47_48 PM](https://user-images.githubusercontent.com/68530218/104122020-8a7bb780-5368-11eb-83c1-52ea41e2835f.png)
![HITK Tech Community and 6 more pages - Personal - Microsoft​ Edge 10-01-2021 04_46_50 PM](https://user-images.githubusercontent.com/68530218/104122031-a1220e80-5368-11eb-9851-b34ed8d0cb58.png)

**Comment by kenkirito** [comment]
## Issue that this pull request solves

#Font size of Button

 Closes: # (235)

## Proposed changes
I have changed the font size of buttons 

### Brief description of what is fixed or changed

## Types of changes

_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] My changes does not break the current system and it passes all the current test cases.

## Screenshots



## Other information

Any other information that is important to this pull request

**Comment by kenkirito** [comment]
please check @mohit355

**Comment by mohit355** [comment]
@kenkirito  Attach these Snapshots to respective PR

**Comment by kenkirito** [comment]
i was asked to send pr from a branch, not from main branch

**Comment by kenkirito** [comment]
@tejan-singh  ask me to Send PR from a branch, not from the main branch. @mohit355  i will also reopen  my request and upload the changes

**Comment by mohit355** [comment]
> @tejan-singh ask me to Send PR from a branch, not from the main branch. @mohit355 i will also reopen my request and upload the changes

He is Right, Never forgot to create a branch from the main branch before creating a PR.

**Comment by kenkirito** [comment]
@mohit355  done check
