### ISSUE TITLE
ADD ISSUE_TEMPLATE

### ISSUE THREAD

**Issue by tharunc** [HITK-TECH-Community/Community-Website#238]
Hello there,
           I would like to add an issue template for your repository. This template would have four issues namely bug, documentation, feature, proposal. Kindly assign me this issue as a part of **DWOC**.
THANK YOU

**Comment by Kajol-Kumari** [comment]
Hey @tharunc I appreciate your time for reporting this but we already have bug and feature request issue templates. Tho I would be happy if you can enhance them a bit and add other templates as well
