### ISSUE TITLE
Enhancement in Resource sharing page

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#247]
Deliverables:

- [ ] Make the top margin small, same as `contact-us` page
- [ ] Change the pencil icon with the same icon being used in `contact-us` page
- [ ] The calender icon should also have the hovering effect and cursor pointer
- [ ] Replace the `level of trust` checkbox with select box having the placeholder of `level of trust`
- [ ] Put the `valid until` text under input box only

**Comment by urvashi-code1255** [comment]
@Kajol-Kumari can I take this issue?

**Comment by Kajol-Kumari** [comment]
sure @urvashi-code1255

**Comment by kenkirito** [comment]
Can i take this issue

**Comment by Sloth-Panda** [comment]
@Kajol-Kumari  Hey I can help with this let me know

**Comment by Sloth-Panda** [comment]
@Kajol-Kumari  if not issue is not yet solved can you please assign it to me cause it's been few days
