### ISSUE TITLE
Enhancement in `our motive` section

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#248]
Deliverables:

- [ ] On hovering, the whole card content should be white
- [ ] Make the icon size a bit smaller

**Comment by abhay313** [comment]
Please assign this to me

**Comment by abhay313** [comment]
![Screenshot from 2021-01-11 22-34-23](https://user-images.githubusercontent.com/43968252/104214338-4d452180-545d-11eb-8b4c-f13811dafb6d.png)

text and icons are already white on hovering what else we have to change on hovering of card?

**Comment by salil-naik** [comment]
@abhay313 Please pull the changes from the main branch.

**Comment by abhay313** [comment]
Please check size of icons

**size: 40px**

![Screenshot from 2021-01-12 09-16-38](https://user-images.githubusercontent.com/43968252/104267385-8611e480-54b7-11eb-942d-57dffeb8a2dd.png)

**size: 50px**

![Screenshot from 2021-01-12 09-16-53](https://user-images.githubusercontent.com/43968252/104267425-9fb32c00-54b7-11eb-990e-8c1646e70e6d.png)

**size: 55px**

![Screenshot from 2021-01-12 09-27-33](https://user-images.githubusercontent.com/43968252/104267890-98d8e900-54b8-11eb-81fb-46fee7c33fa7.png)

**size: 60px**

![Screenshot from 2021-01-12 09-17-24](https://user-images.githubusercontent.com/43968252/104267497-b35e9280-54b7-11eb-9800-577184988445.png)

**Comment by Kajol-Kumari** [comment]
@abhay313 can we please have a better icon for the third card. Rest looks good to go!

**Comment by salil-naik** [comment]
@abhay313 40px is fine.

Give padding/margin on either side of the icon. 
If you see the first-ever screenshot you pasted in this thread, there is equal padding/margin on left and right of the icon.

**Comment by abhay313** [comment]
Please check it once
`size: 40px;`
`margin: 5px 10px 0 5px;`

![Screenshot from 2021-01-12 12-55-34](https://user-images.githubusercontent.com/43968252/104282903-be282000-54d5-11eb-9d97-402c09c4d0d5.png)

**Comment by abhay313** [comment]
do we need to change third icon ?

**Comment by salil-naik** [comment]
> do we need to change third icon ?

Yes.

**Comment by abhay313** [comment]
Can you suggest anyone, please ?

**Comment by abhay313** [comment]
https://fontawesome.com/icons/book-open?style=solid
https://fontawesome.com/icons/chalkboard-teacher?style=solid
https://fontawesome.com/icons/graduation-cap?style=solid
https://fontawesome.com/icons/book-reader?style=solid

anyone looks better?

**Comment by Kajol-Kumari** [comment]
Hey @abhay313 let's use [this](https://fontawesome.com/icons/user-graduate?style=solid) icon
