### ISSUE TITLE
[Frontend] Enhancing the top section of the homepage in mobile view.

### ISSUE THREAD

**Issue by salil-naik** [HITK-TECH-Community/Community-Website#249]
In the top section of the homepage, the left-aligned text and title look off below the centre aligned image.

Make the title and text centre aligned in order to attain consistency in design. (_In mobile view only_)
![image](https://user-images.githubusercontent.com/20141508/104208183-8a59e580-5456-11eb-9557-f3661737c884.png)

**Comment by AbhipsaGuru1012** [comment]
@salil-naik I would like to work on this issue.
