### ISSUE TITLE
Enhancement in Privacy policy Page

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#257]
Deliverables:

- [ ] Populate the `privacy-policy` page with the data written in [here](https://docs.google.com/document/d/1oEMf8bfSkvUN3JCWAsCwtqaWc12Qd-FyC4qQx-cTnko/edit?usp=sharing)
- [ ] Enhance the design of the page in order to have these data fit properly on the page

**Comment by vedikaag99** [comment]
@Kajol-Kumari Can I work on this issue?

**Comment by Kajol-Kumari** [comment]
sure @vedikaag99 !

**Comment by Sloth-Panda** [comment]
Would like to work on this @Kajol-Kumari
