### ISSUE TITLE
Settings page for Admin

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#259]
Deliverables:

- [ ] Add `settings` card on the admin dashboard
- [ ] It should take to a Page having the details of the admin(put dummy data as of now) and a section below that `Invite Admins`
- [ ] `Invite Admins` section should have a form kind of thing having only one field i.e `email` along with a button `Send Invitation`

**Comment by kenkirito** [comment]
can I work on this

**Comment by Kajol-Kumari** [comment]
Go ahead @kenkirito

**Comment by kenkirito** [comment]
@Kajol-Kumari just wanted to ask should I have to add one more card below the sign-in page in the admin for it

**Comment by Kajol-Kumari** [comment]
Hey @kenkirito on the admin dashboard you would be able to see the `Dashboard`. You can see that dashboard by uncommenting the code of `navbar` component

**Comment by kenkirito** [comment]
@Kajol-Kumari I will be making pr at midnight

**Comment by kenkirito** [comment]
![111](https://user-images.githubusercontent.com/68530218/105503262-5ef3b800-5cec-11eb-80ad-0ec173a7e56e.png)
![112](https://user-images.githubusercontent.com/68530218/105503276-61eea880-5cec-11eb-8bc4-45321ef9d957.png)

**Comment by kenkirito** [comment]
i have link thhe first page on setting option

**Comment by kenkirito** [comment]
@Kajol-Kumari review

**Comment by Kajol-Kumari** [comment]
Make the heading of this section to `Invite Admins` and there should be a `invite` button after the input field in the form

**Comment by kenkirito** [comment]
ok sure
