### ISSUE TITLE
[Backend] Login/Signup api only for admin

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#26]
- API for allowing users to signup as admin and only after admin approves that person, he/she will be given admin previledges.

There won't be any signup/login for normal users

**Comment by Aaryan8751** [comment]
@Kajol-Kumari Could you please provide some information about the login/signup API. Do we need to create a new API or we have to use some other API.

**Comment by NewCoderBoi** [comment]
Is there an existing api for user login and authentication? @Aaryan8751

**Comment by Kajol-Kumari** [comment]
Hey @Aaryan8751 WE need to create a new APIs for login and signup by integrating it with JWT. Also this will require the database integration for store the users info for which we would be using mongoDB atlas.

**Comment by Aaryan8751** [comment]
@Kajol-Kumari ok I understood. Could you assign me this work?

**Comment by Kajol-Kumari** [comment]
sure @Aaryan8751 You can go ahead with this issue :)

**Comment by Aaryan8751** [comment]
@Kajol-Kumari the structure of the backend seems a little different may I make a new one using the express-generator.

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari the structure of the backend seems a little different may I make a new one using the express-generator.

Surr @Aaryan8751 as  it is hust strating stage you can go ahead with doing the changes :)

**Comment by jackfrost13** [comment]
@Aaryan8751 Noted! Will review it asap
