### ISSUE TITLE
Enhacement in Footer

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#260]
Deliverables:

- [ ] After clicking on input field of the footer, it should have same border as other input fields of the forms on the website 
- [ ] Fix the color of gmail icon of the footer to white(same as other icons)

**Comment by vedikaag99** [comment]
@Kajol-Kumari can I work on this?

**Comment by AbhipsaGuru1012** [comment]
@Kajol-Kumari can I work on this issue?

**Comment by Kajol-Kumari** [comment]
Hey @vedikaag99 as you already have 3 issues assigned so can't assign this to you untill any of your PR gets merged. 

@AbhipsaGuru1012 go ahead with this issue.
