### ISSUE TITLE
[Frontend] Admin Login and Signup Page

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#27]
There would be a login and signup screen only for admins so in this PR.

We need the Frontend pages for
1. Login
2. Signup

**Comment by Aaryan8751** [comment]
@Kajol-Kumari I wanna work on this.

**Comment by Kajol-Kumari** [comment]
Sure @Aaryan8751 you can go ahead with it.

**Comment by Aaryan8751** [comment]
@Kajol-Kumari I have added the login and signup front-end. The pull request is merged with Issue#10.
![LoginSignup](https://user-images.githubusercontent.com/60098288/101653007-e949ca80-3a64-11eb-85b8-36fce3584ed3.png)
Here is the screenshot of the login and signup front-end.

**Comment by Kajol-Kumari** [comment]
Closing via [this](https://github.com/HITK-TECH-Community/Community-Website/pull/29) PR
