### ISSUE TITLE
Enhacment in Admin Dashboard

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#271]
This issue is more of a discussion as we would only be accepting one PR for this after we are done with the discussion in here.

Deliverables:
- Better UI for the Admin dashboard. You can see this by vising the `admin-dashboard` path on dev-setup

**Please make sure to show us the design here so that we can verify if it's acceptable or not**

**Comment by vedikaag99** [comment]
@Kajol-Kumari I can give it a try!

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari I can give it a try! The PR will only be the design or the entire implementation of it as well?

we want it's implementation as well but that only after we gave confirmation to go ahead with the design or screenshot that you can share here :)

**Comment by amanprateek123** [comment]
Please assign this issue to me

**Comment by Kajol-Kumari** [comment]
> Please assign this issue to me

Hey @amanprateek123 please feel free to show us the design here and we would be happy to assign you :)

**Comment by amanprateek123** [comment]
@Kajol-Kumari  Got it!

**Comment by ishubham21** [comment]
Can I work on this under SWOC?

**Comment by Kajol-Kumari** [comment]
> Can I work on this under SWOC?

Hey @ishubham21 sure. Give it a try and let me know your progress.
