### ISSUE TITLE
Enhancement in Resource Sharing Page

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#276]
Deliverables:

- [ ] Remove the `Phone no.` field from the resource sharing form.
- [ ] Make the calender icon's by-default color same as other icons
- [ ] Make the radio button fill color same as linear gradient color used for border of input field on click.

**Comment by urvashi-code1255** [comment]
@Kajol-Kumari Can I work on this issue?

**Comment by Kajol-Kumari** [comment]
sure @urvashi-code1255 go ahead with this issue!

**Comment by urvashi-code1255** [comment]
> * [ ]  Make the radio button fill color same as linear gradient color used for border of input field on click.

@Kajol-Kumari Could you suggest any way to do this? As I have searched but there is no way I found to achieve this

**Comment by Kajol-Kumari** [comment]
@urvashi-code1255 please checkout [this](https://stackoverflow.com/questions/4253920/how-do-i-change-the-color-of-radio-buttons#:~:text=Change%20the%20outer%20rim%20color,drop%20shadow%20inset%20where%20needed. ) For radio button's fill color change and for linear gradient checkout [this](https://github.com/HITK-TECH-Community/Community-Website/blob/main/frontend/src/components/resource/resources.css#L103) You need to apply tye same gradient

**Comment by urvashi-code1255** [comment]
I will send its PR tomorrow....

**Comment by urvashi-code1255** [comment]
![Capture](https://user-images.githubusercontent.com/63122133/105635025-de1cf380-5e86-11eb-85ec-07514c27f78f.PNG)

@Kajol-Kumari Is this Okay?

**Comment by Kajol-Kumari** [comment]
Hey @urvashi-code1255 don't fill the whole radio button, leave a little gap like we have previously. Rest looks good!
