### ISSUE TITLE
[frontend] Join Us Page

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#277]
Deliverables:

- [ ] Add a `join us ` section below `curious to know about us` section on the home page
- [ ] Edit the already present [Join us component](https://github.com/HITK-TECH-Community/Community-Website/tree/main/frontend/src/components/home/join_us) to have a button `Join Us`  which will direct to a page containing a form having the fields same as [this](https://docs.google.com/forms/d/1WfwwnS1B_DUMSR1NAK_f1u1bOWEt2beO2Nk_vVZCfNc/edit?ts=5f9af712) form.
- [ ] Add `college name` field as well in the form
- [ ] Make sure it's UI isconsistent with the other pages like `contact-us`

**Comment by vedikaag99** [comment]
@Kajol-Kumari can I work on this issue?

**Comment by Sloth-Panda** [comment]
@Kajol-Kumari would like to work on this

**Comment by nehaparmar99** [comment]
I'd like to work on it.

**Comment by Kajol-Kumari** [comment]
Hey @vedikaag99 @Sloth-Panda @nehaparmar99 I am Sorry but I can only assign it to one of you and that also on the basis of FCFS So here I am assigning it to @Sloth-Panda  as @vedikaag99 is already working on two issues currently(corousel one & Admin dashboard enhacement) We will be opening more issue very soon. Please keep an eye. 

Happy learning :)

**Comment by Kajol-Kumari** [comment]
@Sloth-Panda can you please provide an update on this issue?

**Comment by Sloth-Panda** [comment]
I am on it @Kajol-Kumari  will let you know by tomorrow

**Comment by Sloth-Panda** [comment]
I am so sorry got busy in few other things have unassigned self

**Comment by nehaparmar99** [comment]
Can I work on it then?

**Comment by vedikaag99** [comment]
@Kajol-Kumari can I work on it then?

**Comment by Kajol-Kumari** [comment]
@vedikaag99 please go ahead with this issue.

**Comment by vedikaag99** [comment]
![Screen Shot 2021-01-28 at 3 14 52 PM](https://user-images.githubusercontent.com/67699840/106119784-972b4880-617b-11eb-99a0-ee969f37b271.png)
![Screen Shot 2021-01-28 at 3 14 35 PM](https://user-images.githubusercontent.com/67699840/106119816-9eeaed00-617b-11eb-951d-3bc12114e2f7.png)
@Kajol-Kumari Is this okay?

**Comment by Kajol-Kumari** [comment]
@vedikaag99 this looks preety good! Just change the text below `join us` `Join us in the mission of reducing the knowledge gap in students`
