### ISSUE TITLE
Use bootstrap container for carousel in the homepage

### ISSUE THREAD

**Issue by salil-naik** [HITK-TECH-Community/Community-Website#279]
Use bootstrap's container class to contain the carousel. On bigger screens, the content (carousel) should remain in between. 
Refer to Our Motive section on the homepage. (image attached below)

![image](https://user-images.githubusercontent.com/20141508/105191722-6afd3f80-5b5d-11eb-8db3-5ef988c46ce5.png)

**Comment by vedikaag99** [comment]
@salil-naik hey I can work on this.

**Comment by vedikaag99** [comment]
![Screen Shot 2021-01-20 at 10 06 04 PM](https://user-images.githubusercontent.com/67699840/105205865-b7e81280-5b6b-11eb-8da8-7380b0afc4f3.png)
![Screen Shot 2021-01-20 at 10 05 09 PM](https://user-images.githubusercontent.com/67699840/105205871-b9b1d600-5b6b-11eb-9904-4a8a2080511b.png)
done. please check @salil-naik
