### ISSUE TITLE
[Open For all] Admin Home page UI

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#28]
There would be a separate page for admins only:

1. Home page 
2. Settings Tab [ for approving users as admin ]
3. Manage Broadcast page 

Any other basic tabs that an admin is expected to have.

**Comment by sreechand2002** [comment]
Is this the admin dashboard with the above mentioned tabs in the sidebar ?

**Comment by Kajol-Kumari** [comment]
> Is this the admin dashboard with the above mentioned tabs in the sidebar ?
> can you give me more description above mentioned pages ?

Hey @sreechand2002 Yes, this is the admin dashboard and regarding the tabs, it can be either on the side or on the top nav-bar whichever design will look better, we will pick that up. This issue only demands the UI of the admin dashboard and we will open the issues u=for other pages shortly.

**Comment by LNR14** [comment]
Is this issue completed? Or can I work on this issue?

**Comment by Kajol-Kumari** [comment]
> Is this issue completed? Or can I work on this issue?

Hey @LNR14 this issue if open for grab. You can go ahead with this issue. Please confirm once if you want to go ahead with it, so that I can assign it to you.

**Comment by LNR14** [comment]
yes I want to go ahead with this issue. I have completed the issue and can push the changes to master if necessary. 

- [x] I have completed the admin page 
- [x] Created a navbar and this can be accessed using '/admin' in the url
![admin Page](https://user-images.githubusercontent.com/27141814/102400851-138d1200-3fa8-11eb-87f7-dd2c85b8cd0a.PNG)

**Comment by Kajol-Kumari** [comment]
Hey @LNR14 the issue is of design only(not code) i.e you just need to come up with a UI design which we can use for coding later. You can use tools like figma for the same. Please let me know if you need any further clarification.

**Comment by LNR14** [comment]
Are there any issues related to development rather than design? If there is please let me know. thank you

**Comment by Kajol-Kumari** [comment]
Hey @LNR14 maybe you should look at [this](https://github.com/HITK-TECH-Community/Community-Website/issues/53) issue. It's for design implementation i.e development. Let me know if you would like to go ahead with this issue.

**Comment by SuNiL-Chau** [comment]
Hi @Kajol-Kumari can I contribute to this design?

**Comment by Kajol-Kumari** [comment]
> Hi @Kajol-Kumari can I contribute to this design?

sure @SuNiL-Chau You can go ahead with this issue.

**Comment by SuNiL-Chau** [comment]
Hey @Kajol-Kumari can you please provide me brand colours?

**Comment by Kajol-Kumari** [comment]
Hey @SuNiL-Chau you need to follow [this](https://colors.lol/blocky) color pallet

**Comment by SuNiL-Chau** [comment]
Hey @Kajol-Kumari kindly have a look into below figma file link and will be waiting for your feedback.
https://www.figma.com/file/KIwDSv3VcoD682JFVdgPuK/test?node-id=0%3A1

**Comment by Kajol-Kumari** [comment]
> Hey @Kajol-Kumari kindly have a look into below figma file link and will be waiting for your feedback.
> https://www.figma.com/file/KIwDSv3VcoD682JFVdgPuK/hitk-tech-design?node-id=0%3A1

Hey @SuNiL-Chau Nice start, can you try to put something in the page as well as I can see only navbar as of now. Maybe put icons having title `Broadcasts`, `About Us` , `FAQs` etc you can put dummy data as of now as we are only focusing on design in this issue.

**Comment by SuNiL-Chau** [comment]
> > Hey @Kajol-Kumari kindly have a look into below figma file link and will be waiting for your feedback.
> > https://www.figma.com/file/KIwDSv3VcoD682JFVdgPuK/hitk-tech-design?node-id=0%3A1
> 
> Hey @SuNiL-Chau Nice start, can you try to put something in the page as well as I can see only navbar as of now. Maybe put icons having title `Broadcasts`, `About Us` , `FAQs` etc you can put dummy data as of now as we are only focusing on design in this issue.

Okay cool will work on it and will update here once done :+1:

**Comment by abhinav-huria** [comment]
I want to work on this.

**Comment by SuNiL-Chau** [comment]
Hey @Kajol-Kumari  Kindly have a look at the design and provide feedback
https://www.figma.com/file/KIwDSv3VcoD682JFVdgPuK/hitk-tech-design?node-id=0%3A1

**Comment by Kajol-Kumari** [comment]
@SuNiL-Chau it's pretty good 🤩 See if you want to add on something to it and make a PR with tur figma pink under `assets` folder at proper location

**Comment by SuNiL-Chau** [comment]
> @SuNiL-Chau it's pretty good  See if you want to add on something to it and make a PR with tur figma pink under `assets` folder at proper location

Hey @Kajol-Kumari what you want to add on it?

**Comment by Kajol-Kumari** [comment]
Hey @SuNiL-Chau let's keep this design only, just make sure to add the images that you have used for this design in the PR as well.

**Comment by SuNiL-Chau** [comment]
> Hey @SuNiL-Chau let's keep this design only, just make sure to add the images that you have used for this design in the PR as well.

Okay will add SVG & dummy img of the avatar & SVG of the graph too later on chart.js or d3.js can be used for real data's

**Comment by SuNiL-Chau** [comment]
Hey @Kajol-Kumari have created a PR kindly check :)

**Comment by SuNiL-Chau** [comment]
Hey, @Kajol-Kumari in case this issue was just limited to the design of admin page then please keep it assign me & close it thank you :)

**Comment by yashsehgal** [comment]
Is this PR closed? Because I have a design idea too.

**Comment by Kajol-Kumari** [comment]
> Is this PR closed? Because I have a design idea too.

Hey @yashsehgal this issue is still open for grab. Feel free to show us your design here :)

**Comment by yashsehgal** [comment]
> Hey @yashsehgal this issue is still open for grab. Feel free to show us your design here :)

Sure, I will do this task.

**Comment by kanishkaa24** [comment]
@Kajol-Kumari 
I want to work on this. Please assign.

**Comment by Kajol-Kumari** [comment]
Hey @kanishkaa24 yes! it's open. You can go ahead with this issue

**Comment by yashsehgal** [comment]
Here is the design I have made, Hope this will help.

![admin-page](https://user-images.githubusercontent.com/62352288/103752636-f5a75000-502f-11eb-8c79-f11c78f60152.png)

**Comment by Kajol-Kumari** [comment]
Hey @yashsehgal the UI looks nice and clean! Just replace the Viewers with `Admins` along I would like to see if you can comeup with anything for `dashboard` section

**Comment by yashsehgal** [comment]
> Hey @yashsehgal the UI looks nice and clean! Just replace the Viewers with `Admins` along I would like to see if you can comeup with anything for `dashboard` section

Sure

**Comment by yashsehgal** [comment]
> Hey @yashsehgal the UI looks nice and clean! Just replace the Viewers with `Admins` along I would like to see if you can comeup with anything for `dashboard` section

Can you guide me with the `dashboard` section. Like, What features should I add?

**Comment by yashsehgal** [comment]
> Hey @yashsehgal the UI looks nice and clean! Just replace the Viewers with `Admins` along I would like to see if you can comeup with anything for `dashboard` section

What about this one?

![image](https://user-images.githubusercontent.com/62352288/103788323-b6dfbd00-5064-11eb-8e1f-84bd03092d06.png)

`This is just an edited section of the Admin Page`

**Comment by Kajol-Kumari** [comment]
@yashsehgal In the dashboard section ,You can show the admin count, Total broadcasts etc in the form of a card having some icon in it.

**Comment by yashsehgal** [comment]
Got it. And There's one more thing I want to ask. What is the graph about? Or Shall I remove that graph?

**Comment by yashsehgal** [comment]
Hope this one is to the point.

![admin-page](https://user-images.githubusercontent.com/62352288/103858216-f991ab80-50dd-11eb-86e3-eada14c2b57d.png)

**Comment by Kajol-Kumari** [comment]
> Got it. And There's one more thing I want to ask. What is the graph about? Or Shall I remove that graph?

Hey @yashsehgal ! In place of graph, provide the count of admins,broadcasts etc. with icons

**Comment by yashsehgal** [comment]
Just text data, Gotcha!

**Comment by Kajol-Kumari** [comment]
> > Got it. And There's one more thing I want to ask. What is the graph about? Or Shall I remove that graph?
> 
> Hey @yashsehgal ! In place of graph, provide the count of admins,broadcasts etc. with icons

^^^ along with icons 
![Screenshot from 2021-01-07 12-44-23](https://user-images.githubusercontent.com/44888949/103863061-2b0e7500-50e6-11eb-843b-fc78eb122c2c.png)
see this image for reference, use icon in place of title here and in place of button, show the count

**Comment by yashsehgal** [comment]
> > > Got it. And There's one more thing I want to ask. What is the graph about? Or Shall I remove that graph?
> > 
> > 
> > Hey @yashsehgal ! In place of graph, provide the count of admins,broadcasts etc. with icons
> 
> ^^^ along with icons
> ![Screenshot from 2021-01-07 12-44-23](https://user-images.githubusercontent.com/44888949/103863061-2b0e7500-50e6-11eb-843b-fc78eb122c2c.png)
> see this image for reference, use icon in place of title here and below that, show the count all in a card

Okay, I am on it.

**Comment by yashsehgal** [comment]
What about this one?

![admin-page](https://user-images.githubusercontent.com/62352288/103869097-df60c900-50ef-11eb-9050-b01c709f1905.png)

**Comment by Kajol-Kumari** [comment]
Instead of single card, we need to have 3 sperate card and also the count needs to be in horizontal centre position

**Comment by yashsehgal** [comment]
> Instead of single card, we need to have 3 sperate card and also the count needs to be in horizontal centre position

Okay, I do these changes.

**Comment by yashsehgal** [comment]
I think it's good now :)

![image](https://user-images.githubusercontent.com/62352288/103871894-a6c2ee80-50f3-11eb-8c86-995a7a4eb4d4.png)

**Comment by Kajol-Kumari** [comment]
Hey @yashsehgal it's good to go now :)
