### ISSUE TITLE
Shift after hovering on `admin?` button

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#280]
Currently if we hover over `admin?` button, we notice a left shift.

Deliverable:
- [ ] Remove that shift issue

GIF of the issue:
![shift-bug](https://user-images.githubusercontent.com/44888949/105314917-91b28900-5be4-11eb-8c51-b867f85edc3b.gif)

**Comment by kenkirito** [comment]
@Kajol-Kumari assign me this issue and also unassigned me from api testing as I am unable to resolve it. I will be making a pr for my remaing task at midnight

**Comment by sanjay270899** [comment]
@Kajol-Kumari Can I work on this issue?

**Comment by Kajol-Kumari** [comment]
Hey @sanjay270899 we follow FCFS so can't asisgn this to you. Please keep an eye we would be opening more issues very soon :) 

@kenkirito Please go ahead with this issue

**Comment by kenkirito** [comment]
https://user-images.githubusercontent.com/68530218/105414098-0b865900-5c5d-11eb-9908-8037efe638a8.mp4

**Comment by kenkirito** [comment]
@Kajol-Kumari done check
