### ISSUE TITLE
[Frontend] Bugs in the website

### ISSUE THREAD

**Issue by vedikaag99** [HITK-TECH-Community/Community-Website#283]
**Describe the bug**
1) `login page` image is not visible.
2) Making the background of the `resource sharing` page white for consistency with other pages.
3) Making the field border effect on the `contact us` page same as that of the `resource sharing` page.

![Screen Shot 2021-01-21 at 10 40 11 PM](https://user-images.githubusercontent.com/67699840/105385762-b4bb5800-5c39-11eb-8d33-f4bc25d17eb2.png)
![Screen Shot 2021-01-21 at 10 40 19 PM](https://user-images.githubusercontent.com/67699840/105385777-ba18a280-5c39-11eb-8890-00428af06258.png)
![Screen Shot 2021-01-21 at 10 40 23 PM](https://user-images.githubusercontent.com/67699840/105385790-bc7afc80-5c39-11eb-93c7-9065267ff2f6.png)
@Kajol-Kumari please review this and assign me as I'd like to work on it under DWoC.

**Comment by Kajol-Kumari** [comment]
Thanks for reporting these @vedikaag99 please go ahead with this issue :+1:
