### ISSUE TITLE
[Frontend] Enhancement in 404 Page

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#287]
Deliverables:

- [ ] Make a better UI for the 404 page.

**Please make sure to show the design here once before making the PR.**

Reference link - [here](https://cdn.mos.cms.futurecdn.net/PuXipAW3AXUzUJ4uYyxPKC-1200-80.jpg)

**Comment by sakshikhachane** [comment]
@Kajol-Kumari I would like to work on this issue.

**Comment by vedikaag99** [comment]
@Kajol-Kumari can I also give this a try along with sakshi?

**Comment by vedikaag99** [comment]
![Screen Shot 2021-01-23 at 12 33 27 AM](https://user-images.githubusercontent.com/67699840/105533948-cfadcb00-5d12-11eb-8dce-101dda1f6b1e.png)
@Kajol-Kumari Please review.

**Comment by Kajol-Kumari** [comment]
Hey @vedikaag99 this looks nice, just make sure it's appearing correct way for small devices

**Comment by vedikaag99** [comment]
![Screen Shot 2021-01-23 at 11 25 20 AM](https://user-images.githubusercontent.com/67699840/105570219-c00fa000-5d6d-11eb-943c-98c8777eb0a7.png)
done @Kajol-Kumari
