### ISSUE TITLE
[Frontend] All Broadcasts Page

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#288]
Deliverables:

- [ ] Add a button at the end of the `broadcast` page that should take to a new page containing all the broadcasts
- [ ] Add `all-broadcasts` route
- [ ] The UI of the broadcast page will be similar to `Get Involved` page having list of cards of fixed size and the extra texts shouls end with ellipses (`...`)

P.S- Put dummy data in the card for now

**Comment by kenkirito** [comment]
assign me

**Comment by nehaparmar99** [comment]
Can I work on it?

**Comment by Kajol-Kumari** [comment]
@kenkirito @nehaparmar99 go ahead with the issue! 
Happy learning :)

**Comment by nehaparmar99** [comment]
@Kajol-Kumari I've linked my PR, please let me know if any other changes are required.

**Comment by kenkirito** [comment]
https://user-images.githubusercontent.com/68530218/105947998-31ae5d80-6090-11eb-88c8-07f506396ee5.mp4
