### ISSUE TITLE
[Frontend] Enhacement in visited menu

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#289]
Deliverables:
- [ ] Reduce the width of the background gradient of visited menu text for small screens

![Screenshot from 2021-01-22 18-43-49](https://user-images.githubusercontent.com/44888949/105495254-f4d61580-5ce1-11eb-8868-a6e1513db789.png)

**Comment by sakshikhachane** [comment]
@Kajol-Kumari I would like to work on this issue also. I will complete it tomorrow itself. Please assign me this issue.

**Comment by Kajol-Kumari** [comment]
Go ahead @sakshikhachane :)

**Comment by sakshikhachane** [comment]
@Kajol-Kumari Is this width fine?
<img width="362" alt="HITk" src="https://user-images.githubusercontent.com/53635792/105507464-3ae6a580-5cf1-11eb-847f-b38345e8e1a0.PNG">

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari Is this width fine?
> <img alt="HITk" width="362" src="https://user-images.githubusercontent.com/53635792/105507464-3ae6a580-5cf1-11eb-847f-b38345e8e1a0.PNG">

A bit less please, width of background should be similar to the one we see on large screens

**Comment by sakshikhachane** [comment]
@Kajol-Kumari Is this looking better now?

<img width="220" alt="nav" src="https://user-images.githubusercontent.com/53635792/105608095-f2e68200-5dc7-11eb-91ed-55346a6f3ceb.PNG">
