### ISSUE TITLE
Enhancement in `Admin?` button

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#297]
Deliverable:

- [ ] Make the active link of `admin?` button same as its onhover effect
- [ ] For small screens, a white background appears after click on `admin?` button, fix it same as the previous task

**Comment by vedikaag99** [comment]
@Kajol-Kumari Can I take up this issue?

**Comment by sakshikhachane** [comment]
@Kajol-Kumari I would like to work on this.

**Comment by AbhipsaGuru1012** [comment]
@Kajol-Kumari can I work on this issue?

**Comment by Kajol-Kumari** [comment]
Hey @vedikaag99 go ahead with this issue. @sakshikhachane @AbhipsaGuru1012  we can only assign this issue to one person and that also on the basis of FCFS. I request you guys to keep an eye, we would be opening up new issues very soon.

**Comment by vedikaag99** [comment]
@Kajol-Kumari hey I have done the second task but can you please guide me for the first task? I tried styling for `nav-admin-button.active` but it is not working

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari hey I have done the second task but can you please guide me for the first task? I tried styling for `.nav-admin-button.active` class but it is not working and have also tried adding `activeClassName="active-button"` to the link element and then styling `.active-button` class.

Try inspecting(ctrl+shift+I in chrome) the element and figuring out the class that is over-writing the style.
