### ISSUE TITLE
[Frontend] Use bootstrap container for hero section in the homepage 

### ISSUE THREAD

**Issue by salil-naik** [HITK-TECH-Community/Community-Website#299]
Use bootstrap's container class to contain the content in the hero section. On bigger screens, the content should remain in the middle.
Refer to Our Motive section on the homepage. (image attached below)
<br />
![image](https://user-images.githubusercontent.com/20141508/105191722-6afd3f80-5b5d-11eb-8db3-5ef988c46ce5.png)

**Comment by sakshikhachane** [comment]
@salil-naik I would like to work on this issue.

**Comment by Swastik1710** [comment]
Hey , can I please work on this issue ?

**Comment by Swastik1710** [comment]
Hey @salil-naik  , thanks for assigning this to me.
Can you please elaborate a bit more on this issue.

**Comment by Swastik1710** [comment]
Is it this what you're asking for ?

![Hero Section](https://user-images.githubusercontent.com/71871571/105892987-89b97580-6038-11eb-9c55-26b26de64c9e.jpg)

**Comment by salil-naik** [comment]
@Swastik1710 Yes. Just put a `<div>` around it with bootstraps `container` class.
