### ISSUE TITLE
[Frontend] Add basic react structure 

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#3]
- Add initial structure for frontend using react having basic components

**Comment by codewithvk** [comment]
Can you assign me? I m happy to work on this issue.

**Comment by Kajol-Kumari** [comment]
Sure @codewithvk go ahead with this issue. Assigning it to you.
Happy coding :)

**Comment by Kajol-Kumari** [comment]
Closed via #8
