### ISSUE TITLE
[Bug] Fix the button width of the forms

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#306]
Deliverable:

- [ ] Fix `submit`, `sign in` and `let's talk` button's width
- [ ] Make it smaller for the small screens

**Comment by amanprateek123** [comment]
please assign the issue to me @Kajol-Kumari

**Comment by Kajol-Kumari** [comment]
Go ahead @amanprateek123

**Comment by amanprateek123** [comment]
Is this size okay?
![Screenshot from 2021-01-27 13-22-14](https://user-images.githubusercontent.com/42955585/105960057-b86c3600-60a2-11eb-8bf5-801e548aaa5f.png)
