### ISSUE TITLE
[Frontend] Admin panel Restructure

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#307]
Deliverable:

- [ ] Shift the basic structure codes(left panel codes) from `dashboard.js` to `admin.js` and respective css to `admin.css`
- [ ] Make separate route for each options in the menu like `dashboard`, `manage-resources`, `manage-contactUs`, `setting` etc
- [ ] Make separate folder for each of the menu like `dashboard`, `manage_resources`, `manage_faqs` etc
- [ ] Make a different component(keep it blank as of now just with a title ) in the respective component folder for each options present in the left menu and just render it in the main component

p.s - In case of settings, Render the current `setting` component instead of creating a new one

**Comment by amanprateek123** [comment]
@Kajol-Kumari  please assign this issue to me

**Comment by nehaparmar99** [comment]
I'd like to work on it

**Comment by Kajol-Kumari** [comment]
> I'd like to work on it

Hey sorry! Can't assign this to more than one person

**Comment by amanprateek123** [comment]
@Kajol-Kumari  why we have to make different routes for different tabs? I think all can be done in a single route.

**Comment by amanprateek123** [comment]
@Kajol-Kumari  please update me on this :)

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari why we have to make different routes for different tabs? I think all can be done in a single route.

Sorry I missed it. As we will be rendering different components under each tab so it would make it more organised to keep it that way.
