### ISSUE TITLE
[Frontend] Scroll to Top Button

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#311]
Deliverable:

- [ ] Make a component `scroll_to_top` under `utility` folder that can be imported to all the pages
- [ ] The button should take to the top of the page

**Comment by nehaparmar99** [comment]
I'd like to give it a try!

**Comment by Kajol-Kumari** [comment]
> I'd like to give it a try!

sure @nehaparmar99 !

**Comment by kenkirito** [comment]
@Kajol-Kumari can i also work on this issue

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari can i also work on this issue

sure @kenkirito Go ahead with this issue :)
