### ISSUE TITLE
[Frontend] View broadcast Feature

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#312]
Deliverable:

- [ ] Make the cards under `all_broadcasts` flipable and on the other side of the card, there should be a `view` button that should open up a modal and show the whole broadcast message(similar to what we have in broadcast page)

**Comment by nehaparmar99** [comment]
I'd like to work on it

**Comment by Kajol-Kumari** [comment]
Go ahead @nehaparmar99

**Comment by kenkirito** [comment]
can i work on this issue

**Comment by Kajol-Kumari** [comment]
> can i work on this issue

Hey! We can't assign this issue to more than one person

**Comment by Kajol-Kumari** [comment]
Hey @nehaparmar99 can you please provide an update on this issue?

**Comment by nehaparmar99** [comment]
I'll make the pr by tonight.
Have been a bit busy w my exams

**Comment by nehaparmar99** [comment]
Back card upon hover,Back card without hover
![Screenshot (302)](https://user-images.githubusercontent.com/48972593/106789968-efc97c80-6678-11eb-856f-26c5fa94fde0.png)
View button on hover
![Screenshot (304)](https://user-images.githubusercontent.com/48972593/106790043-07086a00-6679-11eb-9308-489074be7b0e.png)
Is it fine?
Also the modal's similar to the one on the broadcasts page, should I style that too?

**Comment by kenkirito** [comment]
@Kajol-Kumari I have made a flip card in my previous pr and you also merged it into main. If you want you can also use it

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari I have made a flip card in my previous pr and you also merged it into main. If you want you can also use it

Yes @kenkirito we are using that only. Thanks for suggesting :)
