### ISSUE TITLE
[Frontend] Like feature for broadcasts

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#313]
Deliverable:

- [ ] Add a like button on broadcast card under `Recent Broadcast` and `Previous Broadcast` section. As we haven't integrated our backend. Store the total number of likes in local storage maybe and show a temp count.
- [ ] It should as soon as one clicks on it

**Comment by urvashi-code1255** [comment]
@Kajol-Kumari Can I give it a try?

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari Can I give it a try?

sure @urvashi-code1255  :)

**Comment by Vrushti24** [comment]
Hey @Kajol-Kumari  can I work on this ??

**Comment by Kajol-Kumari** [comment]
> Hey @Kajol-Kumari can I work on this ??

Hey @Vrushti24 you can go ahead with this issue
Happy Learning :)

**Comment by Vrushti24** [comment]
Thank you!

**Comment by urvashi-code1255** [comment]
> Thank you!

Hey @Vrushti24 You go for this issue. As I am busy with my exams. So, will get back to work after it.

**Comment by Vrushti24** [comment]
Sure, no problem.

**Comment by kenkirito** [comment]
can i work on this issue

**Comment by Vrushti24** [comment]
Hey @Kajol-Kumari  I have been trying to add the button but not working I have been doing same thing for so long I don't know now what should I do ?

**Comment by Abhishek971999** [comment]
Hey @Vrushti24  , Can you please explain what are you trying to achieve and what is going wrong. Also if you share some images regarding some errors if you are getting anything then that would be great.
