### ISSUE TITLE
[Bug] Hide and Show button doesn't work until we refresh the page

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#314]
Steps to reproduce:
1. Click on `admin?` button
2. Type the password
3. Click on `hide/show` icon next to it
It doesn't work
4. Refresh the page
5. Again type the password
6. Click on `hide/show` icon
This time it works

Deliverable:
Fix the `hide/show` toggle button so that it should work no matter if we refresh the page or not

**Comment by kenkirito** [comment]
Assign me

**Comment by sakshikhachane** [comment]
@Kajol-Kumari I would like to work on this issue.

**Comment by AbhipsaGuru1012** [comment]
@Kajol-Kumari can I work on this issue?

**Comment by Kajol-Kumari** [comment]
@kenkirito please go ahead with this issue.

**Comment by ashuvssut** [comment]
@Kajol-Kumari, mam, if by any chance, the assigned contributor fails to submit his/her PR in a settled deadline, will the other interested contributors get a chance to get assigned and work on the issue?

If yes, I would like try to fix to this issue

**Comment by Kajol-Kumari** [comment]
Hey @kenkirito can you please let us know if you would he able to gid it? It not I will assign it to someone else.

**Comment by kenkirito** [comment]
Assign it to someone else . Sorry some issue arises so not able to do it

**Comment by ashuvssut** [comment]
@Kajol-Kumari , Please assign me this issue. I will submit PR today
