### ISSUE TITLE
Enhacement in Footer Icons

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#319]
Deliverable:

- [ ] Please make the border around the icons curved around the corners as it's looking like a glitch this way.

![Screenshot from 2021-01-31 14-43-47](https://user-images.githubusercontent.com/44888949/106379642-575e9e00-63d3-11eb-95d6-e99937a4ca51.png)

**Comment by ashuvssut** [comment]
@Kajol-Kumari  please assign me this issue

**Comment by Kajol-Kumari** [comment]
Go ahead @ashuvssut 
Happy learning :)

**Comment by ashuvssut** [comment]
@Kajol-Kumari I have tried three different approaches to this.

I am showing you the best one I came up with
![Desktop Recording 3](https://user-images.githubusercontent.com/60546840/106430299-75062480-6420-11eb-9aa9-bb822045fa32.gif)

I am unable to create curved edges on the span. I checkout out many stackoverflow and CSS Tricks for some ideas..but sadly none were helpful to create a perfect 90degree curved edge. 

so after 6hrs🥴 i came up with this approach to the problem.

I have written customizable css that only require you to change 2 variables and you do not need to bother about alignment or something. those two css variables are
```css
:root{
    --r: 12px; /* corner radius */
    --w: 4px; /* width of the border */
}
```
I dont think I can improve more from this current design

If you like this one then I will proceed to implement it in the footer and create my PR.

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari I have tried three different approaches to this.
> 
> I am showing you the best one I came up with
> ![Desktop Recording 3](https://user-images.githubusercontent.com/60546840/106430299-75062480-6420-11eb-9aa9-bb822045fa32.gif)
> 
> I am unable to create curved edges on the current `span`. I checkout out many stackoverflow and CSS Tricks for some ideas..but sadly none were helpful to create a perfect 90degree curved edge.
> 
> so after 6hrs🥴 i came up with this approach to the problem.
> 
> I have written customizable css that only require you to change 2 variables and you do not need to bother about alignment or anything to change its size. those two css variables are
> 
> ```css
> :root{
>     --r: 12px; /* corner radius */
>     --w: 4px; /* width of the border */
> }
> ```
> 
> I dont think I can improve more from this current design
> 
> so @Kajol-Kumari , mam, kindly tell me If you like this one or not. Only then, I will proceed to implement it in the footer and create my PR.

If that's the case It would be better if you can implement the second one from the GIF you shown

**Comment by ashuvssut** [comment]
mam both are same only. the difference is: there is an extra darkblue `div` element on top of the second one

I will be submitting my PR today! 😁😁😁
So happy that you accepted that one.
