### ISSUE TITLE
[Bug] Buttons on clicks shows black border

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#327]
Deliverable:

- [ ] The buttons on click, should just take us to the desired location and shouldn't have any border showing up

GIF of the Bug:
![button-bug](https://user-images.githubusercontent.com/44888949/106455938-e2fb2c00-64b2-11eb-802a-50c13271b1df.gif)

**Comment by nehaparmar99** [comment]
I'd like to do this

**Comment by AbhipsaGuru1012** [comment]
@Kajol-Kumari can I work on this issue?

**Comment by Kajol-Kumari** [comment]
Hey @nehaparmar99 I can see that you are already assigned two issues so I request you to get atleast one of the PR merged before claiming a new issue.

@AbhipsaGuru1012 You can go ahead with this issue

Happy Learning :)

**Comment by nehaparmar99** [comment]
> Hey @nehaparmar99 I can see that you are already assigned two issues so I request you to get atleast one of the PR merged before claiming a new issue.
> 
> @AbhipsaGuru1012 You can go ahead with this issue
> 
> Happy Learning :)

I've linked the PR to one of them yesterday only.The other I'll do by tomorrow

**Comment by Kajol-Kumari** [comment]
> > Hey @nehaparmar99 I can see that you are already assigned two issues so I request you to get atleast one of the PR merged before claiming a new issue.
> > @AbhipsaGuru1012 You can go ahead with this issue
> > Happy Learning :)
> 
> I've linked the PR to one of them yesterday only.The other I'll do by tomorrow

Thanks for the update but we are sorry, we can't assign more than 2 issues at a time to a single person
