### ISSUE TITLE
Enhancement in Join us form

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#328]
Deliverable:

- [ ] The `join us` form's radio button should have the same fill color as we have in resource form

**Comment by AbhipsaGuru1012** [comment]
@Kajol-Kumari  can I work on this issue?

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari can I work on this issue?

Sure! Go ahead with this issue 
Happy Learning :)
