### ISSUE TITLE
CONTRIBUTING.md image not loading

### ISSUE THREAD

**Issue by LeeRenJie** [HITK-TECH-Community/Community-Website#330]
**Describe the bug**
The image in the CONTRIBUTING.md file is not loading. Fixing this will help beginners to be clearer on how to contribute step by step

**To Reproduce**
1. Go to CONTRIBUTING.md
1. Scroll down to the steps' images
1. See error

**Expected behavior**
Image showing step by step of how to start to contribute to this project

**Screenshots**
<img width="529" alt="Screenshot 2021-02-01 210723" src="https://user-images.githubusercontent.com/67599130/106463084-e520b300-64d1-11eb-9c00-693ef7345835.png">

**Comment by LeeRenJie** [comment]
Can I be assigned to work on this? From DWOC

**Comment by Kajol-Kumari** [comment]
Hey @LeeRenJie thank you reporting this issue and please go ahead and fix it. 
Happy learning :)

**Comment by LeeRenJie** [comment]
Alright, thanks! I will create a folder inside the assets folder to hold all relevant images is that ok?

**Comment by LeeRenJie** [comment]
Do you recommend the example images to be in Light or dark mode of github?

**Comment by Kajol-Kumari** [comment]
> Alright, thanks! I will create a folder inside the assets folder to hold all relevant images is that ok?

yeah that's totally fine

**Comment by Kajol-Kumari** [comment]
> Do you recommend the example images to be in Light or dark mode of github?

i would recommend it to be of dark mode as developers rarely opt light mode where-ever they have an option :)

**Comment by LeeRenJie** [comment]
@Kajol-Kumari what should I name the folder? will "img" be fine?
