### ISSUE TITLE
Sign In Button should be aligned properly

### ISSUE THREAD

**Issue by Utkarshn10** [HITK-TECH-Community/Community-Website#336]
Deliverable:
Sign in button should be properly aligned in center and space should be given at its bottom.

**Screenshots**
Currently its not properly aligned as shown in screenshot.

![Screenshot (34)](https://user-images.githubusercontent.com/58587256/106636040-8594d700-65a7-11eb-9806-8f58c49523c3.png)

**Comment by Utkarshn10** [comment]
@Kajol-Kumari Can I work on this issue?

**Comment by abhay313** [comment]
Can I work on this issue ?

**Comment by Kajol-Kumari** [comment]
Hey @Utkarshn10 can you please check if you have the latest pull as the buttons seems to appear correctly on my end.

**Comment by Utkarshn10** [comment]
Hey @Kajol-Kumari, sorry I was on my previous branch when I ran the project. The issue is already resolved. @abhay313 thanks for volunteering , you can look for other issues since this issue was already resolved. I am closing this issue.
