### ISSUE TITLE
Enhancement in Join Us form

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#337]
Deliverable:

- [ ] Rename the `Interested Domain` to `Interested Domains`
- [ ] Make checkbox instead of dropdown for `Interested Domains` section
- [ ] The title and checkbox should be one below other just like we have `Level of trust` in resource form(see below image for refrence)
- [ ] In the `Year of study` section, make buttons displayed below the title as shown below.
- [ ] Reduce the height of `How can you contribute to help the community` input box

![Screenshot from 2021-02-03 12-26-27](https://user-images.githubusercontent.com/44888949/106710435-f1188c00-661b-11eb-9345-8305966ab240.png)

**Comment by vedikaag99** [comment]
@Kajol-Kumari can I work on this?

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari can I work on this?

sure @vedikaag99 Go ahead with this issue :)
