### ISSUE TITLE
Fix Error message for Newsletter signup

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#338]
Deliverable:

- [ ] Show proper error message for the `Sign Up for our Newsletter` input box currently it shows something like below.
- [ ] The error message should appear below the input box and should be short and precise.
![Screenshot from 2021-02-03 12-35-20](https://user-images.githubusercontent.com/44888949/106710799-8fa4ed00-661c-11eb-87e1-7a3b2cc398b8.png)

p.s IN order to see this message click on `Sign up` button in footer

**Comment by AbhipsaGuru1012** [comment]
@Kajol-Kumari I would like to work on this. Please assign this to me

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari I would like to work on this. Please assign this to me

Go ahead @AbhipsaGuru1012 
Happy Learning :)

**Comment by AbhipsaGuru1012** [comment]
![newsletter](https://user-images.githubusercontent.com/58511560/107065242-8aa19280-6802-11eb-8886-a3cf8379171a.PNG)


@Kajol-Kumari please let me know if this is okay?

**Comment by Kajol-Kumari** [comment]
> ![newsletter](https://user-images.githubusercontent.com/58511560/107065242-8aa19280-6802-11eb-8886-a3cf8379171a.PNG)
> 
> @Kajol-Kumari please let me know if this is okay?

Hey @AbhipsaGuru1012 this looks good.
