### ISSUE TITLE
Enhancement in Footer Icons

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#339]
Deliverable:

- [ ] Currently, footer icons seems very large w.r.t other contents present in the footer. Make it a bit smaller so that it looks consistent with the size of other contents in the footer

**Comment by AbhipsaGuru1012** [comment]
@Kajol-Kumari can I work on this?

**Comment by LeeRenJie** [comment]
@Kajol-Kumari can I be assigned for this?

**Comment by Kajol-Kumari** [comment]
@AbhipsaGuru1012 please go ahead with this issue and @LeeRenJie I am sorry but we need to follow FCFS so I request you to look for other opened issues.
Happy Learning :)

**Comment by LeeRenJie** [comment]
Alright, no problem!

**Comment by AbhipsaGuru1012** [comment]
![icons](https://user-images.githubusercontent.com/58511560/106740262-2b942000-6640-11eb-9094-970d209746e9.PNG)

@Kajol-Kumari please let me know if the size of icons is okay?

**Comment by Kajol-Kumari** [comment]
> ![icons](https://user-images.githubusercontent.com/58511560/106740262-2b942000-6640-11eb-9094-970d209746e9.PNG)
> 
> @Kajol-Kumari please let me know if the size of icons is okay?

Hey! Keep the icon size a bit large and reduce that yellow border gap and size

**Comment by AbhipsaGuru1012** [comment]
> > ![icons](https://user-images.githubusercontent.com/58511560/106740262-2b942000-6640-11eb-9094-970d209746e9.PNG)
> > @Kajol-Kumari please let me know if the size of icons is okay?
> 
> Hey! Keep the icon size a bit large and reduce that yellow border gap and size

Okay sure, I will make the changes

**Comment by Kajol-Kumari** [comment]
Hey @AbhipsaGuru1012 this looks nice. Please make a PR so that I can test if that's looking fine or not :)
