### ISSUE TITLE
Cards on Admin Dashboard should take to respective pages

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#340]
Deliverable:

- [ ] Currently, the cards displayed on admin dashboard doesn't take us anywhere. It should take us to the respective tabs of the menu.
- [ ] Change the cards by default color with `#016795` and on hover it's color should be `#1B2431` on the dashboard.

**Comment by amanprateek123** [comment]
assign this issue to me @Kajol-Kumari

**Comment by Kajol-Kumari** [comment]
> assign this issue to me @Kajol-Kumari

sure @amanprateek123 
Go ahead with this issue :)
