### ISSUE TITLE
Enhancement in FAQ Section

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#341]
Deliverable:

- [ ] Currently when we expand a new question, the previous question remain's opened. It should close the previously opened question ideally.
- [ ] As we expand the question, the footer shifts downwards, ideally it shouldn't make any shift in the footer

Bug GIF:
![faq](https://user-images.githubusercontent.com/44888949/106712536-1a86e700-661f-11eb-9e5d-e30642d674a1.gif)

**Comment by LeeRenJie** [comment]
Can I try this?

**Comment by Kajol-Kumari** [comment]
> Can I try this?

sure @LeeRenJie 
Go ahead with this issue :)

**Comment by amanprateek123** [comment]
assign this issue to me @Kajol-Kumari

**Comment by sakshikhachane** [comment]
@Kajol-KumariI would like to work on this issue.

**Comment by Kajol-Kumari** [comment]
> assign this issue to me @Kajol-Kumari

Hey @amanprateek123 please go ahead with this issue. @sakshikhachane please look for other issue as we need to follow FCFS.
Happy Learning :)
