### ISSUE TITLE
Add Community-logo for required places

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#342]
Delivearble:

- [ ] Replace the favicon icon that currently appears in the page title with [this](https://github.com/HITK-TECH-Community/Community-Website/blob/main/frontend/public/community-logo.png) logo
- [ ] Adjust the size and add proper hovering effect to the navbar's logo

**Comment by vedikaag99** [comment]
@Kajol-Kumari can I work on this?

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari can I work on this?

sure @vedikaag99 
Go ahead :)
