### ISSUE TITLE
admin button in the navbar

### ISSUE THREAD

**Issue by palak199** [HITK-TECH-Community/Community-Website#343]
**Is your feature request related to a problem? Please describe.**
The top navbar looks so attractive but the admin button(highlighted in screenshot) has a question mark which isn't required.
![image](https://user-images.githubusercontent.com/43077980/106742535-297f9080-6643-11eb-95b0-3e291de24a7c.png)

**Describe the solution you'd like**
This button text can be replaced with word login I suppose.

**Additional context**
It is a very minute change though.
- [x]  i would like to make this change

**Comment by Kajol-Kumari** [comment]
Hey @palak199 thanks for the issue but this is the required behaviour as you now. Btw if you can come up with a better active-link effect, I would be happy to accept your PR :)
