### ISSUE TITLE
Remove inherited undesired stylings by using css modules

### ISSUE THREAD

**Issue by ashuvssut** [HITK-TECH-Community/Community-Website#344]
**Describe the bug**
I was having difficulties styling my material-ui components. Its all because of the css that apply to all components js/jsx files.

Developers have to override other styles to make thier styles to get applied. searching for those styles is really tiresome.

As you know a single material ui component has lots of span elements when rendered. these span elements inherit other undesired styles form other componets. see the example below:

![image](https://user-images.githubusercontent.com/60546840/106755012-7bdc9500-65e2-11eb-9282-af68af68cd0b.png)
I am working on the broadcast page. I was trying to style my components. _See that awkward margin on top applied on the button label._ I thought it came from some `margin:5px`..then checked for `padding:5px`, then `line-height`, and what not😂. I wasted a lot of my time there. And at last found the culprit `top:5px` which was inherited by css written in carousel.css. 

**Additional context**
Please convert all css files to css modules files. I know there are 24 css files containing stylings of class names like `abc-def` which would need to be converted to abcDef and so on. 

Its a very tiresome process but it is worth it.

Please assign 4 people to convert 6 css files each. this is very tiresome and boring process but its worth it. 

*PS* resouces.css has a lot of classes(around 60). So assign accordingly

**Comment by ashuvssut** [comment]
this is the list of those css files. So, you can assign people easily now.
**! exclude app.css and index.css**
![image](https://user-images.githubusercontent.com/60546840/106757890-bdbb0a80-65e5-11eb-86aa-0ddf89f7eeb6.png)

 you can assign me any 5

**Comment by Kathuria** [comment]
@ashuvssut : Alternative to this approach can be adding new class wrapper on each component to control styles, 
say Contact us page - So component top style can start from **community-about-us** {community-<Component_Name>}. And this way we can wrap styles hierarchy. If there are any common styles then should be separated out and that will definitely applied on all tags - just like in your case of span button. That should be handled by component owner by increasing specificity.

This would be time saving but after effects can be there like if above mentioned e.g. of span is expected like this in any of case that would be broken. This case needs to validated on complete website.

**Comment by Kajol-Kumari** [comment]
Thanks for opening up the issue. We would preferable go with css-modules but we may require wrapper class as well from few components, where we can't explicitly define the classnames using `css-module`. Closing this issue for now and I will open up a new one having list of all the css files so that I can assign it to multiple people
