### ISSUE TITLE
Conevert css files to css module

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#349]
Deliverable:
Currently the css defines is global and so gets applied to the classes wherever defined. So we are shifting to `css-modules` for tackling this issue.

Below is the list of css files, feel free to claim any of the below sections. Make sure to make the changes in corresponding `js` file.

- [x] section 1: - @amanprateek123 
1. [admin.css](https://github.com/HITK-TECH-Community/Community-Website/blob/main/frontend/src/components/admin/admin.css)
2. [dashboard.css](https://github.com/HITK-TECH-Community/Community-Website/blob/main/frontend/src/components/admin/dashboard/dashboard.css)
3. [profile.css](https://github.com/HITK-TECH-Community/Community-Website/blob/main/frontend/src/components/admin/profile/profile.css)
4. [setting.css](https://github.com/HITK-TECH-Community/Community-Website/blob/main/frontend/src/components/admin/setting/setting.css)

- [x] section2 - @ashuvssut 

1. [404.css](https://github.com/HITK-TECH-Community/Community-Website/blob/main/frontend/src/components/404/not_found.css) 
2. [about_us.css](https://github.com/HITK-TECH-Community/Community-Website/blob/main/frontend/src/components/about/about_us.css)
3. [Login.css](https://github.com/HITK-TECH-Community/Community-Website/blob/main/frontend/src/components/auth/login/login.css)
4. [contact_us.css](https://github.com/HITK-TECH-Community/Community-Website/blob/main/frontend/src/components/contact/contact_us.css)

- [ ] section3 - @nehaparmar99 

1. [modal.css](https://github.com/HITK-TECH-Community/Community-Website/blob/main/frontend/src/components/broadcast/Carousel/Modal/Modal.css)
2.  [Carousel.css](https://github.com/HITK-TECH-Community/Community-Website/blob/main/frontend/src/components/broadcast/Carousel/Carousel.css)
3. [all_broadcasts.css](https://github.com/HITK-TECH-Community/Community-Website/blob/main/frontend/src/components/broadcast/all_broadcasts/all_broadcasts.css)
4. [broadcast,css](https://github.com/HITK-TECH-Community/Community-Website/blob/main/frontend/src/components/broadcast/broadcast.css)

- [x] section4 - @sakshikhachane 

1. [FAQ.css](https://github.com/HITK-TECH-Community/Community-Website/blob/main/frontend/src/components/faq/faq.css)
2. [footer.css](https://github.com/HITK-TECH-Community/Community-Website/blob/main/frontend/src/components/footer/footer.css)
3. [motive.css](https://github.com/HITK-TECH-Community/Community-Website/blob/main/frontend/src/components/home/motive/motive.css)
4. [overview.css](https://github.com/HITK-TECH-Community/Community-Website/blob/main/frontend/src/components/home/overview/overview.css)
5. [home.css](https://github.com/HITK-TECH-Community/Community-Website/blob/main/frontend/src/components/home/home.css)

- [x] section 5 - @vedikaag99 
1. [get_involved.css](https://github.com/HITK-TECH-Community/Community-Website/blob/main/frontend/src/components/get_involved/get_involved.css)
2. [carousel.css](https://github.com/HITK-TECH-Community/Community-Website/blob/main/frontend/src/components/home/carousel/carousel.css)

- [x] section 6 - @ashuvssut 

1. [join_us_form.css](https://github.com/HITK-TECH-Community/Community-Website/blob/main/frontend/src/components/home/join_us/join_us_form/form.css)
2. [join_us.css](https://github.com/HITK-TECH-Community/Community-Website/blob/main/frontend/src/components/home/join_us/join_us.css)

- [ ] section 7 - @nehaparmar99 

1. [navbar.css](https://github.com/HITK-TECH-Community/Community-Website/blob/main/frontend/src/components/navbar/navbar.css)
2. [privacy-ploicy.css](https://github.com/HITK-TECH-Community/Community-Website/blob/main/frontend/src/components/privacy-policy/privacy-policy.css)
3. [button.css](https://github.com/HITK-TECH-Community/Community-Website/blob/main/frontend/src/components/util/button/button.css)
4. [scroll_to_top.css](https://github.com/HITK-TECH-Community/Community-Website/blob/main/frontend/src/components/util/scroll_to_top/scroll_to_top.css)

- [x] section 8 - @sakshikhachane 

1. [resource.css](https://github.com/HITK-TECH-Community/Community-Website/blob/main/frontend/src/components/resource/resources.css)
2. [terms.css](https://github.com/HITK-TECH-Community/Community-Website/blob/main/frontend/src/components/terms/terms.css)

Reference links:
1. https://medium.com/@ralph1786/using-css-modules-in-react-app-c2079eadbb87
2. https://stackoverflow.com/questions/33949469/using-css-modules-how-do-i-define-more-than-one-style-name/33949534

**Comment by sakshikhachane** [comment]
@Kajol-Kumari I would like to work on this issue.

**Comment by vedikaag99** [comment]
@Kajol-Kumari hey can I work on section 5?

**Comment by ashuvssut** [comment]
@Kajol-Kumari  I want to do section2

**Comment by nehaparmar99** [comment]
I'd like to do section 3

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari I want to do **section2** and **section6** both giving you 2 different PRs?
> 
> If I am not allowed to do 2 sections...then you can just assign me section2
> 
> @Kajol-Kumari, mam, I want do both. please consider assigning me both

@ashuvssut sure. Please make sure to open up two separate PRs for each sections

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari I'd like to work on section 3 since I've already been working on the broadcasts part
> Would also like to work on section 7 if it's allowed

please open up 2 PRs for each of them

**Comment by sakshikhachane** [comment]
@Kajol-Kumari 2 sections are allowed so please assign me section 8 also.

**Comment by vedikaag99** [comment]
@Kajol-Kumari hey, I was having some trouble in converting `carousel.css` into `carousel.module.css` as `carousel.js` has some inbuilt css files that it is importing namely -`owl.carousel.css` and `owl.theme.default.css`. These files are stored in `node_modules`. The styles of some component like the arrows and dots are defined in these files and have been overwritten in `carousel.css`. Can you please help me out?

**Comment by nehaparmar99** [comment]
> @Kajol-Kumari hey, I was having some trouble in converting `carousel.css` into `carousel.module.css` as `carousel.js` has some inbuilt css files that it is importing namely -`owl.carousel.css` and `owl.theme.default.css`. These files are stored in `node_modules`. The styles of some component like the arrows and dots are defined in these files and have been overwritten in `carousel.css`. Can you please help me out?

Hey Kajol, I'm facing the same problem.

**Comment by ashuvssut** [comment]
I think For that we have to make a separate `owl-carousel-styles.css ` coz I don't find any other way to do that.

Or maybe inline styling can help

**Comment by ashuvssut** [comment]
> I think For that we have to make a separate `owl-carousel-styles.css` coz I don't find any other way to do that.

then we can use this ☝☝☝ instead.

**Comment by Kajol-Kumari** [comment]
Hey @vedikaag99 @nehaparmar99 as @ashuvssut suggested we will have to make a separate `owl_carousel_styles.css` and keep all the styles related to carousel in there as we can't modify inbuild css properties using css-module

**Comment by nehaparmar99** [comment]
@Kajol-Kumari my section-7 pr wasn't merged, you asked a few changes in it which I was doing.It still needs to be done right?

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari my section-7 pr wasn't merged, you asked a few changes in it which I was doing.It still needs to be done right?

Hey @nehaparmar99 and @vedikaag99 we are looking forward to your PRs and yes we would be accepting the PRs

**Comment by ashuvssut** [comment]
if anyone says to unassign... i would like to take that

**Comment by vedikaag99** [comment]
> if anyone says to unassign... i would like to take that

Hi @ashuvssut I am still struggling on converting carousel.css to carousel.module.css so if you want you can work on that and I can work on the get_involved.css that comes under section 5. Can we do this ? @Kajol-Kumari

**Comment by ashuvssut** [comment]
okay i will convert carousel.css

**Comment by ashuvssut** [comment]
if anyone else is facing problems...then you can give that part of the work to me.🙂

**Comment by Kajol-Kumari** [comment]
> > if anyone says to unassign... i would like to take that
> 
> Hi @ashuvssut I am still struggling on converting carousel.css to carousel.module.css so if you want you can work on that and I can work on the get_involved.css that comes under section 5. Can we do this ? @Kajol-Kumari

sure! @vedikaag99 I will just have to change the label accordingly. I hope that would be fine you guys.

**Comment by Kajol-Kumari** [comment]
@ashuvssut would you like to go ahead with section 3  and section of this issue?

**Comment by sakshikhachane** [comment]
@Kajol-Kumari Should I take?

**Comment by ashuvssut** [comment]
Yes mam

**Comment by ashuvssut** [comment]
I want to do the section3

**Comment by Kajol-Kumari** [comment]
Great! @ashuvssut go ahead with section3 and @sakshikhachane go ahead with section 7
Happy Learning :)

**Comment by ashuvssut** [comment]
Working on it! Will submit my PR today😁

**Comment by ashuvssut** [comment]
[dropdown.css](https://github.com/HITK-TECH-Community/Community-Website/blob/149b291072acba8caeb1e9d38f9f220f9855981c/frontend/src/components/util/dropdown/dropdown.css)
[carousel.css](https://github.com/HITK-TECH-Community/Community-Website/blob/de3fd2c644533c3378ae8be09605efdc9b46f8b4/frontend/src/components/home/carousel/carousel.css)
[card.css](https://github.com/HITK-TECH-Community/Community-Website/blob/2b87ed918f913443d058a4c9af3f3f81b776f7f4/frontend/src/components/broadcast/all_broadcasts/card/card.css)

these 3 css files are yet to be converted

-----------------
[Edit.module.css](https://github.com/HITK-TECH-Community/Community-Website/blob/de3fd2c644533c3378ae8be09605efdc9b46f8b4/frontend/src/components/broadcast/all_broadcasts/Edit/Edit.module.scss)
this file follows "nested" scss.
I can un-'nest' all

----------------
I would like to work on this
