### ISSUE TITLE
[Frontend] Edit Modal for All Broadcasts page

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#353]
Deliverable:

- [ ] Modify the `all_broadcasts` cards to contain two icons i.e edit(pencil icon) and delete (trash icon) which should only be visible when rendered in the admin's broadcast page. (you can use a flag `is_admin` which would be false by default)
- [ ] Define the modal for editing the broadcasts i.e after clicking on edit icon, admin should see a tool box/editor using which he can edit the broadcast.

**Comment by amanprateek123** [comment]
@Kajol-Kumari  please assign this issue to me

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari please assign this issue to me

Go ahead @amanprateek123 
Happy Learning :)

**Comment by kenkirito** [comment]
can i also work on this issue

**Comment by Kajol-Kumari** [comment]
> can i also work on this issue

Hey @kenkirito all the issues with `NO MORE ASSIGNMENT` can't be assigned to anyone else
