### ISSUE TITLE
[Frontend] Broadcast Page for Admin

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#354]
Deliverable:

- [ ] The broadcasts page should contain two cards 1. Add a new broadcast  2. Manage Broadcasts
- [ ] Create anew broadcast should open up a text-editor where the admin can write a new broadcast. 

P.S - As we haven't integrated the backend yet, we only want it's frontend to work fine.

**Comment by amanprateek123** [comment]
@Kajol-Kumari  assign this issue to me as I already working on Admin pannel

**Comment by nehaparmar99** [comment]
Can I work on it?

**Comment by Kajol-Kumari** [comment]
> Can I work on it?

Sure @nehaparmar99

**Comment by nehaparmar99** [comment]
Wanted to know if this needs be done on the all-broadcasts page or the broadcasts page?And the manage broadcasts card should be non functioning for now right?

**Comment by kenkirito** [comment]
can i also work on this issue

**Comment by Kajol-Kumari** [comment]
> Wanted to know if this needs be done on the all-broadcasts page or the broadcasts page?And the manage broadcasts card should be non functioning for now right?

It needs to be done in `all_broadcast` page

**Comment by Kajol-Kumari** [comment]
> can i also work on this issue

sorry @kenkirito we can't assign this to more than one person!

**Comment by nehaparmar99** [comment]
How do I login as an Admin, since I cant see the all-broadcasts page for the admin.
