### ISSUE TITLE
Enhancement in Setting Tab of Admin

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#355]
Deliverable:

- [ ] The setting page should contain following cards
1. My Profile
2. Invite Admin
3. Manage Admins

- [ ] `My Profile` should take the admin to his/her profile page
- [ ] `Invite Admin` should take the admin to a new page containing the invite form(This needs to be created)
- [ ] `Manage Admins` should take the admin to a new page containing the list of admins

**Comment by amanprateek123** [comment]
@Kajol-Kumari  please aaign this issue to me as I am working on Admin Pannel

**Comment by nehaparmar99** [comment]
Can I work on it?
