### ISSUE TITLE
Enhancement in All Broadcasts Page

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#360]
Deliverable:

- [ ] Currently few of the styles are present in `js` file. Keep all styles in `css` file
- [ ] Change the heading from `Broadcasts` to `All Broadcasts`
- [ ] Increase the width of search-box
- [ ] Enhancement in UI of the search-box and filter buttons ( **this will carry bonus point** )

**Comment by LeeRenJie** [comment]
Can I try to work on this?

**Comment by Kajol-Kumari** [comment]
Sure @LeeRenJie Go ahead with this issue. 
Happy Learning :)

**Comment by LeeRenJie** [comment]
<img width="831" alt="not alligned" src="https://user-images.githubusercontent.com/67599130/107119548-53df8100-68c3-11eb-80b3-128ca913d3ee.png">
<img width="446" alt="alligned" src="https://user-images.githubusercontent.com/67599130/107119549-55a94480-68c3-11eb-8db3-cac4dab28d4b.png">

I made the search bar longer. Should I make it aligned with the cards?
Is the search bar long enough?

**Comment by LeeRenJie** [comment]
![image](https://user-images.githubusercontent.com/67599130/107119699-470f5d00-68c4-11eb-83e5-958b0d044ba1.png)
Can I redesign the dropmenu color from the DropMenu,jsx file?

**Comment by Kajol-Kumari** [comment]
@LeeRenJie please make the width of the search box same as the broadcast-card and also please make it aligned with the below cards. And yes, you can resign the dropdown menu. We just want it to look decent and consistent.

**Comment by LeeRenJie** [comment]
Ok will try thanks!

**Comment by LeeRenJie** [comment]
![image](https://user-images.githubusercontent.com/67599130/107141166-0108d680-6962-11eb-9fcc-88f00d7ee07e.png)
Am I supposed to convert all of these into the CSS file? I'm kinda confused. Because I've seen the other components and mostly their styles are in the js file too.

**Comment by LeeRenJie** [comment]
![image](https://user-images.githubusercontent.com/67599130/107141684-7a55f880-6965-11eb-966c-fac19586d1a9.png)
Since fade is imported at the js file, how do I use it in the css file?

**Comment by LeeRenJie** [comment]
### Progress
- [ ] Currently few of the styles are present in js file. Keep all styles in css file
- [x]  Change the heading from Broadcasts to All Broadcasts
- [ ]  Increase the width of search-box
- [x]  Enhancement in UI of the search-box and filter buttons ( this will carry bonus point )

##Problems faced:
I have no clue how to correctly convert the styles from js file into css file. Are there any guides?
I have no clue how to align the search box with the cards too to make it responsive. Are there any guides? Or can this be another issue?
https://user-images.githubusercontent.com/67599130/107151811-92e30480-699f-11eb-99a7-5ec5243ccb13.mp4

**Comment by Kajol-Kumari** [comment]
Hey @LeeRenJie there isn't any specific guidelines as such. You just need to find and use the alternatives wherever possible.
For the search box, you can give it right padding in order to make it aligned with the cards

**Comment by LeeRenJie** [comment]
Alright I'll try again

**Comment by LeeRenJie** [comment]
This is how it looks like now. May I create a PR to be reviewed?
![image](https://user-images.githubusercontent.com/67599130/107192358-77700c00-6a28-11eb-9e03-b40432c2f67b.png)
