### ISSUE TITLE
[ Discussion ]  Decide color pallet for the website

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#37]
As we are almost ready with the UI. We need to decide the color pallete that will be followed while implementing those designs.

This issue is focused on having the discussion on color pallet and it's finalisation.

Feel free to drop your pallete suggestions in the comments below.

**Comment by Aaryan8751** [comment]
These have some good suggestions https://color.adobe.com/explore

**Comment by reetpriye** [comment]
Why not start with something first, then, later on, change according to everyone's wish.
This one seems fine https://colors.lol/blocky

**Comment by Kajol-Kumari** [comment]
Yeah let's start with [this]( https://colors.lol/blocky) pallet and later on we can modify it, if needed. Btw it seems good to me. Thanks @Aaryan8751 and @reetpriye for pallet suggestions!
