### ISSUE TITLE
Fix Resource, Admin and Contact Us Page

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#370]
Deliverable:

- [ ] The resource form got distorted after shifting to `css-module` We need to fix it

- [ ] The contact us form got distorted after shifting to `css-module` We need to fix it
- [ ] The admin page form got distorted after shifting to `css-module` We need to fix it

**Comment by sakshikhachane** [comment]
I would

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari I would like to work on this issue.

sure @sakshikhachane . Go ahead :)
