### ISSUE TITLE
Enhancement in Add Broadcast Page of Admin

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#371]
Deliverable:

- [ ] Make the Page responsive
- [ ] On hover, the placeholder should appear in appropriate size.
- [ ] Put everything on a card and add a submit button at the end of the card
- [ ] Make sure to keep the navigation panel of the admin stick to left and render the edit toolbar on the right panel only

**Comment by sakshikhachane** [comment]
@Kajol-Kumari I would like to work on this issue.

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari I would like to work on this issue.

sure @sakshikhachane 
Go ahead :)

**Comment by Kajol-Kumari** [comment]
@sakshikhachane just a minor add on. Please make sure to have the left panel of the admin stick and render the `add_broadcast` form on the right panel.

**Comment by sakshikhachane** [comment]
@Kajol-Kumari Sure :)
