### ISSUE TITLE
Refactor Broadcast Page

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#372]
Deliverable:

- [ ] Make a `test_data` directory under `frontend/src` folder. Make a file named `broadcast.json` and add the broadcast data there. Remove the strings from [here](https://github.com/HITK-TECH-Community/Community-Website/blob/main/frontend/src/components/broadcast/all_broadcasts/all_broadcasts.js#L10)
- [ ] Use this json to render on the broadcast and `all_broadcast` page and also in the `carousel`

Format of json -

```
{
   "title": "Title of the Broadcast",
   "content" : "This will contain the data of the broadcast (well formatted)",
   "link" : the url will go here
}
```

Please make sure to execute the html tags present in the `content` of the broadcast i.e the content should be well formatted instead of of just string

**Comment by nehaparmar99** [comment]
I'd like to work on it.

**Comment by nehaparmar99** [comment]
I'd like to work on it

**Comment by nehaparmar99** [comment]
I'd like to give it a try.

**Comment by ashuvssut** [comment]
I want to do this. will submit PR within 2 days😁

**Comment by Kajol-Kumari** [comment]
Hey @ashuvssut as we need to follow FCFS so I am assigning this issue to @nehaparmar99 
Happy learning :)
