### ISSUE TITLE
[Frontend] Home page of the Community-Website

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#38]
In this issue, we want to revamp the home page having better header, footer and home page content by following [this](https://colors.lol/blocky) color pallet.

Deliverables:

- [ ] Better Header { Just keep `home`, `Contact Us`, `Broadcasts`, `Resource Share`, `About Us`, `FAQ`  in the header section along with `admin?` on the right side of the header }

- [ ] Better Footer { Use better logo for social media handles, add a line `All right reserved by @Hitk-Tech-Communty`  or `Made with :heart: by HITK Tech Community` in the footer.}
 
- [ ] Better Home page Content { This page should include a brief about who are are (put dummy text as of now) along with our motive(put dummy text as of now) in most attractive way possible }

**Comment by reetpriye** [comment]
I want to work on this one. Can you assign it to me?

**Comment by Kajol-Kumari** [comment]
> I want to work on this one. Can you assign it to me?

Hey @reetpriye please go ahead with this issue.
