### ISSUE TITLE
[Frontend] Fix Button Issues

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#385]
Deliverable:

- [ ] Currently, the button's of different form has deformed. Fix it so that it remains consistent through-out
- Join Us Form
- Contact Us Form
- Admin Form
- Resource Sharing form

Make sure to make the buttons consistent for all the form on all screens

**Comment by vedikaag99** [comment]
@Kajol-Kumari can I work on this issue?

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari can I work on this issue?

sure @vedikaag99 Please go ahead :)
