### ISSUE TITLE
[Frontend] Fix Admin Login Form

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#386]
Deliverable:

- [ ] The hide/show button is behaving weird (sometime it works and other time, it doesn't). Fix it
- [ ] The cursor should be pointer as soon as one hover over the eye icon
- [ ] Don't forget to add hovering effect.(only for show/hide icon)

**Comment by Ohranj** [comment]
I have sent you a pull request for this. Thank you

**Comment by Kajol-Kumari** [comment]
> I have sent you a pull request for this. Thank you

Hey @Ohranj as no one else has claimed this issue. we would he happy to accept your PR but from next time, please make sure to get an issue assigned before coming up with a PR

**Comment by Ohranj** [comment]
Hey, sorry. It was my first PR so I wasn't sure of the correct way to go about it. I know now for the future though. Thank you.
