### ISSUE TITLE
Enhancements in Frontend

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#387]
Deliverable:

- [ ] Reduce the card height for `Recent Broadcast` and `previous broadcast` section same as the card height of `All broadcasts` page
- [ ] Add a dash line below the heading on `All Broadcast` page similar to `Recent Broadcast` page
- [ ] Reduce the Card height for `Get Involved` Page

**Comment by LeeRenJie** [comment]
I would like to work on this

**Comment by Kajol-Kumari** [comment]
> I would like to work on this

sure @LeeRenJie Please go ahead
Happy Learning :)

**Comment by LeeRenJie** [comment]
![image](https://user-images.githubusercontent.com/67599130/107883104-d69db700-6f27-11eb-9ae4-c2fd6e423046.png)
I tried reducing the height of the card but the words were still there. How do I tackle this issue? I tried to tap into the height of the card-item.

**Comment by LeeRenJie** [comment]
> ![image](https://user-images.githubusercontent.com/67599130/107883104-d69db700-6f27-11eb-9ae4-c2fd6e423046.png)
> I tried reducing the height of the card but the words were still there. How do I tackle this issue? I tried to tap into the height of the card-item.

I found a way to solve this but maybe it is better if there is a way to limit the words in the card shown
