### ISSUE TITLE
Enhancement in Admin Panel

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#388]
Deliverable:

- [ ] For Dashboard, please do the following -
    - Remove the count data
    - Make the icons a bit bigger
    - Make the content font a bit bigger(16px maybe)
    - The card should contain only heading and content 

- [ ] The Profile section has got distorted, please fix it

P.S - If you can come up with a better UI for profile section, would be happy to give you bonus points :)

**Comment by LeeRenJie** [comment]
I would like to work on this too

**Comment by Kajol-Kumari** [comment]
> I would like to work on this too

Sure @LeeRenJie Go ahead!
Happy learning :)
