### ISSUE TITLE
[Frontend] Refactor the frontend Codebase

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#389]
Deliverable:

- [ ] Refactor the whole frontend following the guidelines give at https://github.com/HITK-TECH-Community/Community-Website/blob/main/frontend/PROPOSAL.md

**Comment by sakshikhachane** [comment]
@Kajol-Kumari I would like to work on this issue. Please assign me this issue.

**Comment by salil-naik** [comment]
@Kajol-Kumari I think we will have to break this issue down into smaller modules. 

Let me refactor any one component first. Then we can ask others to refer to that and assign 1 component at a time to the contributors.

**Comment by Kajol-Kumari** [comment]
Yeah @salil-naik  makes sense. Will open the issue component-wise then
