### ISSUE TITLE
[Frontend] FAQ page for community website

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#39]
Deliverables:

Make the FAQ page for the community website with design similar to [this](https://files.slack.com/files-pri/T01FW9Q8AHH-F01H30BQMN3/capture.png) following [this](https://colors.lol/blocky) color pallet.

![Capture](https://user-images.githubusercontent.com/44888949/103067594-47d48400-45e1-11eb-8165-dd1b7565303d.PNG)

If you can make it more standard and attaractive, that would be much appreciated :)

**Comment by Aaryan8751** [comment]
@Kajol-Kumari could you please assign me this issue.

**Comment by sreechand2002** [comment]
@Kajol-Kumari can i work on this?

**Comment by Kajol-Kumari** [comment]
Hey @sreechand2002, please look for some other issue as we follow FCFS. So I am assigning it to @Aaryan8751 
looking forward to your PR @Aaryan8751 :)

**Comment by Kajol-Kumari** [comment]
Hey @Aaryan8751 can you please tell us, if you are still working on this issue?

**Comment by Aaryan8751** [comment]
@Kajol-Kumari Actually I am busy in the preparation of my exams. Sorry I could do this one work. I will resume my contributions to this project from January 5.

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari Actually I am busy in the preparation of my exams. Sorry I could do this one work. I will resume my contributions to this project from January 5.

Thanks for letting me know this!

**Comment by Kajol-Kumari** [comment]
@sreechand2002 would you like to go ahead with this issue?

**Comment by sreechand2002** [comment]
Sure @Kajol-Kumari

**Comment by Kajol-Kumari** [comment]
Hey @sreechand2002 please try to implement [this](https://files.slack.com/files-pri/T01FW9Q8AHH-F01H30BQMN3/capture.png) UI for the FAQ page as the previous given template have been implemented already

**Comment by sreechand2002** [comment]
https://github.com/HITK-TECH-Community/Community-Website/issues/10#issuecomment-739879010
should i implement this design

**Comment by Kajol-Kumari** [comment]
> Hey @sreechand2002 please try to implement [this](https://files.slack.com/files-pri/T01FW9Q8AHH-F01H30BQMN3/capture.png) UI for the FAQ page as the previous given template have been implemented already

@sreechand2002 You need to apply the design mentioned here and in this issue description.

**Comment by Kajol-Kumari** [comment]
> [#10 (comment)](https://github.com/HITK-TECH-Community/Community-Website/issues/10#issuecomment-739879010)
> should i implement this design

NO, @sreechand2002 you need to implement this design 
![Capture](https://user-images.githubusercontent.com/44888949/103067579-3db28580-45e1-11eb-9deb-36d9624f4419.PNG)
