### ISSUE TITLE
Integrated Login Feature with backend

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#396]
Deliverable-
- Integrate the login form with backend
- After successful login, it should direct to admin dashboard

For backend, checkout`/backend` folder

**Comment by LeeRenJie** [comment]
I would like to try this

**Comment by tanay13** [comment]
@Kajol-Kumari please assign this to me

**Comment by LeeRenJie** [comment]
https://github.com/rishipr/mern-auth/
Can I work on this with reference of this repo

**Comment by Kajol-Kumari** [comment]
> I wish to work on this, but can I have a guide to follow?

Hey @LeeRenJie I can connect you with someone who can guide you for the same. Feel free to join in our slack channel(you can find the lonk in our readme file) and ping me there once.

**Comment by amanprateek123** [comment]
@Kajol-Kumari  Can I work on this issue ?

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari Can I work on this issue ?

Hey @amanprateek123 sorry but @LeeRenJie is already working on it. Please look for other opened issues.
