### ISSUE TITLE
[Frontend] Fix Navbar

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#399]
Deliverable:

- [ ] Convert `navbar.scss` to `navbar.module.css` 
- [ ] The menu bar icon isn't appearing for small screen, please fix it.

**Comment by LeeRenJie** [comment]
Can I work on this? What is the max-width for small screen?

**Comment by Kajol-Kumari** [comment]
> Can I work on this? What is the max-width for small screen?

Sure @LeeRenJie The maximum width for small screen is `600px`

**Comment by LeeRenJie** [comment]
![image](https://user-images.githubusercontent.com/67599130/108198567-bf90dc00-7156-11eb-8d22-e4d3355ef87d.png)
I managed to fix it, but there is a bug when I press it
![image](https://user-images.githubusercontent.com/67599130/108198626-cfa8bb80-7156-11eb-92c4-44387a5be93c.png)
