### ISSUE TITLE
[Open for all] Add Header and Footer

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#4]
- Add header and footer as reusable component so that It can just be rendered wherever required.

Dependent of issue #3 [ First This issue needs to be resolved ]

**Comment by codewithvk** [comment]
Can we use any react library? Ex. Material UI, Semantic UI

**Comment by Kajol-Kumari** [comment]
Hey @codewithvk yes, You can use material UI

**Comment by codewithvk** [comment]
I want to work on that. can you assign me?

**Comment by sreechand2002** [comment]
can to assign this to me

**Comment by Kajol-Kumari** [comment]
Hey @codewithvk as this issue is dependent on #3. I request you to please finish that one. Also we can't assign more than one issue at once to anybody. So waiting for your PR for the previous one :)

Hey @sreechand2002 you can go ahead with this one one @codewithvk finishes the dependent issue. Meanwhile you can explore on its implementation, I am assigning it to you. Happy Learning :)

**Comment by codewithvk** [comment]
@Kajol-Kumari I already Made pr for #3. You can check.

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari I already Made pr for #3. You can check.

Ah, I saw it late. No worries more issue are coming for grab :)

**Comment by Aaryan8751** [comment]
Hi @Kajol-Kumari  I wanna work on this.

**Comment by Kajol-Kumari** [comment]
Hey @Aaryan8751 you can go ahead with this one. Please make sure to add the test the code and do the following:
1. create a folder with name `header_and_footer`.
2. Make a folder under this with your name and put the header and footer files in there after testing.

This is required as we would be picking up the best style and use it in our website. If you need any further clearance, pleaselet me know.

Happy Coding :)

**Comment by Aaryan8751** [comment]
@Kajol-Kumari  may I use reactstrap, font awesome?

**Comment by Aaryan8751** [comment]
@Kajol-Kumari I have added the header and footer and have also made a pull request. 
![screencapture-localhost-3000-home-2020-12-08-01_52_18](https://user-images.githubusercontent.com/60098288/101401711-b8e51d80-38f8-11eb-87fe-a7bab66b437a.png)
Here is the screenshot of the page Please have a look.
