### ISSUE TITLE
[Frontend] Contact Us Page

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#40]
Deliverables:

- [ ] Make the `contact us` page of the community-website following [this](https://github.com/HITK-TECH-Community/Community-Website/blob/main/assets/Contact_us/SreeChand/Contact%20us.png) design and [this](https://colors.lol/blocky) color pallet.

If you can make this page preetier and consistent, it would be much appreciated :)

**Comment by PinRathod** [comment]
Can I work on this?

**Comment by Aaryan8751** [comment]
could you assign me this issue?

**Comment by Aaryan8751** [comment]
@Kajol-Kumari could you assign me this issue

**Comment by Kajol-Kumari** [comment]
Hey @PinRathod go ahead with this issue :+1: 
@Aaryan8751 please pick up any other issue.

**Comment by Kajol-Kumari** [comment]
Hey @PinRathod can you please let us know if you are still working on this issue?

**Comment by PinRathod** [comment]
Yes,I am working on this issue.

**Comment by sreechand2002** [comment]
@Kajol-Kumari can i take over this issue and complete it within couple of minutes  as i see its been pending since a long time

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari can i take over this issue and complete it within couple of minutes as i see its been pending since a long time

Sure @sreechand2002 you can go ahead with this issue

**Comment by sreechand2002** [comment]
@Kajol-Kumari a contact us page is already implemented , should i replace that with this given design?

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari a contact us page is already implemented , should i replace that with this given design?

No, keep the already present page codes, just implement this new UI in the `/contact` path

**Comment by sreechand2002** [comment]
ok sure, @Kajol-Kumari  can i go with semantic ui react, as in material ui the code is lengthy and by using semantic ui react  its way easier to implement the component's designs

**Comment by Kajol-Kumari** [comment]
> ok sure, @Kajol-Kumari can i go with semantic ui react, as in material ui the code is lengthy and by using semantic ui react its way easier to implement the component's designs

sure @sreechand2002 go ahead with `seantic ui` if you think it will ease the work :)

**Comment by Amit0412** [comment]
CAN I WORK ON THIS?

**Comment by sahebsunny** [comment]
Sir, I love to work on it.
I would be grateful if you can assign this issue to me for DSWOC.
Thank you.

**Comment by Kajol-Kumari** [comment]
Hey @sahebsunny @Amit0412 Thanks for your interest but this page has already been implemented and finalised. We will be opening more issue by morning, feel free to pick any from them.

**Comment by Amit0412** [comment]
OK.THANKYOU MADAM.I WILL WAIT FOR IT.
