### ISSUE TITLE
Enhancement in Edit Broadcast modal

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#400]
Deliverable:

- [ ] Change the pencil icon for edit to a button similar to `view` button 
- [ ] Place the button just below the `view button`
- [ ] The modal UI needs to be improved
- [ ] The modal should appear in the middle of the page(currently, we scroll to bottom and click on edit, we aren't able to see the modal)

**Comment by amanprateek123** [comment]
@Kajol-Kumari assign this issue to me

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari assign this issue to me

Please go ahead! 
Happy Learning :)
