### ISSUE TITLE
Manage Broadcast Feature for Admin

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#401]
Deliverable:

- [ ] The `manage broadcast` card should take to the page of all broadcasts 
- [ ] All the broadcasts should have a delete icon that should allow the admin to delete(currently it would be temporary as we haven't integrated the backend)

**Comment by ashuvssut** [comment]
i want to work on this

**Comment by Kajol-Kumari** [comment]
> i want to work on this

Please go ahead! 
Happy Learning :)

**Comment by ashuvssut** [comment]
can I use [this](https://github.com/useAnimations/react-useanimations) for delete icon
