### ISSUE TITLE
[Frontend] FAQ For Admin 

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#403]
Deliverable:

- [ ] Add two cards `Add FAQ` and `Manage FAQ` similar to broadcast page
- [ ] `Add FAQ` will led to a new page having the left panel same as FAQ page and a form on the right right. This form will contain two fields -
a. Question
b. Answer

**Comment by sakshikhachane** [comment]
@Kajol-Kumari I would like to work on this issue as well.

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari I would like to work on this issue as well.

sure @sakshikhachane Please go ahead with this issue!
Happy Learning :)
