### ISSUE TITLE
[Frontend] Fix menu for smaller screens

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#410]
Deliverable:

- [ ] Currently, the menu list appearing in distorted way for small screens, fix it to appear as expected.

GIF of Issue:
![menu_bug](https://user-images.githubusercontent.com/44888949/108598598-7f2e9980-73b4-11eb-9a08-b5bba3830b0a.gif)

**Comment by sakshikhachane** [comment]
@Kajol-Kumari I would like to work on this issue.

**Comment by ashuvssut** [comment]
😬😬😓😓

**Comment by Kajol-Kumari** [comment]
@sakshikhachane please go ahead :)

**Comment by salil-naik** [comment]
@Kajol-Kumari Sakshi could not solve this as it is a bit complicated. 

I'll figure out the issue and fix it by tomorrow.

**Comment by ashuvssut** [comment]
if by any chance this issue becomes open-to-grab, then I am interested to work on this

**Comment by salil-naik** [comment]
@ashuvssut try to fix the issue.

**Comment by ashuvssut** [comment]
@salil-naik done
