### ISSUE TITLE
Refactoring 404 & About Us component

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#411]
Refactor the `404 and About Us` Component as per the [proposed style](https://github.com/HITK-TECH-Community/Community-Website/blob/main/frontend/PROPOSAL.md). 

Note- Please make sure to follow all the guidelines mentioned in the proposed style properly!

**Comment by amanprateek123** [comment]
@kajol assign this issue to me

**Comment by Kajol-Kumari** [comment]
Sure @amanprateek123 
Please go ahead :)
