### ISSUE TITLE
[Frontend] Refactoring Admin component

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#412]
Refactoring the Whole `Admin` and it's sub-components as per the [proposed style](https://github.com/HITK-TECH-Community/Community-Website/blob/main/frontend/PROPOSAL.md). 

Note- Please make sure to follow all the guidelines mentioned in the proposed style properly!

**Comment by amanprateek123** [comment]
plaese assign this issue to me @Kajol-Kumari

**Comment by Kajol-Kumari** [comment]
Sure @amanprateek123 
Please go ahead :)
