### ISSUE TITLE
Refactoring Login& Contact component

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#413]
Refactoring the `Login` & `Contact` as per the [proposed style](https://github.com/HITK-TECH-Community/Community-Website/blob/main/frontend/PROPOSAL.md). 

Note- Please make sure to follow all the guidelines mentioned in the proposed style properly!

**Comment by sakshikhachane** [comment]
@Kajol-Kumari Please assign me this issue. I assure you to complete this as I have completed working on one issue assigned to me.

**Comment by ShivangiRai1310** [comment]
Would like to work on this issue under SWOC and DWOC.
