### ISSUE TITLE
Refactoring Broadcast component

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#414]
Refactoring the `Broadcast` as per the [proposed style](https://github.com/HITK-TECH-Community/Community-Website/blob/main/frontend/PROPOSAL.md). 

Note- Please make sure to follow all the guidelines mentioned in the proposed style properly!

**Comment by sakshikhachane** [comment]
@Kajol-Kumari Please assign me this issue. I assure you to complete this as I have completed working on one issue assigned to me.

**Comment by Kajol-Kumari** [comment]
Hey @sakshikhachane please go ahead with this issue :)
