### ISSUE TITLE
Refactoring DropMenu & FAQ component

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#415]
Refactoring the  `DropMenu & FAQ` as per the [proposed style](https://github.com/HITK-TECH-Community/Community-Website/blob/main/frontend/PROPOSAL.md). 

Note- Please make sure to follow all the guidelines mentioned in the proposed style properly!

**Comment by amanprateek123** [comment]
@kajol assign this issue to me

**Comment by Kajol-Kumari** [comment]
> @kajol assign this issue to me

Hey @amanprateek123 I am sorry but I can't assign you more than three issues at once.

**Comment by amanprateek123** [comment]
@Kajol-Kumari  but I have 2 issues assigned

**Comment by ashuvssut** [comment]
I want to work on this. I have completed my 2 assigned issues and submitted PRs

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari but I have 2 issues assigned

my bad! your one PR has been merged
