### ISSUE TITLE
Refactoring Footer&Get_Involved component

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#416]
Refactoring the `Footer & Get_involved` as per the [proposed style](https://github.com/HITK-TECH-Community/Community-Website/blob/main/frontend/PROPOSAL.md). 

Note- Please make sure to follow all the guidelines mentioned in the proposed style properly!

**Comment by ashuvssut** [comment]
i want to work on this

will submit PR the within 2 days after assignment

**Comment by sanjay270899** [comment]
@Kajol-Kumari I would Like to work on this.

**Comment by ashuvssut** [comment]
completed all 3 refactoring PRs. please assign me this issue.

Will submit PR on the same day when assigned

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari I would Like to work on this.

@sanjay270899 please go ahead with this issue 
Happy Learning :)

**Comment by Kajol-Kumari** [comment]
@sanjay270899 can you please confirm once if you are working on this issue?

**Comment by sanjay270899** [comment]
@Kajol-Kumari Yes, I am working on it. Just `scss` is left.

**Comment by sanjay270899** [comment]
@Kajol-Kumari Done.
