### ISSUE TITLE
Refactoring Home component

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#417]
Refactoring the `Home` Component as per the [proposed style](https://github.com/HITK-TECH-Community/Community-Website/blob/main/frontend/PROPOSAL.md). 

Note- Please make sure to follow all the guidelines mentioned in the proposed style properly!

**Comment by ashuvssut** [comment]
i want to work on this

will submit PR the within 2 days after assignment

**Comment by Kajol-Kumari** [comment]
Hey @ashuvssut I can assign one more issue so can you please tell me if you would like to go with this one or (#416)

**Comment by ashuvssut** [comment]
assign me this one only

I am working on the issue you assigned me last yesterday. I will be submitting my PR today only.

So you can consider assigning me issue 416 also
