### ISSUE TITLE
Refactoring Privacy_policy & Resource component

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#418]
Refactoring the `Privacy Policy` and `Resource` as per the [proposed style](https://github.com/HITK-TECH-Community/Community-Website/blob/main/frontend/PROPOSAL.md). 

Note- Please make sure to follow all the guidelines mentioned in the proposed style properly!

**Comment by ashuvssut** [comment]
i want to work on this

will submit PR the next day
