### ISSUE TITLE
Refactoring Terms & Util component

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#419]
Refactoring the `Terms` and `Util` as per the [proposed style](https://github.com/HITK-TECH-Community/Community-Website/blob/main/frontend/PROPOSAL.md). 

Note- Please make sure to follow all the guidelines mentioned in the proposed style properly!

**Comment by ashuvssut** [comment]
i want to work on this

**Comment by Kajol-Kumari** [comment]
@ashuvssut please go ahead :)
