### ISSUE TITLE
[Bug] Admin FAQ Bug

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#421]
Deliverable:

- [ ] The FAQ page isn't working as expected. The `add faq` button isn't showing correct form

GIF of Bug
![faq_bug](https://user-images.githubusercontent.com/44888949/108622432-ce310900-745e-11eb-9646-f904d3f88845.gif)

**Comment by Swastik1710** [comment]
Hey @Kajol-Kumari, I would love to work on this.
Please assign me this issue so that I can start working on it.

**Comment by Swastik1710** [comment]
I've made a PR - #423 
Please have a look.

**Comment by Swastik1710** [comment]
Hey , can you please tell me how can I see this page on my Local Machine.
This page isn't visible to me.

**Comment by Kajol-Kumari** [comment]
> Hey , can you please tell me how can I see this page on my Local Machine.
> This page isn't visible to me.

Hardcode in the url `/dashboard` i.e visit `https://localhost:300/dashboard`

**Comment by Swastik1710** [comment]
But /dashboard takes me to this page.
![1](https://user-images.githubusercontent.com/71871571/108632031-dd31ae80-7492-11eb-9471-9921c029e743.jpg)

**Comment by Kajol-Kumari** [comment]
> But /dashboard takes me to this page.
> ![1](https://user-images.githubusercontent.com/71871571/108632031-dd31ae80-7492-11eb-9471-9921c029e743.jpg)
> 
> How can I reach the Welcome Admin page

Pull the latest changes

**Comment by Swastik1710** [comment]
Please have a look at #428
