### ISSUE TITLE
Adding ISSUE TEMPLATES 

### ISSUE THREAD

**Issue by Swastik1710** [HITK-TECH-Community/Community-Website#424]
Adding more issue templates like Documentation, Proposal, etc.
This would help describe the issue clearly.
As of now there are three of them, namely  Bug, Refactor and Feature.

**Comment by Swastik1710** [comment]
Kindly assign it to me so that I can start working on it.

**Comment by Swastik1710** [comment]
Hey @Kajol-Kumari,
Can you please have a look at this?

**Comment by Kajol-Kumari** [comment]
@Swastik1710 please checkout my comment of #238 If you come up with a valid PR, I would be happy to merge :)

**Comment by Swastik1710** [comment]
Hey @Kajol-Kumari , I've made a PR regarding this -> #436 
Please have a look.
