### ISSUE TITLE
[Frontend] Inconsistent Place Holder of Forms

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#429]
Deliverable:

- [ ] The forms have inconsistent placeholder font-size. Make it consistent.(make it same the smaller one's font-size)

GIF Of Bug:
![froms_placeholder](https://user-images.githubusercontent.com/44888949/108668406-3a644900-7501-11eb-9661-459d960dc5bb.gif)

**Comment by LeeRenJie** [comment]
I would like to work on this

**Comment by Kajol-Kumari** [comment]
> I would like to work on this

Please go ahead @LeeRenJie
