### ISSUE TITLE
[Document] Add PR creation template

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#43]
Deliverables:

- [ ] A good enough PR template that contain all the required sections including which issue it closes `closes #issue_num`, Feature/changes introduced through the PR etc.

**Comment by kenkirito** [comment]
working on it

**Comment by Kajol-Kumari** [comment]
Closing via [this](https://github.com/HITK-TECH-Community/Community-Website/pull/44) PR
