### ISSUE TITLE
Admin Dashboard Bug

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#430]
Follow these steps:
1. Go to admin dashboard
2. click on Broadcast card
3. Click on `add_broadcast` card
4. Now, again go to dashboard and click on the `broadcast` card
This time you won't get the page containing two options, instead, you will get the `add_broadcast` page directly.
- The same issue is for FAQ.

GIF of Bug:
![admin_dashboard](https://user-images.githubusercontent.com/44888949/108669025-400e5e80-7502-11eb-8bb1-5cc190ec028f.gif)

**Comment by sakshikhachane** [comment]
@Kajol-Kumari I would like to work on this issue. I have worked on this. I will make PR in 3 hours.
