### ISSUE TITLE
[Frontend] Logo gets hide in Home Page for Small Screen

### ISSUE THREAD

**Issue by sanjay270899** [HITK-TECH-Community/Community-Website#448]
**Describe the bug**

Logo at the Top of the Home Page gets hide (half) when the screen size is between `393px` to `489px`.

**To Reproduce**
1. Go to `Home Page`
2. Click on `Open Inspect Tool`
3. Scroll down to `Toggle Device Emulation`
4. Resize the screen between `393px` to `489px`
4. We can see the logo gets hide somewhat.

**Expected behavior**
It should not get hide.

**Screenshots**

![image](https://user-images.githubusercontent.com/43892590/108986286-fa939200-76b7-11eb-82f5-ce3709a48974.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Edge

**Smartphone (please complete the following information):**

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Yes.

I would Like to Fix this.

**Comment by Kajol-Kumari** [comment]
Hey @sanjay270899 please try refreshing the page as I can't find this issue.

**Comment by sanjay270899** [comment]
@Kajol-Kumari 
![bug_448](https://user-images.githubusercontent.com/43892590/109120175-a0540900-776b-11eb-8911-4f7bd3f98508.gif)

**Comment by Kajol-Kumari** [comment]
@sanjay270899 would you like to fix it's responsiveness?

**Comment by sanjay270899** [comment]
@Kajol-Kumari Sorry for tagging again. But I have checked in other browser also, and same result is coming. You can see in above GIF.
