### ISSUE TITLE
[Frontend] Some Bugs

### ISSUE THREAD

**Issue by sanjay270899** [HITK-TECH-Community/Community-Website#451]
**Describe the bug**

1. Bug 1
Join Us Button is not at center.
![image](https://user-images.githubusercontent.com/43892590/109020555-11e67580-76e0-11eb-833e-2d6c10373303.png)

2. Bug 2
Text of Footer Sign Up Button is out of the button.
![image](https://user-images.githubusercontent.com/43892590/109020434-f67b6a80-76df-11eb-8a2b-b1d790b64c7f.png)

**To Reproduce**
1. Go to `Home Page`
2. Click on `Open Inspect Tool`
3. Scroll down to `Toggle Device Emulation`
4. Resize the screen to `786px` 
4. We can see the above bugs.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] **Windows**
 - Browser [e.g. chrome, safari] **Edge**

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Yes.

I would Like to fix it.

**Comment by Kajol-Kumari** [comment]
Hey @sanjay270899 Thanks for pointing these out. Please go ahead with fixing it.
