### ISSUE TITLE
Handle different kind of error while logging In

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#456]
Deliverable:
We need to handle the follow errors and show relevant message to the user using `Toast`
1. Backend server not runing
2. Status 400 - Unauthorised
3. For rest, show `Something went wrong`

P.S - This issue can only be worked on after closing #454

**Comment by ashuvssut** [comment]
I will work on this

**Comment by Kajol-Kumari** [comment]
Please go ahead @ashuvssut

**Comment by sahildotexe** [comment]
Hey !! I 'm a participant of GSSOC'21, can you assign this issue to me?
