### ISSUE TITLE
[Frontend] Toast Message for showing different kind of messages

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#457]
Deliverable:

- [ ] We need to have a `Toast` component under `util` folder which will contain the code for showing three kinds of messages
- Info
- Error
- Success
You can take reference of [this](https://images.ctfassets.net/itcc7vu35nc1/4JD0rxbVJzBoOltVWS7JkI/2c1c4969bf8d16ffc98d7bc849e286e4/toast_options_action_2x.png) for it's UI

- [ ] The toast message should appear at the bottom-center of the page and should have a good animation effect.

**Comment by ashuvssut** [comment]
i want to work on this

**Comment by amanprateek123** [comment]
@Kajol-Kumari  want to work on this issue
