### ISSUE TITLE
Add Different Error Handling Pages

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#462]
Deliverable:
- Make a folder named as `ErrorHandlerPages` under `component` and make a `LoggedIn` folder that will contain a page saying 

`You are already Logged In, Please visit here to access your Dashboard`

- Display this page to the superadmins who are already logged In and still try to login by clicking on `admin` button

- Move `404` folder form pages to this component

**Comment by amanprateek123** [comment]
assign this issue to me @Kajol-Kumari

**Comment by Kajol-Kumari** [comment]
Please go ahead @amanprateek123 :)

**Comment by Kajol-Kumari** [comment]
Hey @amanprateek123 just an add-on to the above. The navbar shouldn't be visible to these error page including `404` as well.
