### ISSUE TITLE
Logout Functionality Enhacement

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#465]
Deliverable:

Currently, tho the logout is making the token null but it's showing 404 page in between.

- [ ] We shouldn't see any `not found` page in between.
- [ ] After logging out, we should see a toast message saying `Successfully Logged Out!` on the login page(the admin will be directed here after successful logging out)
- [ ] If any error occurs while logging out, we should see a toast message saying `Something went wrong` and no navigation should happen in this case.

Current Logout Functionality -
![logout_bug](https://user-images.githubusercontent.com/44888949/109286255-057d2c80-7848-11eb-84af-32165cbfceb5.gif)

**Comment by amanprateek123** [comment]
@Kajol-Kumari  assign this issue to me
