### ISSUE TITLE
Make the Admin List Dynamic

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#468]
Currently, the admin list under `setting/manage Admin` is static.

- [ ] Fetch the data from backend api `localhost:3500/admin/` and populate this data dynamically. As we don't store image in the backend, you can keep the dummy image.

**Comment by amanprateek123** [comment]
@kajol assign this issue to me

**Comment by amanprateek123** [comment]
@kajol plaese assign this issue to me
