### ISSUE TITLE
Reset Password Feature

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#469]
- [ ] Add the link for resetting password on login form.

- [ ] Reset Password form will contain the following fields

1. Old Password
2. New Password
3. Confirm New Password

- [ ] Integrate it with backend using `http://localhost:3500/admin/password` path. Show toast message after successful password change

**Comment by sukhpreet-singh1** [comment]
can you please assign me this issue under GSSOC 21

**Comment by Kajol-Kumari** [comment]
> can you please assign me this issue under GSSOC 21

Sure! You can go ahead with this issue. 
Happy Learning :)

**Comment by Kajol-Kumari** [comment]
Hey @sahildotexe as this issue is already assigned to someone, I request you to look for some other open issues. @sukhpreet-singh1 can you please provide an update on this issue.

**Comment by sukhpreet-singh1** [comment]
yeah i was going through the code now working on issue

**Comment by garvitgupta13** [comment]
> * [ ]  Add the link for resetting password on login form.
> * [ ]  Reset Password form will contain the following fields
> 
> 1. Old Password
> 2. New Password
> 3. Confirm New Password
> 
> * [ ]  Integrate it with backend using `http://localhost:3500/admin/password` path. Show toast message after successful password change

Can I work on this issue under gssoc21

**Comment by Kajol-Kumari** [comment]
Hey @garvitgupta13 please go ahead with this issue as it's already been more than 15 days and I haven't got an update on it.

**Comment by garvitgupta13** [comment]
I think that only logged-in users should be able to reset their password. So adding a link to reset the password in the login form would not be correct. I guess we should create a form for that, int the admin dashboard.

**Comment by Kajol-Kumari** [comment]
> I think that only logged-in users should be able to reset their password. So adding a link to reset the password in the login form would not be correct. I guess we should create a form for that, int the admin dashboard.

Yeah! this makes sense. So let's add a button of `reset-password` under `setting` tab of the admin panel and render the form after clicking on it.

**Comment by garvitgupta13** [comment]
It says that the `https://community-website-backend.herokuapp.com/admin/password` is not found.
Please look into this issue.
Updates:

- Created a form in settings tab
- Added toast message
- Only backend integrating part is left

![image](https://user-images.githubusercontent.com/70805691/112593034-ed8bcf00-8e2c-11eb-98d8-c3dcb520e7f2.png)

**Comment by Kajol-Kumari** [comment]
can you please use the baseurl of `localhost:3500` istead of heroku one and try testing the integration by runing the backend server on your local

**Comment by garvitgupta13** [comment]
> can you please use the baseurl of `localhost:3500` istead of heroku one and try testing the integration by runing the backend server on your local

![image](https://user-images.githubusercontent.com/70805691/112624302-774e9300-8e53-11eb-9f88-833fa3a5455a.png)
It also shows the same

**Comment by Kajol-Kumari** [comment]
Hey @garvitgupta13 it's seema like you are hitting tye wrong url. I will test the api via postman once and will let you know the correct path

**Comment by Kajol-Kumari** [comment]
Hey @garvitgupta13 I just noticed that you are making `POST` request instead make a `PUT` request to the same url and it would work perfectly fine

**Comment by garvitgupta13** [comment]
Everything is done.
But I am getting just one warning:
![image](https://user-images.githubusercontent.com/70805691/112670365-d5e13480-8e86-11eb-875c-1bd99be11e78.png)
Should I ignore this warning and create a pull request.

**Comment by Kajol-Kumari** [comment]
Hey @garvitgupta13 if the feature is working fine. Please feel free to open up the PR. We will take a look at it and will let you know if any changes are required

**Comment by garvitgupta13** [comment]
> Hey @garvitgupta13 if the feature is working fine. Please feel free to open up the PR. We will take a look at it and will let you know if any changes are required

just fixed that warning
