### ISSUE TITLE
Forgot Password Feature

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#475]
Deliverable:
Add a forgot password form having following field
1. Email Id
2. `Submit` Button

After clicking on `Submit` button, a new page should come up saying `An invitation link has been sent on your registered email, please check your inbox for further steps` Along with two buttons 1. To go to login page 2. To go to login page

**Comment by sukhpreet-singh1** [comment]
can you assign me this issue under GSSOC 21

**Comment by Shubham-Kumar-2000** [comment]
Hi, I would like to work on this feature as I have already implemented this on many projects I can easily do that. 
under GSSOC 21

Can you assign me this ?
@jackfrost13

**Comment by jackfrost13** [comment]
@Shubham-Kumar-2000 Please take up one task at a time
@sukhpreet-singh1 you have been already assigned something, please finish that first

**Comment by Shubham-Kumar-2000** [comment]
So should I make the frontend only Or should I work on both? @jackfrost13

**Comment by jackfrost13** [comment]
This issue is only for frontend, hence you need to work only on frontend right now.

**Comment by jackfrost13** [comment]
@sahildotexe This issue has been already assigned please look at other issue
