### ISSUE TITLE
[Backend] Delete admin

### ISSUE THREAD

**Issue by jackfrost13** [HITK-TECH-Community/Community-Website#477]
Create a route to delete an admin. This can be performed only if the request is made by a SuperAdmin.
Refer to existing route for help

API testing is required. Refer #81 for resources

**Comment by sukhpreet-singh1** [comment]
can you please assign me this issue.

**Comment by jackfrost13** [comment]
you are GSSoC participant right?

**Comment by sukhpreet-singh1** [comment]
yess

**Comment by Abhinaba006** [comment]
I am a GSSoC 21 participant, I will like it to work on this issue and deliver as fast as possible with clean and understandable code,  can you please @jackfrost13 assign me on this issue

**Comment by jackfrost13** [comment]
This has been already assigned. Please look at other open issued (unsassigned)

**Comment by jackfrost13** [comment]
@sukhpreet-singh1 Please update your status and open pr.

**Comment by kumarshobhit** [comment]
Hi. I would like to work on this issue. I am a GSSOC participant

**Comment by jackfrost13** [comment]
> Hi. I would like to work on this issue. I am a GSSOC participant

You have been assigned an issue. Complete that before taking up another

**Comment by kumarshobhit** [comment]
Ok noted. Thanks

**Comment by kumarshobhit** [comment]
Hi. I need a little help.For testing purposes, I might need to create a new admin. Please help as to how can I do that.

**Comment by jackfrost13** [comment]
You can do that using the `/admin/superadmin` route

**Comment by kumarshobhit** [comment]
ok noted. Thank you

**Comment by jackfrost13** [comment]
@kumarshobhit any update? please udpate else will have to reassign this to someone else

**Comment by kumarshobhit** [comment]
You may please reassign it. I won't be able to work on it.

**Comment by harshakhmk** [comment]
I would like to work on it

**Comment by PriyankjeetPradhan** [comment]
Can you assign this issue to me? ................I found this project **interesting** to work on.

**Comment by SciSaif** [comment]
Hi, is this issue still open? If so i would like to work on it!

**Comment by Gurdeep475** [comment]
I would like to work on this issue under GSSOC`22.

**Comment by PriyankjeetPradhan** [comment]
Hi , I'm a GSSOC'22 participant. Can you please assign this issue to me and I'll be happy to work with it.

**Comment by Kajol-Kumari** [comment]
@SciSaif please go ahead with this issue. @PriyankjeetPradhan please look for other issues as we can assign on the basis of FCFS(First Come, First Serve)

**Comment by arinmodi** [comment]
@Kajol-Kumari, please assign this to me
