### ISSUE TITLE
[Backend] Reset Password

### ISSUE THREAD

**Issue by jackfrost13** [HITK-TECH-Community/Community-Website#479]
Create a route via which one can reset their password.
It should only intake an email id.
Check if the email exists and then send them an email with a link to reset their password. The link should be valid only for 60 mins. 

Add API Testing for it. Refer #81 for help

Feel free to ask questions if you have any doubts

This depends on #152

**Comment by Itsaadarsh** [comment]
Hey there @jackfrost13, I'd like to work on this feature. So if it's not already assigned to anyone I'd like you it assign it to me so that I could get started right away.

**Comment by Itsaadarsh** [comment]
Hey @jackfrost13, I've planned to use [nodemailer](https://nodemailer.com/about/) as a 3rd party service for sending authentication emails to clients who forgot their password so for sending those emails I need an email ID, could you provide me with an email ID hence I can integrate it with the application ( [your-email] ----> [client-email] ).

And can you give an email ID that does not use Gmail as its email service as nodemailer does not perform quite well with Gmail ID's.

![image](https://user-images.githubusercontent.com/54549066/110419169-cc9e4c80-80be-11eb-82ca-1942b4b63a56.png)

**Comment by Itsaadarsh** [comment]
Okay, I get it but I don't think that has anything to do with this issue, I've completed all the backend logic for sending an email with a reset password link and also made a reset password route to authenticate and link `/auth/forgetpassword/:token` the token will expire in 60 min. So all I want is an email account with its ID and Password once you provide me with that I'll add the variables to the `config` file and send a PR right away. 

Workflow:

1) `/auth/forgotpassword` (POST) : Body ({ email }) -> Verifying the email and sending a reset password link to the particular email with an expiration period of 60 min.

2) `auth/forgotpassword/:token` (POST) : Body ( {newPassword} ) -> Verifying the token and upating the new password over the database

**Comment by jackfrost13** [comment]
You can skip the email thing for now, you can raise the PR. Regarding the email configs and sending email we will have a seperate service, that can be incorporated later. For the meanwhile you can send the verification link as a response to `forgotPassword` endpoint.

In your workflow the endpoints should be located in `/admin/...` instead of `auth`

**Comment by Itsaadarsh** [comment]
Hey @jackfrost13, PR sent kindly review it and let me know if any changes needed.
