### ISSUE TITLE
[Frontend] Add About Us Section for Admin

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#482]
Deliverable-

- [ ] About Us page should have two cards similar to faqs 
    1. Manage Teams
    2. Add Team Member
 
- [ ] Manage Teams will take us to a new page having cards with dummy data as of now.
- [ ] Add Team Member card will take us to a page containing form with following fields along with a `submit` button -
    1. Full Name
    2. picture Upload
    3. Short Description
    4. linkedIn URL
    5. Github URL
    6. Twitter URL
    5. Teams(Open Source, Broadcast, Design, Social, Resource Sharing) =>This will be a multiple select box with the options given

Please make sure to render the page on the right side keeping the left side navigation panel same for these pages.

**Comment by Shubham-Kumar-2000** [comment]
Can assign me this under GSSoC'21 ?

**Comment by Kajol-Kumari** [comment]
> Can assign me this under GSSoC'21 ?
> @Kajol-Kumari

Sure! Please go ahead with this issue.
Happy Learning :)

**Comment by prerna2712** [comment]
Can I too work on this?

**Comment by sahildotexe** [comment]
Can I work with @Shubham-Kumar-2000 on this issue?

**Comment by Kajol-Kumari** [comment]
Hey! We can't assign this issue to more than one person. Please keep an eye on the issues list. We would be opening up more issues by tomorrow.

**Comment by Shubham-Kumar-2000** [comment]
@Kajol-Kumari  I am working on the 1st part of this issue it would be great if you assign the other parts to others

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari I am working on the 1st part of this issue it would be great if you assign the other parts to others

Hey @Shubham-Kumar-2000 I don't feel this issue is big enough to be broken down we just  need static frontend in this issue(just two cards and a form)
