### ISSUE TITLE
Enhancement in Code Structure

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#484]
Deliverable -
Currently, few of the components consists of `<a></a>` tag which leads to the complete reloading of the wesbsite in order to navigate.

- [ ] Replace these `<a></a>` tags with `<Link>` in order to avoid reloading the whole page. List of component to handle -
    1. Footer.jsx
    2. LoggedIn.jsx
    3. Home/JoinUs.jsx
    4. Home/Motive.jsx
    5. Privacypolicy.jsx
    6. Terms.jsx

**Comment by AbhipsaGuru1012** [comment]
@Kajol-Kumari  I would like to work on this issue. Please assign this to me.

**Comment by anshulsharma123** [comment]
@Kajol-Kumari  I would like to work on this issue please assign this issue to me under gssoc21

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari I would like to work on this issue. Please assign this to me.

Please go ahead @AbhipsaGuru1012 
Happy Learning :)

**Comment by Kajol-Kumari** [comment]
@AbhipsaGuru1012 can I please get a quick update on this as it's kinda blocking few issues

**Comment by AbhipsaGuru1012** [comment]
@Kajol-Kumari I am working on it. I will be making a PR by today.

**Comment by AbhipsaGuru1012** [comment]
@Kajol-Kumari I have made the PR. Please review.

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari I have made the PR. Please review.

Thanks for the PR. Will review it by soon.
