### ISSUE TITLE
Enhancements In Forms

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#488]
Deliverable - 

- [ ] The validation error message of reset-password[forgot-password] should be displayed similar to :point_down: 
![Screenshot from 2021-03-10 11-27-21](https://user-images.githubusercontent.com/44888949/110583666-08efac80-8194-11eb-8e57-7a61a461ddd4.png)

- [ ] Add reCAPTCHA in the contact form.

**Comment by AbhipsaGuru1012** [comment]
@Kajol-Kumari can I work on this issue?

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari can I work on this issue?

Sure @AbhipsaGuru1012 Please go ahead with this issue.
Happy Learning :)

**Comment by Kajol-Kumari** [comment]
Hey @AbhipsaGuru1012 can I please get an update on this?

**Comment by Kajol-Kumari** [comment]
> > Hey @AbhipsaGuru1012 can I please get an update on this?
> 
> @Kajol-Kumari I am working on it. I will try to submit a PR by tomorrow. Apologies for the delay.

Thanks for the update :) 
We are looking forward to it 😄

**Comment by AbhipsaGuru1012** [comment]
@Kajol-Kumari I have made the PR. Please review.

**Comment by Jassi10000** [comment]
@Kajol-Kumari Mam is the issue still open , or the PR has completed the task?
If it's open by chance please assign me
