### ISSUE TITLE
[Front End] Adding Dark Mode and few UI changes

### ISSUE THREAD

**Issue by Coder-Srinivas** [HITK-TECH-Community/Community-Website#490]
Features lacking/ Need Improvements :
1) Dark Mode
2) Social Media Icons overlap with the members profile picture in the about page
3) Broadcast Section is a bit clumsy 
4) Color Theme of the Join us Section is different from the website's theme and is not visually appealing

Solution :
1) Adding a button to toggle dark mode
2) Changing the positioning of the Social Media Icons
3) Changing the complete look of the broadcast section using animations and styling
4) Changing the Theme of the Website to make it visually more appealing
5) Using a preprocessor like SASS

Can I work on this issue as a part of GSSoC 2021 along with my friends @guruc-134 and @FireQueen-3010

SUB-ISSUE CLAIMS
------------------------------------------------------------

- [ ]  Adding a button to toggle dark mode - @Coder-Srinivas

->This will be considered as a single issue as this (Level 3)

- [x]  Changing the positioning of the Social Media Icons - @guruc-134

-> I would like to see it's final look, if it looks better than what we have now, then only I would be able to accept it(Level-2)

- [ ] Changing the complete look of the broadcast section using animations and styling - @FireQueen-3010

-> I would like to see it's final look, if it looks better than what we have now, then only I would be able to accept it(Level-3)

- [ ] Changing the Theme of the Website to make it visually more appealing - @FireQueen-3010

-> I would like to see it's final look, if it looks better than what we have now, then only I would be able to accept it(Level-3)

- [ ] Using a preprocessor like SASS - @Coder-Srinivas

-> I would like to see it's final performance, if found better than what we have now, then only I would be able to accept it. Btw I need a bit of more explanation on this.

----------------------------------------------------------------------------
**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Yes

**Comment by FireQueen-3010** [comment]
I would love to collaborate to work on this.

**Comment by guruc-134** [comment]
i would like to work on the issues mentioned above along with @Coder-Srinivas

**Comment by Kajol-Kumari** [comment]
Hey @Coder-Srinivas Thanks for coming up with these awesome suggestions. I would like to break this issue into sub-issues

1. Adding a button to toggle dark mode
->This will be considered as a single issue as this (**Level 3**)

2. Changing the positioning of the Social Media Icons
-> I would like to see it's final look, if it looks better than what we have now, then only I would be able to accept it(**Level-2**)

3. Changing the complete look of the broadcast section using animations and styling
-> I would like to see it's final look, if it looks better than what we have now, then only I would be able to accept it(**Level-3**)

4. Changing the Theme of the Website to make it visually more appealing
-> I would like to see it's final look, if it looks better than what we have now, then only I would be able to accept it(**Level-3**)

5. Using a preprocessor like SASS
-> I would like to see it's final performance, if found better than what we have now, then only I would be able to accept it. Btw I need a bit of more explanation on this.

YOU CAN CLAIM AT MOST TWO OF THESE 5 SUB-ISSUES
\cc: @Coder-Srinivas @FireQueen-3010 @guruc-134

**Comment by FireQueen-3010** [comment]
Hi, we have a doubt, do we get to take two issues each individually or together?

**Comment by Kajol-Kumari** [comment]
> Hi, we have a doubt, do we get to take two issues each individually or together?

It should be individually so that we can give you the required score

**Comment by FireQueen-3010** [comment]
Hi, I would like to claim the theme change of the website issue and changing the complete look of broadcast section issues respectively.

**Comment by FireQueen-3010** [comment]
thank you for assigning me.

**Comment by Coder-Srinivas** [comment]
@Kajol-Kumari SASS is just a CSS preprocessor which makes the developers life easy. We can use mixins, functions and variables which improves code reuseability.

**Comment by Coder-Srinivas** [comment]
@Kajol-Kumari  I would like to claim the dark mode feature and the SASS preprocessor would be used by all of us.

**Comment by guruc-134** [comment]
i would like to work the issue 2: Changing the positioning of the Social Media Icons  while using SASS preprocessor in the styling

**Comment by Kajol-Kumari** [comment]
@Coder-Srinivas @FireQueen-3010 @guruc-134 please go ahead with this issue. Looking forward to your proposed solutions
Happy Learning :)

**Comment by Kajol-Kumari** [comment]
Hey @Coder-Srinivas Let's not go with the `Using a preprocessor like SASS` right now as we already have `sass` and we don't need this as of now.

**Comment by Coder-Srinivas** [comment]
@Kajol-Kumari I have few doubts. Can u please clarify?

**Comment by Coder-Srinivas** [comment]
For the dark mode, where am I supposed to keep the toggle button? Like should I keep one in the home page? This way whenever a user wants to toggle dark mode, he is supposed to go to the home page. But if I keep it on the nav bar, how can other components know when the toggle bar is triggered.

And also when dark mode is triggered, should all the components be a bit darker or only the white ones. Because I feel that few darker components cannot be affected by dark mode. Can you please suggest a solution?

**Comment by jackfrost13** [comment]
@Kajol-Kumari Is this issue supposed to be open?

**Comment by FireQueen-3010** [comment]
Hi @Kajol-Kumari , don't you think the footer will look even better if it matched with the navbar?
![image](https://user-images.githubusercontent.com/59244300/113108516-b0578080-9222-11eb-916c-ae2e4861ff47.png)
Also the hover effects for the footer links have not been changed for the dark mode.
So, can I work making the footer better and according to theme of the dark mode?
