### ISSUE TITLE
[Backend] Route for adding broadcasts

### ISSUE THREAD

**Issue by jackfrost13** [HITK-TECH-Community/Community-Website#494]
Add a route for adding broadcasts. Authenticated API
Model for broadcasts need to be added.

Estimated Fields:
1. Title
2. Content (long html formatted text)
3. Link
4. Timestamps
5. isExpired
6. imageURL
7. category

API Testing is required.
For help on API Testing refer #81

**Comment by amanjha21** [comment]
Hi Aman Jha here, I want to work on this issue as part of gssoc'21. But I am not getting what you mean by broadcast. Please clarify and assign it to me so, I can start solving this issue. Thanks

**Comment by jackfrost13** [comment]
We publish broadcasts(posts) related to several important open source events, internships, etc. We required a db for it so that we can control it via apis
Head over to https://hitk-tech-community.netlify.app/broadcasts to view our current broadcasts(static right now)
Let me know if you have any queries

**Comment by jackfrost13** [comment]
@amanjha21 Can you please share an update?

**Comment by amanjha21** [comment]
@jackfrost13  I am currently working on this issue. I slowed down due to my exams but they are now over I will soon make a PR If everything goes fine else I will DM you.

**Comment by jackfrost13** [comment]
can you provide a timeframe? Also I believe you must be aware of your exams prior taking this up?
Please don't take up issues when you do not plan to complete it timely. It deprives others from taking the issue and blocks it

**Comment by amanjha21** [comment]
Sorry, I will keep in mind from next time.
I will resolve this issue latest by the 22nd.
