### ISSUE TITLE
[Backend] Update Broadcast

### ISSUE THREAD

**Issue by jackfrost13** [HITK-TECH-Community/Community-Website#495]
Update existing broadcast. Authenticated API
Requires API Testing.
Refer #81  For API Testing resources.

This depends on #494 (Can be taken up once dependant issues are completed)

**Comment by PriyankjeetPradhan** [comment]
can you assign this me ...... I would like work with API's

**Comment by PriyankjeetPradhan** [comment]
Can you assign this issue to me? (GSSOC'22 participant)

**Comment by saheelsapovadia** [comment]
If the issue still exists could you assign it to me ?, I'd like to work on it. 😃

**Comment by arinmodi** [comment]
@jackfrost13, would like to work

**Comment by arinmodi** [comment]
@Kajol-Kumari, I have some questions

which fields are allowed to update ?
should I append the imageUrl array into existing imageUrls or just replace it ?
should I append the tags array into existing tags or just replace it ?

**Comment by arinmodi** [comment]
> @Kajol-Kumari, I have some questions
> 
> which fields are allowed to update ? should I append the imageUrl array into existing imageUrls or just replace it ? should I append the tags array into existing tags or just replace it ?

@Kajol-Kumari, please give update ?

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari, I have some questions
> 
> which fields are allowed to update ? should I append the imageUrl array into existing imageUrls or just replace it ? should I append the tags array into existing tags or just replace it ?

@arinmodi we should replace the existing one with the new one

**Comment by arinmodi** [comment]
@Kajol-Kumari, I have made the PR #807
