### ISSUE TITLE
[Backend] Delete a brodcast

### ISSUE THREAD

**Issue by jackfrost13** [HITK-TECH-Community/Community-Website#496]
Delete existing broadcast. Authenticated API
Requires API Testing.
Refer #81 For API Testing resources.

This depends on #494 (Can be taken up once dependant issues are completed)

**Comment by amanjha21** [comment]
Hi Aman Jha here, I want to work on this issue as part of gssoc'21. Please assign it to me. Thanks

**Comment by jackfrost13** [comment]
@amanjha21 please update progress

**Comment by amanjha21** [comment]
It's almost done. I will be making PR latest by tomorrow.
