### ISSUE TITLE
[Backend] Add Contact Us Form route

### ISSUE THREAD

**Issue by jackfrost13** [HITK-TECH-Community/Community-Website#499]
Create a route for storing contact us form data.
Post storage send an email to the existing admins about it. (Using our email service)

Public API
Requires API Testing.
Refer #81 For API Testing resources.

**Comment by Simran2337** [comment]
I want to work on this as GSSOC participant

**Comment by Simran2337** [comment]
I want to work on this as GSSOC participant @Kajol-Kumari 
Sorry for miscommunication

**Comment by Simran2337** [comment]
@jackfrost13  can I work on the issue?

**Comment by jackfrost13** [comment]
ai already assigned you on this!
Happy coding ;)

**Comment by Simran2337** [comment]
Thankyou :)

**Comment by Simran2337** [comment]
This task can be taken up by someone sir.
I am leaving for out of station urgently!
I apologize for the problem.

**Comment by Pranjal-2001** [comment]
Can you assign it to me?

**Comment by jackfrost13** [comment]
@Pranjal-2001 Please update the progress on this

**Comment by rohithmsr** [comment]
Can I take up this issue? @jackfrost13

**Comment by rohithmsr** [comment]
@jackfrost13 Should I have to create a schema for Contact-Us form and add form through post request and send as email to admin??

Could you break down the issue into smaller steps, so that I can understand

**Comment by jackfrost13** [comment]
Yes your understanding is correct

**Comment by rohithmsr** [comment]
@jackfrost13 it says authentication error when I get request for admins, what to do? What is that jwt token is for? How to use that during request?

**Comment by jackfrost13** [comment]
you need to login first using /auth/login route
from there you will get a jwt token which you need to use for all authenticated requests

**Comment by rohithmsr** [comment]
How to use that? I use Postman, i tried uisng it in params, headers etc. I can't figure out where and how to use jwt? @jackfrost13 . I am new to web dev, so plz bear with my silly questions

**Comment by jackfrost13** [comment]
No issues, we all are beginners at some point.
In postman use the Auth tab and select bearer token option to provide the token

**Comment by rohithmsr** [comment]
As soon as I add the contact us form, I should send email right? What should be the format of the email?? @jackfrost13

**Comment by jackfrost13** [comment]
Yes it should be an async operation. We do not want latency to be affected by this. You can create an email template for the same

**Comment by rohithmsr** [comment]
I am getting error when I give post request using /emailTest, I gave email,data,type as 'INVITE-ADMIN' in the request body, still getting error. What should I do?

**Comment by rohithmsr** [comment]
So, I get all the emails of the admins to send the response from the user, and what if one of the admin email id is invalid,

How to handle such cases, since even if one fails it may cause failure of all other emails right?

@jackfrost13

**Comment by jackfrost13** [comment]
Hey, that will be highly unlikely since admins need to first verify the emails. But point taken, we will look into this.
Thanks for bringing this up

**Comment by rohithmsr** [comment]
@jackfrost13 Could you update the level of this issue?

**Comment by rohithmsr** [comment]
I have made my PR

**Comment by jackfrost13** [comment]
Hi, yes I saw your PR. in-depth review will take some time, running bit busy
