### ISSUE TITLE
[Backend] Add basic backend code

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#5]
- Add basic backend server having main route file, index file and separate folder for controllers and middlewares.

**Comment by NewCoderBoi** [comment]
Please assign this to me.

**Comment by Kajol-Kumari** [comment]
@NewCoderBoi looking forward for your PR 
Happy Coding :)

**Comment by NewCoderBoi** [comment]
Created a PR. Please check and recommend changes to be made, if any.

**Comment by Kajol-Kumari** [comment]
Closing via [this](https://github.com/HITK-TECH-Community/Community-Website/pull/14) PR
