### ISSUE TITLE
[Backend] Add FAQ(POST) 

### ISSUE THREAD

**Issue by jackfrost13** [HITK-TECH-Community/Community-Website#501]
Admins can add a FAQ.
Create FAQ Model for DB.
Authenticated API
Requires API Testing. Refer #81 .

Please confirm the model structure before implementation

**Comment by promaroy** [comment]
Can I work on this?

**Comment by promaroy** [comment]
Will a question and answer field suffice for the FAQ model?

**Comment by jackfrost13** [comment]
Yes, just keep another one as isActive field incase we want to temporarily disable a FAQ

**Comment by jackfrost13** [comment]
@promaroy What is the update on this?

**Comment by Kriti-bit** [comment]
Hi, I am a GSSoC'21 Participant. I would like to work on this issue

**Comment by dhwaj1902** [comment]
Is there any update regarding this issue? or else I can try this one out.

**Comment by Kriti-bit** [comment]
Hi @dhwaj1902, I am working on this issue. I'll create a PR by this week end.

**Comment by dhwaj1902** [comment]
Ok.

**Comment by jackfrost13** [comment]
@Kriti-bit Please raise PR by today else will have to reassign it to @dhwaj1902
