### ISSUE TITLE
[Frontend] Template for Forgot Password recovery

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#502]
Deliverable:

- [ ] We need a page containing a form with following fields
1. New Password
2. Confirm New Password

Add a validation check for the passwords i.e both the passwords should match, else show the proper error message via toast.
This page should appear on the route `/forgotPassword/{id}`

**Comment by ankitaugale23** [comment]
I would like to take this up. Shall I?

**Comment by Kajol-Kumari** [comment]
> I would like to take this up. Shall I?

Sure @ankitaugale23 
Please go ahead!
Happy Learning :)

**Comment by ankitaugale23** [comment]
Sure thanks. I am working on this and will update you in 2 days with the changes.

**Comment by ankitaugale23** [comment]
I will make a PR  tomorrow till 9 pm.

**Comment by Kajol-Kumari** [comment]
> I will make a PR tomorrow till 9 pm.

Thanks for the update :)

**Comment by ankitaugale23** [comment]
@Kajol-Kumari my work is almost done. (attaching an image link of a screenshot of a page to show how it looks.

[https://drive.google.com/file/d/1n6M0tBlgsfExZT_i0JXgdri7BZbBJB3A/view?usp=sharing](url)
But I am just confused at this point (as you said that page should show up at this route /forgotPassword/{id} ) So will just be adding the route in App.js will do or do I have to fetch the data and then do something else? 
It will be really helpful if you could guide me on this so I can make a PR.

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari my work is almost done. (attaching an image link of a screenshot of a page to show how it looks.
> 
> [https://drive.google.com/file/d/1n6M0tBlgsfExZT_i0JXgdri7BZbBJB3A/view?usp=sharing](url)
> But I am just confused at this point (as you said that page should show up at this route /forgotPassword/{id} ) So will just be adding the route in App.js will do or do I have to fetch the data and then do something else?
> It will be really helpful if you could guide me on this so I can make a PR.

Hey @ankitaugale23 as we don't have backend ready for it. Just add the route as of now. Later on, qe would add the id validator so that the page gets rendered only for valid ids.

**Comment by ankitaugale23** [comment]
ok. Thank you so much. Making a PR now.
