### ISSUE TITLE
[Frontend] The JWT Token isn't getting removed after Expiry

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#503]
Deliverable -
Currently, the jwt token remains in the local storage forever. Which is allowing the admins to access the dashboard even after the token gets expired

- [ ] we need to clear it as soon as it expires.(Expiry time can be found out from the token itself.)

**Comment by Simran2337** [comment]
I want to work on this as GSSOC participant

**Comment by Siddharth1006** [comment]
I would like to work on this issue as a GSSOC'21 participant.

**Comment by sk1122** [comment]
I can try fixing this issue @Kajol-Kumari

**Comment by Kajol-Kumari** [comment]
> I can try fixing this issue @Kajol-Kumari

Sure @sk1122 please go ahead :)

**Comment by garvitgupta13** [comment]
Hey @Kajol-Kumari please describe this issue.
Currently as I logout from admin panel the token gets removed

**Comment by Kajol-Kumari** [comment]
> Hey @Kajol-Kumari please describe this issue.
> Currently as I logout from admin panel the token gets removed

So the token should ideally expire after 12hrs so if you login to the admin dashboard and don't log out. And next day, you try to login, you are directly directed to dashboard saying that `you are already logged in ` which shouldn't happen

**Comment by garvitgupta13** [comment]
I can remove it from the local storage but where should I place that function.

**Comment by sk1122** [comment]
@garvitgupta13 if you want to work on this you could, go ahead.

**Comment by garvitgupta13** [comment]
I can create a function to remove the token as soon as it expires.
But I am unable to figure out where to call that function ?
Hey @Kajol-Kumari can you guide me how to handle that function

**Comment by Kajol-Kumari** [comment]
Hey @garvitgupta13 IMO the efficient approach would be to allow the admin to vidit dashboard, but as soon as it hits any api and get `unauthorized error` in response, then log out the user

**Comment by garvitgupta13** [comment]
Hey @Kajol-Kumari please assign me this issue under gssoc21.

**Comment by garvitgupta13** [comment]
Hey @Kajol-Kumari, can you assign me this issue under gssoc21? 
I would like to give it a try.

**Comment by Kajol-Kumari** [comment]
> Hey @Kajol-Kumari, can you assign me this issue under gssoc21?
> I would like to give it a try.

sure!
