### ISSUE TITLE
[Frontend] Add Validation Check in Resource Form

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#504]
Deliverable:

- [ ] In Resource Sharing Form, please add the following validations
    1. Email Validation check 
    2. Url validation check for the field (Resource URL)
    3. Required Validation check for the following fields
        - Name
        - Email
        - Resource URL
        - Level of Trust
        - Valid Date
        
The error should be shown in proper way, you can take the reference of footer's signup form for reference

**Comment by garvitgupta13** [comment]
Hey @Kajol-Kumari , I am a gssoc21 participant, please assign me this issue. I have already implemented this in one of my personal projects using joi-validator

**Comment by Kajol-Kumari** [comment]
> Hey @Kajol-Kumari , I am a gssoc21 participant, please assign me this issue. I have already implemented this in one of my personal projects using joi-validator

Please go ahead @garvitgupta13 
Happy Learning :)

**Comment by garvitgupta13** [comment]
I have added validation to the resource form.

- Implemented email validation (Gives error on giving wrong mail)
- Implemented URL validation (Gives error on giving wrong URL)
- Implemented date validation (Gives error on giving date of incorrect date)
- Required validation implemented on:
            (I)   Name
            (ii)  Email
            (iii) Resource URL 
           (iv)  Level of trust
            (v)  Date

[Link to Demo Video](https://drive.google.com/file/d/1HMtZD13CDnXMWR4zQRQQE1cVSeJjhww9/view?usp=sharing)

Please let me know if there are any other changes or can I create a pull request.
I have used joi-browser for its implementation
