### ISSUE TITLE
[Frontend] Enhancement in Contact Us Form

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#505]
Deliverable -

- [ ] Add the following Validations in Contact US Form
    1. Email validation
    2. Required validation for all the fields

Please make sure to show the error message properly (You can take reference of footer's signup to newsletter form validation for reference)   

- [ ] After clicking on `submit` button we should see a card, saying `We have heard you!! We will soon get back to you if required!` (Yo can take the reference of forgot password's card for this)

**Comment by anshulsharma123** [comment]
@Kajol-Kumari I want to work on this issue

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari I want to work on this issue

Sure, please go ahead with this issue @anshulsharma123 
Happy Learning :)

**Comment by anshulsharma123** [comment]
@Kajol-Kumari  mam I worked on this issue but I am not able to solve this So I think I should not waster your time please assign this issue to some other peoples

**Comment by ShubhamSj07** [comment]
@Kajol-Kumari , I would like to take this issue.

**Comment by Kajol-Kumari** [comment]
Hey @anshulsharma123 that for letting us Know this. @ShubhamSj07 Please go ahead with this issue
Happy Learning :)

**Comment by ShubhamSj07** [comment]
@Kajol-Kumari , i had added validations on contact form & after submitting we can see card.
Also, i had figured in footer section, hover effect on git-icon was black color due to which icon was getting hidden
So, i had  added  color #7af7cd , now it lgtm.
Also, in footer section, i had updated email validations for news letter
I had attached preview of this issue solved!

https://user-images.githubusercontent.com/56510414/111061487-a2d39400-84c9-11eb-8af1-883b8b189fb6.mp4

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari , i had added validations on contact form & after submitting we can see card.
> Also, i had figured in footer section, hover effect on git-icon was black color due to which icon was getting hidden
> So, i had added color #7af7cd , now it lgtm.
> Also, in footer section, i had updated email validations for news letter
> I had attached preview of this issue solved!
> 
>  HITK-Validation_Issue.mp4

@ShubhamSj07 please open up the PR so that I can see you code and give reviews on it.

**Comment by Jassi10000** [comment]
Is this issue open ? , if so pls assign it to me  @Kajol-Kumari

**Comment by ShubhamSj07** [comment]
@Jassi10000 , I am working on this issue!

**Comment by Jassi10000** [comment]
@ShubhamSj07 Ohh buddy , I saw your PR , but the issue was also opened that's why I asked , 
anyways , gud luck
