### ISSUE TITLE
[Frontend] Validation Check for Join Us Form

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#506]
Deliverable -

- [ ]  In Resource Sharing Form, please add the following validations
    1. Email Validation check
    2. Required Validation check for the following fields
         - Name
         - Email
         - Interested Domain
         - Year of Study
         - College Name
The error should be shown in proper way, you can take the reference of footer's signup form for reference

**Comment by AnshMishra2001** [comment]
Can i work on this issue?

**Comment by garvitgupta13** [comment]
Hey @Kajol-Kumari , I am a gssoc21 participant, please assign me this issue. I have already implemented this in one of my personal projects using joi-validator

**Comment by Kajol-Kumari** [comment]
> Can i work on this issue?

sure @AnshMishra2001 
Please go ahead :)

**Comment by Jassi10000** [comment]
@Kajol-Kumari Mam can you pls assign it to me , as being a GSSOC'21 participant I also want to try my hands on this issue

**Comment by Kajol-Kumari** [comment]
> Can i work on this issue?

Hey @AnshMishra2001 can you please provide an update on this issue?

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari Mam can you pls assign it to me , as being a GSSOC'21 participant I also want to try my hands on this issue

Hey! If the current assignee didn't respond in 24hrs then will surely assign it to you :)

**Comment by AnshMishra2001** [comment]
I am working on this issue

**Comment by Jassi10000** [comment]
> > @Kajol-Kumari Mam can you pls assign it to me , as being a GSSOC'21 participant I also want to try my hands on this issue
> 
> Hey! If the current assignee didn't respond in 24hrs then will surely assign it to you :)

Sure mam, no issues

**Comment by Jassi10000** [comment]
@Kajol-Kumari Mam I have worked on this issue on the forked version and completed 80% of the work , can you plss assign it to me now ,  so that I can complete the 20 %  to complete the task fully

**Comment by Kajol-Kumari** [comment]
Hey @Jassi10000 as @AnshMishra2001 is already working on it, we can't assign it to you

**Comment by Jassi10000** [comment]
Mam is @AnshMishra2001 still working ?

**Comment by Kajol-Kumari** [comment]
@AnshMishra2001 can you please update us wrt this issue?

**Comment by jackfrost13** [comment]
@Jassi10000 Do you want to work on this right now? We can assign this to you since @AnshMishra2001 didn't respond

**Comment by Jassi10000** [comment]
Yeah sure

**Comment by Jassi10000** [comment]
@jackfrost13 Sir I am facing some more issues while submiitting the form , so the form needs some more validations  other than mentioned in the issue 
Can you please make it LEVEL 3  issue  as  that thing is lil hard  .

**Comment by jackfrost13** [comment]
Can you elaborate on the issues you are facing and the extra validation required?

All the issues have been thoroughly thought and then assigned levels. Moreover our aim isn't to encourage participations for points but for learning and experience.

**Comment by Jassi10000** [comment]
Other than mentioned , I will also add validation for contact and Linkedln url

**Comment by jackfrost13** [comment]
I don't think so that should be much of an effort. @Kajol-Kumari What do you think? I think we are using joi in the frontend also right?

**Comment by Kajol-Kumari** [comment]
Hwy @jackfrost13 yeah we are using joi only in frontend as well. Also @Jassi10000 we have merged most of the similar PR under level -2 so I won't be right to make a different label for just this one. 

If you see issue closely, you need to implement just two types of validation- 
1. Required
2. Email 
So this issues isn't hard. Please let us know if you need any help with this issue or any further clearance on its label

**Comment by Jassi10000** [comment]
No issues mam , I will submit my PR with the best changes from my side with all validations mentioned in issue

**Comment by Jassi10000** [comment]
@Kajol-Kumari  @jackfrost13  Am facing this issue while commiting my changes
![hitkDoubt](https://user-images.githubusercontent.com/64856348/112760306-0bffef00-9014-11eb-85e6-2d37892e0988.PNG)


and the program has stopped here only from last 25 min , pls help

**Comment by jackfrost13** [comment]
did you try the given commands?

**Comment by garvitgupta13** [comment]
> @Kajol-Kumari @jackfrost13 Am facing this issue while commiting my changes
> ![hitkDoubt](https://user-images.githubusercontent.com/64856348/112760306-0bffef00-9014-11eb-85e6-2d37892e0988.PNG)
> 
> and the program has stopped here only from last 25 min , pls help

commit changes in` Community-Websites`, currently you are writing them in `frontend` folder

**Comment by Jassi10000** [comment]
> did you try the given commands?

Which one?
@jackfrost13

**Comment by Jassi10000** [comment]
> > @Kajol-Kumari @jackfrost13 Am facing this issue while commiting my changes
> > ![hitkDoubt](https://user-images.githubusercontent.com/64856348/112760306-0bffef00-9014-11eb-85e6-2d37892e0988.PNG)
> > and the program has stopped here only from last 25 min , pls help
> 
> commit changes in` Community-Websites`, currently you are writing them in `frontend` folder

Will that do the thing?
As I have made changes in the frontend folder , so that's why asking

**Comment by Kajol-Kumari** [comment]
> > @Kajol-Kumari @jackfrost13 Am facing this issue while commiting my changes
> > ![hitkDoubt](https://user-images.githubusercontent.com/64856348/112760306-0bffef00-9014-11eb-85e6-2d37892e0988.PNG)
> > and the program has stopped here only from last 25 min , pls help
> 
> commit changes in` Community-Websites`, currently you are writing them in `frontend` folder

Hey! So currently you are under `frontend` folder and you should be in the main folder i.e `Community-Website` and then add amd commit the changes. This is what your error is saying.  So try doing this once and see if this works

**Comment by garvitgupta13** [comment]
> > > @Kajol-Kumari @jackfrost13 Am facing this issue while commiting my changes
> > > ![hitkDoubt](https://user-images.githubusercontent.com/64856348/112760306-0bffef00-9014-11eb-85e6-2d37892e0988.PNG)
> > > and the program has stopped here only from last 25 min , pls help
> > 
> > 
> > commit changes in` Community-Websites`, currently you are writing them in `frontend` folder
> 
> Will that do the thing?
> As I have made changes in the frontend folder , so that's why asking

Yes

**Comment by Jassi10000** [comment]
sure @garvitgupta13 and @Kajol-Kumari  , leme try this

**Comment by Jassi10000** [comment]
![hitkDoubt2](https://user-images.githubusercontent.com/64856348/112767809-64e07f00-9036-11eb-8376-9fff0206e610.PNG)

@garvitgupta13 @Kajol-Kumari  Am getting the same thing

**Comment by Kajol-Kumari** [comment]
> ![hitkDoubt2](https://user-images.githubusercontent.com/64856348/112767809-64e07f00-9036-11eb-8376-9fff0206e610.PNG)
> 
> @garvitgupta13 @Kajol-Kumari Am getting the same thing

Let's have a meet to fix it then. Please ping me once on our slack channel(you can find the link in readme)

**Comment by Jassi10000** [comment]
Sure mam @Kajol-Kumari

**Comment by Jassi10000** [comment]
@Kajol-Kumari I am nearly done with the joi validation part , but am facing an error at last , can you assign me a mentor to help me solve that

**Comment by garvitgupta13** [comment]
@Kajol-Kumari if this issue is still open can you assign this issue to me

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari if this issue is still open can you assign this issue to me

Hey @garvitgupta13 you can go ahead with this issue.

**Comment by garvitgupta13** [comment]
Hey, @Kajol-Kumari a suggestion from my side, can we replace the interested domains to a multilist input just like in add team form.
![image](https://user-images.githubusercontent.com/70805691/115907896-18e2f780-a487-11eb-801f-d53c28cc9499.png)
  to
![image](https://user-images.githubusercontent.com/70805691/115908041-4465e200-a487-11eb-8dd6-1b7501d50fc1.png)

Creating this change will make it easy to handle the formdata and its errors.

**Comment by garvitgupta13** [comment]
> Hey, @Kajol-Kumari a suggestion from my side, can we replace the interested domains to a multilist input just like in add team form.
> ![image](https://user-images.githubusercontent.com/70805691/115907896-18e2f780-a487-11eb-801f-d53c28cc9499.png)
> to
> ![image](https://user-images.githubusercontent.com/70805691/115908041-4465e200-a487-11eb-8dd6-1b7501d50fc1.png)
> 
> Creating this change will make it easy to handle the formdata and its errors.

Hey @Kajol-Kumari , all validations are done only domains part is left, please let me know should I replace the domains part with multilist input or not

**Comment by Kajol-Kumari** [comment]
Hey @garvitgupta13 please go ahead with replacing the current one with the select box same as we have in add-teams section.

**Comment by garvitgupta13** [comment]
Hey @Kajol-Kumari all validations are done for ipnut fields, but I am facing difficulty in adding dark theme to the multilist input form. Can you help me with that
