### ISSUE TITLE
[Frontend] Validation for Invite Admin Form

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#510]
Deliverable -
We need validation for the `Invite Admin` form

- [ ] Required validation
- [ ] Email Validation

For those who are unfamiliar our website, Inorder to see this form, do -
1. Click on `admin` button from navbar
2. Login using the below credentials -
```
{
    "email" : "hitktechcommunity@gmail.com",
    "password" : "hitkc0mmunityW3bsit3"
}
```
3. Go to `Settings` tab from admin dashboard
4. Click on `Invite admin` card

**Comment by Kajol-Kumari** [comment]
@bishakhne0gi please go ahead with this issue

**Comment by bishakhne0gi** [comment]
Yes, thank you ma'am
