### ISSUE TITLE
The cards in the "About Us Section"

### ISSUE THREAD

**Issue by Suvojit-roy** [HITK-TECH-Community/Community-Website#515]
The cards in the about us section has the icons overlapped on the images. It will be better if the social media icons can be a little lower

![Screenshot (3)](https://user-images.githubusercontent.com/56533500/111032281-648a9600-8431-11eb-9e99-faf3b0f33f21.png)

Yes,I have read the code of conduct.
I would like to work on this issue.

**Comment by Kajol-Kumari** [comment]
Hey @Suvojit-roy Thank you for taking time to report this issue. This issue has already been worked on via https://github.com/HITK-TECH-Community/Community-Website/issues/490 So, I am closing this one, Please feel free to claim any  unassigned issue to work on
Happy Learning :)
