### ISSUE TITLE
Adding GSSOC badge to Readme file

### ISSUE THREAD

**Issue by vedikaag99** [HITK-TECH-Community/Community-Website#516]
**Describe the bug**
1. Designing the program badge for gssoc and adding it under the `Programs we have been associated with` in README.md file
2. Centre aligning the dash below `All Broadcasts` text in all-broadcasts page for small screens.
I would like to work on this issue under gssoc'21.

**Screenshots**
Currently the dash is weirdly to the left for the smaller screens
![Screen Shot 2021-03-13 at 11 36 40 PM](https://user-images.githubusercontent.com/67699840/111039820-1b990880-8456-11eb-905a-d987aba3c12e.png)

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Yes

**Comment by Kajol-Kumari** [comment]
Hey @vedikaag99 Thank you for pointing these issues. Please go ahead with these issues and open up separate PRs for each one of them :)
