### ISSUE TITLE
[Frontend] Make the FAQ and About Us card Consistent

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#524]
Deliverable:
Currently, the `faq` cards and `team member` cards isn't consistent with the broadcasts cards of admin panel. Make it consistent(same card size, font-size, font-style etc)

Below is the Broadcasts card UI. WE want the faq and team member cards look similar to this
![Screenshot from 2021-03-16 10-35-09](https://user-images.githubusercontent.com/44888949/111258763-9ecb8180-8643-11eb-87f8-2f5a3ff21333.png)

Here is the card for `Team Member` section. As you can see we don't have the consistency in font-size of the content, card size is also not consistent etc. We want it's look similar to broadcast page as shown above
![Screenshot from 2021-03-16 10-35-08](https://user-images.githubusercontent.com/44888949/111258827-c0c50400-8643-11eb-8962-c0faad6ca076.png)

Here is the card for `FAQ` section. As you can see, tho we have the consistent card size but the card content isn't left aligned. We want it's look similar to broadcast page as shown above
![Screenshot from 2021-03-16 10-35-05](https://user-images.githubusercontent.com/44888949/111258921-f1a53900-8643-11eb-8bbf-7c49f3bedce5.png)

Also, replace the Add `+` icon in the first card of all these three pages with something better like [this](https://fontawesome.com/v4.7.0/icon/plus-square-o) or [this](https://fontawesome.com/v4.7.0/icon/file)

**Comment by garvitgupta13** [comment]
Hey, @Kajol-Kumari can you please describe this issue. Currently, faq card and team member card seems to be fine, in which way you want to modify them

**Comment by Kajol-Kumari** [comment]
> Hey, @Kajol-Kumari can you please describe this issue. Currently, faq card and team member card seems to be fine, in which way you want to modify them

Hey @garvitgupta13 please look at the updated issue description. I have explained everything in detail

**Comment by Devenkapoor7303** [comment]
Can I Work on this issue @Kajol-Kumari

**Comment by Devenkapoor7303** [comment]
@Kajol-Kumari  can u please tell me how can i access the admin panel as currently in FAQ There are no cards 


![Capture](https://user-images.githubusercontent.com/73438023/111472831-392cd300-86df-11eb-91f5-6a481410e39e.JPG)

**Comment by garvitgupta13** [comment]
Here are the [admin credentials](https://github.com/HITK-TECH-Community/Community-Website/blob/main/frontend/src/test_data/superadmin_credential.json)
I can solve this issue.

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari can u please tell me how can i access the admin panel as currently in FAQ There are no cards
> 
> ![Capture](https://user-images.githubusercontent.com/73438023/111472831-392cd300-86df-11eb-91f5-6a481410e39e.JPG)

Hey! Click on the admin button from navbar -> Login using the credentials given [here](https://github.com/HITK-TECH-Community/Community-Website/blob/main/frontend/src/test_data/superadmin_credential.json)

**Comment by Devenkapoor7303** [comment]
Okay Got the credentials
