### ISSUE TITLE
[Frontend] Implement Broadcast page Design

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#53]
Deliverables :

- [ ] Implement [this](https://www.figma.com/file/Hdxtv50E5vuzDoGGZMnfhC/BroadcastPage) broadcast design using material UI library 
- [ ] use [this](https://colors.lol/blocky) color pallete

**Comment by kenkirito** [comment]
working on it

**Comment by LNR14** [comment]
Can you assign this issue for me?

**Comment by Kajol-Kumari** [comment]
Hey @kenkirito can you please let us know if you have started working on this issue?

**Comment by kenkirito** [comment]
yes

**Comment by codewithvk** [comment]
@Kajol-Kumari Can you give me link. Which slider you want to use?

**Comment by patel-atul** [comment]
Hey @Kajol-Kumari  Can I work on it.

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari Can you give me link. Which slider you want to use?

Hey @codewithvk if you are taking about the slider for this page, use can use the same we have used in our home page and if you can find better library do implement it

**Comment by Kajol-Kumari** [comment]
> Hey @Kajol-Kumari Can I work on it.

Sure @patel-atul go ahead!

**Comment by patel-atul** [comment]
@Kajol-Kumari  Unassign me from this task I am not familiar with react I thought it was HTML CSS JS task.
apologies to all

**Comment by kenkirito** [comment]
i am working n this task. i am busy due to my exams but I will try to complete it on wensday

**Comment by harikishantk** [comment]
@Kajol-Kumari can you assign me up?

**Comment by Abhishek971999** [comment]
> @Kajol-Kumari Can you give me link. Which slider you want to use?

Hey @codewithvk, it is react-owl-carousel. It is already added to the dependencies so you need not install it again. You can see the implementation on the home page for reference. You can find more info at [react-owl-carousel](https://www.npmjs.com/package/react-owl-carousel)

**Comment by kenkirito** [comment]
![HITK Tech Community and 25 more pages - Personal - Microsoft​ Edge 30-12-2020 05_37_12 PM](https://user-images.githubusercontent.com/68530218/103368692-38c46900-4aee-11eb-8dba-2cdfe3d161d4.png)

**Comment by kenkirito** [comment]
i am figring out popup

**Comment by amanprateek123** [comment]
@Kajol-Kumari  if this issue  is not assigned then please assign this to me.

**Comment by kenkirito** [comment]
![HITK Tech Community and 44 more pages - Personal - Microsoft​ Edge 05-01-2021 08_33_33 PM](https://user-images.githubusercontent.com/68530218/103664139-f1c7ef00-4f97-11eb-9daf-003f4d93fba3.png)

**Comment by kenkirito** [comment]
![HITK Tech Community and 45 more pages - Personal - Microsoft​ Edge 05-01-2021 08_53_41 PM (1)](https://user-images.githubusercontent.com/68530218/103664325-29cf3200-4f98-11eb-94c9-41b822e69f24.png)

**Comment by kenkirito** [comment]
hi you have told me in the morning to work on the remaining issues so I start working on it.

**Comment by kenkirito** [comment]
![HITK Tech Community and 8 more pages - Personal - Microsoft​ Edge 06-01-2021 01_31_53 AM](https://user-images.githubusercontent.com/68530218/103693771-d1138f80-4fbf-11eb-9df4-66b44b8433c5.png)

**Comment by kenkirito** [comment]
https://user-images.githubusercontent.com/68530218/103693819-e5f02300-4fbf-11eb-84b6-e4b03002f36c.mp4

**Comment by kenkirito** [comment]
![HITK Tech Community and 9 more pages - Personal - Microsoft​ Edge 06-01-2021 01_39_41 AM (1)](https://user-images.githubusercontent.com/68530218/103693922-16d05800-4fc0-11eb-9921-fa457f2bf303.png)

**Comment by kenkirito** [comment]
![HITK Tech Community and 44 more pages - Personal - Microsoft​ Edge 05-01-2021 08_47_35 PM](https://user-images.githubusercontent.com/68530218/103694081-5303b880-4fc0-11eb-8c15-5f434bc897b9.png)

**Comment by kenkirito** [comment]
it is good

**Comment by Kajol-Kumari** [comment]
Hey @kenkirito functionality seems to work fine. Can you please try to put the broadcasts in the form of heading+content in the carousel card, it will be good to go then :)

**Comment by kenkirito** [comment]
like u want to add heading in card

**Comment by kenkirito** [comment]
or you want some content under broadcast page

**Comment by Kajol-Kumari** [comment]
@kenkirito the card content is currently like just a paragraph text, I meant to change it to `heading` and below that paragraph text

**Comment by kenkirito** [comment]
![HITK Tech Community and 6 more pages - Personal - Microsoft​ Edge 06-01-2021 01_06_10 PM (1)](https://user-images.githubusercontent.com/68530218/103741970-0ea80500-5020-11eb-90ba-737dfb048832.png)

**Comment by kenkirito** [comment]
@salil-naik has also asked for some changes

**Comment by kenkirito** [comment]
https://github.com/HITK-TECH-Community/Community-Website/pull/197
