### ISSUE TITLE
No need to use body-parser when using express version 4.16+

### ISSUE THREAD

**Issue by abhay27chauhan** [HITK-TECH-Community/Community-Website#535]
**Describe your Proposal**
Express version 4.16+, their own body-parser implementation is now included in the default Express package so there is no need for you to download another dependency.

You have added a line to your code that looks like the following:

- app.use(bodyparser.json()); 

If you are using Express 4.16+ you can now replace that line with:

- **app.use(express.json());** 

you also have the following code in your environment:

- app.use(bodyParser.urlencoded({extended: true}));

You can replace that with:

- **app.use(express.urlencoded());**

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Yes

**Comment by Kajol-Kumari** [comment]
Hey @abhay27chauhan Thanks for bringing it to out attention. We look forward to your PR for the same :)

**Comment by abhay27chauhan** [comment]
@Kajol-Kumari kindly pls review
