### ISSUE TITLE
[Frontend] Add proper Validation for Login Form

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#537]
Deliverable -

- [ ] Use `joi-validator` for validating the login fields i.e all the fields are required and there should be a validation check for email in `username`
- [ ] Proper error message should be shown (take the reference from signup form of the footer)

**Comment by akshitakanojia** [comment]
Hi @Kajol-Kumari , I would like to work on this issue.

**Comment by Jassi10000** [comment]
@Kajol-Kumari Mam can you please assign this to me too 
 , I have code ready for this , I did that even for JOIN US form

**Comment by Kajol-Kumari** [comment]
Hey @Jassi10000 again, if the issue is already assigned, we can't assign it to you! Please look for an issue that hasn't been assigned to anyone
