### ISSUE TITLE
[Frontend] Add Validation in the Add FAQ Form

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#538]
Deliverable -

- [ ] Add required validations for the the admin's add FAQ Form (Login to admin dashboard -> got to FAQs -> click on Add FAQ Card)
- [ ] Show proper error message (consistent with other form example -> signup form of footer)
- [ ] The minimum length of the content in both `question` and `answer` fields should be 8 (Add the required validation for the same)

P.S - As we are using `joi-validator` everywhere, I recommend you to go with the same, in order to be consistent.

**Comment by mrunalvilas** [comment]
hey I am a GSSoC'21 participant can i work on this issue

**Comment by Kajol-Kumari** [comment]
> hey I am a GSSoC'21 participant can i work on this issue

Sure @mrunalvilas please go ahead
Happy Learning :)

**Comment by mrunalvilas** [comment]
@Kajol-Kumari  thank you for assigning it to me!
it will be great if you could specify the deadline for PR.

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari thank you for assigning it to me!
> it will be great if you could specify the deadline for PR.

Hey we generally give 3days for coming up with a PR but if requested, we would be happy to extend it further as per your requirements :)
