### ISSUE TITLE
[Discussion/Code] Better UI for Admin Profile

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#539]
Deliverable -
 Current UI of the `View Admin Profile` isn't good. This issue is basically focused to decide the UI and later will be assigned with the person who come with it for coding it.

GIF Showing current Admin Profile UI
![admin_profile](https://user-images.githubusercontent.com/44888949/111479195-c2332100-8756-11eb-8b22-932b6534549c.gif)

**Comment by kanishkaa24** [comment]
Hello Mam! Can I work on this?

**Comment by Kajol-Kumari** [comment]
> Hello Mam! Can I work on this?

Hey @kanishkaa24 sure! But please share the UI here first so that we can finalise that and can assign you to code the same.

**Comment by kanishkaa24** [comment]
> > Hello Mam! Can I work on this?
> 
> Hey @kanishkaa24 sure! But please share the UI here first so that we can finalise that and can assign you to code the same.

Okay Mam. Please assign.

**Comment by garvitgupta13** [comment]
We can add image section too, where they can upload their pic too, but for this you need to change the admin schema too.

**Comment by Kajol-Kumari** [comment]
> We can add image section too, where they can upload their pic too, but for this you need to change the admin schema too.

Hey we don't want to add image as it will just increase the extra work and we will have to do a lot of changes in backend including schema. Currently, we are just trying to improve it's UI and we will keep the same image for all admins

**Comment by Hardik-07** [comment]
Hello ma'am, are the designs finalized??  
if not then I would like to work on it

**Comment by Kajol-Kumari** [comment]
> Hello ma'am, are the designs finalized??
> if not then I would like to work on it

Hey! Please feel free to share here the design that you come up with :)

**Comment by akshitakanojia** [comment]
Hi @Kajol-Kumari is this issue open?

**Comment by akshitakanojia** [comment]
If yes, then I've made a design for that
![admincard](https://user-images.githubusercontent.com/44370673/115245876-02fdcb80-a143-11eb-8800-7cb367cb363a.png)

**Comment by Kajol-Kumari** [comment]
Hey @akshitakanojia the design looks good to me can you please implement this by code and come up with the PR?

**Comment by akshitakanojia** [comment]
Yes sure!
