### ISSUE TITLE
Bug report while running frontend 

### ISSUE THREAD

**Issue by kenkirito** [HITK-TECH-Community/Community-Website#54]
@Kajol-Kumari 
 Windows operating system

install npm install react-scripts@2.1.8

'React' must be in scope when using JSX error due to not using
import React from 'react'
import ReactDOM from 'react-dom'
![HITK Tech Community and 8 more pages - Personal - Microsoft​ Edge 18-12-2020 07_41_45 PM](https://user-images.githubusercontent.com/68530218/102623865-2bf85a80-4169-11eb-8bad-353f6e91db82.png)

**Comment by 07yuvraj** [comment]
Can you let me know what i have to do so that i could work on this?

**Comment by Swastik1710** [comment]
There's no such issue existing. It works totally fine. I guess you need to run npm install when inside the frontend folder.

**Comment by kenkirito** [comment]
yes
