### ISSUE TITLE
Adding Name validation in Resources sharing form

### ISSUE THREAD

**Issue by kanishka8276** [HITK-TECH-Community/Community-Website#546]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 
Resources Sharing form allows to enter numbers and special characters in the names field.
**Describe the solution you'd like**
We should use name validation so that the user enters genuine name.

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Write your answer here.
Yes.

**Comment by jackfrost13** [comment]
@Kajol-Kumari do you think we require this now?

**Comment by Kajol-Kumari** [comment]
Hey @kanishka8276 I don't think we need it as taking name isn't our priority here

**Comment by Kajol-Kumari** [comment]
> Hey @kanishka8276 I don't think we need it as taking name isn't our priority here
