### ISSUE TITLE
[Frontend] Implement About Us Design

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#55]
Deliverables:

- [ ] Keep the header same as current one and make the rest of the page structure including footer as per the deisgn [here](https://github.com/HITK-TECH-Community/Community-Website/tree/main/assets/About%20us%20page)
- [ ] Make Sure to use [this](https://colors.lol/blocky) pallet

update:
Everyone, working on this issue, please try to implement the meet the crew section from [this](https://www.canva.com/design/DAERm1blcVE/FgNJwq-gUKFeVXiBzXGQ4A/edit) design

**Comment by Kajol-Kumari** [comment]
@LNR14 would you like to go ahead with this issue?

**Comment by LNR14** [comment]
Yeah I would like to go ahead with this issue.

**Comment by LNR14** [comment]
Hey I am not able to use reactStrap ROW and COL elements in my about us design. Is there anything you could help me with??

**Comment by Abhishek971999** [comment]
@LNR14 What issues are you facing while using it? 
If you are looking for how to use reactstrap layout, then use the following [link](https://reactstrap.github.io/components/layout/)

**Comment by LNR14** [comment]
I did use that and this is the output
![reactstrap](https://user-images.githubusercontent.com/27141814/102792503-39326680-436e-11eb-8874-c846bc8998ff.PNG)

This is what I am getting
I feel like some kind of JS or CSS file is overriding this.

**Comment by Abhishek971999** [comment]
You have to import the bootstrap CSS file in the component for reactstrap.
Try doing the following
`import 'bootstrap/dist/css/bootstrap.min.css';
` in the react component 
It is mentioned on the home page of [ReactStrap](https://reactstrap.github.io/)

**Comment by LNR14** [comment]
Thank you. This has helped me.

**Comment by LNR14** [comment]
Thank you. This has helped me. 
I am trying to do this issue sorry for the late response. When I am trying to import reactstrap within about-us is that other UI layout is changing because this is an import. I am going to try without reactstrap.

**Comment by shrinishant** [comment]
Is this issue still open to be contributed? If so, then I'm interested in coding the page according to the design as mentioned above in pngs. I would html, css, bootstrap and javascript. This is my very first time contributing an open source project. But, I've made some great projects in context of this issue. You can check them through my LinkedIn profile https://www.linkedin.com/in/nishant-shrivastva-3981a61b7

**Comment by Kajol-Kumari** [comment]
Hey @shrinishant It's good to know the you want to start your open source journey with our organisation, go ahead with this issue and we look forward to your awesome contributions :)

**Comment by kanishkaa24** [comment]
I would like to work on this issue.

**Comment by Kajol-Kumari** [comment]
Sure @kanishkaa24 go ahead with this issue.

**Comment by kanishkaa24** [comment]
Hey 
Where can I find the images to be used on the webpage ?

**Comment by Kajol-Kumari** [comment]
> Hey
> Where can I find the images to be used on the webpage ?

Hey @kanishkaa24 put dummy images for now. We will be updating it finally on our end :)

**Comment by shrinishant** [comment]
Mam, can we discuss about this project on some platform like LinkedIn( I've send you invitation already here), slack or whatsapp. That would be really helpful.

**Comment by Kajol-Kumari** [comment]
> Mam, can we discuss about this project on some platform like LinkedIn( I've send you invitation already here), slack or whatsapp. That would be really helpful and productive.

Hey @shrinishant we have our slack channel for discussion purpose whose link is mentioned in the readme. You can join in [our slack community](https://join.slack.com/t/hitkteckcommunity/shared_invite/zt-jgr1sd87-lhiXHO_x63Kt7h8VBxDaFw) and discuss about the issue/enhancements of anything relevant you wish :)

**Comment by harikishantk** [comment]
@Kajol-Kumari can I also contribute in it?

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari can I also contribute in it?

sure @harikishantk go ahead with this isue!

**Comment by sahebsunny** [comment]
Sir, I have made this issue and I love to work on it.
I would be grateful if you can assign this issue to me.
Thank you.

**Comment by Kajol-Kumari** [comment]
Everyone, working on this issue, please try to implmenet the `meet the crew` section from [this](https://www.canva.com/design/DAERm1blcVE/FgNJwq-gUKFeVXiBzXGQ4A/edit) design
