### ISSUE TITLE
[Frontend]: Adding a 404 page

### ISSUE THREAD

**Issue by ShambhaviSharma0110** [HITK-TECH-Community/Community-Website#551]
**Is your feature request related to a problem? Please describe.**
A 404 page for when an unknown route is entered 
**Describe the solution you'd like**
This page would pop up whenever a route that is not known will be searched for, an error page.

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Write your answer here.
yes

**Comment by Kajol-Kumari** [comment]
Hey @ShambhaviSharma0110 Thank you for taking time to report this issue but we already have `404` page. I recommend you to please look at the codebase and our project once :)
