### ISSUE TITLE
[Frontend] Change the Navigation Panel to Collapsible Menu For Admins

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#553]
Deliverable -

- [ ] The navigation panel for the admin takes a lot of space for small screen. Please change it in the form of collapsible menu for small screens(similar to navbar of our website)

GIF of the issue ->
![admin](https://user-images.githubusercontent.com/44888949/111911322-173ea200-8a8b-11eb-947e-bc14c71456ef.gif)

**Comment by akshitakanojia** [comment]
Hi @Kajol-Kumari, I would like to work on this issue.

**Comment by Kajol-Kumari** [comment]
> Hi @Kajol-Kumari, I would like to work on this issue.

Sure @akshitakanojia Please go ahead with this issue.
