### ISSUE TITLE
Customizing Scrollbar

### ISSUE THREAD

**Issue by ShubhamSj07** [HITK-TECH-Community/Community-Website#554]
Default Scrollbar is not looking good specially in our amazing dark-mode.
I would like to fix this!

Default one
![Previous-Scrollbar](https://user-images.githubusercontent.com/56510414/112150458-20a04980-8c06-11eb-853f-80116d1e1e88.JPG)

Customized one
![Customized-Scrollbar](https://user-images.githubusercontent.com/56510414/112150492-285fee00-8c06-11eb-8a0c-c4b5e72c487b.JPG)

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Yes

Please assign me this issue.

**Comment by Kajol-Kumari** [comment]
Hey @ShubhamSj07 thanks for suggesting this. Would love to see it implemented :)
