### ISSUE TITLE
Add Updated Code Structure to the Conventions FIle

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#555]
Delieverable -

- [ ] Currently, we have the outdated folder structure [here](https://github.com/HITK-TECH-Community/Community-Website/blob/main/frontend/conventions.md#folder-structure) We need to replace it with the current up-to-date structure

**Comment by AshuKV** [comment]
Can I work on this issue under GSSoC'21? Kindly assign it to me.

**Comment by Kajol-Kumari** [comment]
> Can I work on this issue under GSSoC'21? Kindly assign it to me.

Sure @AshuKV ! Please go ahead with this issue :)
