### ISSUE TITLE
Improvement of News-letter Section of Footer

### ISSUE THREAD

**Issue by ShubhamSj07** [HITK-TECH-Community/Community-Website#558]
**Is your feature request related to a problem? Please describe.**
After succesfully submitting an email for our newsletter ,we can show an card/msg like

https://user-images.githubusercontent.com/56510414/112461090-9aab0c80-8d85-11eb-9ab1-6379c3a46b3f.mp4

Also, msg/card will be responsive on all screen-sizes!
![Newletter_Preview](https://user-images.githubusercontent.com/56510414/112461898-71d74700-8d86-11eb-9977-2b6ee2829ca3.JPG)

Pls, assign me this issue
**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Yes

**Comment by jackfrost13** [comment]
LGTM what do you say @Kajol-Kumari

**Comment by Kajol-Kumari** [comment]
> LGTM what do you say @Kajol-Kumari

+1 @ShubhamSj07 please go ahead with this :)
