### ISSUE TITLE
[Frontend] Checkbox get distorted for small screen

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#562]
Deliverable - 

- [ ] Fix the checkbox of `join us` form for small screens

Screenshot of the bug -
![Screenshot from 2021-03-26 16-30-49](https://user-images.githubusercontent.com/44888949/112622548-32c1f800-8e51-11eb-8021-a3d383e03e3f.png)

**Comment by akshitakanojia** [comment]
Hi @Kajol-Kumari , can I work on this issue?

**Comment by Sandi-09** [comment]
can i work on this issue

**Comment by Kajol-Kumari** [comment]
Hey @akshitakanojia please go ahead with this issue.
@Sandi-09 as we need to follow FCFS I request you to look for some other issue.
