### ISSUE TITLE
Adding dark-theme to Footer

### ISSUE THREAD

**Issue by ShubhamSj07** [HITK-TECH-Community/Community-Website#565]
**Is your feature request related to a problem? Please describe.**
Project is looking awesome with this amazing dark mode, but footer remains with same theme for light as well as dark!
So, i would like to add dark theme to footer.
I had attached preview ..

https://user-images.githubusercontent.com/56510414/112715439-33689600-8f06-11eb-979a-cbb0bb762285.mp4

![Dark_Footer](https://user-images.githubusercontent.com/56510414/112715521-a5d97600-8f06-11eb-8971-28d060921efa.JPG)

Pls, assign me this issue
**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Yes

**Comment by ShubhamSj07** [comment]
@Kajol-Kumari , pls review this issue

**Comment by Kajol-Kumari** [comment]
Hey @ShubhamSj07 I am not sure if this color combination you have used will look consistent with the rest. 
@Coder-Srinivas Can you please help us with the color combination pick for the dark theme? Btw feel free to open up the PR for this @ShubhamSj07 we will let you know if any change is required.

**Comment by Coder-Srinivas** [comment]
@ShubhamSj07, the input tag has no styling effect when active. Have a look at the contact us section. Implement the same here.

Regarding the sign up button, use the following colors :
` background: #69a9dd;
  border: 2px solid #69a9dd;
  color: #171717;`

And on hovering, use the following gradient :
`  background: linear-gradient(
    45deg,
    #2b5876 0%,
    #4e4376 90%
  );
  color: whitesmoke;`

Colors used in dark mode :
#69a9dd
#282c35
#333333
#414a4c

Try to align the background theme with that of the website.

**Comment by pragati-kumar** [comment]
@ShubhamSj07 I'm a GSSOC'21 participant. I would like to contribute to this issue and can get started ASAP. Could you assign this to me? I propose that we use a toggle button to switch themes.

**Comment by ShubhamSj07** [comment]
@pragati-kumar , lol I am working on this issue!
