### ISSUE TITLE
[Frontend] footer get left aligned on lower resolutions

### ISSUE THREAD

**Issue by nlok5923** [HITK-TECH-Community/Community-Website#566]
**Describe the bug**
Footer get left aligned at lower resolutions 
**To Reproduce**
1. Go to landing page
2. Reduce resolutions to mobile view 
3. See error

**Expected behavior**
Footer should be center aligned

**Screenshots**
![image](https://user-images.githubusercontent.com/56120084/112718633-51d88c80-8f1a-11eb-8c22-d33278b020fd.png)

**Desktop (please complete the following information):**
 - OS: all
 - Browser all
 - Version all

**Smartphone (please complete the following information):**
 - Device:  all
 - OS: [e.g. all
 - Browser all
 - Version all

**Additional context**
I would like to resolve this issue.

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Write your answer here.
Yes

**Comment by Kajol-Kumari** [comment]
@nlok5923 Thanks for pointing this. Please go ahead with this issue
Happy learning :)

**Comment by tanishq-arya** [comment]
Is this still an issue. Can I work on this ?

**Comment by hardikshah197** [comment]
May I take up this issue? if no one is working on it?
@nlok5923 @Kajol-Kumari

**Comment by Kajol-Kumari** [comment]
> May I take up this issue? if no one is working on it?
> @nlok5923 @Kajol-Kumari

@hardikshah197 you can go ahead with it.

**Comment by CodingwithMe123** [comment]
Can I take this Issue or is it fixed?

**Comment by Kajol-Kumari** [comment]
@aritroCoder it's still open. Please feel free to go with it.

**Comment by pushkar2112** [comment]
Hi,
If this issue is currently not assigned to anyone or has not been fixed yet, I would like to give it a try.
Cheers!

**Comment by aritroCoder** [comment]
Is this solution OK?

https://user-images.githubusercontent.com/92646038/144732500-40a5f2ab-4a22-4580-b194-8fbab1210c7a.mp4

**Comment by Kajol-Kumari** [comment]
@aritroCoder yes the changes looks good.

**Comment by ikavyajain** [comment]
What's the status of this? If there is no PR, Can I work on this?
@Kajol-Kumari

**Comment by sulogna2001** [comment]
Hey Can you assign me this issue for GSsoc22

**Comment by Mridul07Sharma** [comment]
Plz Assign it to me. I am GSSOC 22 participant

**Comment by Kajol-Kumari** [comment]
Closing this one as this should be covered under https://github.com/HITK-TECH-Community/Community-Website/issues/748
