### ISSUE TITLE
[Frontend] improve icons on carousel

### ISSUE THREAD

**Issue by tushartiwari7** [HITK-TECH-Community/Community-Website#569]
**Describe your Proposal**
improve arrow icons on corousel section. i will update it with a more fancy and minimalistic look which doesn't affects the readability

**Additional context**
the previous icons are very old fashioned and occupies unneccessary background space also which reduces readability 

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Write your answer here.
Yes

**Comment by tushartiwari7** [comment]
please assign me this issue add gssoc21 and level2 labels

**Comment by tushartiwari7** [comment]
![hitk-tech-community netlify app_](https://user-images.githubusercontent.com/66322728/112728759-ccbb9a80-8f4e-11eb-8fd4-4ef5795aa8b1.png)
i was talking about these arrow icons on carousel.

**Comment by Kajol-Kumari** [comment]
Hey @tushartiwari7 can you please show us the icons design that you want to use in place of the current one?

**Comment by tushartiwari7** [comment]
![_C__Users_TUSHAR_Downloads_left-arrow svg](https://user-images.githubusercontent.com/66322728/112746327-a9830080-8fcb-11eb-9bd6-9e474edc235b.png)
this is one such example which i think best suits.
if not i have more collection too.

**Comment by Kajol-Kumari** [comment]
@tushartiwari7 please go ahead with the issue. We look forward to your PR

**Comment by tushartiwari7** [comment]
thanks! i will start working on it ASAP 👍

**Comment by tushartiwari7** [comment]
sorry closed that by mistake.
