### ISSUE TITLE
[Frontend] Resource sharing Page

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#57]
Deliverables:

- [ ] Make the resource sharing page having a form with the fields same as [this](https://www.figma.com/file/sh8ubRJgEXtQRbxCiJ3b48/Untitled?node-id=0%3A1)
- [ ] Use [this](https://colors.lol/blocky) color plattet for implementing the design

**Comment by Isha77agarwal** [comment]
Can I work on this?

**Comment by 07yuvraj** [comment]
May i also work on this along with @Isha77agarwal

**Comment by Kajol-Kumari** [comment]
Sure @Isha77agarwal and @07yuvraj You both can go ahead with this issue.
Looking forward to your PRs :)

**Comment by sravanireddy1102** [comment]
@Kajol-Kumari can i work on this?

**Comment by Kajol-Kumari** [comment]
Sure @sravanireddy1102 , you can go ahead with this issue!

**Comment by Aniket31-coder** [comment]
Hey!
Can I work in this issue?

**Comment by Kajol-Kumari** [comment]
Sure @Aniket31-coder !  You can go ahead with this

**Comment by harikishantk** [comment]
@Kajol-Kumari  I would like to contribute to this, May I?

**Comment by vedikaag99** [comment]
@Kajol-Kumari I'd like to work on this as well.

**Comment by kanishkaa24** [comment]
![Resource Sharing ](https://user-images.githubusercontent.com/71253790/103302865-a14a1200-4a2a-11eb-862f-1bfea98cf363.png)
@Kajol-Kumari Please review this.

**Comment by Kajol-Kumari** [comment]
@kanishkaa24 please use any standard image here and the form also don't look much promising. You can checkout `contact-us` page for reference of the form design
