### ISSUE TITLE
[Frontend] Scroll Feature Not Working Properly

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#570]
Deliverable -

- [ ] The scroll feature of view broadcast doesn't seem to work as expected.

GIF of the Bug -
![broadcat_bug](https://user-images.githubusercontent.com/44888949/112746358-d505eb00-8fcb-11eb-8ab2-496a601cdde3.gif)

**Comment by nlok5923** [comment]
i would like to work on this issue

**Comment by Kajol-Kumari** [comment]
> i would like to work on this issue

Sure @nlok5923 please go ahead with this issue. We look forward to your PR

**Comment by pragati-kumar** [comment]
Hello @Kajol-Kumari . I'm a GSSOC'21 participant and I would really like to contribute to this issue. I think the position attribute should be switched to 'sticky'. Could you please assign the problem to me?

**Comment by Kajol-Kumari** [comment]
Hey @pragati-kumar as this issue has already been assigned to someone we can't assign this to you. Please look for some other issue

**Comment by pragati-kumar** [comment]
> Hey @pragati-kumar as this issue has already been assigned to someone we can't assign this to you. Please look for some other issue

Sure. Thanks for responding!

**Comment by Kajol-Kumari** [comment]
Hey @nlok5923 can I please get an update on this issue?

**Comment by nlok5923** [comment]
Yeah I am working on it  still getting little distortion with social icons.

**Comment by Kajol-Kumari** [comment]
> Yeah I am working on it still getting little distortion with social icons.

This issue is not about the footer fix.(Please read it's description once)

**Comment by nlok5923** [comment]
Sorry my bad currently I am working on footer issue so you can unassign me to this issue.

**Comment by satcasm** [comment]
Hey @Kajol-Kumari can I take on this issue?

**Comment by satcasm** [comment]
Hey @Kajol-Kumari , apologies for the delay but have a look again it doesn't seems necessary to add a scroll-bar.
If it is still required let me know.
Screenshot Reference:
![image](https://user-images.githubusercontent.com/56315878/116512220-4eec0580-a8e5-11eb-8e59-c87e77524737.png)

**Comment by Kajol-Kumari** [comment]
Hey @satcasm it's required only when the texts go beyond the window height. You can check the same for the `Private AI Series` broadcast
