### ISSUE TITLE
Invite Admin component is giving error on submitting

### ISSUE THREAD

**Issue by garvitgupta13** [HITK-TECH-Community/Community-Website#572]
**Describe the bug**
Upon submitting any valid email to invite admin section the component breaks

**To Reproduce**
- Submit any valid email in invite admin section

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/70805691/112754228-bc5ffa00-8ff8-11eb-9e96-feef232ddb32.png)
![image](https://user-images.githubusercontent.com/70805691/112754246-d13c8d80-8ff8-11eb-9f0f-d5fe4a6c2fea.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Yes

Please assign me this issue under `gssoc21`

**Comment by garvitgupta13** [comment]
I have fixed this break, please assign me this so I can create a pull request
![image](https://user-images.githubusercontent.com/70805691/112755399-216a1e80-8ffe-11eb-9596-2d005d5510f9.png)

**Comment by Kajol-Kumari** [comment]
Hey @garvitgupta13 as you pointes out thia one. It would be great if you can fix all the warnings that we get jn the console as soon as the pages loads in(you would better able tp view it if you run it on your local) . Also in the dev environment, we get a few warnings in the terminal after runing the frontend. Can you please fix them as well (Excluding the unused variable warnings as we will be using those variables later on)

**Comment by garvitgupta13** [comment]
Removed all the warnings except the unused variables.
![image](https://user-images.githubusercontent.com/70805691/112878969-2904f280-90e6-11eb-800e-8499648072d4.png)
