### ISSUE TITLE
Add validation in add team member form

### ISSUE THREAD

**Issue by garvitgupta13** [HITK-TECH-Community/Community-Website#584]
**Is your feature request related to a problem? Please describe.**
Add form validation in add team member form

**Describe the solution you'd like**
Use `joi-browser` to apply form validation

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
yes

**Comment by Kajol-Kumari** [comment]
Hey @garvitgupta13 thanks for opening up this issue. Would you like to go ahead with this issue?

**Comment by garvitgupta13** [comment]
> Hey @garvitgupta13 thanks for opening up this issue. Would you like to go ahead with this issue?

yes mam, please assign this issue to me

**Comment by Kajol-Kumari** [comment]
Hey @garvitgupta13 please make sure to show proper validation message as below -
- For image (required) please use toast message to show the error.
For rest of the fields, please show the error message same as we are showing in different forms. 
Also after Clicking on submit button, Reset the form and show a toast message saying `Member added successfully!`

I hope to see all these implementation in the PR. Please let me know if you need any clarification on any of these

**Comment by garvitgupta13** [comment]
> Hey @garvitgupta13 please make sure to show proper validation message as below -
> 
> * For image (required) please use toast message to show the error.
> * For rest of the fields, please show the error message same as we are showing in different forms.
> * Also after Clicking on submit button, Reset the form and show a toast message saying `Member added successfully!`
> 
> I hope to see all these implementation in the PR. Please let me know if you need any clarification on any of these

Hey @Kajol-Kumari, currently the image section has already a default image set for admin and there is an option to change it. 
If the person doesn't change his image then also there is a default one for him than what does the required part in the image refers to
Please clarify 1st point.

**Comment by Kajol-Kumari** [comment]
> > Hey @garvitgupta13 please make sure to show proper validation message as below -
> > 
> > * For image (required) please use toast message to show the error.
> > * For rest of the fields, please show the error message same as we are showing in different forms.
> > * Also after Clicking on submit button, Reset the form and show a toast message saying `Member added successfully!`
> > 
> > I hope to see all these implementation in the PR. Please let me know if you need any clarification on any of these
> 
> Hey @Kajol-Kumari, currently the image section has already a default image set for admin and there is an option to change it.
> If the person doesn't change his image then also there is a default one for him than what does the required part in the image refers to
> -Please clarify 1st point.
> -Please let me know if there is an optional field in the form

Hmm, so for image, we can ignore the validation. 
The linkedIn, github and twitter urls are optional.
