### ISSUE TITLE
404 page needs to be fixed for dark mode

### ISSUE THREAD

**Issue by vedikaag99** [HITK-TECH-Community/Community-Website#592]
**Describe the bug**

In the dark mode, there's a white gap below button as shown in my screenshots which needs to be removed. This gap is visible for both large and small screens.

**To Reproduce**
1. Go to 'http://localhost:3000/NotFound'
2. Scroll down to the 'Go Home' button
3. See error

**Screenshots**
![Screen Shot 2021-04-04 at 3 30 14 PM](https://user-images.githubusercontent.com/67699840/113505313-9340eb80-955b-11eb-88d7-d7a8bacf99ec.png)
for smaller screens:
![Screen Shot 2021-04-04 at 3 30 26 PM](https://user-images.githubusercontent.com/67699840/113505321-9936cc80-955b-11eb-9f0c-9d1222fe42d6.png)

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Yes.

Can I work on it under gssoc'21?

**Comment by Kajol-Kumari** [comment]
Hey @vedikaag99 thanks for pointing this to our notice. Please feel free to go ahead with this issue :)
