### ISSUE TITLE
Need to click the button instead of Card in Settings of Admin Dashboard

### ISSUE THREAD

**Issue by dhwaj1902** [HITK-TECH-Community/Community-Website#593]
**Describe the bug**
We need to click the button(p tag) to open that setting, I can make the card clickable so that it is easy to navigate.
We can also add icons also in these cards like in the dashboard.
![2021-04-05 14-50-49](https://user-images.githubusercontent.com/57860123/113559781-9bfaf580-961f-11eb-998f-35365e5399d5.gif)

**Comment by dhwaj1902** [comment]
Please approve this, so that I can start working on this bug.

**Comment by dhwaj1902** [comment]
`husky > pre-commit (node v14.4.0)
/d/AA Work/GSoC/Community-Website/backend/node_modules/.bin/lint-staged: line 5: cygpath: command not found
internal/modules/cjs/loader.js:1032
  throw err;
  ^

Error: Cannot find module 'D:\lint-staged\bin\lint-staged.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
husky > pre-commit hook failed (add --no-verify to bypass)`

I am getting this error while committing the changes to my forked repo.
Please help me regarding this.

**Comment by dhwaj1902** [comment]
@Kajol-Kumari can you also look into this issue.

**Comment by Kajol-Kumari** [comment]
Hey @dhwaj1902 I am hoping to see you come up with a better UI than what we have now. If you are thinking of removing the button look. As the current UI is looking preety good to me.

**Comment by dhwaj1902** [comment]
@Kajol-Kumari  I have already changed the card in this [pr](https://github.com/HITK-TECH-Community/Community-Website/pull/594). 
Please review this [pr](https://github.com/HITK-TECH-Community/Community-Website/pull/594).
