### ISSUE TITLE
Add Loader while fetching api 

### ISSUE THREAD

**Issue by dhwaj1902** [HITK-TECH-Community/Community-Website#595]
**Describe the bug**
We can add Loader while fetching API from the backend.
Here is one of the example.
We can add loader in Manage Admin while fetching API so that there is no component of no admin found. No Admin found will only be displayed when there is no admin.

![2021-04-05 16-11-03](https://user-images.githubusercontent.com/57860123/113566249-f4cf8b80-9629-11eb-9134-86e9fa702f2b.gif)

**Comment by dhwaj1902** [comment]
Please approve this issue so that I can work on this.

**Comment by Kajol-Kumari** [comment]
Hey @dhwaj1902 it's a genuine request not to start working on an issue until it gets assigned to you as we don't want your effort to go in vain.

Btw thanks for proposing this idea and we look forward to a loader with a good UI.

**Comment by dhwaj1902** [comment]
Sorry for that, I will keep this in mind in the future😊.
