### ISSUE TITLE
[Open for all] UI Design for Broadcast page of the website

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#6]
- Make UI for the broadcast of the website using any of the UI designing tool like figma

**Comment by JLopezz3** [comment]
Hello, I'd like to help design the broadcast page. What kind of design would you like?

**Comment by Kajol-Kumari** [comment]
Hey @JLopezz3 I am attaching here the rough diagram of the design we are looking for. So basically along with header and footer there will be two sections. First section would be `Recent Broadcasts` that will contains 3-5 most recent broadcasts in form of slider cards and each card will be clickable which on click will display the complete braodcast message. Sceond section would be of `Previous broadcasts` which will also be a slider of card havng left and right arrow key for navigation and clickable cards.   
![WhatsApp Image 2020-12-10 at 11 56 04 AM](https://user-images.githubusercontent.com/44888949/101729766-ceb43780-3ade-11eb-8cab-c7ce93309e8c.jpeg)

If you need any further clearance or want to discuss about the design feel free to drop me a msg at our [slack](https://join.slack.com/t/hitkteckcommunity/shared_invite/zt-jgr1sd87-lhiXHO_x63Kt7h8VBxDaFw) channel 
Happy Coding :)

**Comment by JLopezz3** [comment]
Okay I will get started on it. I will update you with the Figma when I'm done. Thank you

**Comment by JLopezz3** [comment]
I have the rough-draft of the Broadcast page on my Figma. 
[FIGMA LINK HERE](https://www.figma.com/file/Hdxtv50E5vuzDoGGZMnfhC/BroadcastPage?node-id=0%3A1)
Let me know what you think, or what I should change. Thanks 
![1](https://user-images.githubusercontent.com/58873590/102108519-a8e9a400-3df8-11eb-94b9-2ffaf9601223.png)

**Comment by Kajol-Kumari** [comment]
Hey @JLopezz3 , please add a folder with name `broadcast page` in [here](https://github.com/HITK-TECH-Community/Community-Website/tree/main/assets) and `readme.md` file  under this file .There you can add the design link and also please attach the screenshot of the design in this folder and make a PR.

**Comment by JLopezz3** [comment]
I think I need to be invited as a collaborator because I do not have push access.

**Comment by kanishkaa24** [comment]
I want to work on this issue. @Kajol-Kumari

**Comment by Kajol-Kumari** [comment]
sure @kanishkaa24 . Go ahead with this issue :)

**Comment by kanishkaa24** [comment]
![Broadcast](https://user-images.githubusercontent.com/71253790/103234069-be1c1200-4964-11eb-9298-779aa3f82e05.png)
@Kajol-Kumari Please review this and let me know the changes.

**Comment by Kajol-Kumari** [comment]
Hey @kanishkaa24 it's looking go to me 👍

**Comment by Sshivani-12** [comment]
Interested!

**Comment by SHITIZ-AGGARWAL** [comment]
@Kajol-Kumari 
I would like to contribute some designs to if possible

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari
> I would like to contribute some designs to if possible

sure @SHITIZ-AGGARWAL Looking forward to your designs :)

**Comment by yashsehgal** [comment]
Hey There, This is my approach for webpage design. This is just an experimental UI following a retro-classic theme. Hope you'll like it.

![broadcasts-page-ui](https://user-images.githubusercontent.com/62352288/103734622-60e22980-5012-11eb-873a-1df8577267a4.png)

**Comment by Kajol-Kumari** [comment]
@yashsehgal the design looks clean, but maybe in place of `learn more` button, put 2-3 dummy lines

**Comment by yashsehgal** [comment]
Okay, I will do that.

**Comment by yashsehgal** [comment]
There you go, Here are the changes that I have made.

![broadcasts-page-ui](https://user-images.githubusercontent.com/62352288/103746816-b2e17a00-5027-11eb-9a28-bac5a1c83176.png)

**Comment by SHITIZ-AGGARWAL** [comment]
@Kajol-Kumari here are my designs
https://drive.google.com/drive/folders/1o659BFpFpOaMsvOsWjHqf0uA2fh5kbEP?usp=sharing
please tell if I can make a PR 
Figma Link: https://www.figma.com/file/gbwpSEiR5FW2G6Zjc0BgE6/Untitled?node-id=0%3A1

**Comment by Kajol-Kumari** [comment]
@yashsehgal @SHITIZ-AGGARWAL the design looks good to me :)

**Comment by yashsehgal** [comment]
Shall I make a PR too?
