### ISSUE TITLE
Login form responsive issue

### ISSUE THREAD

**Issue by ShubhamSj07** [HITK-TECH-Community/Community-Website#601]
**Describe the bug**
Login Form for signing in admin
Form isn't responsive on screen size (< 768px)

On mobile , form is looking like 
![Login_HITK-Issue](https://user-images.githubusercontent.com/56510414/113975923-dce04d80-985d-11eb-871c-e0a46c072c95.JPG)

The image & form are not getting settled well!
I can fix this issue to this
![Login_HITK-Issue_FIXED](https://user-images.githubusercontent.com/56510414/113976048-0ac59200-985e-11eb-8dfb-90a2748a9ada.JPG)

Please assign me this issue
**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Yes

**Comment by ShubhamSj07** [comment]
@Kajol-Kumari , pls review this

**Comment by Kajol-Kumari** [comment]
Hey @ShubhamSj07 Thanks for pointing this. Please go ahead with this issue.
