### ISSUE TITLE
UI Back to top button is not clearly visible

### ISSUE THREAD

**Issue by tanishq-arya** [HITK-TECH-Community/Community-Website#602]
**Describe the bug**
A simple opacity change could fix this issue.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Write your answer here.

**Comment by Kajol-Kumari** [comment]
Hey @tanishq-arya thanks for taking time to point-out this issue. Would you like to work on this issue and come up with a better UI for the `scroll-to-top` button?

**Comment by tanishq-arya** [comment]
@Kajol-Kumari Sure. I was thinking of making it square. Or I can implement any suggestions you want me to.

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari Sure. I was thinking of making it square. Or I can implement any suggestions you want me to.

Umm, let's see if that looks better. Btw I am expecting you to come up with a better color for this button which can be clearly visible in dark as well as light mode

**Comment by tanishq-arya** [comment]
![Screenshot (1149)](https://user-images.githubusercontent.com/77333275/114266015-93386400-9a11-11eb-8004-f2b264d88a15.png)
![Screenshot (1150)](https://user-images.githubusercontent.com/77333275/114266023-959abe00-9a11-11eb-8ed5-d288f18081bf.png)
![Screenshot (1146)](https://user-images.githubusercontent.com/77333275/114266025-96335480-9a11-11eb-98b6-90e22133822c.png)

**Comment by tanishq-arya** [comment]
The last one is when you hover over the outer border changed to circle.

**Comment by tanishq-arya** [comment]
![image](https://user-images.githubusercontent.com/77333275/114266580-a7319500-9a14-11eb-9473-82ad88e24a81.png)

@Kajol-Kumari How about if I change to this color in the dark mode?

**Comment by Kajol-Kumari** [comment]
Hey @tanishq-arya, the dark-mode one is looking good, for the light mode, we need to come up with a better color. For the light mode, maybe try the linear gradient that we are using for the on-hover effect of our icon in the navbar

**Comment by tanishq-arya** [comment]
![image](https://user-images.githubusercontent.com/77333275/114307260-775dbc80-9afc-11eb-9de2-5adcec36d3ee.png)

**Comment by Kajol-Kumari** [comment]
> ![image](https://user-images.githubusercontent.com/77333275/114307260-775dbc80-9afc-11eb-9de2-5adcec36d3ee.png)
> I tried setting the color like in the light mode but linear gradient cant be defined for color in css so I made this by background linear gradient and color white

Umm, this doesn't seems good. Under `our motive` section of the homepage the icons color in the dark mode looks pretty good. Can you please try implementing that for the light mode?

**Comment by tanishq-arya** [comment]
![image](https://user-images.githubusercontent.com/77333275/114431310-f9bdad80-9bdc-11eb-9c24-7b8da55f7074.png)
This one ?

**Comment by tanishq-arya** [comment]
![image](https://user-images.githubusercontent.com/77333275/115703977-63317f00-a388-11eb-9732-eefa48ea42e6.png)

![image](https://user-images.githubusercontent.com/77333275/115704006-6cbae700-a388-11eb-8f11-8b7dbeb71d3f.png)
