### ISSUE TITLE
There is no navbar in Admin Dashboard

### ISSUE THREAD

**Issue by dhwaj1902** [HITK-TECH-Community/Community-Website#604]
Currently, there is no navbar for the admin dashboard.
We can add the Navbar for the admin Dashboard so that the admin can also route to different URLs of the website. Also if there is a navbar we can also change our theme through the admin dashboard.

**Comment by dhwaj1902** [comment]
@Kajol-Kumari please look at this, so that I can work on it.

**Comment by jackfrost13** [comment]
Do we need that right now? @Kajol-Kumari

**Comment by Kajol-Kumari** [comment]
Hey @dhwaj1902 Thanks for taking time to report this but we have hidden the navbar for admin panel intentionally. So, we won't be working on it as of now.
