### ISSUE TITLE
[Frontend] Add `Open Source Contributors` section in About Us page

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#607]
Deliverable -

- [ ] We want to acknowledge all the contributors of our project. So, we want to add `Open Source Contributors` section below `Board Members` section which will contain all the list of our contributors images similar to [this](https://github.com/HITK-TECH-Community/Community-Website#contributors-), which we have in our readme.

**Comment by vedikaag99** [comment]
@Kajol-Kumari can I work on this?

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari can I work on this?

Sure @vedikaag99 please go ahead :)
