### ISSUE TITLE
Enhancement in Admin Panel

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#608]
Deliverable -

- [ ] There is a lot of left and right margin on the admin panel, we need to reduce this.
- [ ] The left navigation card and right panel card in the admin panel are not looking good, we need a better card effect in these cards.
- [ ] Make the size of the Dashboard card, same as that of the setting page, in-order to be consistent.

**Comment by tanishq-arya** [comment]
Please assign me this issue. 

The margin issue can be fixed by
container {
width: 90%;
display : flex;
justify-content: space-between;
**
Also this requires a margin-bottom: 2em; or the footer overlaps
}

**Comment by Kajol-Kumari** [comment]
Please go ahead with this issue @tanishq-arya

**Comment by tanishq-arya** [comment]
I'm sorry for the delay will make a PR soon.
