### ISSUE TITLE
update contributing.md

### ISSUE THREAD

**Issue by khareyash05** [HITK-TECH-Community/Community-Website#610]
Hi! I would like to add the following in contributing.md-
Squash commits in a single issue into one
Updating the forked and local repo as the updations are made in the upstream

**Comment by jackfrost13** [comment]
I don't think so it of much need.
1. Merge can be done only by squashing
2. TBH, it doesn't matter if the local/forked is updated or not. The person working on the issue would have to inherently update with upstream before merging.

@Kajol-Kumari Any thoughts?

**Comment by Kajol-Kumari** [comment]
Hey @khareyash05 Thanks for pointing these but as @jackfrost13 suggested we don't need to add these in our readme.
