### ISSUE TITLE
Clustering

### ISSUE THREAD

**Issue by Shubham-Kumar-2000** [HITK-TECH-Community/Community-Website#614]
**Describe the bug**
Server is currently running in a non cluster mode.

**To Reproduce**
1. Start the server you will find that it is running in only one thread.

**Expected behavior**
Sever should run in cluster mode to run multiple instances of the server in fork mode to make it faster.

**Additional context**

[Reason](https://www.w3schools.com/nodejs/ref_cluster.asp#:~:text=same%20server%20port.-,Node.,thread%2C%20to%20handle%20the%20load.)

[Module](https://www.npmjs.com/package/cluster)

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Yes

@jackfrost13 I would like to work on this issue as a gssoc 21 participant.

**Comment by jackfrost13** [comment]
Hey, currently since the project is under dev hence it is running like that.
If you want to work on it, we can assign you this issue
