### ISSUE TITLE
Hover effect on buttons

### ISSUE THREAD

**Issue by satcasm** [HITK-TECH-Community/Community-Website#615]
When we hover over button after selecting in dark mode the text color inside the button changes but whereas in light mode it doesn't.
Would like to work on it under GSSOC' 21.
Please assign this issue to me.
Thanks!

Screenshot Reference:
![image](https://user-images.githubusercontent.com/56315878/114308162-83e41400-9b00-11eb-9151-a37c0fcf76c8.png)
![image](https://user-images.githubusercontent.com/56315878/114308185-96f6e400-9b00-11eb-9a1c-b3f260f63bc3.png)

**Comment by jackfrost13** [comment]
I do not think it is a bug, I believe it was intensional
@Kajol-Kumari Please confirm if this issue is required

**Comment by Kajol-Kumari** [comment]
> I do not think it is a bug, I believe it was intensional
> @Kajol-Kumari Please confirm if this issue is required

Yeah, this isn't a bug. Thanks for your time @satcasm
