### ISSUE TITLE
Adding hover-effect on profile-cards in about-us section

### ISSUE THREAD

**Issue by ShubhamSj07** [HITK-TECH-Community/Community-Website#616]
**Is your feature request related to a problem? Please describe.**
I would like too add hover-effect for profile-cards both dark & light mode
Right now, no effect is added!

Preview 

https://user-images.githubusercontent.com/56510414/114341575-bbda6e00-9b77-11eb-94c2-cd0257498545.mp4

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Yes
Please assign me this issue

**Comment by jackfrost13** [comment]
@Kajol-Kumari Please confirm if we need to prioritise this for now

**Comment by Kajol-Kumari** [comment]
Hey @ShubhamSj07 you can work on this provided we see a better effect :)

**Comment by ShubhamSj07** [comment]
@Kajol-Kumari , so am i assigned to this issue to start working for same ?

**Comment by ShubhamSj07** [comment]
Heyy @Kajol-Kumari , pls review this card effects
For light theme, i took ref of about section img bg color


https://user-images.githubusercontent.com/56510414/114518609-29ac9580-9c5d-11eb-978b-1ea74a5871f2.mp4

**Comment by jackfrost13** [comment]
Hey @ShubhamSj07 I don't find this desgin very intriguing and much differentiating. @Kajol-Kumari Your thoughts?

**Comment by ShubhamSj07** [comment]
Pls review this effects @Kajol-Kumari 

https://user-images.githubusercontent.com/56510414/115361276-0e520500-a1de-11eb-92cd-6330267d92d9.mp4

**Comment by Kajol-Kumari** [comment]
Hey @Shubham-Kumar-2000 can you please try to give here the hover effect similar to `our motive` section of the home page. It would look consistent that way. WDYT?

**Comment by ShubhamSj07** [comment]
Heyy, @Kajol-Kumari again mistakely u had tagged another shubham 🤣 
yeah, this effect is looking cool

https://user-images.githubusercontent.com/56510414/115572038-2b213200-a2dd-11eb-97a6-274bbee4b4cf.mp4

**Comment by Kajol-Kumari** [comment]
Hey @ShubhamSj07 can u please push the change so that I can test it?
