### ISSUE TITLE
Enhancement in Join Us section in home page

### ISSUE THREAD

**Issue by AbhipsaGuru1012** [HITK-TECH-Community/Community-Website#619]
**Describe the bug**
The text in the Join Us section in smaller screen size is left aligned. I would like to center align it.

**To Reproduce**

**Expected behavior**

**Screenshots**
![hitk-mobile](https://user-images.githubusercontent.com/58511560/114714769-0b739200-9d50-11eb-831c-7abafa77628d.PNG)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
I would like to work on this issue under GSSoC'21

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Write your answer here. - Yes

**Comment by AbhipsaGuru1012** [comment]
@Kajol-Kumari please let me know if I can work on this issue

**Comment by Kajol-Kumari** [comment]
Hey @AbhipsaGuru1012 you can go ahead with this issue

**Comment by AbhipsaGuru1012** [comment]
@Kajol-Kumari I have made a PR. Please review
