### ISSUE TITLE
Responsive Issue for Open Source Contributors Section

### ISSUE THREAD

**Issue by ShubhamSj07** [HITK-TECH-Community/Community-Website#625]
**Describe the bug**

**To Reproduce**
1. Go to '/about-us'
2. Scroll down to OSC Section
3. Check out responsiveness on mobile-screen size, etc.

**Screenshots**
![OSC-Responsive Issue](https://user-images.githubusercontent.com/56510414/115988665-60c56400-a5d8-11eb-9bfd-ea6b0166cb6f.JPG)
![OSC-Mobile-Responsive Issue](https://user-images.githubusercontent.com/56510414/115988669-64f18180-a5d8-11eb-9425-db0521e6184b.JPG)

I can fix this too
![OSC-Issue Fixed0](https://user-images.githubusercontent.com/56510414/115988680-6fac1680-a5d8-11eb-9b21-3d4b0ac95386.JPG)
![OSC-Issue Fixed](https://user-images.githubusercontent.com/56510414/115988683-733f9d80-a5d8-11eb-8b9c-948e135219c0.JPG)

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Yes

**Comment by Kajol-Kumari** [comment]
Hey @ShubhamSj07 thanks for pointing this issue. Just an add-on => in the screenshot of after-fix, I can see that the image is getting a bit cropped from right and bottom. Please consider that as well while fixing.
