### ISSUE TITLE
[Frontend] Enhancement in Forms

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#627]
Deliverables-
Currently, when any error message is shown, there is a shift in the ui, which doesn't look good. This issue is directed towards removing that ui shift in all the forms that have validations

Issue demonstration -
https://user-images.githubusercontent.com/44888949/115999525-bfef9c80-a609-11eb-80b8-17ed7191bf60.mov

**Comment by garvitgupta13** [comment]
Hey @Kajol-Kumari please assign this issue to me

**Comment by Kajol-Kumari** [comment]
Hey @garvitgupta13 please go ahead with this issue.
Happy Learning :)

**Comment by GuptaTanisha** [comment]
@Kajol-Kumari I have solved the issue.Please review it.

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari I have solved the issue.Please review it.

Hey @GuptaTanisha we don't accept the PRs for the issues that is already assigned to someone else. I request you to never work on an issue which is already assigned to someone unless the issue is open for more than one person.

**Comment by garvitgupta13** [comment]
Update:
I have started working on this issue and will be creating a PR as soon as the #629  merges.
