### ISSUE TITLE
Improving responsiveness of profile-cards on small screens

### ISSUE THREAD

**Issue by ShubhamSj07** [HITK-TECH-Community/Community-Website#630]
**Describe the bug**

**To Reproduce**
In about us section,
Profile cards are not responsive on small screen sizes 
They look like this
![Profile-Card-Issue](https://user-images.githubusercontent.com/56510414/116270121-71263c00-a79c-11eb-86b9-eb5819a4d16a.JPG)

I can fix this too
![Profile-Card-Issue-FIXED](https://user-images.githubusercontent.com/56510414/116270152-7a170d80-a79c-11eb-90fa-f3b22367c260.JPG)

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Yes

**Comment by Kajol-Kumari** [comment]
please go ahead @ShubhamSj07 :)
