### ISSUE TITLE
Minor Css Fix [admin-btn]

### ISSUE THREAD

**Issue by ShubhamSj07** [HITK-TECH-Community/Community-Website#634]
**Describe the bug**

**To Reproduce**
When we make screen-size _<1000px_, **admin btn**  is mess up!
![Btn-Issue-HITK](https://user-images.githubusercontent.com/56510414/116696010-f6992e80-a9de-11eb-9fb7-c16a50527c30.JPG)

I would like to fix this 
![Btn-Issue-HITK--FIXED](https://user-images.githubusercontent.com/56510414/116696076-0ca6ef00-a9df-11eb-89d4-88aa8d8aa030.JPG)

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Yes

**Comment by ShubhamSj07** [comment]
@Kajol-Kumari , pls review this

**Comment by jackfrost13** [comment]
Go Ahead
