### ISSUE TITLE
Dark Theme changes are not reflected in domains of join-us form

### ISSUE THREAD

**Issue by garvitgupta13** [HITK-TECH-Community/Community-Website#638]
**Describe the bug**
Dark theme changes are not reflected in multi-list input of the join-us form

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to join-us form
2. Switch to dark-theme
3. See an error

**Expected behavior**
![image](https://user-images.githubusercontent.com/70805691/117250919-8ddc0700-ae61-11eb-8b09-a483c06ff049.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/70805691/117250342-b44d7280-ae60-11eb-9c2d-50a170da4cda.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
These changes are reflected on my local system but not on the deployed one.

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
YES

**Comment by garvitgupta13** [comment]
Please assign me this issue

**Comment by Kajol-Kumari** [comment]
Hey @garvitgupta13 thanks for pointing this. Apart from the changes that you have attached in the screenshot, please make the theme of search-box  consistent with other input fields for the dark theme as well.

**Comment by garvitgupta13** [comment]
> Hey @garvitgupta13 thanks for pointing this. Apart from the changes that you have attached in the screenshot, please make the theme of search-box consistent with other input fields for the dark theme as well.

Hey, @Kajol-Kumari can you guide me on how to change the colour of that search bar in multi-list input field.
I was unable to find info related to that in [documentation](https://www.npmjs.com/package/react-multi-select-component) and I tried to inspect that element but I was unable to get any useful info from that.
