### ISSUE TITLE
[Frontend] Integrate Add FAQ Feature

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#639]
Integrate the add faq api with admin's add faq page. You can take reference from [here](https://github.com/HITK-TECH-Community/Community-Website/commit/e9eadfaa704d89e4cbba0f0476c617ab970291fa)

You can find this form at 
1. Login to admin panel
2. Go to faq tab
3. Click on add faq button

**Comment by garvitgupta13** [comment]
Please assign me this issue under `gssoc2021`

**Comment by Kajol-Kumari** [comment]
Please go ahead @garvitgupta13

**Comment by garvitgupta13** [comment]
The current form misses the tag field.
`Tags` is mentioned as a necessary field in backend documentation.
Please let me know which tag list should I add to the form.

**Comment by Kajol-Kumari** [comment]
Hey @garvitgupta13 we need to send the tags in the form of an array of strings so please make the input field of the same similar to the image given below
![WhatsApp Image 2021-05-06 at 8 13 21 PM (1)](https://user-images.githubusercontent.com/44888949/117319696-2d70b800-aea9-11eb-8879-5af56f25714e.jpeg)

**Comment by garvitgupta13** [comment]
> Hey @garvitgupta13 we need to send the tags in the form of an array of strings so please make the input field of the same similar to the image given below
> ![WhatsApp Image 2021-05-06 at 8 13 21 PM (1)](https://user-images.githubusercontent.com/44888949/117319696-2d70b800-aea9-11eb-8879-5af56f25714e.jpeg)

I just came across [this](https://leekevinyg.github.io/react-tag-input/)
Can we use this for taking input from users.

**Comment by Kajol-Kumari** [comment]
Hey @garvitgupta13 yeah we can use it in the form to take the input from user but I would request to look for promising package as this one doesn't seem to be that promising.

**Comment by Kajol-Kumari** [comment]
@garvitgupta13 can you please check [this](https://www.npmjs.com/package/react-tag-input) once as this seems promising and as per our requirement as well.

**Comment by garvitgupta13** [comment]
The current form validation involves the question and answer to be less than 8 characters. Should I change it ?
![image](https://user-images.githubusercontent.com/70805691/117403197-6cdcea00-af25-11eb-9245-f4635332edf2.png)

As mentioned in issue #538 minimum length should be of 8 characters, but the current implementation is of maximum length of 8 characters

**Comment by Kajol-Kumari** [comment]
Hey @garvitgupta13 thanks for pointing. The validation is supposed to be of min length of 8 chars so please change the same
