### ISSUE TITLE
[Frontend] Enhancement in Add Broadcast Page

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#640]
Deliverable-
1. The UI of the add broadcast page needs to be improved
2. The add broadcast form should contain the following fields -
 ```
 title: {
      type: String,
    },
    content: {
      type: String,
    },
    link: {
      type: String,
    },
    expiresOn: {
      type: Date,
    },
    imageUrl: {
      type: Array,
    },
    tags: {
      type: Array,
    }
```
The tag input field should be similar to the one given below 
![WhatsApp Image 2021-05-06 at 8 13 21 PM (1)](https://user-images.githubusercontent.com/44888949/117320041-7de81580-aea9-11eb-9ea6-5b6b8a57ee8a.jpeg)

**Comment by AbhipsaGuru1012** [comment]
@Kajol-Kumari can I try to work on this issue under GSSoC'21?

**Comment by Kajol-Kumari** [comment]
Sure @AbhipsaGuru1012 please go ahead with this issue.

**Comment by Kajol-Kumari** [comment]
> ![add_broadcast](https://user-images.githubusercontent.com/58511560/117566892-db14de80-b0d6-11eb-899f-19c4c2953ba3.PNG)
> 
> @Kajol-Kumari is this okay?

Hey @AbhipsaGuru1012 this looks preety good but we need to work on few points -
1. We need one `url` field that will contain the url of the resources. 
2. In content field, we wish to have markdown editor. Will it be possible to have atleast few of the features incorporated under `content` field?

**Comment by AbhipsaGuru1012** [comment]
@Kajol-Kumari sure, I will get back with the changes soon.

**Comment by Kajol-Kumari** [comment]
Hey @AbhipsaGuru1012 Please add bold and italic feature as well. Rest looks good to me :)

**Comment by AbhipsaGuru1012** [comment]
@Kajol-Kumari I have made a PR. Please review.
