### ISSUE TITLE
Navbar Theme-Toggler Issue

### ISSUE THREAD

**Issue by ShubhamSj07** [HITK-TECH-Community/Community-Website#642]
**Describe the bug**

**To Reproduce**
![HITK-Toggle-Issue](https://user-images.githubusercontent.com/56510414/117577097-082cb580-b106-11eb-94d8-84afdd49e4dd.JPG)

On mobile screen, when we open navbar & if user wants to swtich theme , clicks on toggler btn but user still stays  on navbar.
After switching theme navbar should be collasped!

I would like to fix 

https://user-images.githubusercontent.com/56510414/117577051-cc91eb80-b105-11eb-87ed-35bbe0109b23.mp4

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Yes

**Comment by Kajol-Kumari** [comment]
please go ahead @ShubhamSj07
