### ISSUE TITLE
[Frontend] Integrate Get Broadcasts with the backend

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#644]
Deliverable-
- Currently we are showing dummy data in `all broadcasts` page. Use [this](https://github.com/HITK-TECH-Community/Community-Website/commit/4183d0dc2eb40dccc4475f1d2fb3bda088a88c72) api to fetch the data from db and populate it on the frontend.

**Comment by Kajol-Kumari** [comment]
Sure @garvitgupta13 please go ahead!

**Comment by garvitgupta13** [comment]
> Deliverable-
> 
> * Currently we are showing dummy data in `all broadcasts` page. Use [this](https://github.com/HITK-TECH-Community/Community-Website/commit/4183d0dc2eb40dccc4475f1d2fb3bda088a88c72) api to fetch the data from db and populate it on the frontend.

In the API documentation mentioned here, I am unable to find any info related to the broadcast page. Please do have a look, and if there then please let me know.

**Comment by jackfrost13** [comment]
@garvitgupta13 I guess the wrong link was shared
Refer [this](https://github.com/HITK-TECH-Community/Community-Website/blob/main/backend/docs/broadcast.md)

Feel free to reach out to me if you face any issues wrt backend

**Comment by garvitgupta13** [comment]
> @garvitgupta13 I guess the wrong link was shared
> Refer [this](https://github.com/HITK-TECH-Community/Community-Website/blob/main/backend/docs/broadcast.md)
> 
> Feel free to reach out to me if you face any issues wrt backend

Thanks for the documentation @jackfrost13

**Comment by garvitgupta13** [comment]
Hey @jackfrost13 @KajalSinghBAGHEL I am unable to fetch data for broadcast page
![image](https://user-images.githubusercontent.com/70805691/118352234-f4f26d80-b57d-11eb-82ad-84fdc993bccd.png)
![image](https://user-images.githubusercontent.com/70805691/118352250-0471b680-b57e-11eb-89f0-5d3210de1af4.png)

I am just trying to log the response
 useEffect(() => {
    return fetch(`${END_POINT}/broadcast`, {
      method: "GET"
    })
      .then((response) => console.log(response))
      .catch((err) => {
        console.error("must be a backend problem🤔:", err);
      });
  }, []);

**Comment by jackfrost13** [comment]
It must not have been deployed to heroku
please use postman for testing or localhost

**Comment by garvitgupta13** [comment]
> It must not have been deployed to heroku
> please use postman for testing or localhost

My local backend is not opening.
Can you deploy these changes to Heroku

**Comment by garvitgupta13** [comment]
> It must not have been deployed to heroku
> please use postman for testing or localhost

Still getting the same
![image](https://user-images.githubusercontent.com/70805691/118355187-65a08680-b58c-11eb-81bf-452bab02a29c.png)

**Comment by Kajol-Kumari** [comment]
Hey @garvitgupta13 in order to get the broadcasts you need to provide the query params as well. like `/broadcast?page= &tags= &year= &month= [ GET ]`  Please refer [here](https://github.com/HITK-TECH-Community/Community-Website/blob/main/backend/docs/broadcast.md) for the same

**Comment by garvitgupta13** [comment]
> Hey @garvitgupta13 in order to get the broadcasts you need to provide the query params as well. like `/broadcast?page= &tags= &year= &month= [ GET ]` Please refer [here](https://github.com/HITK-TECH-Community/Community-Website/blob/main/backend/docs/broadcast.md) for the same

![image](https://user-images.githubusercontent.com/70805691/118356118-61c33300-b591-11eb-804b-78e7b8233f0c.png)
Since the following key params are optional I have not passed any value in them

**Comment by jackfrost13** [comment]
Please retry after pulling from main
Fixed the issue

**Comment by garvitgupta13** [comment]
> Please retry after pulling from main
> Fixed the issue

Thanks @jackfrost13 for fixing it, its working now
![image](https://user-images.githubusercontent.com/70805691/118364051-88469580-b5b4-11eb-94c2-501f2205bd0d.png)

**Comment by garvitgupta13** [comment]
On hitting the API `http://localhost:3500/broadcast`  or `http://localhost:3500/broadcast?page=1&tags=tag1&year=2021&month=1` I am getting a proper array
![image](https://user-images.githubusercontent.com/70805691/118366071-de1f3b80-b5bc-11eb-9e18-4f746b52f783.png)

But on hitting `http://localhost:3500/broadcast?page=&tags=&year=&month=` I am getting
```
{errorType: "Invalid or malformed request", statusCode: 400, message: ""page" must be a number, "tags" is not allowed to …"year" must be a number, "month" must be a number", user: "", errStack: ""page" must be a number, "tags" is not allowed to …"year" must be a number, "month" must be a number"}
errStack: "\"page\" must be a number, \"tags\" is not allowed to be empty, \"year\" must be a number, \"month\" must be a number"
errorType: "Invalid or malformed request"
message: "\"page\" must be a number, \"tags\" is not allowed to be empty, \"year\" must be a number, \"month\" must be a number"
statusCode: 400
user: ""
```
While in the documentation it is mentioned as optional param

![image](https://user-images.githubusercontent.com/70805691/118367057-7669f000-b5be-11eb-95da-eefc302d6b85.png)



Hey @jackfrost13 @Kajol-Kumari can you guys help me out how to handle this issue

**Comment by garvitgupta13** [comment]
> Deliverable-
> 
> * Currently we are showing dummy data in `all broadcasts` page. Use [this](https://github.com/HITK-TECH-Community/Community-Website/commit/4183d0dc2eb40dccc4475f1d2fb3bda088a88c72) api to fetch the data from db and populate it on the frontend.

I have added the broadcast to both the pages i.e `broadcast` and `all-broadcast` 
Please review my PR
