### ISSUE TITLE
local backend is unable to open

### ISSUE THREAD

**Issue by garvitgupta13** [HITK-TECH-Community/Community-Website#645]
**Describe the bug**
The backend throws error if we try to open it in our local system

**To Reproduce**
1. Go to backend folder
2. Type 'npm start'
3. See error

**Expected behavior**
It must run on localhost/3500

**Screenshots**
![image](https://user-images.githubusercontent.com/70805691/117668395-84d19980-b1c3-11eb-894f-294a282ca2f7.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Write your answer here.
YES

**Comment by jackfrost13** [comment]
Hey @garvitgupta13 I don't think so there is any issue from our end, please check once again
```bash
agaroh@147dda757d5b Community-Website % git log
commit 5be54b94168d06ae2b0df97b0c7f646081419e5f (HEAD -> main, origin/main, origin/HEAD)
Author: Rohit Agarwal <agaroh@amazon.com>
Date:   Mon May 10 16:36:18 2021 +0530

    fixes test cases

commit 32940616b2d848a4f8731d91aba2162e935c5670
Author: Garvit Gupta <garvitgupta2001@gmail.com>
Date:   Mon May 10 14:13:19 2021 +0530

    ♻️ Integrated [POST] FAQ (#641)
    
    * Add a success card on password change
    
    * Changed the styling of success card
    
    * Corrected the form validation
agaroh@147dda757d5b Community-Website % cd backend 
agaroh@147dda757d5b backend % npm start

> community-website@1.0.0 start
> node index.js

Starting app in non-cluster mode. (To start in cluster mode, pass CLUSTER=yes in config file)
Server running in development mode on port 3500 for worker 29111
Mongoose default connection open for worker 29111
```

**Comment by jackfrost13** [comment]
Also please tag us if you find any issues to get a promt response

**Comment by garvitgupta13** [comment]
> Also please tag/assign us if you find any issues to get a promt response

Hey @jackfrost13 I just pulled the latest commits and ran the backend server but still got the same
![image](https://user-images.githubusercontent.com/70805691/118323261-f8560c80-b51d-11eb-8968-c54f86d82443.png)
I guess the error is due to syntax error at line 35 of [getBrodcast.js](https://github.com/HITK-TECH-Community/Community-Website/blob/main/backend/app/routes/broadcast/getBroadcasts.js)
![image](https://user-images.githubusercontent.com/70805691/118323362-1e7bac80-b51e-11eb-9cc6-fbb21304416b.png)
If I am wrong please correct me

**Comment by jackfrost13** [comment]
umm I dont think so that is the latest commit, can you check once? I had disabled clustering in the lastest commit on main

**Comment by garvitgupta13** [comment]
> umm I dont think so that is the latest commit, can you check once? I had disabled clustering in the lastest commit on main

![image](https://user-images.githubusercontent.com/70805691/118354614-74396e80-b589-11eb-9460-1c59268505fb.png)

**Comment by garvitgupta13** [comment]
Hey @jackfrost13 I made changes in line35 and my localhost was opening 
![image](https://user-images.githubusercontent.com/70805691/118354961-3f2e1b80-b58b-11eb-8ce0-238935080f31.png)
![image](https://user-images.githubusercontent.com/70805691/118354975-49e8b080-b58b-11eb-8890-08eb1012075f.png)
Should I push these changes

**Comment by jackfrost13** [comment]
can you share your gitlog? For me it is working at the HEAD commit

**Comment by garvitgupta13** [comment]
> can you share your gitlog? For me it is working at the HEAD commit

```
commit 1da3cd9634253b6d560596013738e923b834ab99 (HEAD -> main, origin/main, origin/HEAD, brodcast-page)
Merge: ea60d47 5be54b9
Author: Garvit Gupta <garvitgupta2001@gmail.com>
Date:   Sat May 15 01:32:08 2021 +0530

    Merge branch 'HITK-TECH-Community:main' into main

commit 5be54b94168d06ae2b0df97b0c7f646081419e5f (upstream/main)
Author: Rohit Agarwal <agaroh@amazon.com>
Date:   Mon May 10 16:36:18 2021 +0530

    fixes test cases

commit ea60d47790a991df06b7ba9b477e216679e5973e
Merge: 70c33f4 3294061
Author: Garvit Gupta <garvitgupta2001@gmail.com>
Date:   Mon May 10 15:49:43 2021 +0530

    Merge branch 'HITK-TECH-Community:main' into main

commit 32940616b2d848a4f8731d91aba2162e935c5670
Author: Garvit Gupta <garvitgupta2001@gmail.com>
Date:   Mon May 10 14:13:19 2021 +0530

    <E2><99><BB><EF><B8><8F> Integrated [POST] FAQ (#641)

    * Add a success card on password change

    * Changed the styling of success card
:...skipping...
commit 1da3cd9634253b6d560596013738e923b834ab99 (HEAD -> main, origin/main, origin/HEAD, brodcast-page)
Merge: ea60d47 5be54b9
Author: Garvit Gupta <garvitgupta2001@gmail.com>
Date:   Sat May 15 01:32:08 2021 +0530

    Merge branch 'HITK-TECH-Community:main' into main

commit 5be54b94168d06ae2b0df97b0c7f646081419e5f (upstream/main)
Author: Rohit Agarwal <agaroh@amazon.com>
Date:   Mon May 10 16:36:18 2021 +0530

    fixes test cases

commit ea60d47790a991df06b7ba9b477e216679e5973e
Merge: 70c33f4 3294061
Author: Garvit Gupta <garvitgupta2001@gmail.com>
Date:   Mon May 10 15:49:43 2021 +0530

    Merge branch 'HITK-TECH-Community:main' into main

commit 32940616b2d848a4f8731d91aba2162e935c5670
Author: Garvit Gupta <garvitgupta2001@gmail.com>
Date:   Mon May 10 14:13:19 2021 +0530

    <E2><99><BB><EF><B8><8F> Integrated [POST] FAQ (#641)

    * Add a success card on password change

    * Changed the styling of success card

    * Corrected the form validation

    * Removed the warnings

    * Intergrated the faq api with backend

    * enhanced the styling of tags and form

commit 4183d0dc2eb40dccc4475f1d2fb3bda088a88c72
Author: Aadarsh <heyitsaadarsh@gmail.com>
Date:   Sun May 9 22:42:10 2021 +0530

    [Backend] Reset Password feature added (#479) (#487)

    * [Backend] Reset Password feature added (#479)

    * Adding /admin/forgotpassoword to the response URL

    * <F0><9F><8D><81> Minor Fix

    * <F0><9F><8C><BB> Footer Link Issue Resolved (#489)

    * Update slack link

    * Adding /forgotpassword/:token route logic and resolving PR reviews
   ```

**Comment by jackfrost13** [comment]
checkout `5be54b94168d06ae2b0df97b0c7f646081419e5f ` commit and try running

**Comment by garvitgupta13** [comment]
> checkout `5be54b94168d06ae2b0df97b0c7f646081419e5f ` commit and try running

```
PS E:\Community-Website\backend> git checkout 5be54b94168d06ae2b0df97b0c7f646081419e5f
HEAD is now at 5be54b9 fixes test cases
M       frontend/.env
M       frontend/package-lock.json
M       frontend/src/pages/Broadcast/Component/AllBroadcasts/AllBroadcasts.jsx
PS E:\Community-Website\backend> npm start

> community-website@1.0.0 start E:\Community-Website\backend
> node index.js

Starting app in non-cluster mode. (To start in cluster mode, pass CLUSTER=yes in config file)
E:\Community-Website\backend\app\routes\broadcast\getBroadcasts.js:35
  const tags = req.query.tags?.split(',');
                              ^

SyntaxError: Unexpected token '.'
```

Still getting the same

**Comment by garvitgupta13** [comment]
Sir I think we should close this issue as it seems to be a problem in my system only
And I am also able to run localhost after fixing line 35 of getBroadcast.js

But I think there is a syntax error in line 35
`req.query.tags?.split(',');`
The ? in tags is not acting like a ternary operator it should be
`const tags = req.query.tags?req.query.tags.split(','):null;`

Please correct me if I am wrong

**Comment by jackfrost13** [comment]
Hey, no that is not the ternary operator
look for null check in js
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator#relationship_with_the_optional_chaining_operator_.

**Comment by garvitgupta13** [comment]
> Hey, no that is not the ternary operator
> look for null check in js
> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator#relationship_with_the_optional_chaining_operator_.

Thanks for clarifying, I was really unaware of it

**Comment by garvitgupta13** [comment]
I guess we should close this issue this null operator is for node version `14` above and I am using node `12.16.2`

**Comment by jackfrost13** [comment]
Even I am perplexed, maycheck your software versions
