### ISSUE TITLE
Adding floating animation to the svg on the side of contact us form.

### ISSUE THREAD

**Issue by Shivangi-ch** [HITK-TECH-Community/Community-Website#648]
**Is your feature request related to a problem? Please describe.**
No 
**Describe the solution you'd like**
I would like to add the floating animation to the svg on the contact us page.This will make the page look attractive.

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Yes.

**Comment by Shivangi-ch** [comment]
@Kajol-Kumari Please assign this to me.
Demo:
![Hnet-imagesdf](https://user-images.githubusercontent.com/57783826/117811437-2d443400-b27e-11eb-9934-8b682e5e9451.gif)

**Comment by Kajol-Kumari** [comment]
Hey @Shivangi-ch thank you very much for your suggestion but we want our website to look consistent and simple and have no plan to modify our pages UI anymore.
