### ISSUE TITLE
Year in footer

### ISSUE THREAD

**Issue by garvitgupta13** [HITK-TECH-Community/Community-Website#653]
**Describe the bug**
The year inside footer is static

**To Reproduce**

**Screenshots**
![image](https://user-images.githubusercontent.com/70805691/119037782-08fbfc00-b9d0-11eb-967b-b242085a7ee7.png)
**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
YES

**Comment by garvitgupta13** [comment]
@jackfrost13 @Kajol-Kumari, please look at this issue

**Comment by garvitgupta13** [comment]
As per `gssoc21` the `level0` and `level1` tags is for documentation related issues.
![image](https://user-images.githubusercontent.com/70805691/118633501-2e7ddf80-b7ef-11eb-973c-9be27aec3159.png)

**Comment by jackfrost13** [comment]
Those are just sample labels, it has been left configurable by project admins and mentors
If a person is working on entire project documentation that doesn't mean his work is less valuable or anything like that. Hence we decide as per the issue. This involves a very simple fix hence level0
