### ISSUE TITLE
[Frontend] Integrate the Delete Broadcast Feature from Backend

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#660]
Deliverable -

- [ ]  The integration of delete broadcast feature with the backend

- [ ]  A message showing `No Broadcast Found!` should be displayed on the `All Broadcast` and in each section `Broadcasts` page if there isn't any broadcast available.

Ref - The deleteBroadcast api can be found [here](https://github.com/HITK-TECH-Community/Community-Website/blob/main/backend/app/routes/broadcast/deleteBroadcast.js)

**Comment by rockingrohit9639** [comment]
@Kajol-Kumari I would like to work on this issue.

**Comment by Kajol-Kumari** [comment]
@rockingrohit9639 please go ahead with this issue.
Happy Learning :)

**Comment by Kajol-Kumari** [comment]
@rockingrohit9639 please update on this issue.

**Comment by AdnanMuzavor** [comment]
Hey @Kajol-Kumari ,if this issue is still available then I would like to work on it.

**Comment by Kajol-Kumari** [comment]
Closing this one as this has already been implemented
