### ISSUE TITLE
Join Us Form data is not submitting to dataBase

### ISSUE THREAD

**Issue by VenomFate-619** [HITK-TECH-Community/Community-Website#661]
**Describe the bug**
Join Us Form page form data is not submitting to dataBase

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'https://hitk-tech-community.netlify.app/join-us-form'
2. Fill the form
3. Click the submit button
4. No notification for ensuring that data is submitted

**Expected behaviour**
Data should be submitted to an endpoint of backend and a notification should be there

**Screenshots**
on Line number 94 form data is logged
![image](https://user-images.githubusercontent.com/67755128/120753214-765b7100-c528-11eb-8298-dde19c804541.png)

**Desktop (please complete the following information):**
 - OS: Win
 - Browser Edge
 - Version  91.0.864.37

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Write your answer here.
Yes

**Comment by Kajol-Kumari** [comment]
Hey @VenomFate-619 did you tested this on local? As we haven't updated our backend on the hosted url so you might not be able to see this feature on our hostel url

**Comment by VenomFate-619** [comment]
@Kajol-Kumari nope haven't tested locally , I will test it and info it
