### ISSUE TITLE
[Frontend] 🐛  Bug : Scroll Preserve on route change

### ISSUE THREAD

**Issue by kushal98** [HITK-TECH-Community/Community-Website#662]
**Describe the bug**
When a user navigates from one route to the other the browser is preserving the scroll.

**To Reproduce**
Steps to reproduce the behaviour:

1. After landing into home page, scroll down a bit.
2. Click on About Us or any other navigation option.
3. The scroll gets preserved.

**Expected behaviour**
On change of the route the user should be landed on the top of the page instead of the preserved scroll

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser - chrome

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Yes

**Comment by kushal98** [comment]
Please assign this to me.

**Comment by Kajol-Kumari** [comment]
@kushal98 please go ahead 👍

**Comment by CodingwithMe123** [comment]
Is the bug still active? If yes, I can contribute
