### ISSUE TITLE
[Bug] Broadcast Page giving error on Prod

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#667]
Description-
Currently, if you try to visit the broadcast page i.e https://hitk-tech-community.netlify.app/broadcasts for the second time, the site didn't open up.

Requirement-
Fix the above described bug

**Comment by Anurag-Singh-Rajput** [comment]
Hey There,
Can I work on this ? I am a SWOC Participant

**Comment by Kajol-Kumari** [comment]
Sure @Anurag-Singh-Rajput please go ahead. 
Happy Learning :)
