### ISSUE TITLE
[Backend] Add Delete & Get Faq Api

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#668]
Deliverables-

- [ ] Api for DELETE a single FAQ [Note -only admin should be privileged to perform this]
- [ ] Api for getting all the FAQs 

Note - the APIs should be added under [this](https://github.com/HITK-TECH-Community/Community-Website/tree/main/backend/app/routes/faq) folder

**Comment by naveen8801** [comment]
Hey @Kajol-Kumari, I'd like to work on it, please assign :)

**Comment by Kajol-Kumari** [comment]
> Hey @Kajol-Kumari, I'd like to work on it, please assign :)

sure @naveen8801 please go ahead..
Happy Learning :)

**Comment by naveen8801** [comment]
Hi @Kajol-Kumari, actually am getting 400 status when am trying to login as admin with the credentials :-

```
{
    "email" : "admin@gmail.com",
    "password" : "check"
}

```

can you please check them again for me :)

**Comment by Kajol-Kumari** [comment]
Hey @naveen8801 Please use the below credential for logging in -

```
{
    "email" : "hitkadmin@gmail.com",
    "password" : "password"
}
```

**Comment by naveen8801** [comment]
hii @Kajol-Kumari, can you please explain how we are identifying admins inside the database, specifically for delete faq endpoint what should be the body or payload from the client while making req to this endpoint.

**Comment by Kajol-Kumari** [comment]
@naveen8801 as only admins need to log in so you can just keep the payload like
```
{
 user_id
faq_id
}
```

Check if user_id is present in admin collection and if yes, then find if the faq with given id is present in the db . If both of them satisfies, delete that faq from db.

**Comment by naveen8801** [comment]
@Kajol-Kumari , please provide a admin id for testing purpose :)

**Comment by Kajol-Kumari** [comment]
@naveen8801 please use any of the below admin ids for testing -
```
"_id":{"$oid":"606603ff2af446983ad258fa"}
"_id":{"$oid":"606043a028ae3040567de390"}
```

**Comment by naveen8801** [comment]
Hi @Kajol-Kumari , i have made a PR for this issue, please review :)
