### ISSUE TITLE
[Frontend] Add Loader to the Page

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#670]
**Problem-**
The data on the broadcast page gets populated after 2-3 seconds which makes the page looks bad.

**Solution-**
Add loader till the data is being fetched via API and populated on the page so that the page should get rendered only after all the data gets populated.

Note - Please make sure to make this loader a reusable component so that we can use it for other pages as well

**Comment by Anurag-Singh-Rajput** [comment]
I would like to work on this . Also can you add Swoc label

**Comment by Kajol-Kumari** [comment]
sure @Anurag-Singh-Rajput please go ahead with this issue.
