### ISSUE TITLE
[Backend] Add Contact Us Form route 

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#671]
Create a route for storing contact us form data.
Post storage send an email to the existing admins about it. (Using our email service)

Public API
Requires API Testing.
Refer #81 For API Testing resources.

Ref PR - https://github.com/HITK-TECH-Community/Community-Website/pull/580

**Comment by tejasvi541** [comment]
Hey @Kajol-Kumari , can I work on this issue?

**Comment by Kajol-Kumari** [comment]
@tejasvi541 can I please get an update on this issue?

**Comment by tejasvi541** [comment]
Hey @Kajol-Kumari , I have implemented the storing of contact us data, just testing with the send-grid right now for sending emails to admins.
