### ISSUE TITLE
[Frontend] Add FQA Redirects to Dashboard

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#672]
Description-
Currently if we log in as admin and try to add an faq, it directs us to admin dashboard.

Deliverable -
Fix it so that it works as expected

**Comment by kanthalaHarivardhanReddy** [comment]
hey @Kajol-Kumari ,
I would like to work on this issue please assign it to me

**Comment by Kajol-Kumari** [comment]
@kanthalaHarivardhanReddy please go ahead with this issue.. 

Happy Learning :)

**Comment by Kajol-Kumari** [comment]
@kanthalaHarivardhanReddy Please provide the update for this issue?

**Comment by kanthalaHarivardhanReddy** [comment]
I was busy @Kajol-Kumari I will work on it in this weekend and I will be making a pr before the weekend

**Comment by kanthalaHarivardhanReddy** [comment]
hey @Kajol-Kumari ,
after successful submission of FAQ
do you want me to redirect it to the main Dashboard?

**Comment by Kajol-Kumari** [comment]
@kanthalaHarivardhanReddy after we click on `add faq` card present in the admin dashboard , it should direct to the add faq page. And after successful submit of the add-faq form, it should just reset the form

**Comment by kanthalaHarivardhanReddy** [comment]
It is already reseting @Kajol-Kumari mam, after a successful submission of the add faq form

**Comment by Kajol-Kumari** [comment]
> It is already reseting @Kajol-Kumari mam, after a successful submission of the add faq form

Seems like it's been fixed now. We no more need this issue. Thanks for looking into it. I will open new issues very soon.
