### ISSUE TITLE
[Backend] Join Us Form [Post] 

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#674]
Deliverables-

- [ ] Make the api to store the Join Us Form data. Below are the requirements for the same-
- It should be a POST request
- It should be a public api i.e doesn't require any authentication 
- Notify admins i.e As soon as we store the data in database, send email to the Admins

**Comment by naveen8801** [comment]
Hi @Kajol-Kumari, i'd like to work on it, please assign :)

**Comment by Kajol-Kumari** [comment]
sure @naveen8801 Please go ahead 👍 

Happy Learning  :)
