### ISSUE TITLE
[Frontend+Backend] Make the Manage FAQ Page

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#677]
Deliverables-

- [ ] clicking on `Manage FAQ` card should take to a new page having the list of the faqs in card/expandible[similar to [here](https://hitk-tech-community.netlify.app/faqs) ]
- [ ] The list of FAQs should be fetched from [get-faq-api](https://hitk-tech-community.netlify.app/faqs)

Follow below steps to see the manage faq card-
1. Login as admin using the credentials provided in the project readme file
2. Click on Faq section/card
3. Click on `Manage Faq` card [Here you need to start the work]

Ref pr - https://github.com/HITK-TECH-Community/Community-Website/pull/764

**Comment by naveen8801** [comment]
Hi @Kajol-Kumari, I want to take this one, can you please assign it to me :D

**Comment by Kajol-Kumari** [comment]
Please go ahead with this issue @naveen8801 

Happy Learning :)

**Comment by Kajol-Kumari** [comment]
@naveen8801 can I please get an update on this?

**Comment by naveen8801** [comment]
Hi @Kajol-Kumari , unassigning myself , focusing somewhere else :)

**Comment by ritikakhandelwal-17** [comment]
I would like to work on the issue under GSSOC22.

**Comment by Kajol-Kumari** [comment]
@ritikakhandelwal-17 please go ahead with this issue and let me know if you need any clarifications.

Happy Learning :)

**Comment by ritikakhandelwal-17** [comment]
@Kajol-Kumari I am getting several unresolvable errors which running "npm install" command .

![Screenshot (535)](https://user-images.githubusercontent.com/83296933/157725535-1c882e34-5e26-434b-8f2f-955e49b3b9b0.png)

**Comment by Kajol-Kumari** [comment]
@ritikakhandelwal-17 please refer https://stackoverflow.com/questions/45801457/node-js-python-not-found-exception-due-to-node-sass-and-node-gyp this and see if following the steps given inhere helps you

**Comment by Kajol-Kumari** [comment]
@ritikakhandelwal-17 Can you please update on this issue?

**Comment by Aman16-ai** [comment]
I want to work on this issue.

**Comment by Kajol-Kumari** [comment]
> I want to work on this issue.

Please go ahead @Aman16-ai
