### ISSUE TITLE
[Frontend] Integrate GET FAQ with Backend

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#678]
Deliverables-

- [ ] The FQAs on https://hitk-tech-community.netlify.app/faqs page should come from backend using [get-faq](https://hitk-tech-community.netlify.app/faqs) API

**Comment by amanbedi1** [comment]
Could you assign it to me

**Comment by Kajol-Kumari** [comment]
Sure @amanbedi1 please go ahead with this issue. 

Happy Learning :)
