### ISSUE TITLE
[Backend] Integrate Delete Faq with Backend

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#679]
Deliverables-

- [ ] Have an icon/button for each Faq present on the Manage FAQs Page and clicking the same should use the [DELETE API](https://github.com/HITK-TECH-Community/Community-Website/blob/main/backend/app/routes/faq/deleteFaq.js) to remove the data from backend. 
- [ ] There should be a toast showing `Faq deleted successfully` after successful deletion and should show proper message if the deletion fails

NOTE-

- This issue depends on [Issue-677](https://github.com/HITK-TECH-Community/Community-Website/issues/677)

**Comment by hazemessam** [comment]
I want to work on this issue.

**Comment by Kushal-2002** [comment]
I am a GSSOC'22 participant, please assign me to this issue.

**Comment by ritikakhandelwal-17** [comment]
I want to work on this issue, Can you please assign it to me under GSSOC22.

**Comment by lokita282** [comment]
I would like to work on this issue under GSSOC '22

**Comment by Kajol-Kumari** [comment]
Hello @hazemessam please go ahead with this issue.

**Comment by hazemessam** [comment]
@Kajol-Kumari 
Sorry I was thinking that it is a backend task.
Please, unassign me and assign it to a frontend dev

**Comment by Kajol-Kumari** [comment]
@Kushal-2002 are you willing to working this issue?

**Comment by Kushal-2002** [comment]
@Kajol-Kumari yes definitely please assign me.

**Comment by Kajol-Kumari** [comment]
@Kushal-2002 can I please get an update on this issue?

**Comment by Kushal-2002** [comment]
Hi @Kajol-Kumari I am unassigning myself as I have not been able to find a solution to this problem in the issue.

**Comment by Bhawna147** [comment]
hey, @Kajol-Kumari I am a GSSOC'22 participant, please assign me to this issue.

**Comment by Kajol-Kumari** [comment]
@Bhawna147 please go ahead with this issue.

Happy Learning :)

**Comment by AdnanMuzavor** [comment]
Hey @Kajol-Kumari , I found that this issue is not yet been fixed so I would like to take up this one.

**Comment by Trisha-tech** [comment]
Hello @Kajol-Kumari, I would like to work on this issue under JWOC 2023.

**Comment by Anand930singh** [comment]
Can I work on this issue?

**Comment by Kajol-Kumari** [comment]
@Anand930singh  please go ahead with this issue. Just make sure to provide an update on the progress within 1 week.
Happy Learning :)

**Comment by WYGIN** [comment]
I will work on this issue :)

**Comment by Kajol-Kumari** [comment]
@WYGIN  Sure, please go ahead, Happy Learning :)

**Comment by WYGIN** [comment]
@Kajol-Kumari the [DELETE API](https://github.com/HITK-TECH-Community/Community-Website/blob/main/backend/app/routes/faq/DeleteFaq.js) no more exists!

**Comment by Kajol-Kumari** [comment]
Hey @WYGIN  you can find it here - https://github.com/HITK-TECH-Community/Community-Website/blob/main/backend/app/routes/faq/deleteFaq.js

**Comment by WYGIN** [comment]
> @WYGIN can you update the status of this issue?

I am currently not available to work, please assign it to someone else if anyone is interested.

**Comment by SwayamRana808** [comment]
please assign me this issue as GGSoc '24
