### ISSUE TITLE
[Backend] GET API for Join Us

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#680]
- [ ] Make the api to store the Join Us Form data. Below are the requirements for the same-

- It should be a GET request
- It should only be accessible to the admins only i.e requires the auth check

Note - This issue depend on [issue-674](https://github.com/HITK-TECH-Community/Community-Website/issues/674) issue

**Comment by amanbedi1** [comment]
I like to work on can you assign me this issue

**Comment by AbhipsaGuru1012** [comment]
> I like to work on this can you assign me.



> I like to work on this can you assign me.

@amanbedi1 sure, please go ahead

**Comment by amanbedi1** [comment]
If I am correct there is no model (schema) and API endpoints  for storing data of join us form in database so there is no point of making GET endpoint before implementing POST endpoint of Join Us data and connecting it to frontend. If possible I can implement POST functionality also revert back to it.

**Comment by Kajol-Kumari** [comment]
Hey @amanbedi1 as mentioned in the issue description that this issue is dependent on #674 so I request you to please wait for it PR as it will be completed in 1-2 days and after that you can implement this one. Meanwhile you can look for other issues that are `up-for-grab`

**Comment by Kajol-Kumari** [comment]
@amanbedi1 now you can work on this issue as the POST api has been created for the same.

**Comment by amanbedi1** [comment]
Sure

**Comment by amanbedi1** [comment]
@Kajol-Kumari since GET join us will only be used by admin so it's route would be  ```/admin/getJoinUs``` or some thing else

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari since GET join us will only be used by admin so it's route would be `/admin/getJoinUs` or some thing else

@amanbedi1 you can keep the route as `/joinUs` only just change the type from `POST` to `GET` along with adding the check for admin. Please note that you will be provided the admin_id for checking the same.

**Comment by amanbedi1** [comment]
Thank you for clarifying @Kajol-Kumari.

**Comment by arinmodi** [comment]
can I work on this, if anyone is not working on it ?

**Comment by hazemessam** [comment]
I want to work on it under GSSoC'22

**Comment by Kajol-Kumari** [comment]
@hazemessam please go ahead with this issue.
Happy Learning :)

**Comment by hazemessam** [comment]
Thanks, I will start working on it from 1 Mar.

**Comment by yogitasaini** [comment]
Please assign this issue to me

**Comment by hazemessam** [comment]
> Please assign this issue to me

I will work on it today

**Comment by hazemessam** [comment]
@Kajol-Kumari
I have 3 questions

1. Do you want to get all join us records or get a specific record by its id or both?
2. In case you want to get a specific record which format do you prefer?
    1. `GET /joinus/id`
    2. `GET /joinus?id={id}`
3. How to know that the given token belongs to an admin, not just a logged in user?

**Comment by Kajol-Kumari** [comment]
Hi @hazemessam  
1. Only admin is allowed to login to the website so if you receive a token, you can just decode it and verify it using a db call that whether it's an admin or not
2. As of now, we just need  the api to get all the join us record at once.
