### ISSUE TITLE
[Backend] Join Us DELETE using Cron Job API

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#681]
Deliverable-

- [ ] we need a cron job for deleting the join us form data from db periodically after 60days

Note- Make the cron job reusable as we will need it for other apis

**Comment by naveen8801** [comment]
Hi @Kajol-Kumari , can i work on this one please

**Comment by Kajol-Kumari** [comment]
@naveen8801 sure..please go ahead with this issue :)
