### ISSUE TITLE
[Frontend] Make the Manage Broadcast page of Admin Dashboard

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#682]
Deliverables-

- [ ] The `Manage Broadcast` card should take us to a new page containing the list of of broadcasts fetched from backend in the card form. [Ysimilar to https://hitk-tech-community.netlify.app/all-broadcasts page]
- [ ] Each card should have a delete icon which should call the [delete-brodcast-api](https://github.com/HITK-TECH-Community/Community-Website/blob/main/backend/app/routes/broadcast/deleteBroadcast.js)

**Comment by kanthalaHarivardhanReddy** [comment]
Please assign it to me,
I want to work upon this issue

**Comment by Kajol-Kumari** [comment]
@kanthalaHarivardhanReddy please go ahead with this issue.
Just pre-requisite knowledge-
Login to admin dashboard using below credentials-
```
 {
    "email" : "hitktechcommunity@gmail.com",
    "password" : "password"
}
```
Then you would be able to see the `Manage Broadcasts` card on the Admin Dashboard . Please let me know incase you face any issue.

Happy Learning :)

**Comment by kanthalaHarivardhanReddy** [comment]
Hey, @Kajol-Kumari 
I could not able to login as an admin
When I enter the credentials it is showing invalid username and password. I have rechecked the ID and password. Can you help me?

**Comment by Kajol-Kumari** [comment]
@kanthalaHarivardhanReddy please try below credentials once and let me know incase u face any issue-
```
{
    "email" : "kajolkumarisingh222@gmail.com",
    "password" : "password"
}
```

**Comment by kanthalaHarivardhanReddy** [comment]
Yes @Kajol-Kumari mam, the credentials are valid

**Comment by kanthalaHarivardhanReddy** [comment]
@Kajol-Kumari mam also update on 
README.md file - Testing credentials

**Comment by Kajol-Kumari** [comment]
@kanthalaHarivardhanReddy please provide an update for this issue.

**Comment by kanthalaHarivardhanReddy** [comment]
Sorry to tell you @Kajol-Kumari I'm not able to do it as it was more complex than I thought. 
please Apologize me and unassign me this issue.

**Comment by Aniket-508** [comment]
@Kajol-Kumari I want to work on this issue under JWoC.
