### ISSUE TITLE
[Frontend] enhancement in All Broadcast Page

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#683]
Deliverables-

- [ ] Each card should have the month and year of the broadcast at the end of of each card
- [ ] The search should take place correctly based on the title of the broadcast [It's not working as expected rn]

All Broadcasts Page - https://hitk-tech-community.netlify.app/all-broadcasts

**Comment by SarveshLimaye** [comment]
@Kajol-Kumari would like to work on this issue

**Comment by Kajol-Kumari** [comment]
@SarveshLimaye please go ahead with this issue.

Happy Learning :)
