### ISSUE TITLE
[Frontend] Enhancement in All Broadcasts Page

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#684]
Deliverables-

- [ ] Integrate the feature of `filter by month` and `filter by year` 
- [ ] Selected month and year should be visible to the user

All Broadcasts Page - https://hitk-tech-community.netlify.app/all-broadcasts

**Comment by Anurag-Singh-Rajput** [comment]
Hey @Kajol-Kumari , I would like to work on this

**Comment by AbhipsaGuru1012** [comment]
> Hey @Kajol-Kumari , I would like to work on this

Sure, please go ahead @Anurag-Singh-Rajput

**Comment by Anurag-Singh-Rajput** [comment]
Hey @AbhipsaGuru1012, Please see the attached video

https://user-images.githubusercontent.com/72293742/147817300-4250f798-1640-48da-b0ab-dceac57ead5c.mp4

**Comment by Kajol-Kumari** [comment]
@Anurag-Singh-Rajput please feel free to raise the PR so that we can test the functionality end-to-end

**Comment by Anurag-Singh-Rajput** [comment]
> @Anurag-Singh-Rajput please feel free to raise the PR so that we can test the functionality end-to-end

Done
