### ISSUE TITLE
backend(community user model and routes)

### ISSUE THREAD

**Issue by mak-ux** [HITK-TECH-Community/Community-Website#69]
We must have a community user model and respected routes so that we can fix functionality we are going to provide for a particular user in our community.Isn't It?

**Comment by Kajol-Kumari** [comment]
Hey @mak-ux thanks for reporting this, we were working on it for a while and now the backend basic structure is ready. Soon we will be opening up other backend related issues, till then I am closing this PR

**Comment by mak-ux** [comment]
Great thanks for updating otherwise I was working on authentication part. 
If user structure is ready than let me work on other part. 
Thank you

**Comment by Kajol-Kumari** [comment]
> Great thanks for updating otherwise I was working on authentication part.
> If user structure is ready than let me work on other part.
> Thank you

Hey @mak-ux we won't have any user login/signup instead there would just be admin/login option available and we have already added the required authentication for the same. So I would request you to not start working until we open up the issues for the same.

**Comment by mak-ux** [comment]
Ok
