### ISSUE TITLE
[Frontend] Integrate Join Us Form with backend

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#690]
Deliverable-

- [ ] On submit of the form, the join us api should be called[Make sure you handle errors properly]
- [ ] A success/error toast bar should be displayed accordingly withe message of `Form submitted successfully!` and `Something went wrong` respectively
- [ ] A card saying `Hello There! Your request is in process, we will get back to you soon!` should appear after successful submission. [Take reference of contact-us page for this card]

Join Us Post API -[here]( https://github.com/HITK-TECH-Community/Community-Website/blob/main/backend/app/routes/joinUs/post.js )

Join Us Page - [here](https://hitk-tech-community.netlify.app/join-us-form)

Message Card Sample-
<img width="568" alt="Screenshot 2022-01-03 at 3 52 52 PM" src="https://user-images.githubusercontent.com/44888949/147920210-38a1bc20-7229-4568-a5d8-ac5f815cc4a9.png">

**Comment by aashimawadhwa** [comment]
I am willing to work on this issue please assign it to me ,

**Comment by Kajol-Kumari** [comment]
@aashimawadhwa please go ahead with this issue. 

Happy Learning :)

**Comment by Kajol-Kumari** [comment]
@aashimawadhwa can I please get an update on this issue?

**Comment by sulogna2001** [comment]
Hey Can you assign me this issue for GSsoc22

**Comment by sagnik2001** [comment]
Can I work on this under GSSoC 22

**Comment by haider000** [comment]
Hey, I am interested to work on this issue under GSSoc 2022, can you assign me this issue?

**Comment by Kajol-Kumari** [comment]
@sulogna2001 please go ahead with this issue.

Happy Learning :)

**Comment by mayank-del** [comment]
@Kajol-Kumari  can i work under this issue under gssoc 22?

**Comment by Kajol-Kumari** [comment]
@sagnik2001 @haider000 are you still willing to work on this issue. If yes, please confirm it, else I will assign it to Mayank

**Comment by mayank-del** [comment]
> @sagnik2001 @haider000 are you still willing to work on this issue. If yes, please confirm it, else I will assign it to Mayank

Yes please assign me this under gssoc22

**Comment by mayank-del** [comment]
@Kajol-Kumari , assign it to to me , i will also try

**Comment by deepbeatz** [comment]
@himanshu1221  i want to work in this issue under JWOC

**Comment by Kajol-Kumari** [comment]
@deepbeatz  please go ahead with this issue and keep us posted on the update

**Comment by Kajol-Kumari** [comment]
@avinasharex if you are working on it, please open a draft pr and keep on updating so that i remain aware of the progress

**Comment by Swapnil-Bhatnagar** [comment]
Please assign this issue to me. I want to work on this

**Comment by Kajol-Kumari** [comment]
@Swapnil-Bhatnagar please go ahead with this issue.

Happy Learning :)

**Comment by Swapnil-Bhatnagar** [comment]
> @Swapnil-Bhatnagar please go ahead with this issue.
> 
> Happy Learning :)

Thanks for assigning will update u soon @Kajol-Kumari

**Comment by Kajol-Kumari** [comment]
@Swapnil-Bhatnagar can you please update on this issue?

**Comment by Swapnil-Bhatnagar** [comment]
Yes mam,Working on it sorry for the delay due to my sem exams. Will update
you soon

**Comment by BHS-Harish** [comment]
Hello @Kajol-Kumari 

Assign me the issue 
Let me fix it
