### ISSUE TITLE
[Backend] Add API for Resource Sharing POST operation

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#694]
Deliverable -

- [ ] Create a route for storing resource sharing form data. [ https://hitk-tech-community.netlify.app/resources ]
- [ ] Post storage send an email to the existing admins about it. (Using our email service)
      - Public API
      - Requires API Testing.

- Refer #81 For API Testing resources.

Ref PR - #686

**Comment by Devmindtk** [comment]
I would like to work on this issue. Please assigned it to me and please explain once the issue.
Thank you.

**Comment by Kajol-Kumari** [comment]
Hi @Devmindtk we want to make an api which will store all the data of [this](https://hitk-tech-community.netlify.app/resources) form in the db using the `POST` operation.  Please let me know if you have any sepcific question about the same.

**Comment by 03amir** [comment]
I want to work on this issue under JWOC
