### ISSUE TITLE
[Backend] GET API for Contact Us

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#696]
- [ ] Make the api to store the Join Us Form data. Below are the requirements for the same-

      -  It should be a GET request
      - It should only be accessible to the admins only i.e it requires the auth check

Note - This issue can be worked on once [Pr-695](https://github.com/HITK-TECH-Community/Community-Website/pull/695) pr gets merged

**Comment by tejasvi541** [comment]
Hey @Kajol-Kumari , I would like to work on this issue.

**Comment by Kajol-Kumari** [comment]
Please go ahead @tejasvi541 

Happy Learning :)

**Comment by arinmodi** [comment]
Can i work on this ?

**Comment by arinmodi** [comment]
Hey @Kajol-Kumari, I am getting the "jwt malformed" error while adding auth middleware,

i used the Authrization header with Bearer keyword

**Comment by Kajol-Kumari** [comment]
@arinmodi 
1. @tejasvi541 is already working on this and he will continue to work once his exam gets over
2. This is an open api so you don’t need any authentication token for the same

**Comment by Gurdeep475** [comment]
I would like to work on this issue under GSSOC`22.

**Comment by lokita282** [comment]
I would like to work on this issue under GSSOC '22

**Comment by Kajol-Kumari** [comment]
@tejasvi541 can i please get an update on this issue?
