### ISSUE TITLE
[Backend] Contact Us DELETE using Cron Job API 

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#697]
Deliverable-
- [ ] we need a cron job for deleting the contact us form data from db periodically after 60days
- [ ] Notify admins at the time of deletion via email

Note - This issue is depended on  [pr-#695 ] https://github.com/HITK-TECH-Community/Community-Website/pull/695
Ref Pr - https://github.com/HITK-TECH-Community/Community-Website/pull/692

**Comment by Aniket-508** [comment]
@Kajol-Kumari I want to work on this under JWoC.

**Comment by Kajol-Kumari** [comment]
@Aniket-508 please go ahead with the issue.
