### ISSUE TITLE
[Frontend] Integrate Contact Us Form with backend 

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#698]
Deliverable-

- [ ] On submit of the form, the contact us api should be called[Make sure you handle errors properly]
- [ ] A success/error toast bar should be displayed accordingly withe message of `Form submitted successfully!` and `Something went wrong` respectively

Contact Us Post API - [here](https://github.com/HITK-TECH-Community/Community-Website/blob/main/backend/app/routes/contactUs/post.js)

Contact Us Page -[https://hitk-tech-community.netlify.app/contact-us]( https://hitk-tech-community.netlify.app/contact-us )

**Comment by kanthalaHarivardhanReddy** [comment]
assign me this issue, I can work upon this issue @Kajol-Kumari

**Comment by Kajol-Kumari** [comment]
Hey @kanthalaHarivardhanReddy please try the new credential that I provided u at #682 ,  incase it doesn't work please let me know, I will assign this to you.

**Comment by Aniket-508** [comment]
@Kajol-Kumari I want to work on this issue under JWoC.
