### ISSUE TITLE
[Open for all] UI Design for Contact Us page of the website 

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#7]
- Make UI for the `contact us` page of the website using any of the UI designing tool like figma

**Comment by sreechand2002** [comment]
Assign this to me , i want to work on this

**Comment by Kajol-Kumari** [comment]
@sreechand2002 would you like to go ahead with this? If yes, I will assign it to you and re-assign the previous one to @codewithvk

**Comment by sreechand2002** [comment]
sure, no worries , i can go with this and you can assign the previous one to @codewithvk

**Comment by sreechand2002** [comment]
@Kajol-Kumari  can you  merge the PR of @codewithvk ASAP so i can proceed with my issue without any road block

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari can you merge the PR of @codewithvk ASAP so i can proceed with my issue without any road block

Hey @sreechand2002 It's more of like a designing(UI) issue. You don't need to code anything instead you need to make the prototype of `contact us` page. We can't directly jump to code until we have a design so we have opened UI issues first to finalize our designs

**Comment by sreechand2002** [comment]
so i have to design a mock up in a graphic designing tools right and upload the jpeg or png file to git ?

**Comment by Kajol-Kumari** [comment]
> so i have to design a mock up in a graphic designing tools right and upload the jpeg or png file to git ?
Exactly! You can upload the screenshot of that image under the [`assets`](https://github.com/HITK-TECH-Community/Community-Website/tree/main/assets) folder of the repo.

**Comment by Aaryan8751** [comment]
@Kajol-Kumari could you assign this work also to me?

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari could you assign this work also to me?

Sure @Aaryan8751 Go ahead with this!

**Comment by Aaryan8751** [comment]
@Kajol-Kumari I have added Contact Us UI in the assets folder and made a pull request
![Contact Us](https://user-images.githubusercontent.com/60098288/101504203-f305fc00-3998-11eb-89b2-c23a1559cd96.png)
Here is the UI design.
