### ISSUE TITLE
[Backend] POST API For Questions under Q&A

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#701]
Deliverables-

- [ ] Make the POST API for question addition containing below fields-
    - title[string]
    - description[string]
    - tags[array of strings]
    - isApproved [boolean default-value=`false`]
    - upvotes[number]

**Comment by arinmodi** [comment]
Can i work on this, issue ?

**Comment by Kajol-Kumari** [comment]
Sure @salil-naik please go ahead with this issue.

**Comment by arinmodi** [comment]
Do I need to add auth middleware in posting question ?

**Comment by Kajol-Kumari** [comment]
No @arinmodi this api should be open.

**Comment by arinmodi** [comment]
Hey @Kajol-Kumari, when running test using npm run test command, all the tests are failing, do i need to do some setup for testing ?

**Comment by arinmodi** [comment]
Okay

**Comment by arinmodi** [comment]
Hey @Kajol-Kumari, i made a PR

**Comment by Kajol-Kumari** [comment]
close via #703
