### ISSUE TITLE
[Backend] Fix the failing UTs

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#704]
Deliverables-

- [ ] Currently the UTs are failing for this project. The requirement is to fix the same

**Comment by arinmodi** [comment]
Can i work on this ?

Can i change the testing method from chai to jest ?

**Comment by Kajol-Kumari** [comment]
@arinmodi we have already written few tests using chai so don't want it to go in vain.

I would recommend to go with chai only.please let me know if you would be able to continue with this issue using chai

**Comment by arinmodi** [comment]
No problem, i will write it using chai

**Comment by arinmodi** [comment]
Hey @Kajol-Kumari,
![image](https://user-images.githubusercontent.com/61725413/150646454-5647db93-bfbb-479e-9bb4-3f2aacdbff56.png)

the inviteAdmin API giving above error, let me know how can i fix this ?

**Comment by arinmodi** [comment]
@Kajol-Kumari,

I think invite admin API is completely broken, cause it keeps giving error as I dig into code of it

see,
![image](https://user-images.githubusercontent.com/61725413/150651091-738b3a3c-f67f-4c89-bbab-ae46c0b8047b.png)

So, should I remove it's test ? or what should i do ?

**Comment by Kajol-Kumari** [comment]
Hello @arinmodi you can keep this test commented as I believe this feature wasn't complemented
