### ISSUE TITLE
[Backend] POST API For Answers under Q&A

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#705]
Deliverables-
- [ ] Make the POST API for answer addition containing below fields-
        - question_id [id of the question]
        - isApproved [Boolean, default value = false]
        - created_by [String]
        - created_on [Date]
        - answer [ String]
        - upvotes[number, default=0]

**Comment by arinmodi** [comment]
can I work on this issue ?

**Comment by Kajol-Kumari** [comment]
Sure @arinmodi please go ahead with this issue.

**Comment by arinmodi** [comment]
Hey @Kajol-Kumari, do i need to add auth middleware in post answer API ?

**Comment by Kajol-Kumari** [comment]
No @arinmodi we don't authentication here as it should be open for all.

**Comment by arinmodi** [comment]
Hey @Kajol-Kumari, made a new PR.
