### ISSUE TITLE
[Backend] GET API for answers

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#709]
Deliverables-
- GET API to get all the answers related to a particular questions sorted by the number of `upvotes`
- `question_id` will be extracted from the request body and all the answers should be fetched based on the same.
- It should be an open API(no auth middleware required)

**Comment by arinmodi** [comment]
Can i work on this ?

**Comment by Kajol-Kumari** [comment]
@arinmodi please go ahead with this issue.
