### ISSUE TITLE
Home Page Responsiveness

### ISSUE THREAD

**Issue by Shruti025** [HITK-TECH-Community/Community-Website#715]
**Describe the bug**
The home page is reducing its width for smaller screens and isn't responsive.

**Screenshots**
![image](https://media.discordapp.net/attachments/936699202841497630/947372063214170133/unknown.png?width=414&height=586)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Yes

**Comment by Shruti025** [comment]
I want to work on this issue under JWOC

**Comment by Mobasherah12** [comment]
@Shruti025 please go ahead.

**Comment by thefstalphabet** [comment]
Hey, I would like to work on this issue, under GSSoC'22. Can you please assign it to me?

**Comment by Mridul07Sharma** [comment]
@Shruti025 I want to work on fixing this bug. Can you plz assign it to me.

**Comment by Shruti025** [comment]
@Mobasherah12 As I have conveyed, I am facing issues while running this project on my system so I am unassigning myself
