### ISSUE TITLE
[Frontend] Update footer

### ISSUE THREAD

**Issue by Mobasherah12** [HITK-TECH-Community/Community-Website#716]
**What is the current footer state?**
Presently, the footer of the Community Website looks this way (shown below):

![c42](https://user-images.githubusercontent.com/52857890/155897919-3a2c029a-da31-424b-bb7a-80f688ad0207.PNG)
Pic1

**Proposed Statement**
As we have extended our reach in more social platforms, we are planning to bring some minor changes in the footer. Please refer to the image below: 

![c42 1](https://user-images.githubusercontent.com/52857890/155899698-5f547f00-4567-4af1-ba6a-17a47a7a45f0.jpg)
Pic2

Align the official email below the address (refer to Pic2). 

`Email: hitktechcommunity@gmail.com`

In the Social section, 

- [ ] Replace the gmail icon with instagram icon
- [ ] Add Twitter and YouTube icons 

Links are provided below:
- Instagram: www.instagram.com/hitktechcommunity
- Twitter: https://twitter.com/HitkTech
- YouTube: https://www.youtube.com/channel/UCaMU1D4pJALSHLo6OsiDzGg

**Comment by AnweshaRoses** [comment]
Hello can you please assign this issue to me.
Thank you!

**Comment by tanktejas** [comment]
I have sent a pull request on this issue please see it.

**Comment by Kushal-2002** [comment]
I am a GSSOC'22 participant, please assign this issue to me.

**Comment by sulogna2001** [comment]
Hey Can you assign me this issue for GSsoc22

**Comment by ritikakhandelwal-17** [comment]
I want to work on this issue, Can you please assign it to me under GSSOC22.

**Comment by debjitpurohit** [comment]
i want to work assign to me

**Comment by sahooankeeta** [comment]
Hello,@Mobasherah12.I am a GSSOC22 participant. I want to work on this issue, please assign this to me.

**Comment by sahooankeeta** [comment]
@Mobasherah12 Hello, I am a GSSOC22 participant. Please assign me this issue.

**Comment by neharaut00** [comment]
I want to work on this issue, Can you please assign it to me under GSSOC22.

**Comment by purnimakatiyar** [comment]
I want to work on this issue, Can you please assign it to me under GSSOC22

**Comment by KushalGhosh9899** [comment]
I want to work on this issue under JWOC

**Comment by Arijit018** [comment]
@Mobasherah12  Hello, I am a GSSOC22 participant. Can you Please assign me this issue?

**Comment by Kajol-Kumari** [comment]
@Arijit018 would you like to go ahead with this issue? Please let me know.

**Comment by Kajol-Kumari** [comment]
@Anirban-1490 you can go ahead with this issue.

**Comment by Anirban-1490** [comment]
> @Anirban-1490 you can go ahead with this issue.

ok thanks then assign it to me

**Comment by Mridul07Sharma** [comment]
I am GSSOC 22 participant and i want to work on this issue. Plz assign it to me

**Comment by Anirban-1490** [comment]
@Kajol-Kumari plz unassign me
