### ISSUE TITLE
Updation of Motive and Join Us documentation

### ISSUE THREAD

**Issue by Bikramjit21** [HITK-TECH-Community/Community-Website#718]
**Documentation**
The lines in the motive section are not well structured and the join us lines should be edited.

**Have you spent some time to check if this issue has been raised before?**
No it is new.

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Yes

**Comment by Kajol-Kumari** [comment]
Hey @Bikramjit21  we don't need this updation and so closing this issue. Thank you for taking time to report this.
