### ISSUE TITLE
About Us page Responsiveness

### ISSUE THREAD

**Issue by Muskan626bidani** [HITK-TECH-Community/Community-Website#720]
**Describe the bug**
The About us page is reducing its width for smaller screens and isn't responsive. Content is overflowing and adding a horizontal scroll bar

**Screenshots**
![about page resposiveness](https://user-images.githubusercontent.com/80620237/155974582-08e62b3f-077c-4f81-90bc-4a2bc815bf15.jpg)
**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
yes

**Comment by Muskan626bidani** [comment]
I want to work on this issue under JWOC

**Comment by sagnik2001** [comment]
Can I work on this issue??

**Comment by haider000** [comment]
Hey, I am interested to work on this issue under GSSoc 2022, can you assign me this issue?

**Comment by Rajdip019** [comment]
Can I work o this issue under GSSoC'22? @Kajol-Kumari

**Comment by notsoocool** [comment]
Hey, Can I work on this issues because I know the exact thing to change in your code.

**Comment by Kajol-Kumari** [comment]
@Muskan626bidani we are taking care of all the responsiveness issue of the website under #721 so closing this issue. Thanks for taking time to report this
