### ISSUE TITLE
HITK-TECH-Community image on Homepage is getting cut for scrren-size<768px

### ISSUE THREAD

**Issue by Janvi-Thakkar** [HITK-TECH-Community/Community-Website#721]
**Describe the bug**
HITK-TECH_community image on Homepage is getting cut for scrren-size<768px. The element is not responsive for tablet and Mobile View

**To Reproduce**
1. Go to Homepage
2. Set Screen-size< 768px
3. See error

**Expected behavior**
The image should look responsive

**Screenshots**
![image](https://user-images.githubusercontent.com/55620053/156067943-c2a5403b-b3ec-4d83-a4c9-ab2e40c5b8d4.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Yes

**Comment by Janvi-Thakkar** [comment]
Can I work on this issue?

**Comment by Muskan626bidani** [comment]
Can I work on this issue under Gssoc'2022

**Comment by Rajdip019** [comment]
Hey @Kajol-Kumari can I work on this?

**Comment by sulogna2001** [comment]
Hey Can I work  on  this issue under GSSOC22

**Comment by mayank-del** [comment]
Can i work on this??

**Comment by mayank-del** [comment]
Didi , i made it full responsive, pushing the code

**Comment by Kajol-Kumari** [comment]
Hello @Janvi-Thakkar  Thanks for pointing it. But please increase the scope of this issue to all the pages of the website, not just the home page and please let me know if you would like to work on it.

**Comment by mayank-del** [comment]
Yes ofcourse

**Comment by mayank-del** [comment]
Just tell me the pages, i will solve each and every responsive issue

**Comment by Janvi-Thakkar** [comment]
> Hello @Janvi-Thakkar Thanks for pointing it. But please increase the scope of this issue to all the pages of the website, not just the home page and please let me know if you would like to work on it.

Thank You Kajol. I will surely look at all pages and will list those things here

**Comment by mayank-del** [comment]
@Kajol-Kumari , I didn't understand that @Janvi-Thakkar  pointed the issue and pulled one request also, can we both contribute in this? will there be any issue?

**Comment by Janvi-Thakkar** [comment]
@mayank-del I haven't sent any pull requests yet

**Comment by mayank-del** [comment]
Ok, i will do it.
