### ISSUE TITLE
[Backend] Add the API for adding the Team member details in db

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#722]
Deliverables-
Add a post api to add the team member data in the db with below specifications-
1. It should be token protected [ only admins should be able to make this post request]
2. It should contain following data -
{
    "full_name": string,
    "image": binary,
    "description": string,
    "linkedin_url": uri,
    "github_url": uri,
    "twitter_url": uri,
    "teams" : string[]
}

**Comment by Aman16-ai** [comment]
can i work on it under gssoc22

**Comment by lokita282** [comment]
I would like to work on this issue under GSSOC '22

**Comment by prafullapal** [comment]
I Gssoc contributor. I would like to work on this issue.

**Comment by AdnanMuzavor** [comment]
I would like to work on this issue ma'am. Please!!

**Comment by SHAIKASIFALI** [comment]
can i contribute to this issue ..under jwoc
