### ISSUE TITLE
[Backend] Add GET API For Add Team 

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#723]
Deliverables-

- [ ] GET Team member detail api with following specification
    - It should be open api
    - It should give all the member details in json form

Can only be worked after [this](https://github.com/HITK-TECH-Community/Community-Website/issues/722) issue

**Comment by Aman16-ai** [comment]
can i work on it under gssoc22

**Comment by lokita282** [comment]
I would like to work on this issue under GSSOC '22

**Comment by thedreader** [comment]
I would like to work on this issue here.

**Comment by prafullapal** [comment]
I am a Gssoc contributor. I would like to work on this issue.

**Comment by Saptarshisamata** [comment]
I would like to work on this issue under GSSOC'22

**Comment by Kajol-Kumari** [comment]
@lokita282 please go ahead with this issue.

**Comment by saheelsapovadia** [comment]
Is this still open and up for grabs? If yes, I'd like to work on it.😃

**Comment by Kajol-Kumari** [comment]
@lokita282 can you please update us in this issue?

**Comment by hazemessam** [comment]
@Kajol-Kumari  Please, assign me this issue.

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari Please, assign me this issue.

Please go ahead with this issue

Happy Learning :)
