### ISSUE TITLE
[Frontend] Integrated the Get Team API With Frontend

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#724]
Deliverables-

- [ ] The founder &Co-founder details should be hardcoded
- [ ] Rest all the cards should be populated a/c the data fetched from backend

Get Board Members API - https://github.com/HITK-TECH-Community/Community-Website/blob/main/backend/app/routes/teamMember/getTeamMembers.js

**Comment by Ayushmina-20** [comment]
Please assign this issue to me as I am interested.

**Comment by jaydeepdey03** [comment]
Can I work on it under GSSOC'22

**Comment by its-ayush-07** [comment]
Hey! I'm interested to work on this issue.

**Comment by thedreader** [comment]
I would like to work on this issue here. So, please assign it to me.

**Comment by Aman16-ai** [comment]
can i work on this issue.

**Comment by Kajol-Kumari** [comment]
Hey @Ayushmina-20 As this issue is dependent on https://github.com/HITK-TECH-Community/Community-Website/issues/723 so please collaborate with @its-ayush-07 and work on this one or else you can wait till he comes up with a pr

Happy Learning :)

**Comment by Ayushmina-20** [comment]
@its-ayush-07 if anything required from my end I would be happy to contribute

**Comment by Kajol-Kumari** [comment]
@Ayushmina-20 for the details of founder and co-founder please dm me on discord. [ As this value needs to be hardcoded ] And once #723 gets implemented, you can proceed on this issue

**Comment by aakankshabhende** [comment]
Any updates? @Ayushmina-20

**Comment by its-ayush-07** [comment]
Can I work on this under GSSoc22?

**Comment by Hritik1503** [comment]
I want to work for on this issue under jwoc , please assign me

**Comment by arpit456jain** [comment]
@Kajol-Kumari i am interested in this issue

**Comment by Hemu21** [comment]
@Kajol-Kumari  can you please assign this to me.
