### ISSUE TITLE
[Frontend] Integrate Add Team Member API with Frontend

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#725]
Deliverables-

- [ ] Integrate the add team member form of admin panel with the backend api

https://hitk-tech-community.netlify.app/dashboard -> About US --> Ad Team Memeber

This issue is can be worked after the completion of https://github.com/HITK-TECH-Community/Community-Website/issues/722 this issue

**Comment by Aman16-ai** [comment]
can i work it on under gssoc22

**Comment by its-ayush-07** [comment]
Hey! I'm interested to work on this issue.

**Comment by DarkFalc0n** [comment]
I want to work on this issue under JWOC

**Comment by Ayushmina-20** [comment]
Hey! I'm interested to work on this issue.

**Comment by Kajol-Kumari** [comment]
Hi @its-ayush-07 please go ahead with this issue. Just note that this issue needs https://github.com/HITK-TECH-Community/Community-Website/pull/726 this pr to be merged first.

Happy Learning :)

**Comment by meet503186** [comment]
Can i work on this issue?

**Comment by Hritik1503** [comment]
I want to work for on this issue under jwoc , please assign me

**Comment by Kajol-Kumari** [comment]
> I want to work for on this issue under jwoc , please assign me

I have assigned you one issue for now,once you complete that please feel free to claim any other..

**Comment by SHAIKASIFALI** [comment]
I want to work on this under jwoc please assign me

**Comment by Hemu21** [comment]
@Kajol-Kumari I want to work on this issue can you please assign this to me.

**Comment by Kajol-Kumari** [comment]
@Hemu21  Assigning this to you. Please note that I won't assign any further issue to you, until one of the assigned issue get resolved. Happy Learning :)

**Comment by Hemu21** [comment]
@Kajol-Kumari I had added it in frontend, But api is not responding.

**Comment by Hemu21** [comment]
@Kajol-Kumari backend api is not responding for adding team members. coding is completed can you please check it api once.
