### ISSUE TITLE
Adding hover effect on the logo in the home page 

### ISSUE THREAD

**Issue by PM-00-STAR** [HITK-TECH-Community/Community-Website#727]
I am a GSSoC22 contributor , would like to add hovering effect on the frontend 

Request you to allow me contribute
![WhatsApp Image 2022-03-03 at 19 52 58](https://user-images.githubusercontent.com/81418245/156583696-a87da652-6b2e-403e-b610-e56e38129ad0.jpg)

**Comment by Kajol-Kumari** [comment]
Hey @PM-00-STAR thanks for opening the issue but we are not planning to implements this, hence closing it.
