### ISSUE TITLE
[Backend] Add GET api for fetching the questions of Q&A

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#728]
Deliverabels-

- [ ] We need 2 GET api for fetching the question
    - Get all the questions
    - Get a particular question using `id` where id will be provided in the json body

Ref- https://github.com/HITK-TECH-Community/Community-Website/tree/main/backend/app/routes/Q%26A/question

**Comment by Aman16-ai** [comment]
Please assign this task to me
