### ISSUE TITLE
[Backend] PATCH/PUT API for updating the upvotes of Question & Answers stored in Db

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#729]
Deliverables-

- [ ] Create an API for updating (both increase&decrease) the upvote of question [the api will resider under [here](https://github.com/HITK-TECH-Community/Community-Website/tree/main/backend/app/routes/Q%26A/question)]
- [ ] Create an API for updating (both increase&decrease) the upvote of answers [The api will reside under [here](https://github.com/HITK-TECH-Community/Community-Website/tree/main/backend/app/routes/Q%26A/answers)]
- [ ] Write test for both of the apis

**Comment by himanshusanecha** [comment]
I am interested to work on this issue.

**Comment by Kajol-Kumari** [comment]
please go ahead @himanshusanecha 
Happy Learning :)

**Comment by himanshusanecha** [comment]
> 

Thanks
