### ISSUE TITLE
[Backend] PATCH/PUT API for updating the isApproved field of Question & Answers stored in Db

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#730]
Deliverables-Deliverables-

- [ ] Create an API for updating the isApproved field of questions data [the api will resider under [here](https://github.com/HITK-TECH-Community/Community-Website/tree/main/backend/app/routes/Q%26A/question)]
- [ ] Create an API for updating the isApproved field of answers data [The api will reside under [here](https://github.com/HITK-TECH-Community/Community-Website/tree/main/backend/app/routes/Q%26A/answers)]
- [ ] Write tests for both of them

**Comment by prafullapal** [comment]
I would like to work on this issue

**Comment by Kajol-Kumari** [comment]
please go ahead @prafullapal 

Happy Learning  :)

**Comment by aakankshabhende** [comment]
Any updates? @prafullapal

**Comment by arinmodi** [comment]
Can i work on this ?

**Comment by Kajol-Kumari** [comment]
> Can i work on this ?

Sure, please go ahead

**Comment by arinmodi** [comment]
@Kajol-Kumari, i have made the PR for this issue, can you please review that ?
