### ISSUE TITLE
[Backend] POST Api for resource storage

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#736]
-Deliverable -

- [ ] Create a route for storing resource sharing form data. [ https://hitk-tech-community.netlify.app/resources ]
- [ ] Post storage send an email to the existing admins about it. (Using our existing email service)
      - Public API
      - Requires API Testing.
Data -
{
"name": string, (required)
"email": string, (required)
"url": uri, (required)
"description": string,
"trust_level": number, (required)
"expiry_date": date, (required)
"additional_info": string,
"created_at": string/date
"modified_at": string/date
}

- Refer #81 For API Testing resources.

Ref PR - #686

**Comment by AdnanMuzavor** [comment]
Ma'am Please assign this issue to me under GSSOC'22.

**Comment by Kajol-Kumari** [comment]
Please go ahead @AdnanMuzavor 

Happy Learning :)

**Comment by salma77** [comment]
@Kajol-Kumari Please assign me to this issue under GSSOC'22

**Comment by Raj3045** [comment]
Hey, I would like to work on this issue ,can you assign it to me?

**Comment by Kajol-Kumari** [comment]
Hey @Raj3045 it's already assigned. Please look for other opened issues
