### ISSUE TITLE
[Backend] GET API For Resource Data

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#737]
Deliverables-

- [ ] Add a GET API for getting all the resource data with following specifications
    - It should be protected by authmiddleware i.e only admin should access it

- [ ] Add the required tests

Please note - This issue is dependent on https://github.com/HITK-TECH-Community/Community-Website/issues/736

**Comment by AdnanMuzavor** [comment]
Ma'am Please assign this issue to me.

**Comment by Aman16-ai** [comment]
Can I work on it?

**Comment by AdnanMuzavor** [comment]
Ma'am please assign this issue to me under GSSOC'22.

**Comment by Kajol-Kumari** [comment]
Please go ahead @AdnanMuzavor 

Happy Learning :)
