### ISSUE TITLE
[Backend] Delete API for resource Data

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#738]
Deliverables-

- [ ] A delete API which will be a cron job[ please use the existing reusable functions] It should delete the resource data of 2 months ago.
- [ ] A delete API which will get the `id` in request body and delete a particular resource data.
- [ ] Both APIs should be well tested

Ref PR for the cron job api - https://github.com/HITK-TECH-Community/Community-Website/pull/692

**Comment by Aman16-ai** [comment]
Can I work on this issue ??

**Comment by Kajol-Kumari** [comment]
Please go ahead @Aman16-ai 

Happy Learning :)

**Comment by Aman16-ai** [comment]
Can you please tell me something about resource data??

**Comment by Kajol-Kumari** [comment]
Hey @Aman16-ai this issue is dependent on https://github.com/HITK-TECH-Community/Community-Website/issues/736 so please collab with @AdnanMuzavor Also you can find the schema of the data in the referred issue

**Comment by Raj3045** [comment]
hello , I would like to work on this issue, can I work on this?
