### ISSUE TITLE
[Frontend] Enhancement In Add Broadcast Page 

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#739]
Deliverable-
1. The UI of the add broadcast page needs to be improved
2. The add broadcast form should contain the following fields -
 ```
 title: {
      type: String,
    },
    content: {
      type: String,
    },
    link: {
      type: String,
    },
    expiresOn: {
      type: Date,
    },
    imageUrl: {
      type: Array,
    },
    tags: {
      type: Array,
    }
```
The tag input field should be similar to the one given below 
![WhatsApp Image 2021-05-06 at 8 13 21 PM (1)](https://user-images.githubusercontent.com/44888949/117320041-7de81580-aea9-11eb-9ea6-5b6b8a57ee8a.jpeg)

Ref PR - https://github.com/HITK-TECH-Community/Community-Website/pull/647 

Steps to go to add Broadcast page-
1. Login as admin (https://hitk-tech-community.netlify.app/dashboard)
2. Click on Broadcast card from dashboard
3. Click on `Add Broadcast` card

**Comment by Lalit3716** [comment]
Hi! Can I work on this ?

**Comment by Kajol-Kumari** [comment]
sure @Lalit3716, Please go ahead with this issue.

Happy Learning :)
