### ISSUE TITLE
Issue in Readme.md

### ISSUE THREAD

**Issue by aniketsingh98571** [HITK-TECH-Community/Community-Website#74]
For the Frontend part, you have mentioned this step in order to install the project on our machine. I have just added the second point because after navigating using `cd Community-Website` we cannot do directly `npm install` and also changed the file name.

1. Navigate to the community-website folder using cd `Community-Website`.
2. cd `frontend`
3. Run npm install. It will install all the required packages and dependencies.
4. Run npm start to run the server.
5. Navigate to http://localhost:3000 to view it in the browser.

**Comment by aniketsingh98571** [comment]
@Kajol-Kumari  Please look into it and assign it to me for SWOC.

**Comment by Kajol-Kumari** [comment]
Go ahead with this issue @aniketsingh98571

**Comment by Sloth-Panda** [comment]
Hey, Can I also do this for DWOC?

**Comment by Kajol-Kumari** [comment]
Hey @Sloth-Panda we can't assign this issue to more than one person so please look at other issues

**Comment by aniketsingh98571** [comment]
@Kajol-Kumari  Please refere to #95 for this Issue #74
