### ISSUE TITLE
[Frontend] Integrate GET Contact Us Data 

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#740]
Deliverables -

- [ ] Go to admin dashboard(by logging in using admin credential, which can be found in project readme) => Click on `Contact Us` tab. It should call the GET Contact US API and should show the list of data in the form of card.[one data in one card]
- [ ] Each card should have a delete button/icon [based on whichever ui looks better ]

Similar to - https://github.com/HITK-TECH-Community/Community-Website/pull/764

**Comment by codepley** [comment]
I would like to work on this issue. How can I be assigned for this?

**Comment by artimanputra** [comment]
I would like to work on this issue, can I work on it?

**Comment by Kajol-Kumari** [comment]
Sure @artimanputra  Please go ahead with this issue.

Just make sure that this issue is dependent on #696 so you might need to collab with the other person working on the same

**Comment by meet503186** [comment]
I would like to work on this issue. Can I work on it?

**Comment by Kajol-Kumari** [comment]
@meet503186 please go ahead with this issue. @artimanputra unassigning this to you as I didn't get any progress since last 20 days

**Comment by Kajol-Kumari** [comment]
@meet503186 please update on this issue.

**Comment by sharma-tanishq** [comment]
Hi I am a GSSOC22 contributer can i work on this?

**Comment by Kajol-Kumari** [comment]
Sure @sharma-tanishq  please go ahead with this issue.

Happy Learning :)

**Comment by shaunak-09** [comment]
Hi can you please assign this task to me?

**Comment by Kajol-Kumari** [comment]
> Hi can you please assign this task to me?

Please go ahead. We will give 1 week buffer for this issue to be completed.

Happy Learning :)

**Comment by neokd** [comment]
I would like to work on this issue under JWOC

**Comment by neokd** [comment]
Thanks

**Comment by Shreyas-SAS** [comment]
Can I get some additional info about this issue. Wish go work on it under swoc but would like to know more about deliverables before commitment.

Thanks.

**Comment by Shreyas-SAS** [comment]
@thevirengarg before assignment can I get some insights on deliverables?

**Comment by Shreyas-SAS** [comment]
1. Is the creation of the contact us API a part of the project or is it already available and just a fetch request is needed for presenting data in form of cards with a button for deletion?
2. By deletion, it should delete on API server storage as well right just like a database delete?
3. Should there be a method to add a new contact as well or only delete?
4. If API creation is required, where can I find the current contact dataset and required schema?

First 3 are main points. 4th can be started from empty list. No issues with that.

Please share a bit more details on that and any deadline that is required.

**Comment by thevirengarg** [comment]
> 1. Is the creation of the contact us API a part of the project or is it already available and just a fetch request is needed for presenting data in form of cards with a button for deletion?
> 2. By deletion, it should delete on API server storage as well right just like a database delete?
> 3. Should there be a method to add a new contact as well or only delete?
> 4. If API creation is required, where can I find the current contact dataset and required schema?
> 
> First 3 are main points. 4th can be started from empty list. No issues with that.
> 
> Please share a bit more details on that and any deadline that is required. 

@Kajol-Kumari

**Comment by Kajol-Kumari** [comment]
@Shreyas-SAS 
1. The contact us api is already there, you just need to integrate it. (contact-us-get-api)[https://github.com/HITK-TECH-Community/Community-Website/blob/main/backend/app/routes/contactUs/get.js]
2. For now, i just need a delete icon on the UI, no api integration as the delete api is still WIP
3. There shouldn't be any method to add any new contact page in admin dashboard. I would recommend you to go to the website (https://hitk-tech-community.netlify.app/) and explore the flow -

  click o `Admin?` button on the right side -> Log in using admin credential, which can be found in [project readme](https://github.com/HITK-TECH-Community/Community-Website?tab=readme-ov-file#testing-credentials-) => Click on Contact Us tab

4. No api creation is required, its just ui integration with existing API

**Comment by iMADi-ARCH** [comment]
@thevirengarg

**Comment by Shreyas-SAS** [comment]
Just read through the referenced conversation. As long as work is done by anyone I am happy with it. 

@thevirengarg or @Kajol-Kumari please assign @iMADi-ARCH with the issue. It seems he has already completed the issue. 

Thanks,
Shreyas.
