### ISSUE TITLE
[Frontend] Integrate GET Join Us API 

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#741]
Deliverables -

- [ ] Go to admin dashboard(by logging in using admin credential, which can be found in project readme) => Click on `Join Us` tab. It should call the GET Join Us API and should show the list of data in the form of card. [one data in one card]
- [ ] Each card should have a delete button/icon [based on whichever ui looks better ]

The api can be found at https://github.com/HITK-TECH-Community/Community-Website/blob/main/backend/app/routes/joinUs/index.js

**Comment by Lalit3716** [comment]
I would like to work on it but do we have any existing design for cards ?

**Comment by Kajol-Kumari** [comment]
> I would like to work on it but do we have any existing design for cards ?

@Lalit3716 You should be able to use https://github.com/HITK-TECH-Community/Community-Website/tree/main/frontend/src/pages/Broadcast/Component/AllBroadcasts/Card this component for the same.

**Comment by Lalit3716** [comment]
> > I would like to work on it but do we have any existing design for cards ?
> 
> @Lalit3716 You should be able to use https://github.com/HITK-TECH-Community/Community-Website/tree/main/frontend/src/pages/Broadcast/Component/AllBroadcasts/Card this component for the same.

Oh Okay! You can assign this to me then!

**Comment by Lalit3716** [comment]
Hi, I am extremely sorry to inform you that I will be unable to do this task due to unavailability of time on my side.
Kindly assign this issue to someone else.
Thank You!

**Comment by Aman16-ai** [comment]
Can I work on this issue?

**Comment by Kajol-Kumari** [comment]
Sure @Aman16-ai Please go ahead
