### ISSUE TITLE
[Enhancement] Remove all the Eslint Errors from backend files

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#746]
Deliverables-

- [ ] During commit, we are seeing many eslint issues(as shown in the ss below,) This issue intends to solve them all.

**Comment by AdnanMuzavor** [comment]
![Screenshot (696)](https://user-images.githubusercontent.com/78341720/156888008-06324549-e0af-413c-bee4-98dfe83c2e30.png)

**Comment by AdnanMuzavor** [comment]
![Screenshot (697)_LI](https://user-images.githubusercontent.com/78341720/156888439-148e7258-4f47-4d92-89b0-d555d1df0db0.jpg)

**Comment by hazemessam** [comment]
@Kajol-Kumari 
Please, assign it to me

**Comment by Kajol-Kumari** [comment]
Please go ahead @hazemessam 

Happy Learning :)

**Comment by hazemessam** [comment]
@Kajol-Kumari  Sorry I'm very busy. I will start working on it by tomorrow or on Thursday.

**Comment by hazemessam** [comment]
@Kajol-Kumari  Sorry, I'm very busy, you can unassign me.

**Comment by vinrusty** [comment]
Can I please work on this issue?

**Comment by Devmindtk** [comment]
I would like to work on this issue.
