### ISSUE TITLE
[Documentation] Add contributor code of conduct to the project

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#75]
Make a `code_of_conduct.md` file in the project and add the contributor guidelines in here.

Reference link - https://www.contributor-covenant.org/version/1/3/0/code-of-conduct/

**Comment by kanishkaa24** [comment]
Hey!
I would love to work on this.

**Comment by Sloth-Panda** [comment]
Hey, would love to do this

**Comment by Kajol-Kumari** [comment]
@Sloth-Panda up ahead with this issue. @kanishkaa24 you already have 2 issues on your end so please fix them first. 

Looking forward to your awesome contributions :)
