### ISSUE TITLE
[Frontend] Integrate POST Resource with the form

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#759]
Deliverables-

- [ ] Integrate the https://hitk-tech-community.netlify.app/resources form with backend [POST] api

Ref - https://github.com/HITK-TECH-Community/Community-Website/blob/main/backend/app/routes/resources/addResource.js

**Comment by meet503186** [comment]
I want to work on this issue. Can i work on it?

**Comment by Kajol-Kumari** [comment]
Please go ahead @meet503186 
Happy Learning :)

**Comment by nishant3721** [comment]
@Kajol-Kumari Can I work on it?

**Comment by saisrivenkat** [comment]
Hii, can I work on this issue?

**Comment by Kajol-Kumari** [comment]
sure @saisrivenkat please go ahead with this issue.
Happy Learning :)

**Comment by avdhendra** [comment]
kajol kumari can you elaborate more it what need to be done

**Comment by Kajol-Kumari** [comment]
> kajol kumari can you elaborate it more . what need to be done

@avdhendra Here, we need to integrate the frontend for with the backend API, as soon as the user submits the form, the mentioned api should get called and the data should be stored in the DB

**Comment by avdhendra** [comment]
i would like work on this issue can u assign it to me
