### ISSUE TITLE
[Documentation] Add contribution guidelines

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#76]
Make a `contributing.md` file and add the guidelines for contributing to this project. You can refer [this](https://github.com/Canvasbird/canvasboard/blob/master/contribution.md) for the same ad make the required changes in here.

**Comment by kanishkaa24** [comment]
Hey!
I would love to work on this.  I prepared contributing guidelines this morning itself.

**Comment by Kajol-Kumari** [comment]
Sure @kanishkaa24 go ahead with this issue.

**Comment by singhsaurav23** [comment]
hey, Can I work on this issue? @Kajol-Kumari

**Comment by chehak123** [comment]
hii 
i would like to work on this issue

**Comment by Kajol-Kumari** [comment]
Hey @singhsaurav23 @chehak123 we can't assign this issue to more than one people so please look at some other issue or wait patiently as we will be opening new issues very soon :)

**Comment by kanishkaa24** [comment]
Hello 
I have made a pull request for the same.

**Comment by Kajol-Kumari** [comment]
Closing via [this](https://github.com/HITK-TECH-Community/Community-Website/pull/84) PR

**Comment by jackfrost13** [comment]
@kanishkaa24 Can you please incorporate Commit message guidelines from [this](https://github.com/BLNDLYBLV/DWOC2020-Node_Builder/wiki/Contribution-Guidelines)

**Comment by kanishkaa24** [comment]
Sure

**Comment by kanishkaa24** [comment]
@jackfrost13 
I have made the changes.

**Comment by jackfrost13** [comment]
Thanks, I will have a look ;)

**Comment by kanishkaa24** [comment]
Is it fine or do I need to make any other changes?

**Comment by jackfrost13** [comment]
> Is it fine or do I need to make any other changes?

Yes, I have requested for a minor change. Please have a lot

**Comment by kanishkaa24** [comment]
@jackfrost13 
I have made the suggested changes.

**Comment by jackfrost13** [comment]
@kanishkaa24 Can you please confirm, in response to which event you have contributed?

**Comment by kanishkaa24** [comment]
> @kanishkaa24 Can you please confirm, in response to which event you have contributed?

I'm participating in DWOC and SWOC.

**Comment by jackfrost13** [comment]
Thanks for the update!
