### ISSUE TITLE
[Frontend] Integrate GET Resources API

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#760]
Deliverables -

- [ ] Go to admin dashboard(by logging in using admin credential, which can be found in project readme) => Click on `Resources` tab. It should call the GET Resources API and should show the list of data in the form of card. [one data in one card]
- [ ] Each card should have a delete button/icon [based on whichever ui looks better ]

The api can be found at https://github.com/HITK-TECH-Community/Community-Website/blob/main/backend/app/routes/resources/getResource.js

**Comment by vinrusty** [comment]
Can I please work on this issue?

**Comment by Kajol-Kumari** [comment]
Please go ahead @vinrusty 

Happy learning :)

**Comment by vinrusty** [comment]
A "CORS" error is occurring saying "No 'Access-Control-Allow-Origin' header is present on the requested resource" while fetching the API. Can you please help me out

**Comment by vinrusty** [comment]
A 401 Unauthorized error is occurring while fetching this API "GET https://hitk-community-website-backend.herokuapp.com/resources/getresources 401 (Unauthorized)". Can you please help me out?

**Comment by vinrusty** [comment]
should the card have the expiry date and the updated date as well?

**Comment by vinrusty** [comment]
ok on it

**Comment by vinrusty** [comment]
I made my own card instead of using the one which is already there. Is it fine?
