### ISSUE TITLE
[Backend] Add Team API Throwing CORS Error

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#766]
Deliverables-

- [ ] Modify the add team api to handle all the failing cases similar to https://github.com/HITK-TECH-Community/Community-Website/blob/main/backend/app/routes/contactUs/post.js 

PR Blocked - https://github.com/HITK-TECH-Community/Community-Website/pull/743

**Comment by vinrusty** [comment]
Can I please work on this issue?

**Comment by Kajol-Kumari** [comment]
Please go ahead @vinrusty
