### ISSUE TITLE
[Frontend] Integrate The Profile Page of Admin With Backend

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#767]
Deliverables-

- [ ] Currently the Data of logged In admin is static. Make it dynamic by integrating [this](https://github.com/HITK-TECH-Community/Community-Website/blob/main/backend/app/routes/admin/getAdmins.js#L34) API

The profile page can be found at -
1. Log in as admin => click on profile/admin image from the top left corner of the admin panel

**Comment by vinrusty** [comment]
Can I work on this issue? @Kajol-Kumari

**Comment by Gurdeep475** [comment]
I would like to work on this issue under GSSOC`22.

**Comment by Kajol-Kumari** [comment]
@vinrusty please work in the assigned issue first. @Gurdeep475 please go ahead with this issue

**Comment by Kajol-Kumari** [comment]
@Gurdeep475 please update on this issue..

**Comment by Sukriti-m** [comment]
Hi @Kajol-Kumari 
If this task is being delayed, then I'd be glad to work on this issue.
I'd be grateful if you could assign this task to me under GSSoC22.

**Comment by Gurdeep475** [comment]
I am getting this error while installing the necessary packages for Node Frontend. Please help me to resolve it.
![image](https://user-images.githubusercontent.com/32095032/163662766-91c381a0-7a35-422e-9c29-a5b33d7d0654.png)

**Comment by aakankshabhende** [comment]
Is your node version the latest? @Gurdeep475

**Comment by Gurdeep475** [comment]
> Is your node version the latest? @Gurdeep475

yes

**Comment by its-ayush-07** [comment]
Can I work on this under GSSoc22?

**Comment by SHAIKASIFALI** [comment]
I would love to work on this issue under the jwoc 2k23 can u please assign me this issue

**Comment by Kajol-Kumari** [comment]
@SHAIKASIFALI waiting for your progress on this

**Comment by SHAIKASIFALI** [comment]
@Kajol-Kumari working on it will update you on sunday

**Comment by SwayamRana808** [comment]
I would love to work on this issue under the GGSoc '24 can u please assign me this issue.

**Comment by Kajol-Kumari** [comment]
@SwayamRana808  please go ahead with this issue. Happy Learning :)

**Comment by SwayamRana808** [comment]
[api ](https://github.com/HITK-TECH-Community/Community-Website/blob/main/backend/app/routes/admin/getAdmins.js)
return array 
![Screenshot 2024-05-13 095246](https://github.com/HITK-TECH-Community/Community-Website/assets/122097724/c095b309-ee23-4dda-9575-9c5b3ae15645)
how can i filter a logged in admin .Can you please help.

**Comment by SwayamRana808** [comment]
should i store username or email in localstorage to compare it with above?

**Comment by Kajol-Kumari** [comment]
@SwayamRana808 seems like first there is need of getAdmin api, which should return the current loggedIn admin detail using its emailId, let me raise a issue for that

**Comment by Kajol-Kumari** [comment]
This issue depends on https://github.com/HITK-TECH-Community/Community-Website/issues/869, I will keep it on hold till the required api gets created

**Comment by Kajol-Kumari** [comment]
Hey @SwayamRana808 
The api exists and below is curl for the same. Also, just FYI that current implementation of admin page is based on localstorage, in this pr, please replace it with the getAdmin api call - 


```
curl --location --request GET 'https://community-website-backend.onrender.com/admin?type=self' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer <token>' \
--data-raw '{
    "email": "hitktechcommunity@gmail.com"
}'
```

**Comment by SwayamRana808** [comment]
but how i will get email? please help!

**Comment by Kajol-Kumari** [comment]
> but how i will get email? please help!

that you can get from local-storage.

**Comment by SwayamRana808** [comment]
i think this issue is solved using local storage . I  can implement getAdmin api that uses just token if you want to ?

**Comment by Kajol-Kumari** [comment]
> i think this issue is solved using local storage

That's right, but i want you to implement it using the api like i shared above - https://github.com/HITK-TECH-Community/Community-Website/issues/767#issuecomment-2107847643

**Comment by SwayamRana808** [comment]
what should i do? @Kajol-Kumari

**Comment by SwayamRana808** [comment]
But isn't it is logged out?

**Comment by Kajol-Kumari** [comment]
> But isn't it is logged out?

we will only showing the admin profile when admin in logged in right? and as soon as admin logs in, we set the emailId in localstorage, so i am not getting what exact issue you are facing?

**Comment by SwayamRana808** [comment]
the route of api that we have to integrate uses get method
![Screenshot 2024-05-15 135556](https://github.com/HITK-TECH-Community/Community-Website/assets/122097724/b3ae4b7b-c2dd-4b92-a038-be2d5785fb78)
and inside api we use request body email
![Screenshot 2024-05-15 135614](https://github.com/HITK-TECH-Community/Community-Website/assets/122097724/2a2c466f-9a1b-4c6e-89e6-871e8fe4d729)
and when i 
![Screenshot 2024-05-15 135634](https://github.com/HITK-TECH-Community/Community-Website/assets/122097724/60779a21-ac03-4ec5-8544-f7a0b769e1f3)
tried to fetch data using get method i got error

**Comment by Kajol-Kumari** [comment]
ah, i see, probably we should change the api to take the email as query param instead of body as its never a good idea to have body in get api, will you be willing on the fixing the api(if yes, please raise an issue and start working) else i will create one

**Comment by SwayamRana808** [comment]
yes , I have raised issue #883 . please assign me .
