### ISSUE TITLE
[Frontend] Enhancement in the Website

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#771]
Deliverables-

- [ ] Add loader the the admin login api call i.e in [this](https://github.com/HITK-TECH-Community/Community-Website/blob/main/frontend/src/pages/Login/Login.jsx#L91) function
- [ ] The Manager broadcast page should show the list of all apis [Please refer all broadcast page for the same]
- [ ] Shift the `Open Source Contributors` section from `About Us` ([here](https://hitk-tech-community.netlify.app/about-us)) page to the `Get Involved Page` ([here](https://hitk-tech-community.netlify.app/get-involved)) Also rename the title to `Our Open Source Contributors`
- [ ] Make the cursor to pointer when hovering over the `change theme` button

**Comment by abhinav80066** [comment]
Hey @Kajol-Kumari, I would like to work on this issue. Please assign me this issue.

**Comment by Kajol-Kumari** [comment]
@nitishsaini706 we already have the three-dotted loaded defined under `util`. You just need to use it.

**Comment by nitishsaini706** [comment]
@Kajol-Kumari I've installed project for the third time and I'm still facing same errors , Could you please help

**Comment by Kajol-Kumari** [comment]
@nitishsaini706 can you please share me via discord/here what issue you are facing?

**Comment by nitishsaini706** [comment]
@Kajol-Kumari Done.I've informed in the group that i need help

**Comment by aakankshabhende** [comment]
@nitishsaini706 is your issue solved?

**Comment by nitishsaini706** [comment]
@aakankshabhende no you can work on this issue

**Comment by aakankshabhende** [comment]
Okay I'll assign this issue to someone else @nitishsaini706

**Comment by Aman16-ai** [comment]
can i work on this issue?

**Comment by AyushSingh22** [comment]
Go ahead @Aman16-ai

**Comment by Aman16-ai** [comment]
Can you please explain this : The Manager broadcast page should show the list of all apis [Please refer all broadcast page for the same]

> Deliverables-
> 
> * [ ]  Add loader the the admin login api call i.e in [this](https://github.com/HITK-TECH-Community/Community-Website/blob/main/frontend/src/pages/Login/Login.jsx#L91) function
> * [ ]  The Manager broadcast page should show the list of all apis [Please refer all broadcast page for the same]
> * [ ]  Shift the `Open Source Contributors` section from `About Us` ([here](https://hitk-tech-community.netlify.app/about-us)) page to the `Get Involved Page` ([here](https://hitk-tech-community.netlify.app/get-involved)) Also rename the title to `Our Open Source Contributors`
> * [ ]  Make the cursor to pointer when hovering over the `change theme` button

In 2nd task do i need to show all backend apis in admin's broadcast manager ?

**Comment by Kajol-Kumari** [comment]
@Aman16-ai No, typo from my end. What I meant is in the admin's broadcast page, we need the whole list of broadcasts just like we have in all broadcast page. As of now, only few list of broadcasts is being shown on the admin panel

**Comment by navyasharma0203** [comment]
Can I work on this issue??

**Comment by AyushSingh22** [comment]
@Aman16-ai  Kindly Update, whether you are working or not.
Its 12 days Now.
