### ISSUE TITLE
[Frontend] Integarate Join Us Delete Feature

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#773]
Deliverables-

- [ ] The `URL` on the resource list card should open up in a new tab. Use `target=_blank` for the same
- [ ] Integrate the `Delete` api present at [here](https://github.com/HITK-TECH-Community/Community-Website/blob/main/backend/app/routes/resources/deleteResource.js) with the `DELETE` button present on the ui
- [ ] A loader should be present during the api call(similar to the get one) and a toast msg (based on success/error) should be shown. For success- "resource deleted successfully!" and "something went wrong" for error

In order to see the resource list page-
1. Log in as admin
2. Click on `Resources` tab

**Comment by vinrusty** [comment]
Can I please work on this issue?

**Comment by Kajol-Kumari** [comment]
sure, please go ahead @vinrusty

**Comment by vinrusty** [comment]
should the loader be for the card or for the entire page? @Kajol-Kumari
