### ISSUE TITLE
[Backend] Add API For Deletion

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#774]
Deliverables-

- [ ] DELETE API for Join Us. It should reside under [this](https://github.com/HITK-TECH-Community/Community-Website/tree/main/backend/app/routes/joinUs) folder
- [ ] DELETE API for the Team Member. It should reside under [this](https://github.com/HITK-TECH-Community/Community-Website/tree/main/backend/app/routes/teamMember) folder
- [ ] Write the tests for both the apis

**Comment by Aman16-ai** [comment]
can i work on this issue?

**Comment by Kajol-Kumari** [comment]
please go ahead @Aman16-ai
