### ISSUE TITLE
[Backend] Add API For Updation

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#775]
Deliverables-

- [ ] Add Update api for Team Members. It should reside under [this](https://github.com/HITK-TECH-Community/Community-Website/tree/main/backend/app/routes/teamMember)folder
- [ ] Add update api for FAQs. It should reside under [this](https://github.com/HITK-TECH-Community/Community-Website/tree/main/backend/app/routes/faq) folder
- [ ] Write tests for both the pis

**Comment by Aman16-ai** [comment]
can i work on this issue?
