### ISSUE TITLE
[Frontend] Integrate GET Questions in Frontend

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#784]
Deliverables-

- [ ] As soon as someone visits on `Q&A` page, there should be the [GET Questions](https://github.com/HITK-TECH-Community/Community-Website/blob/main/backend/app/routes/Q%26A/question/getAllQuestion.js) call.
- [ ] The list of questions should appear one below another in the form of listed card having the upvotes/downvote icon, total upvote/downvote count and all the required data [ This might need discussion , so please share the design before moving to code]

**Comment by vinrusty** [comment]
Can I please work on this issue?

**Comment by Kajol-Kumari** [comment]
Please go ahead @vinrusty

Please share the ui u have in your mind before implementing so that we don't make unnecessary effort..

**Comment by aakankshabhende** [comment]
Any updates? @vinrusty

**Comment by nisKULDEEP** [comment]
can you assign this to me

**Comment by Bikram-ghuku** [comment]
Can I work on this Issue?

**Comment by monoMonu** [comment]
@Kajol-Kumari can you please assign this issue to me under SWOC season 4?

**Comment by TejasNasre** [comment]
Hey @Kajol-Kumari this issue is too old  i guess i want to work on this issue.If you please assign me this issue it would be great for me as you mentioned in the description you need some ui so i am attaching screenshots :

![uiquestion](https://github.com/HITK-TECH-Community/Community-Website/assets/113225478/6072f61a-115c-4149-bf53-306aefa3592f)
As the schema has title,description,tags,upvotes and is Approved also has timestamps so in the ui card when can show the title in heading and desc in para and add the createdAt and by which person name, we can add tags and upvote buttons.

the color theme will be : 
![color](https://github.com/HITK-TECH-Community/Community-Website/assets/113225478/9b571518-6e8d-40d8-8ab4-a9eaf4f127e2)

i want to work on this issue and contribute to community please assign me.
GSSoC'24 Contributor

**Comment by Kajol-Kumari** [comment]
Hey @TejasNasre there are 2 parts to it.
1. to integrate the GET Question backend api with ui
2. the ui to show those questions and capability to `upvote` and `downvote`. The UI you shared is fine but you need to replace the `download` and `answers` as upvote and downvote.

**Comment by TejasNasre** [comment]
thanks to assign me this issue @Kajol-Kumari i will work on it.

yes i will add both dynamic ui and the upvote downvote functionality the ui is only for sample purpose i will change and before make a PR i will share the screenshot here.

**Comment by TejasNasre** [comment]
Getting error while npm install in frontend :

![error](https://github.com/HITK-TECH-Community/Community-Website/assets/113225478/3e7b6354-dc9f-4e85-b8a8-e53784ddd4f3)

problem in node-sass and most of the libraries are deprecated can you please assist me @Kajol-Kumari

**Comment by Kajol-Kumari** [comment]
Hey @TejasNasre you should be using node version 14 for this project, checkout - https://github.com/HITK-TECH-Community/Community-Website/discussions/860

I have already highlighted it in readme installation step as well

**Comment by TejasNasre** [comment]
@Kajol-Kumari Thanks I Will Start Working On Issue

**Comment by TejasNasre** [comment]
i make a simple ui for test and calling api http://localhost:3500/getallquestions but gives Invalid or malformed request and 404 why?

**Comment by TejasNasre** [comment]
i also add test questions to get fetch but not greeting response

**Comment by Kajol-Kumari** [comment]
> i make a simple ui for test and calling api http://localhost:3500/getallquestions but gives Invalid or malformed request and 404 why?

Hey @TejasNasre the path isn't correct. `https://community-website-backend.onrender.com/question/getallquestions` the path should be `/question/getallquestions`

**Comment by TejasNasre** [comment]
Thanks @Kajol-Kumari Successfully integrated get question with frontend i will share soon the integrated ui  in chat i want to sask you i want to hit this https://community-website-backend.onrender.com/question/getallquestions or http://localhost:3500/getallquestions when i make a PR

**Comment by Kajol-Kumari** [comment]
@TejasNasre you should just provide the path, the baseurl should be taken form environment variable, please check the other api implementations for reference - https://github.com/HITK-TECH-Community/Community-Website/blob/main/frontend/src/pages/Faq/Faq.jsx#L59

**Comment by TejasNasre** [comment]
I made ui and also add responsiveness and stuff the only remaining thing is upvote and downvote if you will provide to the endpoint it would be great 😃

**Comment by Kajol-Kumari** [comment]
@TejasNasre  this issue is just to integrate the get questions calls. Also, i wonder, how we will show the answers with respective questions in the ui you shared above

**Comment by TejasNasre** [comment]
ok i implemented the getallquestion and showed  in frontend also implemented also implemented upvote functionality now can i raise  PR or if you have any change you can comment now.

**Comment by TejasNasre** [comment]
@Kajol-Kumari if we want to show the answer in the ui we can take the question id and for that question we have answer id so when user click on the question card we can pop out the answer component and showed the answer for that question 😁

**Comment by Kajol-Kumari** [comment]
hmm, the current ui looks fine for now then. please feel free to raise the pr

**Comment by TejasNasre** [comment]
ok i am raising PR
