### ISSUE TITLE
[Frontend] Integrate Get Team on Admin Panel

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#789]
Deliverables-
1. Under Admin Panel, `About Us` => `Manage Team` It should call the Get Team api and the actual data should be populated
2. Clean the redundant team data from the test folder

Note - This issue is dependent on https://github.com/HITK-TECH-Community/Community-Website/issues/723

**Comment by AdnanMuzavor** [comment]
I would like to work on this issue.

**Comment by Kajol-Kumari** [comment]
please go ahead @AdnanMuzavor 
Happy Learning :)

**Comment by aakankshabhende** [comment]
Any updates? @AdnanMuzavor

**Comment by AdnanMuzavor** [comment]
@Kajol-Kumari sorry for delay, occupied with exams these days.
If you want you can unassign me I may take up some other issue, thank you!!

**Comment by its-ayush-07** [comment]
Can I work on this under GSSoc22?

**Comment by AdnanMuzavor** [comment]
On it @aakankshabhende !!

**Comment by AdnanMuzavor** [comment]
@Kajol-Kumari the data which I am getting from backend using API is of team members and not of team.
There is no specific API for getting teams rather the API gives team members who belong to different team.
Shall I render team members and their details as returned by API?

**Comment by arinmodi** [comment]
@Kajol-Kumari, can I work on this ?

**Comment by arinmodi** [comment]
@Kajol-Kumari, https://hitk-community-website-backend.herokuapp.com/teamMember/getTeamMembers, not working

![image](https://user-images.githubusercontent.com/61725413/198549765-01aa0c43-8940-4ef1-b62e-2f2e883b28f3.png)

**Comment by Kajol-Kumari** [comment]
> > @Kajol-Kumari, https://hitk-community-website-backend.herokuapp.com/teamMember/getTeamMembers, not working
> > ![image](https://user-images.githubusercontent.com/61725413/198549765-01aa0c43-8940-4ef1-b62e-2f2e883b28f3.png)
> > In Local, it is working perfect
> 
> @Kajol-Kumari, ?

Can we please check if the baseurl is correctly getting updated after deployment

**Comment by arinmodi** [comment]
To check that, I need heroku access

**Comment by arinmodi** [comment]
@Kajol-Kumari,

![image](https://user-images.githubusercontent.com/61725413/198696024-c5331a09-0da2-4c88-9623-b5e3d5be663c.png)

is this what expected, right ? I changed the API url to localhost url and it's getting response

**Comment by arinmodi** [comment]
> @Kajol-Kumari,
> 
> ![image](https://user-images.githubusercontent.com/61725413/198696024-c5331a09-0da2-4c88-9623-b5e3d5be663c.png)
> 
> is this what expected, right ? I changed the API url to localhost url and it's getting response

@Kajol-Kumari  ?

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari,
> 
> ![image](https://user-images.githubusercontent.com/61725413/198696024-c5331a09-0da2-4c88-9623-b5e3d5be663c.png)
> 
> is this what expected, right ? I changed the API url to localhost url and it's getting response

We need to show all the details except created date & time. Also as far as I remember the Get team api is an authenticated api. Also with the heroku base, i am anticipating CORS issue which we need to fix as we can't deploy with baseurl as localhost

**Comment by arinmodi** [comment]
Get Team API is not authenticated, i checked that

**Comment by arinmodi** [comment]
@Kajol-Kumari, I think backend code changes since last 6 months are not published to heroku cause the all routes which are made or updated during last 6 months are not working on heroku base

**Comment by Kajol-Kumari** [comment]
Hmm.... I am not even able to login (wierd) 👀 
<img width="826" alt="Screenshot 2022-10-30 at 1 01 53 PM" src="https://user-images.githubusercontent.com/44888949/198867527-7d1cedcc-f40c-4ca3-9c2a-280628d6edf2.png">

**Comment by arinmodi** [comment]
@Kajol-Kumari, Currently I am building this feature with localhost url and at the time of PR i will change that url, is it ok ?

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari, Currently I am building this feature with localhost url and at the time of PR i will change that url, is it ok ?

Hi @arinmodi Now, the backend is up. If if have done the change. feel free to raise the PR

**Comment by sarkartanmay393** [comment]
@Kajol-Kumari Hey Kajol, I want to work on it under JWOC

**Comment by Hemu21** [comment]
Hello @Kajol-Kumari can you please assign this issue to me. I am GSSoC'24 contributor.

**Comment by Kajol-Kumari** [comment]
@Hemu21  please go ahead, Happy Learning:)

**Comment by Hemu21** [comment]
@Kajol-Kumari  I had created the PR. can you please check it.
