### ISSUE TITLE
[Backend] Route for adding admins

### ISSUE THREAD

**Issue by jackfrost13** [HITK-TECH-Community/Community-Website#79]
### Work to be done:

- Add a route for creating admins.[POST]
- Validation Schema for the request body
- API Testing using Postman demonstrating all possible cases(valid, invalid) with test cases

#### Request Body Structure:

| Parameter | Description                                        |
| --------- | -------------------------------------------------- |
| email     | string,required, email regex                       |
| password  | string,required                                    |
| firstName | string,optional                                    |
| lastName  | string,optional                                    |
| contact   | string,optional,format(+91XXXXXXXXXX), phone regex |
| username  | string ,optional                                   |

_**NOTE: Please go through the backend code to get a feel of the code structure and follow that.**_

*For API Testing briefing, refer to https://github.com/HITK-TECH-Community/Community-Website/issues/81*

**Comment by hasheemismath** [comment]
I would like to work on this issue, can you assign it to me!
@jackfrost13

**Comment by Kajol-Kumari** [comment]
sure @hasheemismath. Go ahead with this issue!

**Comment by jackfrost13** [comment]
@hasheemismath Can you please update us with your progress on the issue?

**Comment by N00Bmaster2810** [comment]
@jackfrost13 sir if this issue is open can I work on it?

**Comment by jackfrost13** [comment]
@hasheemismath Do you have an update? Else we would be going ahead with other participants

**Comment by jackfrost13** [comment]
@N00Bmaster2810 Go ahead with the issue
@hasheemismath I am removing you due to no response from your end.

**Comment by N00Bmaster2810** [comment]
Ok thank you @jackfrost13

**Comment by jackfrost13** [comment]
> Ok thank you @jackfrost13 

Happy Coding ;)
Just keep a check that you follow our coding practices and code structure ;)
Let me know if you need any inputs from my end!

**Comment by N00Bmaster2810** [comment]
Ok sir @jackfrost13
