### ISSUE TITLE
[Frontend] Join US Enhancements

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#790]
Deliverables-

- [ ] The join Us cards under the admin panel should not have the `URL` button as it doesn't seem to require
- [ ] The `LinkedIn` text should open the linkedIn url in a new Page
- [ ] The delete button should call the delete api present [here](https://github.com/HITK-TECH-Community/Community-Website/blob/main/backend/app/routes/joinUs/deleteJoinUs.js) with proper toast message [Take reference from Resource deletion]

For seeing the Join Us page-
1. Log In as admin
2. Click to Join Us card from dashboard

**Comment by rahulthakur19** [comment]
Can i work on this issue? @Kajol-Kumari

**Comment by Kajol-Kumari** [comment]
Go ahead @rahulthakur19 

Happy Learning :)

**Comment by aakankshabhende** [comment]
Any updates? @rahulthakur19

**Comment by rahulthakur19** [comment]
Working on it.

**Comment by srivastavaritik** [comment]
Please assign me this issue if not solved yet

**Comment by AyushSingh22** [comment]
@rahulthakur19  Its more than a month Now !
Let us assign to someone else.

**Comment by srivastavaritik** [comment]
> @rahulthakur19 Its more than a month Now ! Let us assign to someone else.

please assign me this issue

**Comment by srivastavaritik** [comment]
> @rahulthakur19 Its more than a month Now ! Let us assign to someone else.

please assign me this issue

**Comment by himanshu1221** [comment]
Hey I want to work on this issue could you please assign me this under JWOC

**Comment by himanshu1221** [comment]
hey @Kajol-Kumari I a quite busy with my schedule removing my assignment

**Comment by yashpandey06** [comment]
I want to work for on this issue . please assign

**Comment by sohail300** [comment]
Hey, can u assign me this issue?

**Comment by Kajol-Kumari** [comment]
@sohail300  assigning it to you, please keep on updating the progress. Happy Learning :)

**Comment by thevirengarg** [comment]
Hey @sohail300, 
What's the progress on the issue??

**Comment by sohail300** [comment]
> Hey @sohail300, What's the progress on the issue??

Currently on the third one.

**Comment by thevirengarg** [comment]
> > Hey @sohail300, What's the progress on the issue??
> 
> Currently on the third one.

Till when you expect to make a Pull request for this issue.

**Comment by sohail300** [comment]
Surely will make it today.

**Comment by SwayamRana808** [comment]
I would like to work on this under GGSOC '24 .Please assign this to me.

**Comment by Kajol-Kumari** [comment]
@SwayamRana808  please go ahead with the issue. Happy Learning :)

**Comment by SwayamRana808** [comment]
Hi , i have made the changes can you please review it .
