### ISSUE TITLE
Adding issue forms for the repo

### ISSUE THREAD

**Issue by MonarchGitHub** [HITK-TECH-Community/Community-Website#792]
I want to add a few issue forms so that it will be convenient for new contributors to open issues. There are already issue templates for this project but they are deprecated now, issue forms instead work way better. I plan to create  **Bug Report**, **Documentation**,  and **Feature Request** forms. 

**_The Bug Report issue form will have the following fields_**

- **Description of the bug**
- **How to Reproduce**
- **Expected behavior**
- **Urgency indicator**
- **Desktop Info (OS, Version, Browser, etc):**

**_The Documentation issue form will have the following fields_**

- **Description for documentation**

**_The Feature Request issue form will have the following fields_**

- **Is your feature request related to a problem? Please describe.**
- **Describe the solution you'd like**
- **Describe alternatives you've considered**

**Comment by aakankshabhende** [comment]
@MonarchGitHub do you mean a PR template?

**Comment by MonarchGitHub** [comment]
No, issue templates are similar to PR templates but they are used to create issues. I will attach a screenshot of the issue templates below:-

<img width="632" alt="ace 33-2" src="https://user-images.githubusercontent.com/74449136/165888339-42a0caa8-5bdf-4d95-9aad-5532dfdf0811.png">
