### ISSUE TITLE
[Frontend] Integrating the POST Resource with the form

### ISSUE THREAD

**Issue by TG922** [HITK-TECH-Community/Community-Website#793]
### Deliverables:
 
- [ ]  Integrate the https://hitk-tech-community.netlify.app/resources form with backend [POST] api
 
 Ref - https://github.com/HITK-TECH-Community/Community-Website/blob/main/backend/app/routes/resources/addResource.js

**Comment by Kajol-Kumari** [comment]
@TG922 this is duplicate of https://github.com/HITK-TECH-Community/Community-Website/issues/759 
Please feel free to claim it and raise the pr for the same

**Comment by TG922** [comment]
Ok @Kajol-Kumari
