### ISSUE TITLE
Improve UI of Contact Us page

### ISSUE THREAD

**Issue by SachinMittal1766** [HITK-TECH-Community/Community-Website#797]
**Is your feature request related to a problem? Please describe.**
Current UI of Contact Us page can be improved.

**Describe the solution you'd like**
I would like to modify it.

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Yes

**Comment by aakankshabhende** [comment]
You can start working on the issue @SachinMittal1766

**Comment by AyushSingh22** [comment]
Kindly Update regarding your progress so far @SachinMittal1766

**Comment by amreekminocha** [comment]
Hi.. is there anyone working on the issue
If not I will be glad to work upon it.

**Comment by Aniket-011** [comment]
I want to work on this issue under JWOC

**Comment by abhrajit117** [comment]
I want to work on this issue to enhance the UI for a better interaction

**Comment by Kajol-Kumari** [comment]
> I want to work on this issue under JWOC

Sure, give it a try.

**Comment by Code1705** [comment]
i want to contribute to this issue under JWOC, please assign me

**Comment by Code1705** [comment]
I want to contribute by making the contact us ui attractive, please assign me under JWOC.

**Comment by Kajol-Kumari** [comment]
Assigning it to @Coder-Srinivas as i didn't get any update since 2 weeks

**Comment by Code1705** [comment]
Please label the issue under jwoc

**Comment by Code1705** [comment]
please label the issue after that i can start working

**Comment by Awesomeasma** [comment]
I would like to work on this under JWOC
