### ISSUE TITLE
Refactoring <component-name> component

### ISSUE THREAD

**Issue by AyushSingh22** [HITK-TECH-Community/Community-Website#799]
Refactoring the `Curious to know More about Us?` as per the [proposed style](https://github.com/HITK-TECH-Community/Community-Website/blob/main/frontend/PROPOSAL.md). 

**- We can see all the fonts are varied in each section** 
**- The vector and graphics are also unsystematic**  
**- The color, graphics, and design are also making this section fuzzier**

![Screenshot (893)](https://user-images.githubusercontent.com/63851629/167243026-58bfcbdf-e437-4ec5-a25d-0c8a9cf97c4b.png)

**Additional context**
**Refactor / Redesign this section with an aligned & uniform set of graphics design, color and front.**

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Write your answer here.
Yes

**Comment by vasantisuthar** [comment]
I am a GSSOC'22 contributor and I would like to work on this issue. 
Please assign this to me.

**Comment by aakankshabhende** [comment]
You can start working on this issue @AyushSingh22

**Comment by AyushSingh22** [comment]
> You can start working on this issue @AyushSingh22

I am a mentor  for this project like you :)

**Comment by AyushSingh22** [comment]
> I am a GSSOC'22 contributor and I would like to work on this issue. Please assign this to me.

**Go ahead @vasantisuthar** 
All the best !!

**Comment by srivastavaritik** [comment]
Please assign me this issue if it is not solved yet.

**Comment by AyushSingh22** [comment]
Kindly Update @vasantisuthar 
Its 10 days now.

**Comment by vasantisuthar** [comment]
I'll submit the PR in the next 2 days. Sorry for delay.

**Comment by AyushSingh22** [comment]
@vasantisuthar Its your last call.

**Comment by vasantisuthar** [comment]
I have designed the images, graphics, and fonts of the section and added them to the project also. But I am unable to install the dependencies, it is giving me the error.

**Comment by vasantisuthar** [comment]
I am getting errors of deprecated dependencies. Unable to install packages

**Comment by vasantisuthar** [comment]
> I am getting errors of deprecated dependencies. Unable to install packages

@AyushSingh22 can you please have a look?

**Comment by SwayamRana808** [comment]
I am a GSSOC'24 contributor . I would love to work on this issue.
Please assign this to me.

**Comment by Kajol-Kumari** [comment]
closing this one, will later take it as enhancement
