### ISSUE TITLE
Refactoring resources component

### ISSUE THREAD

**Issue by vasantisuthar** [HITK-TECH-Community/Community-Website#801]
Refactoring the resources as per the [resources](https://github.com/HITK-TECH-Community/Community-Website/blob/main/frontend/PROPOSAL.md). 

The resources page needs UI enhancement, also the image should not be there in responsive mobile layout as it hides the actually resources form, the page should be elegant and focused on the design that drive good user interaction.

If this needs to be enhanced, I would like to work on this issue.

**Comment by aakankshabhende** [comment]
You can start working on it @vasantisuthar

**Comment by biswarup-naha** [comment]
@aakankshabhende I can make the necessary changes if assigned to me.

**Comment by Kajol-Kumari** [comment]
closing it out as it doesn't fall under current MVP scope
