### ISSUE TITLE
Improvement of UI of 'Email' input field in Footer

### ISSUE THREAD

**Issue by AbirSantra** [HITK-TECH-Community/Community-Website#802]
**Describe your Proposal**
I would like to suggest that the placeholder, as well as the text in the 'Email' input field of the Newsletter Signup form in the footer, be left-aligned since it looks better in my opinion.

**Additional context**
Currently, the input field is center-aligned. As shown in the screenshot attached.

![image](https://user-images.githubusercontent.com/78201921/167668740-a1d6b00b-877b-471a-90e8-189415273175.png)

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Yes, I have read the Code of Conduct.

**Comment by aakankshabhende** [comment]
Yes you can start working on it @AbirSantra

**Comment by arinmodi** [comment]
@Kajol-Kumari, can I work on this ?

**Comment by kshitij01042002** [comment]
@Kajol-Kumari can you assign me this under KWoC?

**Comment by Aarav238** [comment]
I would like to work on it @Kajol-Kumari . Please assign this to me.

**Comment by Code1705** [comment]
i want to contribute to this issue under JWOC please assign me.

**Comment by Kajol-Kumari** [comment]
Hi @Code1705 we can't assign an issue to more than one person so please look for the unassigned issue

**Comment by Aarav238** [comment]
by today i will raise pr regarding this issue @Kajol-Kumari

**Comment by Aarav238** [comment]
@Kajol-Kumari  I am facing some issues in raising pr

**Comment by vk20july** [comment]
I want to work on this issue under jwoc @Kajol-Kumari

**Comment by Shreyansh-333** [comment]
@Kajol-Kumari I just attended your live session for SWOC. I can work on this if it still needs to be done. Thank You

**Comment by AmulGaurav** [comment]
Hey, I would like to work on this issue under SWOC.

**Comment by Kajol-Kumari** [comment]
I am assigning it to @Shreyansh-333  on the basis of FCFS, if not updated within a week @AmulGaurav  please feel free to take this up.

**Comment by Kajol-Kumari** [comment]
@Amruta7203 assigning it to you

**Comment by Amruta7203** [comment]
@Kajol-Kumari Assign this issue to me
