### ISSUE TITLE
Update "curious to know more about us" section

### ISSUE THREAD

**Issue by Ranjana550** [HITK-TECH-Community/Community-Website#805]
Heyy,
I would like to update the "curious to know more about us" section according to the theme of the website.
The font styles used here, in this section are not uniform so would like to create new designs for the same.
I am a GSSOC'22 contributor, please assign it to me.

![image](https://user-images.githubusercontent.com/71266173/169651089-ac3a32ba-a597-4a9a-a628-3074404eb583.png)

Thank you in advance! :)

**Comment by AyushSingh22** [comment]
@Ranjana550 This issue is already in process. #799 
Thank you for your concern.
