### ISSUE TITLE
Change the color of JoinUs Section

### ISSUE THREAD

**Issue by AbhiPatel10** [HITK-TECH-Community/Community-Website#813]
**Describe the bug**

Join Us Section is not looks good. We need to set as per the Theme color.

**To Reproduce**
1. Go to 'Home Page
3. Scroll down to Join Us section

**Expected behavior**

Currunt Join Us Section
![image](https://user-images.githubusercontent.com/76242769/223101036-7af17af7-f436-4486-afc7-735a30281d1c.png)

We Can it to like this
![image](https://user-images.githubusercontent.com/76242769/223101605-7160ef8e-22e0-4aaa-b83b-d5c2f56e1ee6.png)

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 
All

**Additional context**

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Write your answer here.

Yes

**Comment by AbhiPatel10** [comment]
Please assign this issue to me under JWOC

**Comment by mani200307** [comment]
Can I work up on with this issue?

**Comment by karantec** [comment]
please assign me this issue under gSSOC 2023

**Comment by AyushDhimanIITR** [comment]
Can I work on it?

**Comment by yashpandey06** [comment]
I want to work for on this issue under jwoc , please assign me

**Comment by Shivgitcode** [comment]
Please assign this issue to me @thevirengarg

**Comment by kashi-verma** [comment]
please assign the project to me

**Comment by kashi-verma** [comment]
Thanks @HITK-TECH-Community/Community-Website

**Comment by Swapnil-Bhatnagar** [comment]
Please assign this issue to me sir! I want to fix it out

**Comment by Harshaljain04** [comment]
Hey @kashi-verma please assign this issue to me, I'll complete it as required

**Comment by Kajol-Kumari** [comment]
@kashi-verma  can you update the progress of this issue?

**Comment by kashi-verma** [comment]
Yes, I am working on it. 0

**Comment by Kajol-Kumari** [comment]
closed via #929
