### ISSUE TITLE
Change in the About Section

### ISSUE THREAD

**Issue by Satyam5665** [HITK-TECH-Community/Community-Website#816]
**Is your feature request related to a problem? Please describe.**
Yes, in the About Section, there is no profile picture displayed for founders and Co-founders and Board Members.

**Describe the solution you'd like**
I will add the profile pictures of all members taking if from their respective professional social-sites.

**Describe alternatives you've considered**
Either to remove the picture component.

**Additional context**

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Yes, I have went through the Code of Conduct and I'll follow it.

**Comment by younikarn** [comment]
Can I take this issue? Please assign it to me

**Comment by singodiyashubham87** [comment]
@Satyam5665 Will you please explain, how are you going to proceed with the issue.

**Comment by Iisha10** [comment]
@Satyam5665  can you please explain the issue?do we just have to add the profile picture of members?

**Comment by Kajol-Kumari** [comment]
Closing this one as seems like we already have issue created for about section
