### ISSUE TITLE
Adding scroll-reveal to improve the UI || Work under KWoC

### ISSUE THREAD

**Issue by sambitsingha** [HITK-TECH-Community/Community-Website#818]
**The scroll reveal , if added will load the elements one affter the other. It can be customised according to time-delay and directions according the UI.**

**Comment by Muhammad-Owais-Warsi** [comment]
Hey, can i contribute to this issue, it would be great.

**Comment by Kajol-Kumari** [comment]
Hey @Muhammad-Owais-Warsi We already have the scroll feature in our website. Any further elaboration would be good. Also, i would like to prioratize the functionality first so would recommend to check the opened issue and pick from them for contribution

**Comment by Muhammad-Owais-Warsi** [comment]
Okay, thanks for the info.

**Comment by sambitsingha** [comment]
@Kajol-Kumari Like I have mentioned , the **scroll reveal I am talking about , tends to reveal each element of the website on scroll.**
## Below is a demo video of what I am talking about**


https://github.com/HITK-TECH-Community/Community-Website/assets/110420002/2d0ce42d-ebe6-4f28-b947-f3a345a58ab3

### I opened this issue to add this feature. Would like to work on it , if assigned. Thank you :)

**Comment by Muhammad-Owais-Warsi** [comment]
Okay, thank you to let me know
