### ISSUE TITLE
[Typo] In the nav bar

### ISSUE THREAD

**Issue by Balaji-Avk** [HITK-TECH-Community/Community-Website#819]
**Describe the bug**
There is a typo in nav bar , it shows "admin ?" instead of "admin"

**To Reproduce**
1. Go to 'login page'
2. See error

**Expected behavior**
It should be admin

**Screenshots**
![image](https://github.com/HITK-TECH-Community/Community-Website/assets/132835499/180dfdfd-42b8-42ef-8574-1b848ad509cb)

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
yes

**Comment by Kajol-Kumari** [comment]
Hey @Balaji-Avk  its intentional. Think of it like asking the user if he is an admin or not.
