### ISSUE TITLE
Login page is just loading 

### ISSUE THREAD

**Issue by Shu12388y** [HITK-TECH-Community/Community-Website#820]
**Describe the bug**
When a user is try to login with wrong id and password the UI is  just loading 

**To Reproduce**
1. First we have to handle the error
2. I want to add npm package that react hot toast
3. Which will give a good user experience and good way of handle error

**Expected behavior**

**Screenshots**
![Screenshot (121)](https://github.com/HITK-TECH-Community/Community-Website/assets/91714143/13d064e8-b02f-487f-90a3-99b4d00d4f16)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Write your answer here.
yes

**Comment by Shu12388y** [comment]
@Kajol-Kumari can you assign this issue to me under swoc

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari can you assign this issue to me under swoc

I think, the interface is loading 'coz api is failing to give the response. I will check on this once and then assign it to u if this is actually an issue.

**Comment by Kajol-Kumari** [comment]
closing it as it has been fixed now. There was some issue with backend server
