### ISSUE TITLE
Refactoring Improve the UI of the FAQ section

### ISSUE THREAD

**Issue by Shu12388y** [HITK-TECH-Community/Community-Website#821]
Refactoring the `<component name>` as per the [proposed style](https://github.com/HITK-TECH-Community/Community-Website/blob/main/frontend/PROPOSAL.md). 

**Additional context**
I want to improve the UI section of FAQ

![Screenshot (122)](https://github.com/HITK-TECH-Community/Community-Website/assets/91714143/77358b50-9bf2-4124-a2df-ab43be9678b4)

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Write your answer here.
yes

@Kajol-Kumari can you assign this issue to me under swoc

**Comment by younikarn** [comment]
Can I take this issue?

**Comment by Thanush19** [comment]
i'll work on this....

**Comment by Ankitapanda25** [comment]
hello @Shu12388y  could you assign it to me? I would really like to work on this

**Comment by thevirengarg** [comment]
@Shu12388y Any update on the progress of the issue?

**Comment by Shu12388y** [comment]
@thevirengarg I am  working on it. I am designing it on figma  after that I will code it

**Comment by Shu12388y** [comment]
@thevirengarg can I use ui libraries in this project or plain css

**Comment by thevirengarg** [comment]
> @thevirengarg can I use ui libraries in this project or plain css

It's up to you, whichever you feel will be better for the website and in which you are more comfortable. 
I feel using the UI Library would be better.

**Comment by thevirengarg** [comment]
@Shu12388y Are you still working on this pull request? Please update us with the progress.

**Comment by Shu12388y** [comment]
@thevirengarg yes i am working on it

**Comment by thevirengarg** [comment]
@Shu12388y If you don't raise a PR in 24 hours, I will unassign you the issue.

**Comment by masterboy376** [comment]
Hello @thevirengarg, I have successfully setup the project on my local machine, and would be all set to solve this issue under GSSOC'24

**Comment by kanishk-2** [comment]
Hi @Kajol-Kumari I'm a gssoc'24 contributor i would like to contribute to this project and solve this issue plz assign this issue to me

**Comment by A-b-i-r-a-m-i-G-S** [comment]
@Kajol-Kumari I would like to work on the issue as part of GSSOC'24. Kindly assign the issue to me.

**Comment by Kajol-Kumari** [comment]
Hey folks, the `proposal.md` file doesn't exist anymore as the required changes has been done so closing this issue
