### ISSUE TITLE
[Style]: Enhance Background Pattern Visibility

### ISSUE THREAD

**Issue by harmeetsingh11** [HITK-TECH-Community/Community-Website#825]
**Description:**
The current background pattern is minimally visible and becomes apparent only when viewed closely against the plain white background. To improve user experience and aesthetics, I propose adding a dynamic and more visible pattern background with distinct colors.

**Proposed Changes:**
Introduce a  pattern background that enhances visibility and adds a touch of color to the overall design. This will contribute to a more engaging and visually appealing user interface.

**Additional Context:**
Consider experimenting with different color schemes and patterns to find the optimal combination that not only improves visibility but also aligns with the design aesthetics.

**Expected Behavior:**
Users should experience a more noticeable and dynamic background pattern that complements the overall design.

**Screenshots**

![HITK-Tech-Community](https://github.com/HITK-TECH-Community/Community-Website/assets/130365071/41073d7e-d56a-429d-9b2c-cfe72513f1cc)

**Record**

- [x] I agree to follow this project's Code of Conduct 
- [x] I'm a SWOC 4.0 contributor
- [x] I want to work on this issue

**Comment by harmeetsingh11** [comment]
@thevirengarg I'm attempting to set up this project locally, but I encounter the same error every time. I've tried a few solutions without success. Even when attempting to install it on Codespaces, I still face this persistent issue. Can you assist me with this?
![Screenshot 2024-01-11 201421](https://github.com/HITK-TECH-Community/Community-Website/assets/130365071/091f62a7-03de-4680-9107-e9163c0c9d2d)

**Comment by thevirengarg** [comment]
> @thevirengarg I'm attempting to set up this project locally, but I encounter the same error every time. I've tried a few solutions without success. Even when attempting to install it on Codespaces, I still face this persistent issue. Can you assist me with this?
> 
> ![Screenshot 2024-01-11 201421](https://private-user-images.githubusercontent.com/130365071/295952481-091f62a7-03de-4680-9107-e9163c0c9d2d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5OTk2NTcsIm5iZiI6MTcwNDk5OTM1NywicGF0aCI6Ii8xMzAzNjUwNzEvMjk1OTUyNDgxLTA5MWY2MmE3LTAzZGUtNDY4MC05MTA3LWU5MTYzYzBjOWQyZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMVQxODU1NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYmU2MjFhNTM0NDNiODEwZDBkMTVkNDdjNmY5Nzc0OTIwYTdmNjRjMTYyMzBkZTkwOTE0NzZiMDQ2ODIyMjU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JKwdTx0JpYTcr8be56VDrzPFNW_qEj9WsVsouOOjXEg)

@Kajol-Kumari

**Comment by Kajol-Kumari** [comment]
@harmeetsingh11 Make sure you are on node version 14, you can manage multiple node versions using [nvm](https://github.com/nvm-sh/nvm/blob/master/README.md) package. Then delete the `node_modules` , then run `npm install` and then try runing the project

**Comment by harmeetsingh11** [comment]
> @harmeetsingh11 Make sure you are on node version 14, you can manage multiple node versions using [nvm](https://github.com/nvm-sh/nvm/blob/master/README.md) package. Then delete the `node_modules` , then run `npm install` and then try runing the project

@Kajol-Kumari it worked!
Thanks for the solution:)

**Comment by thevirengarg** [comment]
@harmeetsingh11 What's the progress on this pull request??

**Comment by harmeetsingh11** [comment]
@thevirengarg I am working on it.
