### ISSUE TITLE
[BUG]: Address Console Logs When Switching Theme

### ISSUE THREAD

**Issue by harmeetsingh11** [HITK-TECH-Community/Community-Website#826]
**Description:**
Switching the theme from light to dark and vice versa triggers console logs, impacting the user experience. Additionally, there are other logs present that are not suitable for production code.

**Problem:**
The current logging behavior during theme transitions and the presence of unnecessary logs could lead to a less than optimal user experience and may not align with production standards.

**Proposed Changes:**
1. Investigate and resolve console logs triggered during theme changes.
2. Review and remove unnecessary logs that are not suitable for production environments.

**Expected Behavior:**
Theme transitions should occur smoothly without generating console logs. The codebase should adhere to best practices, ensuring a clean and log-free experience for end-users.

**Screenshots**
![Screenshot 2024-01-08 210521](https://github.com/HITK-TECH-Community/Community-Website/assets/130365071/c0826017-b3d9-4467-926d-03fa55851dfa)

**Record** 

- [x] I agree to follow this project's Code of Conduct 
- [x] I'm a SWOC 4.0 contributor
- [x] I want to work on this issue

**Comment by vink08** [comment]
What strategy do you plan for investigating and resolving the console logs triggered during theme changes?

**Comment by harmeetsingh11** [comment]
@vink08 Here's the strategy:
1. Conduct a thorough review of the codebase, specifically focusing on the parts responsible for theme transitions.
2. Identify the specific points in the code where console logs are triggered during theme changes.
3. Analyze the logic and conditions leading to the console logs. Check for any unintended side effects or unnecessary logging statements.
