### ISSUE TITLE
Footer Email Input Validation Message Appears Unnecessarily When Input is Not Provided; Social media icons fails animation on hover [swoc24]

### ISSUE THREAD

**Issue by Shivgitcode** [HITK-TECH-Community/Community-Website#828]
**Describe the bug**

1. Footer Email Input Validation:
When the email input box in the footer is active, the validation message indicating "email required" appears even when no input is provided. This behavior is misleading and should only trigger when a user submits the form without entering a valid email address.

2. Social Media Icons Animation:
On hovering over the social media icons in the footer, some of them fail to display the expected animation. This impacts the user experience, and we need to ensure a consistent and smooth animation for all social media icons.

**To Reproduce**

Footer Email Input Validation:

1. Scroll down to the footer.
2. Click on the email input box.
3. Notice that the "email required" validation message appears even when no input is provided.

Social Media Icons Animation:

1. Scroll down to the footer.
2. Hover over each social media icon in the footer.
3. Observe that some icons do not display the expected animation on hover.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Write your answer here.

**Comment by Jenis07** [comment]
Can you please assign me this issue under IWOC?

**Comment by adi-exe** [comment]
my work is under the process for the issue, can you assign this to please.

**Comment by thevirengarg** [comment]
@adi-exe You can work on it.

**Comment by adi-exe** [comment]
where can i talk about the issue with collaborators. The project is throwing error while install.

**Comment by thevirengarg** [comment]
@adi-exe Use node v14.21.3

**Comment by thevirengarg** [comment]
And you can use discord or slack to communicate, slack link is in the README. Or use SWoC discord channel

**Comment by adi-exe** [comment]
@thevirengarg  sir, can you please add IWOC label to it .
