### ISSUE TITLE
dashbord route protection

### ISSUE THREAD

**Issue by Shu12388y** [HITK-TECH-Community/Community-Website#830]
**Describe the bug**
When we explicitly dashboard route is hitted it is show 404 error page but it should redirect to login page

**To Reproduce**

**Expected behavior**
It should redirect to login page

**Screenshots**
![Screenshot (124)](https://github.com/HITK-TECH-Community/Community-Website/assets/91714143/c6ab394b-63c6-4c08-ba13-505db00c5fb2)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Write your answer here.

**Comment by Kajol-Kumari** [comment]
@Shu12388y  very small bug but should be addressed. Please go ahead with the fix. Happy Learning :)

**Comment by thevirengarg** [comment]
@Shu12388y Are you still working on this issue? What's the progress?

**Comment by Shu12388y** [comment]
@thevirengarg yes i am working on it

**Comment by SwayamRana808** [comment]
please assign me this issue.
