### ISSUE TITLE
Adding GSAP animations to the website

### ISSUE THREAD

**Issue by JATIN0926** [HITK-TECH-Community/Community-Website#839]
I want to add some minimilistic animations to your whole website which will look good , animations will also be on scrolling based , i am giving a link to my one project , where i have added some animations based on scrolling , so you can refer that!

https://elitecricketacademy.netlify.app/

**Comment by vivekop0** [comment]
please assign  under gssoc '24' me this part i can handle the animation u

**Comment by iamrudhresh** [comment]
Hey, hope you're doing great! As an GSSoC contributor, I'm keen on ramping up my involvement for GSSoC'24. Could you assign this issue to me? I'm excited to continue contributing to the project. Thanks a bunch!!

**Comment by Kajol-Kumari** [comment]
Hey Folks, I am not looking for over-engineering in the website, want to keep it simple and clean so this issue won't be required.
