### ISSUE TITLE
[Open for all] Logo for our website

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#85]
- The logo that we currently have doesn't fir for our website, so a new logo is required which will look better as icon for our website

**Comment by kanishkaa24** [comment]
I would love to work on this.

**Comment by Kajol-Kumari** [comment]
Sure @kanishkaa24 looking forward to your creativity :)

**Comment by kanishkaa24** [comment]
What kind of a logo are you looking for?

**Comment by Kajol-Kumari** [comment]
> What kind of a logo are you looking for?

@kanishkaa24 if you see our current logo,it's not visible in the navbar clearly. So we are looking for a better logo that can display our motive along with being visible enough in the navbar. Maybe you can try with letters of `HITK` or anything else that you feel relevant

**Comment by Aniket31-coder** [comment]
I would like to work on the logo!

**Comment by Aniket31-coder** [comment]
Hey!
I have given a try for the logo.

Could you please have a look and tell if any changes are required.
![K](https://user-images.githubusercontent.com/55101835/103174197-27792380-4886-11eb-809f-2a3b0864769c.png)

**Comment by Kajol-Kumari** [comment]
@Aniket31-coder please remove the background and just keep the alphabets. You can take reference of `KOSS` logo from [here](https://kossiitkgp.org/)

**Comment by Aniket31-coder** [comment]
Okay, sure would do that.

**Comment by kanishkaa24** [comment]
[https://www.canva.com/design/DAERh_C0YbE/e_aSWhdRSIzPggVJskadrA/view?utm_content=DAERh_C0YbE&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton](url)

**Comment by kanishkaa24** [comment]
![HITK](https://user-images.githubusercontent.com/71253790/103174465-64461a00-4888-11eb-8297-d8ffdc5ccfd5.png)

**Comment by Aniket31-coder** [comment]
Hey!
I have made the changes, could you please let me know if any other changes is needed!
![K (1)](https://user-images.githubusercontent.com/55101835/103174700-509bb300-488a-11eb-94bb-b7946f713f20.png)

**Comment by Muskan10Mehta** [comment]
I would like to work on this!

**Comment by kanishkaa24** [comment]
![ATHAV](https://user-images.githubusercontent.com/71253790/103176560-c1e26280-4898-11eb-9257-db1c6841378e.png)
This is another design.

**Comment by kenkirito** [comment]
![296b303a-6d2f-4569-b664-a2cda5d8d698_200x200](https://user-images.githubusercontent.com/68530218/103180132-e8b09100-48b8-11eb-9642-a3664acb217c.png)

**Comment by himanshu007-creator** [comment]
i will like to work on logo part

**Comment by himanshu007-creator** [comment]
how is this?
![HITK](https://user-images.githubusercontent.com/65963997/103193500-a90e9700-4902-11eb-8e6d-1fe1d8f87207.gif)

**Comment by Kajol-Kumari** [comment]
Hey Everyone! I am glad to see the innovations but let's not stick with the word `HITK`, let's stick to the purpose i.e creating a resource sharing community. You all can make a PR by putting these logos in the `assets/log/<your_name>` folder but I would like to see if you can think something out of the box.

**Comment by himanshu007-creator** [comment]
@Kajol-Kumari  mam i created the log folder, please merge it.

**Comment by Aniket31-coder** [comment]
Okay, sure @Kajol-Kumari, I will just think something else and let you know.

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari mam i created the log folder, please merge it.

Please make it `logo` and put your design under that. Sorry for the typo!

**Comment by himanshu007-creator** [comment]
@Kajol-Kumari  PR for logo https://github.com/HITK-TECH-Community/Community-Website/pull/113

**Comment by mak-ux** [comment]
https://drive.google.com/file/d/1jlBfnaDQu2SoumTwf31JXW5p3-gbTK8-/view?usp=sharing

please check this one

**Comment by Kajol-Kumari** [comment]
@mak-ux I like the concept of this logo. Looks really nice!

**Comment by Aniket31-coder** [comment]
Hey!

Could you please have a look at this logo and tell if any changes are required. 

![K (2)](https://user-images.githubusercontent.com/55101835/103437907-f36d7c00-4c52-11eb-9f3a-273bd5fd2d56.png)

**Comment by Kajol-Kumari** [comment]
Hey @Aniket31-coder we need very precise meaningful logo without any other background, for reference look at the `KOSS` logo [here](https://kossiitkgp.org/)

**Comment by vedikaag99** [comment]
![image](https://user-images.githubusercontent.com/67699840/103763340-ae28c000-503f-11eb-98aa-11e3c9f625c1.png)
@Kajol-Kumari do review

**Comment by vedikaag99** [comment]
![image](https://user-images.githubusercontent.com/67699840/103765659-88051f00-5043-11eb-9b37-ca314a8c7809.png)
or something like this maybe?

**Comment by Kajol-Kumari** [comment]
> ![image](https://user-images.githubusercontent.com/67699840/103763340-ae28c000-503f-11eb-98aa-11e3c9f625c1.png)
> @Kajol-Kumari please review

This looks great! Just you can try with some other font-style

**Comment by Kajol-Kumari** [comment]
Yes @vedikaag99 looks better :)

**Comment by Jaspreet099** [comment]
Can you assign this issue to me? I make a logo more related to the actual theme of the website.

**Comment by Kajol-Kumari** [comment]
Hey @Jaspreet099 feel free to show us the design. If if would look relevant we will assign it to you :)

**Comment by Jaspreet099** [comment]
![HITKlogo](https://user-images.githubusercontent.com/75212002/103982500-9bca9580-51a9-11eb-948d-0c5855f71ceb.jpg)

**Comment by Kajol-Kumari** [comment]
Hey @Jaspreet099 you to look at the canvasbird logo [here](https://github.com/Canvasbird) for reference, We are looking for precise and short logo

**Comment by Vrushti24** [comment]
can i work on this issue?

**Comment by Kajol-Kumari** [comment]
> can i work on this issue?

Sure! Give it a try :)

**Comment by Vrushti24** [comment]
Okay thanks

**Comment by Vrushti24** [comment]
hey @Kajol-Kumari I have made a logo in adobe illustrator it is simple one u like it ?
![Untitled-1_ @ 51 06% (CMYK_GPU Preview)  28-01-2021 22_21_34 (2)](https://user-images.githubusercontent.com/71961160/106171425-88628700-61b7-11eb-9771-c2aeb43690f8.png)

**Comment by Kajol-Kumari** [comment]
Hey @Vrushti24 Can you please try designing a simple logo for `Tech Community` instead of `HITK`

**Comment by Vrushti24** [comment]
If u like the background items I can only change name with different color
what say ??

**Comment by Kajol-Kumari** [comment]
Hey! Instead of just using word can try some symbols that would say it all?

**Comment by Vrushti24** [comment]
so without name only like symbols sure I will try that @Kajol-Kumari

**Comment by LeeRenJie** [comment]
Would love to try and contribute to this

**Comment by Kajol-Kumari** [comment]
> Would love to try and contribute to this

Sure @LeeRenJie

**Comment by LeeRenJie** [comment]
I have gone for a minimalist design what do you think? Will there be a website name? Because I can't grasp a concept based on "community website" so I went for HITK. Would definitely try another design based on the feedback. Thank You!

![HITK](https://user-images.githubusercontent.com/67599130/106358186-70b90900-6345-11eb-858b-42f4811aa1de.png)

https://user-images.githubusercontent.com/67599130/106358176-5d0da280-6345-11eb-8354-59126129559a.mp4

**Comment by Kajol-Kumari** [comment]
Hey @LeeRenJie This is a good try. Let me give you a gist of our moto so that you can come up with a better idea for the design. 


We are a group of college students trying to fill the knowledge gap by sharing the opportunities and resources related to tech via this website. As of now we have given it the name `HITK Tech Community` as HITK is our college name. But you can ignore the words and just focus on the motive of  `Tech Community`

**Comment by LeeRenJie** [comment]
Alright, I'll give it another go! Thank you for the clarification.

**Comment by LeeRenJie** [comment]
![Logo](https://user-images.githubusercontent.com/67599130/106383355-5d1ea880-6400-11eb-8d29-917399de8e2a.png)

@Kajol-Kumari how about this? I went for a human-like vector logo to show that it is like a community that is connected

**Comment by Kajol-Kumari** [comment]
> ![Logo](https://user-images.githubusercontent.com/67599130/106383355-5d1ea880-6400-11eb-8d29-917399de8e2a.png)
> 
> @Kajol-Kumari how about this? I went for a human-like vector logo to show that it is like a community that is connected

This looks pretty good. Feel free to open up the PR for this :)

**Comment by LeeRenJie** [comment]
The quality of the logo is quite blur tho. Will it be ok?

**Comment by Kajol-Kumari** [comment]
> The quality of the logo is quite blur tho. Will it be ok?

Can I get it's svg format as well then? As we won't be able to use it if it appears blur

**Comment by LeeRenJie** [comment]
I edited from stock images so I couldn't get that format. Maybe I'll try coding it out in SVG or try other alternatives to solve the blurriness.

**Comment by LeeRenJie** [comment]
This should be better in quality. @Kajol-Kumari 
![logo](https://user-images.githubusercontent.com/67599130/106392469-f19f0000-642c-11eb-8ef8-17a6c202b095.png)

**Comment by Vrushti24** [comment]
![16121172883534646999915753825819](https://user-images.githubusercontent.com/71961160/106393863-5a7f7b80-641f-11eb-87b1-f0d306b8fade.jpg)
@Kajol-Kumari I have tried one

**Comment by Kajol-Kumari** [comment]
> ![16121172883534646999915753825819](https://user-images.githubusercontent.com/71961160/106393863-5a7f7b80-641f-11eb-87b1-f0d306b8fade.jpg)
> @Kajol-Kumari I have tried one

Hmm, maybe just try with different color combination. Idea looks pretty good. Fee free to open up the PR for this

**Comment by Vrushti24** [comment]
Okay I will change the colour and I will make a PR thank u

**Comment by Vrushti24** [comment]
PR #325 done please check that out

**Comment by Kajol-Kumari** [comment]
> This should be better in quality. @Kajol-Kumari
> ![logo](https://user-images.githubusercontent.com/67599130/106392469-f19f0000-642c-11eb-8ef8-17a6c202b095.png)

Yeah this looks better. Feel free to open up the PR @LeeRenJie

**Comment by LeeRenJie** [comment]
Yep. Done that at PR #326 @Kajol-Kumari  Thank you.
