### ISSUE TITLE
Ask your question UI can be improved 

### ISSUE THREAD

**Issue by sarthu210** [HITK-TECH-Community/Community-Website#854]
Description of the issue:
The UI of the Ask Your Question page is very simple and after clicking it forms will pop up its alignment is also not perfect.
![Screenshot (498)](https://github.com/HITK-TECH-Community/Community-Website/assets/94531691/12e8e774-0b82-4eeb-88c0-9a51586d8de7)
![image](https://github.com/HITK-TECH-Community/Community-Website/assets/94531691/7833969d-7575-4c9b-a507-afcd47439826)
![image](https://github.com/HITK-TECH-Community/Community-Website/assets/94531691/ae6dc96e-f7fd-4e1d-af88-e8e50645f62c)
Describe the solution you'd like:
I will redesign the Ask Your Question section according to the current theme of the website and improve the alignment of the form submit button and other things.

**Comment by Sooraj002** [comment]
i would like to fix this issue

**Comment by Kajol-Kumari** [comment]
@Sooraj002 i would love to see what you come up with, please make sure the theme matches the website's theme

**Comment by sarthu210** [comment]
> @Sooraj002 i would love to see what you come up with, please make sure the theme matches the website's theme

Mam i want to ask that why this issue is not assigned to me is any mistake I have done??  I am new to open source but good at coding.

**Comment by Sooraj002** [comment]
Thank you

**Comment by MehtabAsHellic** [comment]
Hi Admin,

I'm interested in contributing to your project as part of GSSoC. I've been following your work and believe my skills align well. You can find my portfolio here: (https://sites.google.com/view/uibymehtab) and LinkedIn (https://www.linkedin.com/in/mehtabarkhan/)

Thanks,
Mehtab

**Comment by Sooraj002** [comment]
![Screenshot 2024-05-11 143014](https://github.com/HITK-TECH-Community/Community-Website/assets/95868709/68cc7717-7364-4ba8-805b-256174145e5d)
![Screenshot 2024-05-11 143958](https://github.com/HITK-TECH-Community/Community-Website/assets/95868709/7f806c75-4c20-4d4b-a367-c5399975c904)
![Screenshot 2024-05-11 144006](https://github.com/HITK-TECH-Community/Community-Website/assets/95868709/66f00ab4-55ed-42ba-910d-b79eea17cc42)
I have fixed the close btn position and make the form more compact , tell me if i should build it from ground up or make more chnages or is this ok?😊

**Comment by Kajol-Kumari** [comment]
@Sooraj002 have reverted back on the pr, please incorporate the requested changes.

**Comment by sarthu210** [comment]
Hi Mam I want to work on this issue can you please assign this to me.

**Comment by Sooraj002** [comment]
> @Sooraj002 have reverted back on the pr, please incorporate the requested changes.

ohk

**Comment by Kajol-Kumari** [comment]
@sarthu210 Sooraj is already working on this so can't assign it to anybody else, please look to other opened unclaimed issue, would be happy to assign :)

**Comment by sarthu210** [comment]
> @sarthu210 Sooraj is already working on this so can't assign it to anybody else, please look to other opened unclaimed issue, would be happy to assign :)

Okay np

**Comment by Sooraj002** [comment]
> @sarthu210 Sooraj is already working on this so can't assign it to anybody else, please look to other opened unclaimed issue, would be happy to assign :)

ma'am When i am trying to install npm pakages it is giving me error and the node_modules are not being created
alot of people are facing this error and they are asking me in linkedin to
Can you help me??

**Comment by Kajol-Kumari** [comment]
@Sooraj002  like i have mentioned in [readme](https://github.com/HITK-TECH-Community/Community-Website?tab=readme-ov-file#getting-started-) as well, you need to be on node version 14, in order to work on this project. You can use https://codedamn.com/news/nodejs/nvm-installation-setup-guide to install nvm which can help you to have multiple node versions on your pc

**Comment by Kajol-Kumari** [comment]
Marking and closing as duplicate as its pr has already been merged
