### ISSUE TITLE
Landing page can be improved with more attractive layout

### ISSUE THREAD

**Issue by callmeVAMP** [HITK-TECH-Community/Community-Website#855]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Write your answer here.

**Comment by Kajol-Kumari** [comment]
Hey @callmeVAMP its too vague. also, my current target is to make the project working end to end, and given that the landing page is already quite good, closing this one.
