### ISSUE TITLE
learn.md not found

### ISSUE THREAD

**Issue by nagamukesh** [HITK-TECH-Community/Community-Website#858]
**Documentation**
A clear and concise description of what the issue is.

**Have you spent some time to check if this issue has been raised before?**
yes

**Additional context**
I can make a learn.md file discussing the project explaining all the features and related technologies and screenshots according to gssoc 2024
please assign this issue to me under gssoc 2024

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
yes I did. i read the code of conduct

**Comment by Kajol-Kumari** [comment]
Hey @nagamukesh I have made the readme and contributing.md so self-explanatory that i don't think this will be required for this project, thanks for taking time to open this one but this is not required for this repo.
