### ISSUE TITLE
Fixing FAQs Section 

### ISSUE THREAD

**Issue by AryanAg08** [HITK-TECH-Community/Community-Website#859]
Currently the FAQs doesn't load. It throws a 500 (Internal Server Error) upon reaching to the section. And displays the empty block. 

![image](https://github.com/HITK-TECH-Community/Community-Website/assets/95911067/0aaebae1-8757-4a4a-a640-c60be37d7bae)

**Comment by AryanAg08** [comment]
I want to work on it, Can you assign this this task to me under GSCo'S 24

**Comment by Kajol-Kumari** [comment]
@AryanAg08  Its not a bug and i wonder how would you have fixed it. The backend server was down, i rebooted it and its working, closing this issue. Thanks for taking time to raise it.
