### ISSUE TITLE
[Backend] Create GetAdmin API

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#869]
**Is your feature request related to a problem? Please describe.**
Currently there is no api exposed which can give the current loggedIn user detail.

**Describe the solution you'd like**
There should be an api exposed which should give the current loggedIn user detail. This api should required the authorization key and you can either get the user's email by decoding the token(preferred) or asking the user to give the email in payload

**Comment by SwayamRana808** [comment]
Can i work on this issue. please assign it to me.

**Comment by Kajol-Kumari** [comment]
This issue won't be required. Sharing the working curl to get the current loggedIn admin detail - 
```
curl --location --request GET 'https://community-website-backend.onrender.com/admin?type=self' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer <token>' \
--data-raw '{
    "email": "hitktechcommunity@gmail.com"
}'
```
