### ISSUE TITLE
[Backend] - Mail on signup of newsletter.

### ISSUE THREAD

**Issue by aayushwrld** [HITK-TECH-Community/Community-Website#870]
**Is your feature request related to a problem? Please describe.**
1. welcome email if the user is first time subscriber saying that `you have successfully signed up for hitk-tech-community broadcasts.`
2. subsequent email containing new broadcast detail whenever a new broadcast publish on the website
3. Validation on the email
**Describe the solution you'd like**
I would like that when we signup for newsletter the email gets stored in the database and a Welcome email is sent to the person who signed up for the same.

**Additional context**
I would like to implement this feature for the website. I'll use the package "nodemailer" to implement the same.

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Yes, I've read it.

**Comment by PRANJALJAVIA** [comment]
@Kajol-Kumari Please assign this issue to me. I have worked on the doctor appointment management project, where I have implemented this email sending functionality when doctor approve patient's appointment request than notification using email is sent to the patient .

**Comment by PRANJALJAVIA** [comment]
@Kajol-Kumari , to implement this feature, Do we need to add one new model "User"?, because mail is sent to those who are registered in website.

**Comment by Kajol-Kumari** [comment]
@PRANJALJAVIA yes, creating a new model should be the ideal case here as its an open website

**Comment by Kajol-Kumari** [comment]
covered under #1059
