### ISSUE TITLE
Questions For FAQs

### ISSUE THREAD

**Issue by lakshyajn** [HITK-TECH-Community/Community-Website#871]
**Is your feature request related to a problem? Please describe.**
There are so many columns of FAQs, but they are not filled and not contain any desirable info.

**Describe the solution you'd like**
I will add clear and precise questions and answers, that would be good and enough for people to get the answers.

**Describe alternatives you've considered**
Any alternative would be to create a chatbot, but I think these FAQs would be enough.

Please Assign This Issue To Me 

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Write your answer here. 
Yes

**Comment by Kajol-Kumari** [comment]
@lakshyajn  those faqs are actually coming from backend so they are random/dummy data right now, once the website is in good state, i will add the required faq from the admin panel, no hard-coding is required :)

**Comment by lakshyajn** [comment]
Ohh got it 👍 

If u have any other issue, u can hand over to me :)
