### ISSUE TITLE
[Bug] Fix backend addteammembers api

### ISSUE THREAD

**Issue by Hemu21** [HITK-TECH-Community/Community-Website#872]
**Describe the bug**
There is problem with addTeamMembers api. Because it frontend is unable to add team members and throwing errors. fixing it is most important to fix frontend problems.

**To Reproduce**
1. open thunder client or postman
2. use auth token and try to addteam members.
3. it is not giving any response.

**Expected behavior**
when try to add team members with auth token. we should able to add the data.

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
yes

**Comment by Hemu21** [comment]
@kushal98 can you please assign me this issue

**Comment by Kajol-Kumari** [comment]
please go ahead with the issue @Hemu21 .
Happy Learning :)

**Comment by Hemu21** [comment]
@Kajol-Kumari I Created the PR. I solved that issue can you please check it.

**Comment by Kajol-Kumari** [comment]
depratizing it to `level 1` as its just a typo fix
