### ISSUE TITLE
Refactoring sign up for newsletter component

### ISSUE THREAD

**Issue by sarthu210** [HITK-TECH-Community/Community-Website#874]
Refactoring the sign-up for the newsletter as per the [proposed style](https://github.com/HITK-TECH-Community/Community-Website/blob/main/frontend/PROPOSAL.md). 

**Additional context**
All the components of the footer are left aligned only the subscribe newsletter is aligned center.

![image](https://github.com/HITK-TECH-Community/Community-Website/assets/94531691/8d97e4af-65c4-4ef7-9e1b-f5a1fe0eae49)

**Proposed Solution**
Make it left align only

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Yes

**Comment by Kajol-Kumari** [comment]
Hey @sarthu210 that's intentional, no change is required :)

**Comment by sarthu210** [comment]
okay np!
