### ISSUE TITLE
Filter genuine email

### ISSUE THREAD

**Issue by pankaj-bind** [HITK-TECH-Community/Community-Website#877]
**Is your feature request related to a problem? Please describe.**
In your application anyone can enter using **temporary or disposable email**.

**Describe the solution you'd like**
I will add a feature so that no one could create an account using **temporary or disposable email**.
It will allow only genuine users in your database.
It will help to avoid any bot.

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Write your answer here. Yes

Assign me this work under GSSoC24, I will implement it.

**Comment by Kajol-Kumari** [comment]
@pankaj-bind have you even checked our website? its supposed to be open only so i am not able to understand how will add this genuine email filter :)
