### ISSUE TITLE
[bug] Email Signup Submission Error

### ISSUE THREAD

**Issue by subhadipbhowmik** [HITK-TECH-Community/Community-Website#878]
**Describe the bug**
After submitting my email for subscription I am getting the success message inside the input field. It will be helpful if the success message is showin below the submission input field.

**To Reproduce**
1. Go to [link](https://hitk-tech-community.netlify.app/)
2. Scroll down to bottom and see Sign Up for our Newsletter
3. Submit any Valid email address.
4. Success message is showing inside the email input section.

**Expected behavior**
The Success message will be shown below the email input .

**Screenshots**
<img width="444" alt="hitk-tech-email" src="https://github.com/HITK-TECH-Community/Community-Website/assets/57017965/e2736e01-8e0e-4fcc-a4e5-d396b7c67c27">

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [chrome, safari, brave, arc]
 - Version [11]

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Yes, I have read the Code Of Conduct

**Comment by Kajol-Kumari** [comment]
hmm, even ui of this message is off, i would prefer an ui similar to the one we show in toast message, that would be great.

**Comment by BHS-Harish** [comment]
Hello @Kajol-Kumari 

Please assign me the issue
