### ISSUE TITLE
Join us form select input not visible properly

### ISSUE THREAD

**Issue by Stiffpixels** [HITK-TECH-Community/Community-Website#879]
**Describe the bug**
The select input in the join us form has a transparent background which makes it merge with the content behind, making it hard to select the domains and looks unprofessional. 
**To Reproduce**
1. Go to [join us page](https://hitk-tech-community.netlify.app/join-us-form)
2. Click on select button below interested domains
3. See error

**Expected behavior**
The background should be opaque and not transparent

**Screenshots**
![image](https://github.com/HITK-TECH-Community/Community-Website/assets/32983571/3b369898-5a67-4d0f-97ce-c2c95961c9a1)

fixed:
![image](https://github.com/HITK-TECH-Community/Community-Website/assets/32983571/b95295e7-93ac-4da8-b28a-8b752b9cae09)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser: firefox

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Yes.

**Comment by Kajol-Kumari** [comment]
@Stiffpixels  thanks for pointing, along with the fix you mentioned, can you add this effect in select field? We get it in dark mode but not in light mode.
<img width="678" alt="Screenshot 2024-05-14 at 4 11 43 PM" src="https://github.com/HITK-TECH-Community/Community-Website/assets/44888949/c436bf9f-24b6-441d-a6ab-65610d1d9631">

**Comment by Stiffpixels** [comment]
> @Stiffpixels  thanks for pointing, along with the fix you mentioned, can you add this effect in select field? We get it in dark mode but not in light mode.
> <img width="678" alt="Screenshot 2024-05-14 at 4 11 43 PM" src="https://github.com/HITK-TECH-Community/Community-Website/assets/44888949/c436bf9f-24b6-441d-a6ab-65610d1d9631">
> 

Sure will do.

**Comment by Stiffpixels** [comment]
@Kajol-Kumari  can you guide me through these errors I got while setting up the project I fixed the python2 error but now a new set of errors have emerged. 
![image](https://github.com/HITK-TECH-Community/Community-Website/assets/32983571/a0a8bf2a-2486-46ea-8b46-3d9fdb620f5d)

**Comment by Kajol-Kumari** [comment]
@Stiffpixels  yes, you should be on `node version 14.19.0`
I have added it in readme's installation guide - https://github.com/HITK-TECH-Community/Community-Website?tab=readme-ov-file#getting-started-
