### ISSUE TITLE
[Frontend] Integrate Answers in Q&A Page

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#885]
## Description
Currently the `Q&A` page only have the question list and form to submit the questions. There should be a way to see all the answers of the particular question sorted by the number of upvotes

##Expectation
Integrate the get answers api, filter the ones having `isApproved` as `true` and display it in nice way on the UI
Get Answers api - https://github.com/HITK-TECH-Community/Community-Website/blob/main/backend/app/routes/Q%26A/answers/getAnswers.js 

<img width="1501" alt="Screenshot 2024-05-15 at 8 57 48 PM" src="https://github.com/HITK-TECH-Community/Community-Website/assets/44888949/4fc90014-a941-49af-a949-8278ca10f203">

**Comment by Kajol-Kumari** [comment]
This issue will on hold till https://github.com/HITK-TECH-Community/Community-Website/issues/887 issue gets fixed

**Comment by TejasNasre** [comment]
I want to work on this issue.

**Comment by TejasNasre** [comment]
Please Specify The API Endpoints

**Comment by Kajol-Kumari** [comment]
the endpoints are already mentioned in the issue description, please go through it.

**Comment by TejasNasre** [comment]
i am hitting api like this http://localhost:3000/answers/getanswers/624004398d58c808d8f01dec but not getting any answer

**Comment by Kajol-Kumari** [comment]
@TejasNasre  use https://community-website-backend.onrender.com/ as the baseUrl, in your local, its will not connect to actual db so won’t get the data

**Comment by BHS-Harish** [comment]
Hello @Kajol-Kumari 

Assign me the issue
