### ISSUE TITLE
[Frontend] UI to answer the questions in Q&A Section

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#886]
**Is your feature request related to a problem? Please describe.**
Currently, we only have questions list in `Q&A` section of the website, so user won't be able to answer to those questions.

**Describe the solution you'd like**
Add an ui where any user can answer the question. These questions should get saved using the [post answer api](https://github.com/HITK-TECH-Community/Community-Website/blob/main/backend/app/routes/Q%26A/answers/post.js)

**Comment by TejasNasre** [comment]
I want to work on this issue.

**Comment by Kajol-Kumari** [comment]
@TejasNasre  please go ahead, happy learning :)

**Comment by TejasNasre** [comment]
Please Specify The Endpoints

**Comment by Kajol-Kumari** [comment]
> Please Specify The Endpoints

its already present in the issue description, please check

**Comment by BHS-Harish** [comment]
Hey @Kajol-Kumari 

I'm interested to work on the issue
