### ISSUE TITLE
[Backend] Add Delete API for Questions and Answers

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#889]
## Description 
Two apis taking the id as parameter and doing the deletion.
- [ ] Delete API for questions
- [ ] Deletion API for answer

Please add these 2 apis under `question` and `answer` folder respectively
https://github.com/HITK-TECH-Community/Community-Website/tree/main/backend/app/routes/Q%26A

**Comment by Hemu21** [comment]
@Kajol-Kumari  this issue and #900  are same. can you please assign me one issue and close the another issue.

**Comment by Hemu21** [comment]
@Kajol-Kumari  can you please assign this to me.
