### ISSUE TITLE
The Twitter icon need to be updated in very footer of the page

### ISSUE THREAD

**Issue by Sibam-Paul** [HITK-TECH-Community/Community-Website#892]
**Is your feature request related to a problem? Please describe.**
The Twitter icon need to be updated in very footer of the page

**Describe the solution you'd like**
Updating the icon to from bird to X

**Additional context**
![image](https://github.com/HITK-TECH-Community/Community-Website/assets/158052549/059bc5da-bc4e-4c3b-a690-494c05106922)

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Write your answer here.
Yes

**Please assign me this issue as I want to work on it**

**Comment by Kajol-Kumari** [comment]
Hi @Sibam-Paul I can stick with the same icon, i don't feel like changing it but thanks for pointing.😅

**Comment by Sibam-Paul** [comment]
Ok
