### ISSUE TITLE
[Frontend] Integrate the Delete Team Member API with frontend

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#894]
## Description

- [ ] The delete button is useless rn, integrate the [delete team member api](https://github.com/HITK-TECH-Community/Community-Website/blob/main/backend/app/routes/teamMember/deleteTeamMember.js) with it so that admin can delete the redundantly added members.
- [ ] The image isn't appearing in the fetched member list, fix it.

 
<img width="1498" alt="Screenshot 2024-05-16 at 12 05 09 PM" src="https://github.com/HITK-TECH-Community/Community-Website/assets/44888949/888e04fc-8ae5-430f-8eb4-848cf40b79f9">

**Comment by Hemu21** [comment]
@Kajol-Kumari  can you please assign this to me.
