### ISSUE TITLE
[Backend] Create Delete Contact US API

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#895]
## Description

- [ ] Currently there is no api to delete the contact us data, need an api to be created under [contactUs](https://github.com/HITK-TECH-Community/Community-Website/tree/main/backend/app/routes/contactUs) folder which will take the id and delete the data from db.
- [ ] Only admins should have access to this api, so make sure to add the required validations.

**Comment by EAGLEARCHER** [comment]
Hey @Kajol-Kumari, can you assign me this issue?

**Comment by EAGLEARCHER** [comment]
Hey @Kajol-Kumari, I have created the backend api with all requirements completed. Do I also have to integrate the api to frontend?

**Comment by Kajol-Kumari** [comment]
@EAGLEARCHER No, this issue is just to create the Api, will raise a separate issue for integration once this issue get resolved
