### ISSUE TITLE
[Frontend] Introduce Update Admin Functionality

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#896]
## Description
Currently admins can't update their details from admin portal.

## Expectation
- [ ] Correct the Update admin UI, to show the pre-populated existing info along with an `update` button. Note that image should also be changable.
- [ ] Once admin, fill the required info and click on `update` button, the [updateAdmin](https://github.com/HITK-TECH-Community/Community-Website/blob/main/backend/app/routes/admin/updateAdmin.js) api should get called.
- [ ] Make sure to add the required form validations

<img width="1472" alt="Screenshot 2024-05-16 at 2 12 55 PM" src="https://github.com/HITK-TECH-Community/Community-Website/assets/44888949/a082bf3f-1062-47d8-97a3-b7edba37ee5e">

**Comment by SwayamRana808** [comment]
please assign me this issue as GGsoc 24

**Comment by SwayamRana808** [comment]
How will i pass  _id ? I think it not stored nor getAdmins api send it ? 
![Screenshot 2024-05-17 231829](https://github.com/HITK-TECH-Community/Community-Website/assets/122097724/4c34311c-4e77-4d6f-9227-aac8e4c7b688)

**Comment by SwayamRana808** [comment]
if getAdmins api send _id . it can be passed down as props.
should i change getAdmins api ---

![Screenshot 2024-05-17 233037](https://github.com/HITK-TECH-Community/Community-Website/assets/122097724/7a750b28-33b7-4452-8b18-98d952e7f02d)

**Comment by Kajol-Kumari** [comment]
@SwayamRana808  yeah, it seems like we will have to have id in admin details and getAdmin should fetch that id as well, then only we would be able to make the update call, can u please raise an issue for the same ?

**Comment by SwayamRana808** [comment]
**Is this ok i changed name and email as they were not defined to be updated in updateAdminValidation schema**
![Uploading Screenshot 2024-05-18 152825.png…]()

**Comment by Kajol-Kumari** [comment]
@SwayamRana808  yes, the ui looks fine, i hope i will see the pre-populated data once i click on edit icon

**Comment by SwayamRana808** [comment]
**I have added edit-icon on the profile image but it doesn't do anything. should i keep it ?**
![Screenshot 2024-05-18 185047](https://github.com/HITK-TECH-Community/Community-Website/assets/122097724/036ee7f2-e4bb-4f8e-ad90-cb48be61aa26)

**Comment by Kajol-Kumari** [comment]
The edit icon is redundant on image, u can remove it but admin should be able to change their profile image(in edit mode)

**Comment by SwayamRana808** [comment]
there is no image schema path defined in Admin schema to store image path (:uploads/Admin)
and no multer defined in Admin index.js to parse multiform/form data as i am using formData to send fields to update which can be used to  update image ? 
Should i add that ?

**Comment by Kajol-Kumari** [comment]
yes @SwayamRana808  please add it and refer `teamMember` api, which is using multer to store the images

**Comment by Kajol-Kumari** [comment]
have updated the level to `level 3`  of the issue as this is an extra work that i didn't forsee

**Comment by SwayamRana808** [comment]
**I have made the changes you requested. Please review them.**
