### ISSUE TITLE
[Open for all] UI Design for About Us page of the website

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#9]
- Make UI for the about us page of the website using any of the UI designing tool like figma
It should include a brief about who we are and the details of the team working behind the scene

**Comment by prakarsh7695** [comment]
Hey @Kajol-Kumari ! I want work on this! Can uassign it tome? Also can you brief a little as to what kind of theme are u looking for the page?

**Comment by Kajol-Kumari** [comment]
@prakarsh7695 Sure you can go ahead with this. Also as of now we don't have any theme decided , we would just be selecting out the best design and take it for code.

**Comment by Sshivani-12** [comment]
interested!

**Comment by Kajol-Kumari** [comment]
Go ahead @Sshivani-12 :)

**Comment by Malvika18** [comment]
hey can i work on this

**Comment by Kajol-Kumari** [comment]
Yes @Malvika18 Go ahead with this. Looking forward to your proposed design :)

**Comment by yashsehgal** [comment]
Hey, I am interested in this issue. Can you assign me this?

**Comment by yashsehgal** [comment]
Hey, I am interested in this. Shall I start working on this? I am currently working on the design. I can provide you with the mockups if you want?

**Comment by Kajol-Kumari** [comment]
Go ahead @yashsehgal !

**Comment by abhinav-huria** [comment]
I want to work on this.

**Comment by kanishkaa24** [comment]
Hey!
I want to work on this.

**Comment by kanishkaa24** [comment]
![HITK Tech Community](https://user-images.githubusercontent.com/71253790/103213937-29e68680-4935-11eb-97a2-4ddf629d50a4.png)
![HITK Tech Community (1)](https://user-images.githubusercontent.com/71253790/103213939-2b17b380-4935-11eb-9121-e9a6c609ea2b.png)
@Kajol-Kumari I have come up with these designs.

**Comment by Kajol-Kumari** [comment]
@kanishkaa24 Looks preety good to me just make sure to keep the header and footer same as we have now and make a PR with the image/link under [this](https://github.com/HITK-TECH-Community/Community-Website/tree/main/assets/About%20us%20page) folder

**Comment by kanishkaa24** [comment]
> @kanishkaa24 Looks preety good to me just make sure to keep the header and footer same as we have now and make a PR with the image/link under [this](https://github.com/HITK-TECH-Community/Community-Website/tree/main/assets/About%20us%20page) folder

Where can I find the current header and footer ?

**Comment by Kajol-Kumari** [comment]
> > @kanishkaa24 Looks preety good to me just make sure to keep the header and footer same as we have now and make a PR with the image/link under [this](https://github.com/HITK-TECH-Community/Community-Website/tree/main/assets/About%20us%20page) folder
> 
> Where can I find the current header and footer ?

You can run the project and see it in the website itself .

**Comment by yashsehgal** [comment]
Hey There, This is my approach for webpage design. This is just an experimental UI following a retro-classic theme. Hope you'll like it.

![about-us-page](https://user-images.githubusercontent.com/62352288/103735869-fbdc0300-5014-11eb-89cb-fb8cd6b8a15f.png)

**Comment by Kajol-Kumari** [comment]
@yashsehgal just add one more section in this design `Our Team`. Then this design will be good to go for implementation :)

**Comment by yashsehgal** [comment]
Sure, I will do that.

**Comment by yashsehgal** [comment]
Okay, I have added the `Our Team` section in the design.

![about-us-page](https://user-images.githubusercontent.com/62352288/103745604-c5f34a80-5025-11eb-98f8-cd4dac5c227c.png)

**Comment by yashsehgal** [comment]
> Okay, I have added the `Our Team` section in the design.
> 
> ![about-us-page](https://user-images.githubusercontent.com/62352288/103745604-c5f34a80-5025-11eb-98f8-cd4dac5c227c.png)

Shall I make a new PR for this design?

**Comment by Kajol-Kumari** [comment]
@yashsehgal yes! Go ahead and make the Pr!

**Comment by yashsehgal** [comment]
Okay

**Comment by yashsehgal** [comment]
Hey, I think you have not added the labels here
