### ISSUE TITLE
[Backend] Create Delete Questions API  for Q&A

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#900]
## Description

- [ ] Currently there is no api to delete the question, need an api to be created under [question](https://github.com/HITK-TECH-Community/Community-Website/tree/main/backend/app/routes/Q%26A/question) folder which will take the id and delete the data from db.
- [ ] Only admins should have access to this api, so make sure to add the required validations.

**Comment by Hemu21** [comment]
@Kajol-Kumari  can you please assign this to me.
