### ISSUE TITLE
Justification of footer elements in the center in mobile view .

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [HITK-TECH-Community/Community-Website#903]
**Describe your Proposal**
If the elements in  footer will be aligned in the center  then it may looks good mobile view .

![Screenshot 2024-05-16 200757](https://github.com/HITK-TECH-Community/Community-Website/assets/118350936/bae193bf-e30d-4e52-b54a-398a7b606c1a)

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Write your answer here.
yes

**Comment by Kajol-Kumari** [comment]
Hey @Ayushmaanagarwal1211 it has been kept left aligned intentionally.
