### ISSUE TITLE
Justification of text from both the sides in the about us section .

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [HITK-TECH-Community/Community-Website#904]
**Is your feature request related to a problem? Please describe.**
The text in the about page is only  justified form the left but not from the right .

**Describe the solution you'd like**
The Text should be justified from both the ends .

**Additional context**
![Screenshot 2024-05-16 201216](https://github.com/HITK-TECH-Community/Community-Website/assets/118350936/0b186f72-a580-44b4-b341-fe69d0a99693)

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Write your answer here.
yes

**Comment by Kajol-Kumari** [comment]
honestly, i don't see it as an issue, its left aligned
