### ISSUE TITLE
Elaborate How to install nvm and run this project using the specific node version

### ISSUE THREAD

**Issue by Sooraj002** [HITK-TECH-Community/Community-Website#907]
**read me file should be updated**
The Read ME File doesn't Expain Well

It just says u have to use node version 14 while .

It should be more precise cause I have to spent a lot of time figuring out.

I am a gssoc contributor. 

i would like to update the readme file so that it would make it easier and precise on how to run this project locally saving others time.

**Comment by Sooraj002** [comment]
I would like to solve this issue. Please assign this to me.

**Comment by Kajol-Kumari** [comment]
@Sooraj002 Are u sure you have gone through readme before opening this issue? The installation guide is https://github.com/HITK-TECH-Community/Community-Website?tab=readme-ov-file#setup-the-repository-to-your-local-environment

**Comment by Sooraj002** [comment]
Yes, I did went through those many times still it took me alot of time (Days) in configuring node 14 and its npm pakage. As the people who are contributing are students , So  I think it should be specified how to use nvm to get node 14 and then how to install npm to install npm .So i thought we should add 2-3 steps which include installing nvm then installing node 14 then installing npm version 6

**Comment by Kajol-Kumari** [comment]
@Sooraj002  if you are gonna add nvm and steps to get the node version mentioned in the readme, i would be happy to accept this issue. the issue title was misleading
