### ISSUE TITLE
Ask your question UI can be improved

### ISSUE THREAD

**Issue by Sooraj002** [HITK-TECH-Community/Community-Website#909]
The current "Ask your question " UI is very old, 
I am a gssoc contributor, 
Please assign this to me

**Comment by Kajol-Kumari** [comment]
@Sooraj002  i would like to see what is the new ui that you are proposing before accepting this issue

**Comment by Sooraj002** [comment]
![image](https://github.com/HITK-TECH-Community/Community-Website/assets/95868709/14a66d93-25a1-4916-bd45-1d5adfe0a9bd)
This is the old UI  the close button is not placed properly.
And it is very empty because the tags are not utilizing the available space properly
![image](https://github.com/HITK-TECH-Community/Community-Website/assets/95868709/c9d72a11-e821-474d-9ebc-ca0a1d741293)
As per your request i have made the close button more visible and also changed the tag layout to grid and it is also responsive .
![image](https://github.com/HITK-TECH-Community/Community-Website/assets/95868709/095d337c-5737-428b-be40-72f19c1e1c74)
This version is ready to commit :)

**Comment by Kajol-Kumari** [comment]
Looks good, go ahead
