### ISSUE TITLE
Replace the old twitter logo with the new "X" logo

### ISSUE THREAD

**Issue by Madhu-mac** [HITK-TECH-Community/Community-Website#911]
**Is your feature request related to a problem? Please describe.**
When we go to the footer of the page, It has old twitter logo. We need to replace it with the new one

**Describe the solution you'd like**
Want to change the logo of the twitter icon in the footer 

**Describe alternatives you've considered**
We need to add the new "X" logo to the footer 

**Additional context**
![image](https://github.com/HITK-TECH-Community/Community-Website/assets/99901964/322b69fa-6884-4e65-8245-33b345b96126)

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
**YES**

**Comment by Madhu-mac** [comment]
@Kajol-Kumari Assign me this issue and add labels to it, so that i can work under GSSoC

**Comment by Kajol-Kumari** [comment]
@Madhu-mac  i am not looking for this change, i find the previous icon better :)
