### ISSUE TITLE
Google Auth on Admin login page

### ISSUE THREAD

**Issue by SaurabhS55** [HITK-TECH-Community/Community-Website#912]
Hey there, It will more user friendly, if we add "Login with Google" button in admin login page. Can we add "Login with Google" button?
I would like to work on this feature. could you assign this feature to me under GSSOC'24 label ?

To implement this we gone make use of React OAuth2 NPM library which provides built in support for google Authentication.

**Comment by Kajol-Kumari** [comment]
hmm, sounds interesting, but can't it allow anyone to login? **We need to have a check that only the admins, whose data is in our database, should be allowed to signin using Google**. Please make sure to add this check, else the whole admin purpose will be defined

**Comment by SaurabhS55** [comment]
Yes we can do this by adding check in controller functions.

**Comment by Kajol-Kumari** [comment]
@SaurabhS55  please go ahead with this issue :)

**Comment by Likhita4403** [comment]
Hi, if this issue is not worked on yet, I would like to take this up. @Kajol-Kumari

**Comment by Likhita4403** [comment]
Hi @Kajol-Kumari , for the google based authentication, we would need to create an api client id and such, do you have a gmail account whose credentials I could use

**Comment by Kajol-Kumari** [comment]
Hey @Likhita4403 please use a dummy email for this and share the onboarding step in pr as well, i can't share the email creds wiith u so will create the required things myself by following the steps you will mention

**Comment by Likhita4403** [comment]
Steps:

1. Get a Google API Client ID:


- Go to the [Google API Console Credentials page](https://console.developers.google.com/apis/credentials).
- Create or select a Google APIs project.
- Click Create credentials > OAuth client ID and choose Web application.
- Add your website's URI to Authorized JavaScript origins.

2. Configure OAuth Consent Screen:

- Go to the [OAuth consent screen page](https://console.developers.google.com/apis/credentials/consent) in the Google Developer Console.
- Fill out the required information (application name, logo, support email, etc.).
- Define the necessary scopes for the data your application needs to access.
- Add authorized domains and links to your application's homepage, privacy policy, and terms of service.
- Submit your application for verification if required.

3. Implement Sign In with Google on Your Website:

- 
- Use the Google Identity Services library to add the Sign In button to your admin login page.
- Handle the user authentication flow and retrieve the ID token.
- Verify the ID token on your backend to ensure its authenticity.
- Check if the authenticated user is an admin based on your admin user management system.

These steps need to be followed, please check and let me know once you are done with the required steps from your side.

**Comment by Kajol-Kumari** [comment]
@Likhita4403 i will only get pt1 done, i hope u understand that i wouldn't solve the whole issue on your behalf

**Comment by Likhita4403** [comment]
Yeah I understand, let me know the details once the part 1 is completed

**Comment by Kajol-Kumari** [comment]
@Likhita4403 pt1 and 2 is done but again i can't share u the id and secret, once u raise the pr, i will test the chane using the same

**Comment by BHS-Harish** [comment]
Hey @Kajol-Kumari 

Assign me the issue...

I'm interested to add Sign In with Google functionality using Firebase Authentication

**Comment by Kajol-Kumari** [comment]
not needed for now, so closing it
