### ISSUE TITLE
[Backend] The DELETE teamMemebers API should also delete the respective file stored in the disk

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#916]
## Description
The [deleteTeamMembersAPI](https://github.com/HITK-TECH-Community/Community-Website/blob/main/backend/app/routes/teamMember/deleteTeamMember.js#L9) currently only deletes the data from db and so the image file stored in disk will keep on getting bigger.

## Expected Fix
The delete call should also delete the image file before deleting the data form the DB.

**Comment by Hemu21** [comment]
@Kajol-Kumari  can you please assign this to me.
