### ISSUE TITLE
[Refactor] Frontend API Calls should be kept under the `Service` folder

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#917]
**Describe the bug**
Currently, all the API calls is taking place atleast twice, one for normal flow and one for admin. 

**Expected behavior**
We should keep all the api calls in a single folder `service` and then reuse the same code for all the places.

This issue just a placeholder as there are multiple folders that needs refactoring, so anyone who claims this issue, can pick one folder at a time, i will tag them here and then raise an issue for that, it will be given `level 2` and then start working.

| Folders    | Assignee |
|------------|----------|
| about      |   @Hemu21        |
| admin      |     @Faizanusmani06      |
| Broadcast  |    @Hemu21       |
| ContactUs  |  @Hemu21          |
| Faq        |    @shivamgaur99       |
| Q&A        |     @devmusiczz      |
| Resources  |    @Hemu21       |

**Comment by Faizanusmani06** [comment]
Hey @Kajol-Kumari Please assign the admin folder to me.

**Comment by devmusiczz** [comment]
Hey @Kajol-Kumari I’ll take the QnA folder for refactor. Please assign this to me.

**Comment by Kajol-Kumari** [comment]
@Faizanusmani06  and @devmusiczz  please feel free to open the respective issue and continue on the same, Happy Learning :)

**Comment by Hemxnt** [comment]
assign me this issue

**Comment by Kajol-Kumari** [comment]
@Hemxnt u need to mention the module, please go there issue description properly

**Comment by Hemu21** [comment]
@Kajol-Kumari  can you please assign me the contactUs folder.

**Comment by Hemu21** [comment]
@Kajol-Kumari  can you please assign me the about folder

**Comment by Kajol-Kumari** [comment]
@shivamgaur99 / @Hemu21  assigned the respective modules, please feel free to open the respective issue and continue on the same, Happy Learning :)

**Comment by Hemu21** [comment]
@Kajol-Kumari  can you please assign me the resources folder.

**Comment by Hemu21** [comment]
@Kajol-Kumari  can you please assign me the Broadcast one

**Comment by Hemu21** [comment]
@Kajol-Kumari  can you please assign me the Broadcast folder

**Comment by shivamgaur99** [comment]
@Kajol-Kumari  Since the FAQ folder also contains Q&A-related files, I worked on both FAQ and Q&A in my recent pull request. Can you check it? I didn't see that anyone is already assigned for Q&A.
