### ISSUE TITLE
[Backend] Limiting the Number of upvotes/downvotes a particular user can do

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#919]
**Describe the bug**
As the `Q&A` section is open, users can do the `upvote` and `downvotes` any umber of times.

**To Reproduce**
1. Go to Q&A section of the website - https://hitk-tech-community.netlify.app/q&a 
2. Click on the upvote/downvote button

**Expected behavior**
I am all hears for the perfect solution but i am thinking that there should be a limit either based on the ip of the user of session, user shouldn't be allowed to do more than one upvote/downvote from a single ip/session.

**Screenshots**
<img width="1510" alt="Screenshot 2024-05-18 at 11 45 54 AM" src="https://github.com/HITK-TECH-Community/Community-Website/assets/44888949/f0e85321-66e0-4db8-9d42-690a096cd0fb">

**Comment by Hemu21** [comment]
@Kajol-Kumari  can you please assign this to me.

**Comment by PranjaliBhardwaj** [comment]
This issue is due to maybe not storing data and just creating a toggle function alone isn't a solution. I have read code and familier with MERN Stack, I would like to work on this issue. 
for eg:

import { Provider, LikeButton } from "@lyket/react";

  <Provider apiKey="">
    <LikeButton
      namespace=""
      id=""
    />
  </Provider>

**Comment by Kajol-Kumari** [comment]
@PranjaliBhardwaj that's not the case here, the upvotes and downvotes are getting stored in db, the only thing here is off is user doesn't need to be logged for upvoting/downvoting

@Hemu21  assigning this issue to you bases on FCFS

**Comment by Vyomrana02** [comment]
@Kajol-Kumari if we want to allow upvote without login then have to store ips in db also.

**Comment by navneetthakor** [comment]
hello @Kajol-Kumari,
I am interested in solving this issue. I have developed more then 3 MERN stack applications, and many others with various technology stacks. Currently I am in the final year of Btech. and that's why I have strong grip on MERN stack and network concepts, that makes me able to make this functionality completely working. Could you please assign me this issue under Gssoc'24.

**Comment by Kajol-Kumari** [comment]
Folks as u know the issue is already assigned and moreover, the issue assignment is on First come, first serve . so i won't be able to assign u this issue, please look at other opened issues
