### ISSUE TITLE
[Frontend] Integrate delete for Questions and Answers in admin

### ISSUE THREAD

**Issue by Hemu21** [HITK-TECH-Community/Community-Website#922]
**Describe the bug**
Intergration of Delete Q&A in Admin. 

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Write your answer here.
yes

**Comment by Hemu21** [comment]
@Kajol-Kumari can you please assign this to me.

**Comment by Kajol-Kumari** [comment]
sure @Hemu21 please go ahead. It should cover the integration for both questions and answers, so giving it `level 3`

**Comment by Hemu21** [comment]
@Kajol-Kumari  ok
