### ISSUE TITLE
[Frontend] Integrate Delete Contact Us API

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#927]
## Description

- [ ] Currently, the delete button on contact Us card of the admin panel is dummy, integrate it with the [DELETE CONTACT US API](https://github.com/HITK-TECH-Community/Community-Website/blob/main/backend/app/routes/contactUs/delete.js)
- [ ] Make sure that the generic toast message appear on the success/failure of the call and frontend gets updated accordingly

## Screenshot
<img width="1825" alt="Screenshot 2024-05-18 at 10 24 06 PM" src="https://github.com/HITK-TECH-Community/Community-Website/assets/44888949/42e15e70-bd17-4e2f-aeb4-5f5e45126c31">

**Comment by Hemu21** [comment]
@Kajol-Kumari  can you please assign this to me.
