### ISSUE TITLE
Contact Us Page: Image Appears Cropped in Dark Mode

### ISSUE THREAD

**Issue by shivamgaur99** [HITK-TECH-Community/Community-Website#936]
When viewing the "Contact Us" page in dark mode, the PNG image appears cropped. This means that part of the PNG image is not visible or is cut off, resulting in an incomplete or distorted display, specifically in dark mode.

**Screenshots**
![image](https://github.com/HITK-TECH-Community/Community-Website/assets/128178418/f713ae8d-b583-4374-9386-24317b32fb81)

want to replace this png 
@Kajol-Kumari please assign it to me

**Comment by Kajol-Kumari** [comment]
Its expected behaviour, if we replace this image, we will have to use similar images in other places to maintain the consistency of the website
