### ISSUE TITLE
Newsletter form does not have a margin

### ISSUE THREAD

**Issue by AMISH-KHAN** [HITK-TECH-Community/Community-Website#937]
**Describe the bug**
 The current UI the newsletter in the footer section does not have a margin

![Screenshot 2024-05-20 180955](https://github.com/HITK-TECH-Community/Community-Website/assets/123164129/11205514-fcda-4812-a6d7-8cb086229968)

Please assign this issue to me under GSSoC

**Comment by Kajol-Kumari** [comment]
duplicate if https://github.com/HITK-TECH-Community/Community-Website/issues/802
