### ISSUE TITLE
FEATURE: Adding answers to the FAQ section 

### ISSUE THREAD

**Issue by SadafKausar2025** [HITK-TECH-Community/Community-Website#943]
**Is your feature request related to a problem? Please describe.**

I will add correct questions and answers to the FAQ and which questions and answers will be related to the HIIT-TECK Community

**Comment by Kajol-Kumari** [comment]
@SadafKausar2025 we aren't supposed to add hardcoded values here , its already integrated from backend, once the website is completed E2E, i will add the actual questions from admin panel :)
