### ISSUE TITLE
[Frontend] The Broadcast isn't appearing in correct format

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#946]
##Description

- [ ] The broadcast description should have appeared in formatted view, instead i am seeing html tags in it.
- [ ] The link button on the details page doesn't take to the linked page

## Expectation
- The broadcast detail page should show the formatted text instead of `<p>`, <br>` or any html tag.
- when clicked on link button, it should open the resource link in a new tab. The current data contains the resourceLink but clicking on it doesn't direct us to the expected page.

<img width="1172" alt="Screenshot 2024-05-21 at 10 12 14 PM" src="https://github.com/HITK-TECH-Community/Community-Website/assets/44888949/7dfe8745-d3f0-49ca-b957-708a25017e44">
<img width="379" alt="Screenshot 2024-05-21 at 10 12 25 PM" src="https://github.com/HITK-TECH-Community/Community-Website/assets/44888949/588f4443-69a3-4a40-b0d7-d0e8e9df541d">
<img width="1018" alt="Screenshot 2024-05-21 at 10 15 07 PM" src="https://github.com/HITK-TECH-Community/Community-Website/assets/44888949/d467e90b-f0b1-4423-8699-8ff5db471c42">

**Comment by Hemu21** [comment]
@Kajol-Kumari  can you please assign this to me.
