### ISSUE TITLE
deleteFaq api expecting adminId fix

### ISSUE THREAD

**Issue by SwayamRana808** [HITK-TECH-Community/Community-Website#952]
**Describe the bug**
deleteFaq api expecting adminId where it is not required
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Write your answer here.
yes

**Comment by SwayamRana808** [comment]
please assign this issue  to me  as Ggsoc'24

**Comment by SwayamRana808** [comment]
**faq>index.js [here]( https://github.com/HITK-TECH-Community/Community-Website/blob/main/backend/app/routes/faq/index.js) never used !  
all files of faq are directly implemented as router.use() in app>routes>index.js [here](https://github.com/HITK-TECH-Community/Community-Website/blob/main/backend/app/routes/index.js) and they can be called with any method also as they are using router.use() no specific method ! 
should i change that ?**

**Comment by SwayamRana808** [comment]
if not where should i implement authorization jwt as faq index.js is never used ?

**Comment by Kajol-Kumari** [comment]
can u correct this? ideally `index.js` should have been use, i realised it in few modules that its been done incorrectly. Please fix it, i will update the level of this issue

**Comment by Kajol-Kumari** [comment]
increasing the level of the issue, given that more than expected changes have come up.
