### ISSUE TITLE
Add  Sample Ques and Ans in FAQ Section

### ISSUE THREAD

**Issue by shrutigolwalk0109** [HITK-TECH-Community/Community-Website#955]
Adding some sample ques and ans makes the user experience better I guess. Right now there is nothing in the FAQ section other than one sample question. Can I add some questions about the website or open-source contribution.

Kindly Assign me this issue with the GSSOC label, I would like to work on this.

Screenshot:- 
![image](https://github.com/HITK-TECH-Community/Community-Website/assets/132553685/2c2c18fb-8b18-411b-94f2-b98515e89fa4)

**Comment by Kajol-Kumari** [comment]
Admins will add it once the website is in good state :)
