### ISSUE TITLE
Add "Licensing Page" of MIT License to Werbsite

### ISSUE THREAD

**Issue by MastanSayyad** [HITK-TECH-Community/Community-Website#962]
Hey @Kajol-Kumari, I would like to add a **Licensing** page in the footer section 

![image](https://github.com/HITK-TECH-Community/Community-Website/assets/101971980/2f00755f-7de2-4567-8fa9-457a5b72be84)

- For example like this: (Licensing Page Created by me)

![image](https://github.com/HITK-TECH-Community/Community-Website/assets/101971980/7838dbaa-f018-46fc-9f69-9a92195b1ba5)

Could you please assign this issue to me under GSSOC'24??

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Yes

**Comment by Kajol-Kumari** [comment]
I don't feel the requirement for this, we already have privacy policy and terms of use, along with licence in the code repo
