### ISSUE TITLE
[Bug] : Dark mode verfication container Ui

### ISSUE THREAD

**Issue by sivaprasath2004** [HITK-TECH-Community/Community-Website#965]
**Describe the bug**
- In `Contact Us` page verify the `I'm not robot` verfication can be dark mode ui can be not perfect.

**To Reproduce**
1. Go to `contact-us`
2. Click on 'Dark mode'
3. Scroll down to 'Form'

**Expected behavior**
![Screenshot from 2024-05-25 18-34-19](https://github.com/HITK-TECH-Community/Community-Website/assets/121082414/d2b762d7-abfd-4744-bcde-58b16b30c40d)

**Actual behaviour**
![Screenshot from 2024-05-25 18-34-46](https://github.com/HITK-TECH-Community/Community-Website/assets/121082414/14ec64af-a322-4556-b676-cfd04b67fe2b)

**Desktop (please complete the following information):**
 - OS:Ubuntu
 - Browser : chrome

**Smartphone (please complete the following information):**
 - Device: Realme 8
 - OS: Android
 - Browser : chrome

**Comment by Kajol-Kumari** [comment]
If we make it like what u are suggesting, its visibility will be gone, its as expected currently
