### ISSUE TITLE
Regarding the server

### ISSUE THREAD

**Issue by Jassi10000** [HITK-TECH-Community/Community-Website#97]
I have forked the project , but If I make any changes I need to restart the server again and again.
I want to edit the project readme so that everyone doesn't face the same problem. Please assign me to work on this issue .
with  tag DWOC

**Comment by jackfrost13** [comment]
By server do you mean the backend server?
If yes, then we already have that updated in the project level readme
you need to run `npm run dev` while you are inside `backend` folder

**Comment by Jassi10000** [comment]
Actually I wanted to add an alternative to run server by mentioning about nodemon

**Comment by mak-ux** [comment]
@Jassi10000  nodemon is already added to the package.json.You don't need to start the server again and again.Pull the updated code

**Comment by jackfrost13** [comment]
> Actually I wanted to add an alternative to run server by mentioning about nodemon

`npm run dev` does that only ;)
