### ISSUE TITLE
Dockerize the app

### ISSUE THREAD

**Issue by agarwalhimanshugaya** [HITK-TECH-Community/Community-Website#971]
**Is your feature request related to a problem? Please describe.**
  I think in future this nodejs environment donot use by user and also some used  package in app get update then user find so much difficulty in running the app

**Describe the solution you'd like**
I can suggest a way that you try to dockerize the app so that in future also people dont find difficulty in running this app

**Describe alternatives you've considered**

**Additional context**

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Write your answer here.

**Comment by Kajol-Kumari** [comment]
seems like duplicate of https://github.com/HITK-TECH-Community/Community-Website/issues/543
