### ISSUE TITLE
Ask Your Questions input fields are getting cleared automatically if input does't match the validation due to which user have to write whole input again 

### ISSUE THREAD

**Issue by ayushpatel1248** [HITK-TECH-Community/Community-Website#977]
**Describe the bug**

- Ask Your Questions input fields are getting cleared automatically if input does't match the validation due to which user have to write whole input again in q and a page 

- if we write description less then 10 word then it will show the  "title" length must be at least 5 characters long, "description" length must be at least 10 characters long and after this all input what user has types get cleared 

**To Reproduce**
Steps to reproduce the behaviour:
1. modify the handle submit function 
2.  using prevent default so that after submit  button clicked input does't get cleared

**Expected behavior**

- if input does not meet the validation criteria then also after giving the message input is not cleared and user can do the modification and will not need to write whole input again from the scratch 

**Screenshots**

https://github.com/HITK-TECH-Community/Community-Website/assets/127100604/2f0695dc-c679-4737-bfe1-206b825f7558

**Desktop (please complete the following information):**
 - OS:macos
 - Browser chrome
 - Version 22

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
yes 

assign me this under gssoc24 label

**Comment by Kajol-Kumari** [comment]
assigning this issue yo u @ayushpatel1248 , only the successful submission should reset the form, error shouldn't
