### ISSUE TITLE
Footer Horizontal Divider line is too close to the content and it does not look good 

### ISSUE THREAD

**Issue by Abdev1205** [HITK-TECH-Community/Community-Website#978]
Footer Horizontal Divider line is too close to the content and it does not look good 

![image](https://github.com/HITK-TECH-Community/Community-Website/assets/100786143/1153ecd3-c893-4edd-8219-53fa6d96b553)

I can add some gao between the content so that the divider resembles the design and look good

Please Assign this task as per GSSOC rules and regulation

**Comment by Kajol-Kumari** [comment]
duplicate of https://github.com/HITK-TECH-Community/Community-Website/issues/802
