### ISSUE TITLE
The justification of text in about-us page

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [HITK-TECH-Community/Community-Website#981]
**Describe your Proposal**
I think that the text in the about-us page should be justified from both the sides it may increase UI of the website .

**Additional context**
![Screenshot 2024-05-28 161756](https://github.com/HITK-TECH-Community/Community-Website/assets/118350936/19483cf5-da09-404c-9c72-13c407be93ee)

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Write your answer here.
yes

**Comment by Kajol-Kumari** [comment]
@Ayushmaanagarwal1211  i don't see it a bug as its intentionally kept it in this way
