### ISSUE TITLE
Footer social links are not wrapping on small screen sizes

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [HITK-TECH-Community/Community-Website#982]
**Is your feature request related to a problem? Please describe.**
On small or medium screen sizes the social media links are not wrapping and increasing the height of the footer that is not looking good .

**Describe the solution you'd like**
The social media icons should be wrap and arrange orderly .

![Screenshot 2024-05-28 162010](https://github.com/HITK-TECH-Community/Community-Website/assets/118350936/1ef1d1b0-d772-4d5b-a069-fbaf721cf9a8)

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Write your answer here.
yes

**Comment by Kajol-Kumari** [comment]
@Ayushmaanagarwal1211  its not distorting the ui and its intentionally kept left aligned
