### ISSUE TITLE
Refactoring Footer component :Updating X(formerly twitter) icon 

### ISSUE THREAD

**Issue by swetha5157** [HITK-TECH-Community/Community-Website#987]
Refactoring the `Footer` as per the [proposed style](https://github.com/HITK-TECH-Community/Community-Website/blob/main/frontend/PROPOSAL.md). 

**Additional context**
Changing the X icon(formerly twitter) to its updated logo.
**Screenshot**
![Screenshot 2024-05-29 145341](https://github.com/HITK-TECH-Community/Community-Website/assets/123291594/43bd3ec3-e28f-4fa5-8a7b-fc1475c05d94)
**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Yes, I've read the Code of Conduct

Kindly assign to me @swetha5157 under GSSoC'24 and add level labels

**Comment by Kajol-Kumari** [comment]
@swetha5157 its kept intentionally like that, we are not wiling to change it
