### ISSUE TITLE
FEAT: Missing Sign-Up/Register Form for New Users

### ISSUE THREAD

**Issue by GnanariddhikaRavikumar** [HITK-TECH-Community/Community-Website#988]
Currently, new users attempting to join our platform are unable to find a sign-up/register form. This oversight prevents them from creating accounts and accessing our services. To enhance user experience and facilitate new user onboarding, we need to implement a visible and intuitive sign-up/register form. This issue should be prioritized to ensure a smooth user journey and prevent potential user drop-offs.

**SOLUTION**
Implement a visible and intuitive sign-up/register form that allows new users to easily create accounts and access the platform's services. The form should be prominently displayed on the website or application interface, guiding users through the registration process step-by-step.

Redirecting users to a separate sign-up page.
Integrating social sign-up options (e.g., Google, Facebook, Apple IDs) as alternative registration methods.
Implementing a pop-up modal for the sign-up/register form on the homepage.

**Additional context**
This issue hinders user onboarding and may result in potential user drop-offs. Prioritizing the implementation of a sign-up/register form will enhance user experience and facilitate the growth of the platform's user base.

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
YES

**Comment by Kajol-Kumari** [comment]
@GnanariddhikaRavikumar  this website is intended to be open and accessible to all, so there is no login/sign functionality except the admins
