### ISSUE TITLE
To Solve the bug in forgot password feature

### ISSUE THREAD

**Issue by narayani9120** [HITK-TECH-Community/Community-Website#989]
When you click "Forgot Password," it prompts for your Gmail ID. After entering your email, a pop-up message says "Mail has been sent," but don't receive the email. I like work on this issues .
![WhatsApp Image 2024-05-29 at 15 14 52](https://github.com/HITK-TECH-Community/Community-Website/assets/125353066/901f6207-5cf5-428d-8625-9fda5020be09)

Kindly assign this issue to me .
Under the Gssoc '24

**Comment by Kajol-Kumari** [comment]
@narayani9120  thanks for pointing, please make sure couple of things - 
1. Only of the entered email matches one of the admin/superadmins saved in db, then only send the email for reset , else through error saying, no user found.
2. there should be proper toast message showing the success/failure msg, you can take reference from any other component for the same

**Comment by Kajol-Kumari** [comment]
@narayani9120 any update on the issue?

**Comment by Vaishali-ajmera** [comment]
@Kajol-Kumari Please assign this task to me

**Comment by Vaishali-ajmera** [comment]
There is some issue in Q&A page. Page only is not showing.

**Comment by Vaishali-ajmera** [comment]
For the forgot password functionality whose email id shall I use for the mail sent?

**Comment by BHS-Harish** [comment]
Hey @Kajol-Kumari 

Assign it to me....

**Comment by Kajol-Kumari** [comment]
@BHS-Harish please make sure to follow https://github.com/HITK-TECH-Community/Community-Website/issues/989#issuecomment-2137894646 this
