### ISSUE TITLE
[Frontend] Make better Login Page

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#99]
- The login page is distorted and needs to be fixed

![Screenshot from 2020-12-28 12-44-18](https://user-images.githubusercontent.com/44888949/103196623-854f4f00-490a-11eb-95d4-25449fe3b964.png)

**Comment by the-supernova** [comment]
I would like to work on making a better login page(DWOC Participant)

**Comment by Kajol-Kumari** [comment]
Sure @the-supernova go ahead with this issue. Looking forward to your PR :)

**Comment by shraddha-1402** [comment]
Can i also work on this ?

**Comment by Kajol-Kumari** [comment]
Hey @shraddha-1402 sure. You can also work on this!

**Comment by the-supernova** [comment]
I am new to React..I couldn't find how can I make changes to the login button( I tried changing the loginBtn class and State)...could you guide me?

**Comment by the-supernova** [comment]
I'm new to React...I couldn't find how to make changes to the login button( I tried tweaking loginBtn class and State)..could you guide me in this?

**Comment by Kajol-Kumari** [comment]
> I'm new to React...I couldn't find how to make changes to the login button( I tried tweaking loginBtn class and State)..could you guide me in this?

Hey @the-supernova go to [this](https://github.com/HITK-TECH-Community/Community-Website/tree/main/frontend/src/components/auth/login) file and in here we are using bootstrap so you need to do change sin here and see if you are getting the desired output

**Comment by the-supernova** [comment]
> > I'm new to React...I couldn't find how to make changes to the login button( I tried tweaking loginBtn class and State)..could you guide me in this?
> 
> Hey @the-supernova go to [this](https://github.com/HITK-TECH-Community/Community-Website/tree/main/frontend/src/components/auth/login) file and in here we are using bootstrap so you need to do change sin here and see if you are getting the desired output

I'm there itself, trying to tweak the loginBtn class...I'm not able to resize the login button

**Comment by shraddha-1402** [comment]
![image](https://user-images.githubusercontent.com/69422250/103224828-80ac8a00-494e-11eb-9231-1e4abbde50ce.png)

Is this login page okay? or should i make any other changes?

**Comment by Kajol-Kumari** [comment]
@the-supernova @the-supernova Try making a complete new login component with the fields same as we have now. ANd you can take a look at `contact` page for the look reference :)

**Comment by shraddha-1402** [comment]
> ![image](https://user-images.githubusercontent.com/69422250/103224828-80ac8a00-494e-11eb-9231-1e4abbde50ce.png)
> 
> Is this login page okay? or should i make any other changes?

@Kajol-Kumari  please give suggestions

**Comment by Abhishek971999** [comment]
> > ![image](https://user-images.githubusercontent.com/69422250/103224828-80ac8a00-494e-11eb-9231-1e4abbde50ce.png)
> > Is this login page okay? or should i make any other changes?
> 
> @Kajol-Kumari please give suggestions

@shraddha-1402 try to make a new design discarding this one. You can check out the contact page for inspiration and build something similar to that if you like or if you have something even better go ahead with that.

**Comment by shraddha-1402** [comment]
> > > ![image](https://user-images.githubusercontent.com/69422250/103224828-80ac8a00-494e-11eb-9231-1e4abbde50ce.png)
> > > Is this login page okay? or should i make any other changes?
> > 
> > 
> > @Kajol-Kumari please give suggestions
> 
> @shraddha-1402 try to make a new design discarding this one. You can check out the contact page for inspiration and build something similar to that if you like or if you have something even better go ahead with that.

okay, working on it now!

**Comment by Amit366** [comment]
Can I work on this issue??

**Comment by Kajol-Kumari** [comment]
Sure @Amit366 go ahead with this issue

**Comment by kenkirito** [comment]
can i work on this issue

**Comment by vaishnavirshah** [comment]
Hi, can I contribute to this issue as a part of SWOC-21 ?

**Comment by Kajol-Kumari** [comment]
Hey @kenkirito asyou are already working on two major issues, I request you to finish them first. @vaishnavirshah you can go ahead with this issue :)

**Comment by shraddha-1402** [comment]
![image](https://user-images.githubusercontent.com/69422250/103375392-2a7f4880-4b00-11eb-9af5-33513c41bf1d.png)
Does this login page design look good? should i send pr?

**Comment by Kajol-Kumari** [comment]
Yes @shraddha-1402 looks, great go for making the PR

**Comment by vaishnavirshah** [comment]
@Kajol-Kumari This is the login page I have designed, similar to the contact us page. Since I am not familiar with react, I couldn't do it in the frontend folder and have separately created it. I have used bootstrap for this and have made it responsive using it. If you could guide me how to implement it in the website it will be great!

![LoginPage](https://user-images.githubusercontent.com/61752840/103481003-01abcb80-4dfe-11eb-99c5-f3b270d924d1.jpeg)

**Comment by Kajol-Kumari** [comment]
@vaishnavirshah looks nice just the form needs a bit of enhancement. For the coding part, I would recommend you to take help from already written code of login form. Pull the latest changes and go through the code once by parallely runing it. you would be able to see which part is doing what and similarly you can implement your design

**Comment by vaishnavirshah** [comment]
This is the login page I have designed. 

Normal:
![LoginPage](https://user-images.githubusercontent.com/61752840/103640446-0b583f00-4f76-11eb-9250-fb1c5df82b58.jpeg)

Hover over submit:
![LoginPageHover](https://user-images.githubusercontent.com/61752840/103640450-0d220280-4f76-11eb-8870-4846e2382da0.jpeg)

Are there any changes I should make or should I make a PR?

**Comment by Kajol-Kumari** [comment]
Hey @vaishnavirshah this design looks nice, just make the input fields similar to the fields we have in `contact-us` page and also keep the `submit` button similar to the `contact-us` page in order to be consistent. Also I request you to make a folder by your name under `auth` folder and keep all your login code in there in order to avoid the conflict.

**Comment by vaishnavirshah** [comment]
![image](https://user-images.githubusercontent.com/61752840/103646844-59724000-4f80-11eb-8089-f2b76cd3fe13.png)

Is this fine?

**Comment by Kajol-Kumari** [comment]
Yes! @vaishnavirshah looks nice and clean. You can make the PR now

**Comment by vaishnavirshah** [comment]
@Kajol-Kumari  For SWOC if I make PR today will it get counted or should I make it tomorrow?

**Comment by Kajol-Kumari** [comment]
Make it tomorrow, just to be on safe side :)
