### ISSUE TITLE
No Email Validation in Contact US

### ISSUE THREAD

**Issue by Sailesh3000** [HITK-TECH-Community/Community-Website#993]
![image](https://github.com/HITK-TECH-Community/Community-Website/assets/126142666/ce4a66d9-8ffe-4121-b1c6-083bef12ddd0)
Email field is only checking for '@' only in the email and not .in , .com
Please assign me this issue I am a GSSOC'24 Contributor

**Comment by Tanishka023** [comment]
Hey!! I am excited to contribute to this project; please assign it to me. @Sailesh3000
