### ISSUE TITLE
[BUG]: Like Counter Limiter

### ISSUE THREAD

**Issue by aryansharma220** [HITK-TECH-Community/Community-Website#997]
**Describe the bug**
A single user can like a q&a card multiple times. 

**To Reproduce**
1. Go to Q&A page
2. Click on 'the like button on any post
3. See error

**Expected behavior**
One user should be able to click like button once only.

**Screenshots**

https://github.com/HITK-TECH-Community/Community-Website/assets/133234867/5cb125c7-fccd-470e-aeb0-cbdf652fd8fa

**Desktop (please complete the following information):**
 - Windows 10
 - edge

**Additional context**
Please assign it to me under gssoc.

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Yes

**Comment by Hemu21** [comment]
@aryansharma220  this issue is already exist and assigned to someone they are working on it.

**Comment by aryansharma220** [comment]
> @aryansharma220 this issue is already exist and assigned to someone they are working on it.

ok then I shall close this issue

**Comment by Hemu21** [comment]
@aryansharma220  If you want to work on this issue you can ask admin to assign that issue if the already assigned one won't solve.
