### ISSUE TITLE
Faq should not display on faq page if isActive set false by admin

### ISSUE THREAD

**Issue by shivamgaur99** [HITK-TECH-Community/Community-Website#998]
**Describe the bug**
Faq should not display on faq page if isActive set false by admin. Currently, it shows all active and inactive faq,there are bug in faq page

**To Reproduce**
1. Go to 'admin dashboard'
2. Click on 'faq and q&a'
3. go to Manage faq and then edit faq
4. click checkbox on isActive set disable and still its showing on faq page 

**Screenshots**
![image](https://github.com/HITK-TECH-Community/Community-Website/assets/128178418/b1c1b2a7-32a2-4f54-b608-49b3f88b23e4)

**Comment by Kajol-Kumari** [comment]
Admins should be able to view all the active and inactive faqs in order to approve it :)

**Comment by shivamgaur99** [comment]
Admins should be able to view all the active and inactive faqs in order to approve it :)

yes but we can hide some faqs on faq page if we want; it will still show up in the admin dashboard.
